### ISSUE TITLE
MMM-AssistantMk2.js:556 [Violation] 'setTimeout'

### ISSUE THREAD

**Issue by ejay-ibm** [eouia/MMM-AssistantMk2#100]
Hi,
I'm getting the following in the dev console each time the assistant is called. 
Not sure it's a big deal. Just want to inform you 
Ejay

**Comment by eouia** [comment]
Hmmm.. I didn't get that kind of error. I have no idea where that message is coming at this moment.

**Comment by eouia** [comment]
Well, I cannot find the suspicous point. For now, I'll close this issue, but when I find something about this, I'll inform you.

**Comment by ejay-ibm** [comment]
Don't worry I can not reproduce anymorr

Le ven. 8 mars 2019 à 08:42, Seongnoh Sean Yi <notifications@github.com> a
écrit :
