### ISSUE TITLE
Can't get OAuth redirect to let me sign in.

### ISSUE THREAD

**Issue by jmart1009** [eouia/MMM-AssistantMk2#102]
Everything has worked up to this point, yet when it redirects me from the terminal to get my code, it asks me to sign in and it shows my email. Everytime i click my email, the little blue bar goes across at the top of the little sign in window and nothing happens. If i enter my info in add a new account, it just sends me back to the same screen, and it doesn't let me authorize and get my code. Someone please help.

**Comment by eouia** [comment]
Clear cache or use another browser

**Comment by jmart1009** [comment]
@eouia I will try clearing the cache but how do I use another browser? When I do the command in terminal it kicks me to a browser that has a globe icon, and I use chromium, I don't even know what browser it is, but I can try clearing the cache

**Comment by jmart1009** [comment]
Is there any way I can make it redirect to a different browser? I cleared the cache and it just took me back to the same sign in page but my email was there now, it didn't log me in.

**Comment by eouia** [comment]
Sorry for my late check. I'm on vacation now. How did you solve it?

**Comment by bachoo786** [comment]
@jmart1009 I have the same problem how did you resolve it?

**Comment by bolish** [comment]
Same issue on my side, would appreciate @jmart1009 if you could share the trick.

**Comment by bolish** [comment]
OK, I managed it.... as soon as Chromium opens... Copy the very first link it gives and paste it into a different browser (I used Chrome on MacOs for example, as I'm controlling my Rpi remote via VNC).
It will work and give you the famous code.
