### ISSUE TITLE
use the menu to sign in your phone

### ISSUE THREAD

**Issue by prithesh990** [eouia/MMM-AssistantMk2#103]
**Describe the problem**
A clear and concise description of what the problem you have.

**To Reproduce**
Steps to reproduce the behavior: (Describe what did you do)

**Expected behavior**

**Screenshots**

**Environment:**
 - Device : [e.g. RPI 3b+]
 - OS: [e.g. Raspbian Stretch]
 - Node Version :
 - Etc.

**Before you post issue, try this first**
- Confirm you have completed installation with instruction. (If you have a problem on installation step, find other similar issues or follow instruction carefully. But if you failed again, post issue here.)
- To make things simple, disable or omit or outcomment other modules from config.js except MMM-AssistantMk2 and MMM-Hotword.
- Add `verbose:true` to MMM-Assistant `config:{}` and `testMic:true` to MMM-Hotword `config:{}`. 
- Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
- If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.

Then report me.

**Comment by prithesh990** [comment]
when i start the magicmirror it tell sign in your phone using menu bar so how to do it

**Comment by eouia** [comment]
??? Sorry. I cannot catch your question. I've never heard that kind of thing. Can you take a screenshot or photo and send me? 
Attach here or
email : eouia0819@gmail.com
Telegram: @eouia

**Comment by entripo** [comment]
Hey, I got the same issue, everytime I start the MM the assistant says "Use the menu to sign in" and I can't communicate with it further. There is also a pic that pops up for some seconds, I made a photo: https://imgur.com/a/QQCvN8V I hope you can help me :) keep up the good work!

**Comment by eouia** [comment]
Very interesting. I’ve never met this.
I guess, you might  need google home app or google assistant app on your phone and might need to complete setup of your account or environment. Your account seems not be fulfilled for using google assistant, I don’t know whatever it is.

**Comment by prithesh990** [comment]
thanks for your response but how can we sign in as its not a phone through which we can sign in
we need a connection

**Comment by prithesh990** [comment]
https://github.com/eouia/MMM-AssistantMk2/blob/master/USAGE.md#register-your-mirror-as-google-assistant-related-device
in this page at last this procedure:
Register your Mirror as Google Assistant related device.
whether we have to do this procedure in order to resolve this problem

**Comment by eouia** [comment]
You guys might need to SIGN IN as a user of Google Assitant service itself through Google Assistant App or Google Home app. It is also needed when you are using REAL Google Home Devices.
I've never thought about it. sorry. I'd assumed everyone was already the user of Google Assistant. 

The registration part is optional. Frankly said, there is no real benefit of registration at this moment. It looks nicer, but that's all. This SDK is just on beta stage, so many features of REAL Google Home are not implemented yet or limited or not allowed in this module.

**Comment by eouia** [comment]
Have you got still problem? I'll close this. You can leave more issue whenever. Have a nice day.
