### ISSUE TITLE
How to change the temperature announcement in Celcius

### ISSUE THREAD

**Issue by braunprinz** [eouia/MMM-AssistantMk2#104]
**Describe the problem**
When starting MM, an announcement about the Location (LONDON) / temperature (Fahrnheit). I could change the location but I don't know how to change the temperature in Celcius.

**Environment:**
 - Device : RPB 3 B+
 - OS: Raspbian
 - Node Version :
 - Etc.

**Comment by eouia** [comment]
You can change that in your google assistant app on your phone

**Comment by bachoo786** [comment]
@braunprinz how did you install assistantmk2 on your raspberry? i am following the instructions but do I have to rebuild the electron as i am in kiosk mode? my mm is obviously working fine would this break it by rebuilding the electron?

**Comment by eouia** [comment]
I'll close this issue, because there is no feedback any more. 
You can leave your new issue as a new topic. 
Have a nice day.
