### ISSUE TITLE
Some errors in YouTube play

### ISSUE THREAD

**Issue by ReoLusia** [eouia/MMM-AssistantMk2#105]
When I try YouTube play with "dev" mode found error that

[AMK2] YouTube API is not ready. Check errors MMM-AssistantMk2.js:410 on frontend.

How can I solve this problem?

**Comment by eouia** [comment]
You might have other front-end errors from other modules or AMK2. It will prevent normal loading of YouTube API. Find the errors with dev-console and fix them. (Or report me)

**Comment by eouia** [comment]
My YouTube API is not loaded since those errors were interrupting. Fix them first. (Sorry about them I have no idea how to fix it. Ask to the module creator or to community)

**Comment by ReoLusia** [comment]
I use comment to figure out what is problem, then I found that MMM-AssistantMk2 module makes error.

Is this module have any problem with 'appendChild' ?

**Comment by eouia** [comment]
Maybe or not. if so, it might be module `position`

**Comment by ReoLusia** [comment]
I erase module `position` then WOW, it works! There's no ERROR!

But when I say "Linkin Park in the End youtube", there is no response.

Even [HOTWORD] doesn't work.

**Comment by eouia** [comment]
Maybe you might have assign wrong position(mistypo like "top_wright"). give a proper position name to the module.

**Comment by ReoLusia** [comment]
Oh Wow.... I get goose bumps...

Thank you developer

**Comment by eouia** [comment]
That is common pitfall everybody do. 
I'll close this issue. If you have any other troubles, leave it with new issue.
Have a nice day.
