### ISSUE TITLE
Black screen after successfull install

### ISSUE THREAD

**Issue by bachoo786** [eouia/MMM-AssistantMk2#106]
Hi 

I have successfully installed assistant and can confirm that it is working. However Magic Mirror has stopped working and all I get is a black screen. I am running raspbian stretch.

Here is my log:

```
pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.6.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
No helper found for module: random_quotes.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/                                                                          home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowb                                                                          oy.node'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
No helper found for module: random_quotes.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/e                                                                          lectron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/co                                                                          mmon/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release                                                                          /electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/co                                                                          mmon/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issue                                                                          s
Launching application.

```

**Comment by eouia** [comment]
You’ve missed or failed “electron-rebuild” step on installation. Check it again.

**Comment by bachoo786** [comment]
No I done that already and I followed the instructions on how to install hotword but no joy

**Comment by bachoo786** [comment]
this is what I did:

```
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ npm install --save-dev electron-rebuild
+ electron-rebuild@1.8.4
updated 1 package and audited 617 packages in 12.623s
found 0 vulnerabilities

pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ ./node_modules/.bin/electron-rebuild
✔ Rebuild Complete

```

**Comment by bachoo786** [comment]
and this is what I have in my config.js

```
{
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",
        device        : "plughw:1",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },
```

**Comment by bachoo786** [comment]
so if I was to remove the MMM-Hotword from my config i.e. the last part of the code i.e.
```

{
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },
```
the mirror starts working fine.

**Comment by bachoo786** [comment]
ok I finally managed to get it working by doing this:
```

cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm install --save-dev electron-rebuild
npm install nan
./node_modules/.bin/electron-rebuild   # It could takes dozens sec.
```

thank you soo much @eouia 

I have 3 questions for you:

1). I see the google icon in my magicmirror, is that suppose to animate when I say ok google? 

2). how do I ask google to play and show youtube videos?

3). how do I ask google to show me images on my magic mirror?

thanks again.

**Comment by eouia** [comment]
1. Not animated, but it will be changed by status
1-1. “Ok google” is not hotwod to activate(it is not included. Instead that use others - like “smart mirror”
2. Just say song title, and artist mame if be needed.
3. Not implemented in this module.(but you can build or modify module for it)
This module is not alternative google home itself. This is voice commander to control MM with assistant voice features.

**Comment by bachoo786** [comment]
1. Right ok. Maybe i have also installed another google assistant application and thought it wasn't working but it is.

1-1. So if I use "smart mirror" I expect the google icon to change? ( I am at work at the moment and will try it when I am home).

2. If I say song title, do I expect the video to show on my mirror or is it just the audio? If I was video do I have to do further configuration on my config.js?

3. What controls are you saying? it would be good to have a demonstration on your github page of the things you could do with this module?

**Comment by eouia** [comment]
1-1. If your hotword is detected and AMk2 is ready for your vocal order, The icon will be changed to mic icon.

2. Basically, This SDK what I am using for this module has no feature of playing music or video (Those features are allowed to REAL Google . Home Device only at this moment). 
It will only return googling result. Anyway, I implemented a little feature - If the googling result has an url of Youtube video, My implementation catch that url and play it with my additional YTPlayer.  So, It means, This module can play Youtube video, but that is not the default feature of Google Assistant.

3. Some video demonstrations are here; https://forum.magicmirror.builders/topic/8413/mmm-assistantmk2/1
And this module is some kind of tool to make your own voice commander, not complete one. (Because every user has different Mirror, so hard to make common control)

**Comment by bachoo786** [comment]
ok thanks alot buddy 

I only have this in my config.js for your module :

```
{
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",
        device        : "plughw:1",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },
```

do I need to add additional things to utilize the features you have in your module?

for example If I wanted to use the notificationExec, I would add the below code to my config.js? :

```
command: {
  "SAYHELLO": {
    notificationExec: {
      notification: "SHOW_ALERT",
      payload: {
        message: "You've ordered SAYHELLO.",
        timer: 5000,
      }
    },
  },
  "SAYHELLO2": {
    notificationExec: {
      notification: (params, key) => {
        // params: result of transcriptionHook match or gAction parameters
        // key: which transcriptionHook or gAction call this command

        if (key == "com.example.commands.SAYHELLO2")
        return "SHOW_ALERT" //return value will be used as notification name
      },
      payload: (params, key)=> {
        return { // return value will be used as payload
          message: "You've ordered SAYHELLO2.",
          timer: 5000,
        }
      }
    },
  },
}

```

Thank you once again !!!

**Comment by eouia** [comment]
Yes. but that is just sample. You need some knowledge about what you are doing.
Usually, `command` is combined with trigger (`transcriptionHook` or `gAction`) to activate it.
Here is command and transcription example for reboot. You can examine this sample and expand it as your desire. (Read the USAGE.md for more details)

```js
command: {
  "REBOOT": {
    shellExec: {
      exec: "sudo reboot now",
    },
  },
},

transcriptionHook: {
  "HOOK_REBOOT": {
    pattern: "reboot yourself", 
    command: "REBOOT"   
  },
},
```
This sample shows two stuffs
- transcriptionHook "HOOK_REBOOT" : With this hooking definition, your phrase "reboot yourself" will activate command "REBOOT"
- command "REBOOT" : with this command definition, When this command is activated, it will execute shell command "sudo reboot now"

**Comment by bachoo786** [comment]
thanks alot man

**Comment by bachoo786** [comment]
Hello @eouia sorry to bother again. Do I have to set the wakeup word? I tried saying smart mirror and Jarvis but none worked.

**Comment by bachoo786** [comment]
???

**Comment by eouia** [comment]
There might be so many reasons

- It could be caused by your pronunciation. Say it clearly and loud.
- Your Mic might have too low volume or your H/W environment could make so. (Covered with mirror frame to hard to get the voice)
- Your device name could be wrong in configuration. (Check with `arecord -D plughw:1 -d 10 test.wav` then play it with `aplay test.wav`)
- Check whether your mic is working properly in module by adding configuration value `testMic:true`
- Or you might have some errors which was not fixed. Check the log.

**Comment by bachoo786** [comment]
Do I have to add anything to my config.js or does it look fine?

**Comment by eouia** [comment]
Your configs seems no problem.
But to check mic is working; add this.
```js
{
    module: "MMM-Hotword",
    config: {
      testMic:true,
     ...
```

**Comment by bachoo786** [comment]
when I try arecord -D plughw:1 -d 10 test.wav I get 
```
pi@raspberrypi:~ $ arecord -D plughw:1 -d 10 test.wav
arecord: main:788: audio open error: Device or resource busy

```
however if I try : 

```
pi@raspberrypi:~ $ arecord -D default test.wav
Recording WAVE 'test.wav' : Unsigned 8 bit, Rate 8000 Hz, Mono

```

It seems to work?

**Comment by eouia** [comment]
It means your configuration is wrong. Your device name is not `plughw:1`.
change the properties `device: "plughw:1"` to `device:null` or `device:"default"` and try it again.

**Comment by bachoo786** [comment]
sorry which configuration are you talking about? which file is this?

**Comment by eouia** [comment]
always `config.js`

**Comment by bachoo786** [comment]
ok changed it...I am not at home now will check when I am home.

do I need to change anything in my ./asoundrc file?

**Comment by eouia** [comment]
for ALSA setup, I have no idea because too complex and individual for each environment.
But if you have a success with `device:null` or `device:"default"`, your device name could be `null` or `"default"`

**Comment by bachoo786** [comment]
Ok I shall try and let you know thank you

**Comment by bachoo786** [comment]
sorry buddy if I run this command  `arecord -l`

I get this: 
```

**** List of CAPTURE Hardware Devices ****
card 1: AK5371 [AK5371], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```
this shows that the device is 0?

**Comment by eouia** [comment]
Usually in that case `plughw:1,0` will be the device name.
But it also depends on your ALSA setup (`asound.rc`?) So, I cannot insist exactly.

**Comment by bachoo786** [comment]
right so I am using a bluetooth speaker and this is my .asoundrc file. I know you said you dont use ALSA but here is my .asoundrc

```
pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        channels 1
    }
}

pcm.bluetooth {
    type plug
    slave.pcm {
        type bluealsa
        device "20:18:08:30:A9:66"
        profile "a2dp"
    }
}

pcm.!default {
    type asym
    playback.pcm {
        type plug
        slave.pcm "bluetooth"
    }
    capture.pcm {
        type plug
        slave.pcm "dsnooper"
    }
}
```

**Comment by eouia** [comment]
The problem is, I have not enough knowledge about ALSA. So I cannot give you proper solution.
Anyway, your case seems "dsnooper" could be the candidate of device name. (I didn't try, but...)

**Comment by eouia** [comment]
Anyway you should find proper device name to use with `arecord -D [DEVICENAME]`.

**Comment by bachoo786** [comment]
this command gives me this:

```
pi@raspberrypi:~ $ arecord -D [DEVICENAME]
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM [DEVICENAME]
arecord: main:788: audio open error: No such file or directory
```

**Comment by eouia** [comment]
NO, I means You should find `[DEVICENAME]` of yours.  it could be "plughw:1" or "dsnooper" or just `null`. Not `[DEVICENAME]` characters itself.

**Comment by bachoo786** [comment]
oh ok so it seems like it is "dsnooper" . See the below:

```
pi@raspberrypi:~ $ arecord -D dsnooper
Recording WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
arecord: set_params:1299: Sample format non available
Available formats:
- S16_LE
pi@raspberrypi:~ $ arecord -D plughw:1
arecord: main:788: audio open error: Device or resource busy
pi@raspberrypi:~ $ arecord -D plughw:1,0
arecord: main:788: audio open error: Device or resource busy
```

**Comment by bachoo786** [comment]
and with arecord -D default it gives me ;

```
pi@raspberrypi:~ $ arecord -D default
Recording WAVE 'stdin' : Unsigned 8 bit, Rate 8000 Hz, Mono
RIFF$▒WAVEfmt @data▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}}}}}}~}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}~~▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}~~~~~~~~~~~~▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}~~~~}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}~~~~~~~~}~~~}}}}}~}}}}}}}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}|}}|||||||||||||||||||||||||||||||||||||||||{|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||}||}|}}}}}}}}}}}}}}}}}}}}}}}}}▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}~}~~~~~~~~▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}}~~~~~}}}}}}}}}}~~~~~~~~}}~~}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}~~}}~~~~~~~~~~~}~~~~~~~~~~~~~~~~▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}}|}}}}|}||||||||||||||||▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
```

**Comment by bachoo786** [comment]
so is my device "default" or "dsnooper"?

**Comment by eouia** [comment]
I think both could work, but not sure. try one by one.

**Comment by bachoo786** [comment]
ok buddy thanks alot I will update you when I try them both. Thanks once again !!

**Comment by bachoo786** [comment]
Hey @eouia I had to change the device to default in my config and it started working :) thank you.

The one thing I wanted to ask you why is there a lag of a second when you say Jarvis or smart mirror ? Can it made instant with no lag ?

**Comment by eouia** [comment]
How long the lag? Usually it should be less 0.1 sec.

**Comment by bachoo786** [comment]
It's around 1 second

**Comment by eouia** [comment]
Well, there is nothing to lag intentionally. But rpi is not so powerful machine, so if there are many processes which consume computing power, it could happen.
- MM itself is so what heavy
- some modules which are using system interrupter like refreshing ui or timeInterval job might occupy system clock tick so whole system might run slowly.
- too many background jobs.
- system resources are drained.

Well, those kinds of things I cannot help.

**Comment by bachoo786** [comment]
No buddy no worries thanks again

**Comment by bachoo786** [comment]
hi @eouia I looked at your video this one: https://www.youtube.com/watch?v=SQYdnbgFGw4&feature=youtu.be

and I noticed that the assistant in your setup is always listening because the mic icon is always on. In mine the mic does not appear until I say Jarvis or Smart Mirror.

How can I change it to listen to it always? like yours?

Because the delay I have which is about 1-2 seconds is very surprising I am running MM on rp3b+ with nothing else installed.

**Comment by bachoo786** [comment]
Sorry buddy but can you please help @eouia ?

**Comment by eouia** [comment]
That was old version. I just changed icon. You can see I always said hotwords for awakwning in the clip. Sorry.

**Comment by bachoo786** [comment]
Oh ok I see
Man i am really disappointed with the lag of 2 seconds my cpu is 30% and i am also running Google assistant different from mm. I disabled it but it's the same issue

**Comment by bachoo786** [comment]
Also @eouia whenever I restart my rpi my mic card changes from card 1 to card 2 so I have to then change my .asoundrc file accordingly but do you know why that is happening? The mic card keeps changing is there a way to stop this? Thanks

**Comment by bachoo786** [comment]
I just want to resolve the lag buddy

**Comment by eouia** [comment]
Send me a full configuration file of yours.
Before it, Have you tried removing other modules from configuration except MMM-Hotword/MMM-AssistantMk2? Is there same lag?

**Comment by bachoo786** [comment]
so I removed every module and just kept assistant and hotword and what I noticed is that when I say Jarvis the lag is around 1 second with twice detection so after saying Jarvis I hear the beep sound twice.

**Comment by bachoo786** [comment]
@eouia  I have sent it to you as a rar as it wouldn't send .js

**Comment by eouia** [comment]
beep sound twice? Very weird. lag also be strange but possible, but twice beeping... hmmm... What's going on your mirror...
To make things clearly, You just say "jarvis" once, but after 1sec, beeping twice. right? That seems not normal flow. Maybe reason of your lag issue also be due to.

Anyway, your RAR file is not extracted. Just send me via email with rename it as config.txt

**Comment by bachoo786** [comment]
I have emailed it to u.

I say Jarvis now it doesn't work at all. My mic and speakers are working fine

**Comment by eouia** [comment]
I think your case is not abnormal, but if you want to shorten the gap between process,
Do this.
- Open config.js
- Search `record` section of MMM-AssistantMk2 and MMM-Hotword. (2 locations)
```js
record: {
      silence       : 1.0,        // seconds of silence before ending. shorten it to 0.5
      recordProgram : "arecord",  
      device        : null,
},
```
Your config might have not `silence` field, if so add. (`silence:0.5`)
This module decides when your sentence is ended with this value. Default value is 1s. it means, silence of 1 second become a signal of your turn end. I think 1s is enough but you might feel it as a lag.

**Comment by bachoo786** [comment]
I dont have the silence I put it in my config.js for assistantmk2 and hotword. I changed the value to 0.1 as 0.5 was the same as before but there is no real changes still laggy only a little improvement

**Comment by eouia** [comment]
Sorry nothing to improve i can suggest
