### ISSUE TITLE
Connect MMM-AssistantMk2 with my Chromecast Audio - Spotify

### ISSUE THREAD

**Issue by F17MC** [eouia/MMM-AssistantMk2#107]
**Describe the problem**
I want cast Spotify music from my Raspberry with MMM-AssistantMk2 to my Chromecast Audio.
**To Reproduce**
I have Google Home and Google Assistant App's on my Smartphone. If I say: "Ok google, play Spotify on Chromecast audio" it works fine. 
I want do the same with my MagicMirror. But I can't. Can I do something with MMM-AssistantMk2 to solve it?

I'm thinking how solve it without MMM-AssistantMk2, and I think that it can works with: Raspotify to play Spotify, and PulseAudio-DLNA or PyChromecast to cast the audio from RPI to Chromecast audio.

**Environment:**
 - Device : Rpi 3 B+ 
 - OS:  Raspbian Stretch + Raspbian + MagicMirror + MMM-AssistantMk2
 - Music Device: Chromecast Audio

**Comment by eouia** [comment]
SDK which is used for this module is `Google Assistant SDK for deveices (service)` and the it is still on the BETA stage.
`playing Spotify (or Youtube)` is not allowed to this SDK yet. It is allowed only to REAL Google Assistant Devices (Google Home or Google Assistant App, etc)
So it couldn't be done with this module alone at this moment.

I don't know much about chromecast or Raspotify. But if it could be controlled by external shell command or script, it could be controlled by this module also. (via `command`s and triggers(`gAction` or `transcriptionHook`)

**Comment by ejay-ibm** [comment]
Yes eouia It can "easely" be controled by commands . 
The only tricky part is the necessary token to make it. 
The bearer token necessary to run the command is valid from 3600 second only then it changes. 
the nowplayingonspotify module is already handeling that part and I don't think usefull to add the spotify handeling code directly in MK2

So to answer to @F17MC , no it's not a bug in the Mk2 assistant as it is limited in native command as explained by sean bellow due to the SDK . But the good news is : it is still possible. 
some doc here if you are interested. 
https://developer.spotify.com/documentation/web-playback-sdk/reference/#api-spotify-player

I'm currently working on this to have a module that would allow to call these API . I'm looking for this functionnality as well since I started my MM project. 

Once done it will be easy ( maybe even transparent ) to control it with MK2. 
So the final word is patience... ;) it should arrive soon or late. 
ejay

**Comment by F17MC** [comment]
Thanks a both for your reply.

I'm using MMM-AssistantMk2 + MMM-SpotifyControl and the result is fantastic.
But I have a problem:

I have a problem with MMM-AssistantMk2 + your module.

MMM-AssistantMk2 is working. I say: Smartmirror, play music on Spotify (my command). And it works. The mirror play music with raspotify.

But, later, if I want to say something to MMM-AssistantMk2, I can’t.

It’s my log:

[HOTWORD] stops listening
Speaker error: 1
```
Whoops! There was an uncaught exception...
1
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

```
Maybe the problem is that if the speakers are using by other “process”, MMM-AssistantMk2 have a problem to use?

**Comment by ejay-ibm** [comment]
Hi,

I do not think this is an issue with the speaker.
Could you please send the full logs from start to end ?
Are you using pm2 ? If yes please send me error and out log. ( delete them first before restarting your mirror ) rm <pathto/name of the log out.log   error.log>
just do pm2 show to know where they are .
As well while you reproduce check the developer console ( Ctrl + i ) on the mirror and send me the content .

Just reproduce the case as follow : Start Mirror , request a song, make a new request to the assistant . Quit . and send me the logs. please add as well you config.js file . You can put all in a single zip file.

**Comment by eouia** [comment]
I think it is caused by speaker occupation.
I'm not an expert of that kind, so I cannot declare, but As far as I know,
You might need to adjust ALSA config to mix sound output from multi-source. The error might come when one program is using sound output and the same time, another program try to use sound output also.
Sorry I'm not experienced to ALSA, so I cannot give you proper solution.

**Comment by ejay-ibm** [comment]
You can have multiple output source running at same time. by source i mean process. 
Eg: Raspotify and Mk2 assistant. there's no issue with this. 
If I push the test i'm able to play a spotify song on raspotify , a youtube video in the assistant and something else in the browser. and I can still ask something to the assistant. 

The issue might be a different sampling rate used by the 2 processes . 

Can you send your config.js file and as well your raspotify config  (  /etc/default/raspotify ) ? 

my setup : 
raspotify : 
 /etc/default/raspotify
# Bitrate, one of 96 (low quality), 160 (default quality), or 320 (high quality)
#BITRATE="160"

config : 
record: {
          sampleRate: 16000,record: {
          sampleRate: 16000,
 play: {
          playProgram: "mpg321"

my : .asound
pi@ejaypi:~$ more .asoundrc

pcm.!default {
        type hw
        card 0
}

ctl.!default {
        type hw
        card 0
}

I would like to see the full log as requested earlier to have a full picture. 
as well once the issue appears can you run : 
ps -ef
 command so I can check what is running on your machine while the issue occurs.  

Can you run as well : 
aplay -l
arecord -l

please send everything requested that will help as for now we can only make assumptions. 

  Ejay

**Comment by F17MC** [comment]
I think that the problem is with ALSA for speaker occupation. I'm playing Spotify in my laptop and I can play music, stop music, next song... with module. But if the output is the magic mirror, I have error code 1, speaker error.

**Comment by ejay-ibm** [comment]
please show your .asoundrc file .

**Comment by F17MC** [comment]
pi@MagicMirror:~ $ more .asoundrc

```
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:2,0"
  }
}
```


raspotify:
```
#BITRATE="160"

# To choose a different output device (ie a USB audio dongle or HDMI audio out),
# use `--device` with something like `--device hw:0,1`. Your mileage may vary.
OPTIONS="--device hw:2,0"
```

pi@MagicMirror:~ $ aplay -l
```
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

pi@MagicMirror:~ $ arecord -l
```
**** List of CAPTURE Hardware Devices ****
card 1: CameraB409241 [USB Camera-B4.09.24.1], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

Assistantmk2:
				```
module: "MMM-AssistantMk2",
				position: "bottom_right",
				config: {
					useWelcomeMessage: "Bienvenido Fran",
					notifications: {
							ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
							ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
					},
					deviceLocation: {
							coordinates: { 
									latitude:   40.4893538,
									longitude: -3.6827461 
							},
					},
					onIdle: {
						timer: 0, // ESTABA PUESTO CADA 30min (1000*60*30) if you don't want to use this feature, just set timer as `0` or command as ""
						command: ""
					},
					onActivate: {
						timer: 0,
						command: ""
					},
					defaultProfile: "default", 
					profiles: {
							"default" : { // profile name.
									profileFile: "default.json", // profile file name.
									lang: "es-ES"
							},
					},
					record: { // Full values are in `FOR EXPERTS` section.
							recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
							device: "plughw:1"        // recording device (e.g.: "plughw:1")
					},
					play: { // Full values are in `FOR EXPERTS` section.
							playProgram: "mpg321", // recommended.
					},
					responseVoice: true,

```

When run magicmirror:

```
[AMK2] Device Action: { requestId: 'private' }
[AMK2] Assistant Text Response: 
1841 Mails fetched
[HOTWORD] begins listening.
[HOTWORD] <<  espejito  >> is detected.
[HOTWORD] stops listening
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Transcription: pon  --- Done: false
[AMK2] Transcription: ponme  --- Done: false
[AMK2] Transcription: pon  --- Done: false
[AMK2] Transcription: pon música  --- Done: false
[AMK2] Transcription: pon música  --- Done: false
[AMK2] Transcription: pon música  --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: pon música  --- Done: true
{ requestId: 'private' } { profileFile: 'default.json', lang: 'es-ES' }
[AMK2] Device Action: { requestId: 'private' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[HOTWORD] begins listening.
Refreshed access token because it has expired. Expired at: 11:09:28 now is: 11:09:57
[HOTWORD] <<  espejito  >> is detected.
[HOTWORD] stops listening
Speaker error: 1
Whoops! There was an uncaught exception...
1
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues


```

I don't use pm2, and I don't know how get my complete log.

**Comment by ejay-ibm** [comment]
Can you try this in you .asoundrc: 
~~~~
pcm.!default {
type hw
card 2
}

ctl.!default {
type hw
card 1
}
~~~~

Backup your current one and create a new one with just this.

**Comment by F17MC** [comment]
With this .asoundrc I have the same error but I get the error automatically when I run my mirror.

**Comment by ejay-ibm** [comment]
ok let try 
plughw  instead of hw then

**Comment by F17MC** [comment]
I'm reading about dmix:
https://www.alsa-project.org/main/index.php/Asoundrc

Software mixing

Software mixing is the ability to play multiple sound files or applications at the same time through the same device. There are many ways to have software mixing in the Linux environment. Usually it requires a server application such as ARTSD, ESD, JACK... The list is large and the apps can often be confusing to use.
dmix
These days we have a native plugin for ALSA called the dmix (direct mixing) plugin. It allows software mixing in an easy to use syntax and without the hassle of installing/understanding a new application first.
A very interesting and potentially extremely useful aspect of this plugin is using it combined with the default plugin name. In theory this means all applications that have native ALSA support will share the sound device. In practice not many applications are able to take advantage of this functionality yet. However if you have time to test and report your findings to the application developers it is worth a try:
```
pcm.!default {
        type plug
        slave.pcm "dmixer"
}

pcm.dmixer  {
        type dmix
        ipc_key 1024
        slave {
                pcm "hw:1,0"
                period_time 0
                period_size 1024
                buffer_size 4096
                rate 44100
        }
        bindings {
                0 0
                1 1
        }
}

ctl.dmixer {
        type hw
        card 0
}
```
(To use it with your own name just change the word !default above)
Now try:
`aplay -f cd -D default test.wav`
on multiple consoles.
Some notes:
The dmix PCM name is already defined in the global configuration file /usr/share/alsa/alsa.conf.
- The default sample rate for this device is 48000Hz. If you would like to change it use:
`aplay -D"plug:'dmix:RATE=44100'" test.wav`
- An example command for dmix plugin to use 44100Hz sample-rate and hw:1,0 output device:
`aplay -Dplug:\'dmix:SLAVE=\"hw:1,0\",RATE=44100\' test.wav`
- The dmix PCM name is already defined in the global configuration file /usr/share/alsa/alsa.conf.
Defaults are:
`SLAVE="hw:0,0",RATE=48000`
NB the dmix plugin is not based on client/server architecture, but it writes directly to the soundcard's DMA buffer. There is no limit to the amount of instances that can be run at one time.

**Comment by edd29** [comment]
please i need help I'm new  for this project  I installed MMM-AssistantMk2 + MMM-SpotifyControl which is shows my raspotify my problem i don't know to put command and which js file to play by voice command  can any one send me a copy of your command files if possible.
thanks in advance.

**Comment by ejay-ibm** [comment]
Please Uninstall  MMM-SpotifyControl ( it's now deprecated )   & MMM-nowplayingonspotify modules by commenting there section in a first time in the config.js 
Then install this module :https://github.com/eouia/MMM-Spotify
The doc is pretty clear. 
Ejay

**Comment by edd29** [comment]
I wish you can make video tutorial  to do this so i can follow along  I am hopeless Please...
![Capture](https://user-images.githubusercontent.com/13892977/54886206-5b3b4400-4e7d-11e9-9f57-2fef202065d3.PNG)
Thank you!

**Comment by F17MC** [comment]
Please close the issue. It's solved with MMM-Spotify

**Comment by eddy2969** [comment]
okay Thank you!

**Comment by greg-ry** [comment]
Hi 
I have a similar problem as F17MC. I've setup MMM-Spotify module with MMM-Assistant voice control. 
When the music is playing and I try to say a next commend (i.e. to change artist or stop music) I can't because the speaker is already used . I've tried to setup dmix but it does not seem to work on RPI (or I'm doing something wrong). 
How was this case solved?

**Comment by eouia** [comment]
@greg-ry Well if dmix is not working(sorry I'm not that kind of expert), the remain solution would be using 2 speakers. There is no way mixing output on the application level.

**Comment by greg-ry** [comment]
Thx Sean for the response. How would you configure two speakers? One
through USB or HDMI and another through Analog Audio. Is that what you
mean? How do you do that?

**Comment by greg-ry** [comment]
How did you solve the problem? in your installation did you use dmix?

**Comment by eouia** [comment]
No. I haven't solved this issue. I'm not using MMM-AssistantMk2 to control MMM-Spotify. I didn't try.

But If I were, I'll use two usb speakers. And I'll give different device names with ALSA,  or automatically they will get different names like `plughw:1` and `plughw:2`

However, I doubt it has really worthy to do. I'll rather consider non-verbal type control like gestures.

**Comment by eouia** [comment]
Hmmm. Or.
If I were, and just want to control simply only limited control, I'll consider MMM-Hotword without sound output. It could work without sound output, so if you make some .pmdl(s) like (play, stop, next...) it could be used to make controlling notifications for MMM-Spotify without interference of speaker.

**Comment by bugsounet** [comment]
I have MMM-Hotword / AMK2 and MMM-Spotify with Raspotify. I have no issue.
I use AMK2 recipes for control

**Comment by greg-ry** [comment]
@eouia, I've tried to remove the sound output after hotword, the only sound being produced is the chime sound. For testing purposes I've removed chime from node_helper.js in MMM-Assistant

 playChime: function (cb) {
    var com = this.config.play.playProgram
    var option = this.config.play.playOption
    var file = path.resolve(__dirname, "resources", this.config.startChime)
    //this.play(file, com, option, ()=>{cb()})
   cb();

  },
but then for some reason the transcription of voice didn't work. I didn't debug it further, because the solution is ugly and not supportable in the long run :)

@bugsounet, interesting. I'll try to reinstall ALSA configuration. Can you share your .asoundrc and /etc/asound.conf files please? I must be doing something wrong :|

**Comment by eouia** [comment]
@greg-ry I didn't mean MMM-AssistantMk2, I said about MMM-Hotword. :D

**Comment by greg-ry** [comment]
I know but this chime is managed but assistant module. Im not sure how it
could work in hot word module? Did you suggest to create custom words for
each of the commands? These would trigger notifications to Spotify module
directly? Did I get it right? :)

pon., 4 lis 2019, 16:41 użytkownik Seongnoh Sean Yi <
notifications@github.com> napisał:

**Comment by eouia** [comment]
Yes, right. You don't need to AI Assistant to interpret your voice. For just simple commands like "next", "stop", you can make private model for snowboy, and link your spotify-command to those hotwords.
For example;
you can reserve hotword "smart_mirror" for activating MMM-AssistantMk2, besides, you can add "spotify", "play", "next", "stop" hotwords to emit Spotify-notifications.

**Comment by kondef** [comment]
I have installed Magic Mirror+MMM assistant+Hotword+MMM spotify+ Rapsotify. On starting of magic mirror, the spotify icon appears but i cant make it play music with Hotword.Google assistant just open the web browser when i am asking to play something on spotify. Am i doing something wrong? This is the config of Spotify.
{
  module: "MMM-Spotify",
  position: "bottom_center",
  config: {
    style: "default", // "default" or "mini" available
    control: "default", //"default", "hidden" available
    updateInterval: 1000,
    onStart: null, // disable onStart feature with `null`
    allowDevices: [], //If you want to limit devices to display info, use this.
    // allowDevices: ["RASPOTIFY", "My iPhoneX", "My Home speaker"],
  }
},
