### ISSUE TITLE
ASSISTANT_UNDERSTOOD Uncaught ReferenceError: payload is not defined MMM-AssistantMk2.js:518 

### ISSUE THREAD

**Issue by ejay-ibm** [eouia/MMM-AssistantMk2#108]
Hi Sean , 

New code throw an error : 

Uncaught ReferenceError: payload is not defined 
    at AssistantHelper.changeStatus (MMM-AssistantMk2.js:518)
    at AssistantHelper.transcription (MMM-AssistantMk2.js:503)
    at Class.socketNotificationReceived (MMM-AssistantMk2.js:337)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
	
	
changeStatus @ MMM-AssistantMk2.js:518
transcription @ MMM-AssistantMk2.js:503
socketNotificationReceived @ MMM-AssistantMk2.js:337
(anonymous) @ module.js:246
(anonymous) @ socketclient.js:25
r.emit @ index.js:83
r.onevent @ index.js:83
MMSocket.self.socket.onevent @ socketclient.js:19
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83

Line is code is : 

  if (key == "UNDERSTANDING") {
 518 :      this.sendNotification(this.config.notifications.ASSISTANT_UNDERSTOOD, payload.transcription)
    }

Ejay

**Comment by eouia** [comment]
Sorry, it's my mistake. patched. (hope so)

**Comment by ejay-ibm** [comment]
working like a charm now!
