### ISSUE TITLE
안녕하세요 Assistant가 대답을 안합니다.

### ISSUE THREAD

**Issue by stevetorta** [eouia/MMM-AssistantMk2#109]
Hotword와 Assistant, Notification을 성공적으로 설치 완료후 
매직미러 부팅까지 성공했습니다.
Snowboy 음성으로 인식후 명령어까지 인식하는데 그 후 Assistant문제인지 미러가 대답을 하지 않습니다.
이런 경우에는 어떤조치를 취해야 할까요?

**Comment by eouia** [comment]
NotificationTrigger를 설치하셨다는 것을 보니, 상당히 옛날 버전 기반의 설치 가이드(어딘가에 떠돌고 있다고 하더라구요... 저는 모르는데)를 보고 따라 하신 것 같아요.
일단 설치(electron-rebuild까지)가 다 되셨다는 가정이라면 분명 config.js의 내용이 틀렸을 겁니다. 이 github repository의 README.md나 기타 도큐먼트(*.MD) 등을 보시고 configuration을 맞게 설정하시기 바랍니다.

**Comment by eouia** [comment]
아, MMM-Hotword에 있는 내용도 꼭 읽으세요.

**Comment by eouia** [comment]
피드백이 없으셔서 이슈를 닫습니다. 더 궁금한 게 있으시면 새 이슈로 언제든지 물어보세요.
