### ISSUE TITLE
Error: /urs/lib/arm-linux-gnueabihf/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by sephiran** [eouia/MMM-AssistantMk2#11]
I'm encountering the problem above when executing 'node auth_and_test.js'. Updated and upgraded my Pi, still get the error. I checked my 'GLIBCXX' version and the latest one is 3.4.20. So therefore I need to update that but can't find any information about how to update that. Somebody had the same problem?

Thanks in advance

**Comment by eouia** [comment]
I think you need update your gcc.
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get install build-essentials
sudo apt-get install gcc-5
```

**Comment by eouia** [comment]
Have you solved this problem? Or still?
I'll close this issue, but if you have any problems, ask me anytime.

**Comment by sephiran** [comment]
I tried to update the gcc of the pi as you suggested but it did not work. I had Jessie installed so I updated to Stretch and then it worked :)
Thanks for your help
