### ISSUE TITLE
Update issue

### ISSUE THREAD

**Issue by bachoo786** [eouia/MMM-AssistantMk2#110]
Hi 

I am trying to update to the latest updates and I follow the instructions on your github update but get the following errors:

```
pi@raspberrypi:~ $ cd ~/MagicMirror/modules/MMM-AssistantMk2
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ git pull
Updating 0ac6b4d..a705261
error: Your local changes to the following files would be overwritten by merge:
        package.json
Please commit your changes or stash them before you merge.
Aborting

```

Can you please help?

**Comment by eouia** [comment]
You might have modified that package.json file by yourself. It prevents auto-update. 
Don't worry about it.
First, this update is not so important, so you can skip it.
However, still you want to update, 

```sh
git fetch --all
git reset --hard origin/master
git pull
```

**Comment by bachoo786** [comment]
I have not touched anything without asking you so i have not modified the package.json 

Anyway thanks for guiding me on how to update using the git fetch method.
