### ISSUE TITLE
Specific Module controlling 

### ISSUE THREAD

**Issue by ruhulayaan** [eouia/MMM-AssistantMk2#112]
Is there a way to control a specific module with voice , i want to play/stop this module https://github.com/masters1222/mm-music-player. Or any music module which i can use for streaming locally or remotely

**Comment by eouia** [comment]
MM-Music-Player has any method to control itself?
As far as I see, there is no notification to control that module with notificationExec. and in the code, no good method to control with moduleExec. MM-Music-Player is not designed to be able to communicate with other modules.
I think you'd better to ask the developer to add some notification environment to control his module. (like MUSIC_PLAYER_PLAY / MUSIC_PLAYER_PAUSE / MUSIC_PLAYER_NET ...)

**Comment by ruhulayaan** [comment]
Sorry, but do u know any module or recommend me any, which i can use for playing music through voice commands. 
Thank you

**Comment by eouia** [comment]
Sorry. I'm not using any Music related modules so I have no idea about it. I heard there is a project about spotify but not sure.
