### ISSUE TITLE
Assistant causing other modules not to appear 

### ISSUE THREAD

**Issue by bachoo786** [eouia/MMM-AssistantMk2#113]
Hi

I have had everything running fine but only recently noticed that the assistant is causing other modules not to appear on the mirror except for the weather module apart from that nothing appears on my mirror including assistant module.

When I say Jarvis everything appears and the mirror looks the way I want it.

Is this a known issue ? Why does this happen?

**Comment by eouia** [comment]
That is onIdle feature. By default, after x minutes from last query, onIdle feature will activate(hiding modules). Read the configuration.md and find onIdle, disable it.

**Comment by eouia** [comment]
add this in your configuration.
```js
onIdle: {
      timer: 0,
      command: ""
},
onActivate: {
      timer: 0,
      command: ""
},
```

**Comment by bachoo786** [comment]
I need to add the above under assistantmk2 config yeah?

**Comment by eouia** [comment]
yes.

**Comment by bachoo786** [comment]
thank you works fine
