### ISSUE TITLE
Don't pause hotword and stop assistant speech if new hotword is detected .

### ISSUE THREAD

**Issue by ejay-ibm** [eouia/MMM-AssistantMk2#114]
Hi Sean , 

What would be the right modification to achieve this. 
I found out how to resume hotword before assistant answer finish . 
But I have not been able to stop the assistant answer once a new hotword is detected . 

Why i'm trying that ? Because sometimes the assistant doesn't get my request correctly and start a long answer . I'd like to be able to interrupt it by syaing the hotword and maybe a stop. 

Should I create a STOP hook ? then what would be the notification to send to stop the assistant from answering. 

Thank 
Ejay

**Comment by eouia** [comment]
I tried it before, but it makes some unintentional behaviors (detection delusion from voice response itself) So I abandon it.
Response itself can be canceled by new activation. So HOTWORD_RESUME emission AFTER user's voice order (ASSISTANT_UNDERSTANDING)  could make it. (currently HOTWORD_RESUME will be emitted as ASSISTANT_DEACTIVATED)

But... I'm not sure it is really good for everyone due to detection delusion.

**Comment by ejay-ibm** [comment]
" detection delusion from voice response itself " 
That's the point . I didn't find any notification that allow to stop the assistant from answering. 

So HOTWORD_RESUME emission AFTER user's voice order (ASSISTANT_UNDERSTANDING) could make it.  I made it work , but the assistant voice doesn't stop , so a new request make the assistant give an new answer while the first one is still running . 
That's what I tried to avoid . 
hotword detected = force assistant "shutup"

**Comment by eouia** [comment]
I had some confusing, New activation will clear the screen output and yt playing, but not voice itself. You are right.
Version 2.1.0, I changed the structure of vocal response From realtime pipe stream to speaker To dropping mp3(or wav) file and playing it. The change makes less dependencies on installation and safety from some bugs, But at same time I loose realtime control of playing voice.

Well, I think your request needs changing structure of program with major version change. I'll consider.

**Comment by ejay-ibm** [comment]
With the right combination : Mk2assistant + HotWord + Volume + Notification trigger Module we can avoid several problems . 
My actual notification configuration allow me the following for now. I personnaly think that 's the good way it should work  ( Note That I have disabled the youtube stop function when hotword is triggered by commenting some lines in the code ) I added a manual hook 'STOP YOUTUBE' with as command the line I previously commented. ( hope that's clear ) 

Commented code line in MMM-AssitantMk2.js : 
````
  clearResponse() {
    this.subdom.message.innerHTML = ""
//    this.subdom.youtube.innerHTML = ""
//    this.subdom.youtube.style.display = "none"
//    this.youtubePlaying = false
    //this.sendSocketNotification(this.config.notifications.ASSISTANT_DEACTIVATED)
  }
`````
Hook Command in config.js
````
STOP_VID: {
            moduleExec: {
              module: ["MMM-AssistantMk2"],
              exec: (module, params, key) => {
                module.assistant.subdom.youtube.innerHTML = ""; 
                module.assistant.subdom.youtube.style.display = "none";
                module.youtubePlaying = false;
              }
            }
          },

````


That give the following flow. 
Hotword detected (sleeping ) -> send notification -> Triggernotif -> Volume Store then reduce output volume to 10 -> Assistant Activate > assistant understood > volume back to original with volume RESTORE .

````
MMM-Trigger setup : 

````
 trigger: "HOTWORD_SLEEPING", 
            fires: [
              {
                fire: "VOLUME_STORE",
                 exec: "amixer sset -M 'PCM' 10%"
              }

            ]

          },
  
        {
            trigger: "ASSISTANT_UNDERSTOOD", 
            fires: [
              {
                fire: "VOLUME_RESTORE",
                payload: payload => {
....
...
```` 

That make youtube player independant from assistant speech . 

Hope that clarify my view and helps a bit .

**Comment by eouia** [comment]
Good trial. That's the ideal way to combine my modules as my intention.

**Comment by bastos5** [comment]
Hello,

I would like to know how did you do that  please :) ? "I found out how to resume hotword before assistant answer finish ." Im trying to use a recipe to trigger notification with the pattern "Stop" but it doesnt work. 

Thank You,
bastien

**Comment by eouia** [comment]
@bastos5 
My Telegram Id is `@eouia`, You can contact me on real-time. My convenient time is 10am - 18pm on weekdays.
