### ISSUE TITLE
useWelcomeMessage: "brief today" on in English

### ISSUE THREAD

**Issue by carfnann** [eouia/MMM-AssistantMk2#115]
Hi,

I'm using the option : 
useWelcomeMessage: "brief today",

but although I've setup my profiles as "fr-FR", the brief is still in english.
is it normal?

here my module : 
		{
			module: "MMM-AssistantMk2",
			position: "top_right",
			config: {
				deviceLocation: {
					coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
					latitude: xx.367361, // -90.0 - +90.0
					longitude: x.354922, // -180.0 - +180.0
					},
				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
				profiles: {
					"default" : {
						lang: "fr-FR"
					}
				},
				useWelcomeMessage: "brief today",
			}

**Comment by eouia** [comment]
I think if you assign french welcome message, it will response with french. Despite of your lang setting of “fr”, you’ve used English as query, so assistant had understood your current locale being English, so it might have responded with English.

**Comment by carfnann** [comment]
Indeed, I've misunderstood this feature...
by puting useWelcomeMessage: "bonjour",
I'm getting my French brief.

thanks for your work

**Comment by eouia** [comment]
Nice to hear it. I’ll close this issue
