### ISSUE TITLE
i can't take message (speak, text) from assistant but command execute  is ok like "turn on light or turn off light"

### ISSUE THREAD

**Issue by nevido** [eouia/MMM-AssistantMk2#116]
전등 꺼등과 같이 google assistant 명령어 실행은 되는거 같은데
오늘 날씨 어때.. 그 외적으로 답변을 주는 질문에는 아무런 반응이 없습니다
ㅠㅠ

 i can execute command via assistant like "turn of light or off light"
but can't receive message like " how is the weather" or "hello"

**Comment by nevido** [comment]
전등 꺼등과 같이 google assistant 명령어 실행은 되는거 같은데
오늘 날씨 어때.. 그 외적으로 답변을 주는 질문에는 아무런 반응이 없습니다
ㅠㅠ

**Comment by eouia** [comment]
보통은 그 반대인데요... config을 보여주세요

**Comment by nevido** [comment]
ㅠㅠ 어제 이것저것 만지다 보니 이젠 아예 안되네요 컨버세이션 에러라고 나오네요

컴피그입니다

var config = {
  address: "localhost",
  port: 8080,
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],
  language: "ko",
  timeFormat: 12,
  units: "metric",

  modules: [{
      module: "alert",
    },
    {
      module: "updatenotification",
      position: "top_bar"
    },
    {
      module: "clock",
      position: "top_left",
      config: {
        dateFormat: "LL dddd",
      }
    },
    {
      module: "calendar",
      position: "top_left",
      config: {
        urgency: 21,
        fetchInterval: 3600000,
        calendars: [{
          url: 'https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics',
          symbol: '대한민국 공휴일',
        }, ]
      }
    },
    {
      module: "currentweather",
      position: "top_right",
      config: {
        location: "Ichon, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.
        locationID: "",
        appid: "" //openweathermap.org의 API key를 입력하세요.
      }
    },
    {
      module: "weatherforecast",
      position: "top_right",
      config: {
        location: "Seoul, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.
        locationID: "",
        appid: "" //openweathermap.org의 API key를 입력하세요.
      }
    },
    {
      module: "compliments",
      position: "lower_third",
      config: {
        compliments: {
          anytime: [ //아무때나
            "오늘도 좋은 하루!"
          ],
          morning: [ //아침
            "좋은 아침!",
            "힘찬 아침!",
            "잘 잤나요?"
          ],
          afternoon: [ //오후
            "안녕하세요!",
            "멋져요!",
            "잘 지내고 있나요!"
          ],
          evening: [ //저녁
            "와우! 잘 지냈나요?",
            "멋져보이네요!",
            "반가워요!"
          ],
          day_sunny: [//맑은 낮

          ],
          day_cloudy: [//흐린 낮

          ],
          cloudy: [//흐림

          ],
          cloudy_windy: [//흐리고 바람

          ],
          showers: [//소나기

          ],
          rain: [//비

          ],
          thunderstorm: [//천둥번개

          ],
          snow: [//눈

          ],
          fog: [//안개

          ],
          night_clear: [//맑은 밤

          ],
          night_cloudy: [//흐린 밤

          ],
          night_showers: [//소나기 밤

          ],
          night_rain: [//비오는 밤

          ],
          night_thunderstorm: [//천둥번개 밤

          ],
          night_snow: [//눈오는 밤

          ],
          night_alt_cloudy_windy: [//흐리고 바람부는 밤

          ],
        }
      }
    },
    {
      module: "MMM-NotificationTrigger",
      config: {
        useWebhook: true,
        triggers: [{
            trigger: "ASSISTANT_ACTION",
            triggerSenderFilter: function (sender) {
              if (sender.name == "MMM-AssistantMk2") {
                return true;
              } else {
                return false;
              }
            },
            triggerPayloadFilter: function (payload) {
              return true;
            },
            fires: [{
              fire: "SHOW_ALERT",
              payload: function (payload) {
                return {
                  type: "notification",
                  title: payload[0].execution[0].type,
                  message: payload[0].execution[0].command
                };
              },
            }, ],
          },
          {
            trigger: "ASSISTANT_HOOK",
            fires: [{
              fire: "SHOW_ALERT",
              payload: function (payload) {
                return {
                  title: "HOOK",
                  message: "Are you saying " + payload.hook + "?",
                  timer: 5000
                };
              },
            }, ],
          },
          {
            trigger: "HOTWORD_DETECTED",
            fires: [{
                fire: "HOTWORD_PAUSE"
              },
              {
                fire: "ASSISTANT_ACTIVATE",
                payload: function (payload) {
                  return {
                    "profile": payload.hotword
                  };
                },
                delay: 200
              },
            ]
          },
          {
            trigger: "ASSISTANT_DEACTIVATED",
            fires: [{
              fire: "HOTWORD_RESUME"
            }]
          },
        ]
      }
    },
    {
      module: "MMM-Hotword",  
      config: {
        snowboy: [{
            hotwords: "smartmirror",
            file: "resources/models/smart_mirror.pmdl",
            sensitivity: '6.0',  //"스마트미러" 마이크 감도 조절
          },
          {
            hotwords: "snowboy",
            file: "resources/models/snowboy.umdl",
            sensitivity: '6.0',  //"스노우보이" 마이크 감도 조절
          },
          {
            file: 'resources/models/jarvis.umdl',
            sensitivity: '0.6,0.60',   //"자비스" 마이크 감도 조절
            hotwords: ['jarvis', 'jarvis']
          }
        ],
      }
    },
    {
      module: "MMM-AssistantMk2",
      position: "top_center",
      config: {
        useScreen: true,
        deviceLocation: {
          coordinates: {
            latitude: 37.57,
            longitude: 126.98
          },
        },
        transcriptionHook: {
          "UNICORN": "unicorn"
        },
        profiles: {
          "default": {
            lang: "ko-KR"
          },
        }
      }
    },
  ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {
  module.exports = config;

**Comment by nevido** [comment]
스노우보이에 pmdl은 제것 가지고 온거고..나머진 건들지 않았습니다

**Comment by eouia** [comment]
https://github.com/eouia/MMM-Hotword#tip
이 부분 config.js 수정해주세요.

그리고 NotificationTrigger를 설치하신 것 보니, 어디에선가 돌고 있다는 옛날 버전 설치 문서를 보신 것 같습니다. 그 후 업데이트가 많이 되어 내용이 많이 바뀌었으니 MMM-AssistantMk2와 MMM-Hotword의 git repository README 보세요.

**Comment by nevido** [comment]
감사합니다 
처음 부터 다시 설치하고 있습니다 moudle부분은 git에 들어가서 readme를 보면서 하고 있습니다
거듭 감사드립니다

**Comment by Marcreed48** [comment]
Doesn’t location TOP_CENTER affect the module?

**Comment by eouia** [comment]
> Doesn’t location TOP_CENTER affect the module?

`center` is using dirty(!) trick to locate module position by force, it makes CSS of some modules to be messed. I have no idea to solve it without break current structure of MagicMirror Region CSS rules.

**Comment by Marcreed48** [comment]
Thank you, I noticed Jaeyong has his Assistant MK2 as top center. I thought
I’d check with you if that’s a problem.

**Comment by eouia** [comment]
I'll close this. have a nice day.
