### ISSUE TITLE
Want to stop playing youtube by hotword

### ISSUE THREAD

**Issue by ReoLusia** [eouia/MMM-AssistantMk2#122]
With setting "pauseOnYoutube : false",

using hotword makes error like this...

[HOTWORD] beings listening.
[HOTWORD] << smartmirror >> is detected.
[HOTWORD] stop listing
Speaker error: 2
Whoops! There was an uncaught exception...
2
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub......

**Comment by eouia** [comment]
That will occur when two or more sound streams from programs be trying to use one output device at same time.
In this case, Youtube playing sound and Assistant Sound (I guess it would be a beep) are trying to use one speaker.
I'm not that kind of expert, So I know there would be ALSA mixer to combine outputs together, but don't know how to use it. Sorry. it's out of my module's job.

(If you are using 2 speaker devices, you can assign each output to each speaker. In that case, you don't need mixer)

**Comment by ReoLusia** [comment]
How about stop function of chime alert?

Is it make structure error in node?

**Comment by eouia** [comment]
To avoid this issue, It's better to use `pulseaudio` or any other sound mixer to mix multiple sound-audio output. that would be better way than mute the beep.

No matter what, To mute beep sound, Remove line 135 of node_helper.js
```
//      this.playChime(cb) .   //comment out or remove this line.
```
But this could make some future issue including update.

**Comment by eouia** [comment]
I'll close this issue, because there is no more feedback. You can leave a continuous issue or new at any time.
Have a nice day.
