### ISSUE TITLE
Conversation Error

### ISSUE THREAD

**Issue by bolish** [eouia/MMM-AssistantMk2#126]
Hi there!

I'm facing below Conversation Error issue,

`0|mm  | [AMK2] assistant ready
0|mm  | [AMK2] Conversation starts.
0|mm  | [AMK2] Assistant Text Response: 
0|mm  | [AMK2] Conversation Error: { Error: 3 INVALID_ARGUMENT: Invalid 'audio_in': audio frame length is too long.
0|mm  |     at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
0|mm  |     at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
0|mm  |     at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
0|mm  |     at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
0|mm  |     at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
0|mm  |     at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
0|mm  |     at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
0|mm  |   code: 3,
0|mm  |   metadata: Metadata { _internal_repr: { 'content-disposition': [Array] } },
0|mm  |   details: 'Invalid \'audio_in\': audio frame length is too long.' }
`

I've already read a lot regarding the fact that it could be linked to mic configuration issue.
Nevertheless, my issue is happening randomly after several minutes. It's not there at start so I doubt it's linke to the config itself...

I have my config. setted up as below into .asoundrc

`
pcm.!default {
   type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,1"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
`

because aplay -l output is ,

`aplay -l
**** Liste des Périphériques Matériels PLAYBACK ****
carte 0: ALSA [bcm2835 ALSA], périphérique 0: bcm2835 ALSA [bcm2835 ALSA]
  Sous-périphériques: 7/7
  Sous-périphérique #0: subdevice #0
  Sous-périphérique #1: subdevice #1
  Sous-périphérique #2: subdevice #2
  Sous-périphérique #3: subdevice #3
  Sous-périphérique #4: subdevice #4
  Sous-périphérique #5: subdevice #5
  Sous-périphérique #6: subdevice #6
carte 0: ALSA [bcm2835 ALSA], périphérique 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0
`

and arecord -l output as this, 

`arecord -l
**** Liste des Périphériques Matériels CAPTURE ****
carte 1: C170 [Webcam C170], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 0/1
  Sous-périphérique #0: subdevice #0
`

- all my rec and player test are working fine.
- my config.js is mentionning the right players.
- I just didn't put any device name into MMM-Hotword, but it seems not to be an issue as default setting is empty anyway.
- i honestly don't know how to move forward because despite being not so bad at searching on google and trying things, I do clearly not understand how everything is working...I'm learning step by step thanks to MagicMirror community. 

The only thing which seems confusing to me is the fact that it seems alasmixer seems to never save my config. (seems to be known issue on internet). But even that, I believe it's not the issue, as Hotword and AMK2 are always perfectly working during a certain period of time before crashing.

Hope someone could help me for analysis and debugging!!

Thanks

NOTE : Special thanks to @eouia for this great module (and all your modules in general!!)

**Comment by eouia** [comment]
Sorry, I cannot help you about ALSA or any sound configuration of the device. I have no knowledge to teach others about it. My knowledge about it is very limited.

**Comment by bolish** [comment]
OK, I will try on MM forum and if anything positives comes out, I will link the path here so it can help others too. Regards

**Comment by eouia** [comment]
I'll close this issue. Have a nice day.

**Comment by bolish** [comment]
OK, so for you it's 100% sure that the issue is mic configuration related, and not related to AMK2 itself, correct?

**Comment by eouia** [comment]
I'm not sure anything. But at least, others can use anyway.
