### ISSUE TITLE
hook phrase personnal option

### ISSUE THREAD

**Issue by bolish** [eouia/MMM-AssistantMk2#127]
Hi,

It's not really an issue in itself as @eouia already warned us about.

> Take care of Side effects. If hooked phrase is reserved or used by Assistant, there could be unintended side effects. By exmaple, don't assign add event as hook phrase. This might be used Google Assistant itself. She will try making an event to your Google Calendar but you hooked this process, so failed. And that makes unintended continuous conversations.

Nevertheless, I was wondering if it would not be possible to add an additional parameter to transcriptionhook in order to avoid that ,

Kind of "disable Assistant hook: true / false" for each hook.

When "true", this would make sure that AMK2 will not go searching for Google response but will 100% rely on the command defined by the user itself into config.js.

Is that clear enough? And also, would it be possible?
If not, how are you dealing with it? Workarounds?

(I'm using MK2 for Spotify, show and hide pictures on my mirror, etc...). Most of the time, an existing google hook is very similar and it messes up...

Regards

**Comment by eouia** [comment]
Unfortunately, it's impossible.
Transcription itself and response(and reaction) from Google Assistant Cloud cannot be divided. transcriptionHook is a kind of hack, so there is a limitation.

When a user says something, the recording binary data would send to Google Cloud. Google analyze it and return response(and reaction) including vocal response, visual response, transcription, and some other stuff, It means, transcription is only a part of response result. It cannot be controllable.

Use gAction.

**Comment by bolish** [comment]
Thanks for feedback Sean.
Noted, I will then try gAction later on!
