### ISSUE TITLE
screen_onoff and hide_all_modules

### ISSUE THREAD

**Issue by nevido** [eouia/MMM-AssistantMk2#129]
시간이 얼마 지나면 화면에  우측 날씨 정보만 보입니다.
이거 어떻게 깨우는지요?
hide_and_show_all_modules.js
에서 패턴부분을 한글로 바꾸로 음성으로 명령을 넣으면 될까요?
그리고 유투브 화면이 play될때 중지할순 없나요?
예전에는 magic미러말구..eva~ git 에서는 명령어는 파일로 만들어 play부분도 컨트롤이 가능했던거 같은데..ㅠㅠ
어떻게 해야하죵...

**Comment by eouia** [comment]
1) configuration에서 onIdle이 꺼져 있는지 확인하세요. 이번 업데이트에서 디폴트로 disabled되도록 하긴 했는데, 만약 아니라면 onIdle에서 command를 null로 주거나 timer를 0으로 주세요. 
onIdle은 일정시간동안 음성명령이 없으면 작동되는 기능인데,(default config설명에 써있음) 디폴트 샘플로, 30분간 명령을 안내리면 모듈을 숨기는 기능을 예시로 넣어놨는데 많이들 당황하셔서 이번 업데이트에서는 디폴트로 그냥 빼버렸어요.

2) transcription이 한글로 나온다면 그렇게 바꾸셔도 됩니다. 다만 구글어시스턴트의 자체 예약어들은 사용에 주의해주세요.

3) 터치 인터페이스가 있다면 그냥 화면부분을 터치하면 됩니다.
혹은 다른 입력수단이 있으시면 ASSISTANT_CLEAR 노티피케이션을 전달해주면 됩니다.
아무것도 없으시면, 
pauseOnYoutube:false로 설정한 후, 핫워드를 다시 말해주시면 입력모드로 바뀌면서 유튜브 재생은 멈출겁니다.

**Comment by nevido** [comment]
^^ 감사합니다 ~~
