### ISSUE TITLE
electro-rebuild fail

### ISSUE THREAD

**Issue by mandy3d** [eouia/MMM-AssistantMk2#13]
I tried everything. It fails during electro-rebuild.  I've tried changing my node version I've reinstalled 100 times. I've done upgrade-update and I deleted that folder everyone talks about.

`An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.11.2 | linux | arm
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/pi/.electron-gyp/.node-gyp/iojs-2.0.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/pi/.electron-gyp/.node-gyp/iojs-2.0.0',
gyp info spawn args   '-Dnode_gyp_dir=/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/pi/.electron-gyp/.node-gyp/iojs-2.0.0/<(target_arch)/iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]`

**Comment by eouia** [comment]
It's a well-known issue. The main reason is "node-grpc" didn't make the proper binaries after their new module upgrading distribution.
You can downgrade node-grpc version 1.13 and try it.

**Comment by eouia** [comment]
https://github.com/eouia/MMM-AssistantMk2#some-troubleshootings
Those are All I can suggest.

**Comment by mandy3d** [comment]
Thanks! Sorry I didn't spot it sooner. I got everything running now.

**Comment by eouia** [comment]
Nice to you. I’ll close this issue.
