### ISSUE TITLE
Font and div size issue

### ISSUE THREAD

**Issue by ruhulayaan** [eouia/MMM-AssistantMk2#130]
![IMG_20190328_135515](https://user-images.githubusercontent.com/48345991/55142064-c88ef380-5161-11e9-8ec4-cabcacb73d1b.jpg)
Font issue with rotated screen. Text overlapping and going beyond the screen border. Where to set the font size according to the display width. I am using a 14" x 10" inch monitor. How can i adjust the assistant response box within the width of monitor and also decrease the font size. Thanks

Please check the images uploaded on imgur
https://imgur.com/a/78zfzmy

**Comment by eouia** [comment]
How's your resolution of screen? visual output assumes screen should have enough width to display. (Sorry that is made by Google itself) The visual output itself cannot be adjusted.
So I provided some trick. 
```
screenZoom: "80%", // Adjust responseScreen to your mirror size. (80% is default for 1080pixel width)
```
In your MMM-AssistantMk2 configuration, add this field then adjust it to your size.

**Comment by ruhulayaan** [comment]
Actually i had changed some settings in module css file. After reverting back to default, i was able to set the response window according to my size. And also setting the screenZoom at 75% worked perfectly. Thank you
