### ISSUE TITLE
node helper crash if defined sound player not installed.

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-AssistantMk2#134]
mpg321 (default) not installed, after 1st ding request, nothing works.. 

should add code to detect (which ..) if player is installed, and put out debug message vs crash..

**Comment by eouia** [comment]
Good idea. Thanks for your suggestion.
But Let's think about this. if defined player is not installed successfully, Avoiding error is meaningless and useless. The only way to solve this problem should be installation proper player. So Just avoidance is not enough.
Of course, it's better to show some useful message for user. But it needs more codes and complexity. I'll consider your suggestion on next updates. but cannot guarantee.

**Comment by sdetweil** [comment]
yes, but I didn't see any instructions for media player..  i 'assumed' some default would be installed if uyour module needed to make sounds... 

not see 'error 2' .. which is meaningless...

**Comment by eouia** [comment]
I'll close this issue. This would be solved on next updates. (I'll remove dependency for sound player)
