### ISSUE TITLE
as hung after requesting 'show map'

### ISSUE THREAD

**Issue by sdetweil** [eouia/MMM-AssistantMk2#136]
voice bubble shows 'show map'.
arecord no longer running
notification sent out 
 'ASSISTANT_UNDERSTOOD'
now as hung.. \
what was SUPPOSED to happen..

only Hotword and As installed

**Comment by eouia** [comment]
How's your backend log? Usually, in that case there could be some errors. I need that info to guess what happend.

**Comment by sdetweil** [comment]
backend log?   i have output fron node_helper and  UI dev console (ctrl-shift-i) log... nothing shows error

[HOTWORD] stops listening
MMM-Hotword helper notification PAUSE received
assistant play chime=/home/odroid/MagicMirror/modules/MMM-AssistantMk2/resources/connection.mp3
assistant play sound file=/home/odroid/MagicMirror/modules/MMM-AssistantMk2/resources/connection.mp3
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response:
[AMK2] Transcription: show  --- Done: false
[AMK2] Transcription: Sean  --- Done: false
[AMK2] Transcription: show me  --- Done: false
[AMK2] Transcription: show map  --- Done: false
[AMK2] Transcription: show map  --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: show map  --- Done: true
{ requestId: '5c9a7ec1-0000-27ff-a01d-089e082e1994' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5c9a7ec1-0000-27ff-a01d-089e082e1994' }
[AMK2] Assistant Text Response:
assistant play response=/home/odroid/MagicMirror/modules/MMM-AssistantMk2/tmp/1553873948478.mp3

.......
developers window log
MMM-Hotword socket notification DETECTED received
module.js:154 clock received a module notification: ASSISTANT_ACTIVATE from sender: MMM-Hotword
module.js:154 calendar received a module notification: ASSISTANT_ACTIVATE from sender: MMM-Hotword
MMM-SleepWake.js:58 sleep-wake in notificationReceived
MMM-SleepWake.js:59 notification='ASSISTANT_ACTIVATE'
MMM-SleepWake.js:60 sender=[object Object]
module.js:154 MMM-ImagesPhotos received a module notification: ASSISTANT_ACTIVATE from sender: MMM-Hotword
newsfeed.js:340 newsfeed - received notification: ASSISTANT_ACTIVATE
newsfeed.js:391 newsfeed - unknown notification, ignoring: ASSISTANT_ACTIVATE
module.js:154 clock received a module notification: HOTWORD_PAUSE from sender: MMM-AssistantMk2
module.js:154 calendar received a module notification: HOTWORD_PAUSE from sender: MMM-AssistantMk2
MMM-SleepWake.js:58 sleep-wake in notificationReceived
MMM-SleepWake.js:59 notification='HOTWORD_PAUSE'
MMM-SleepWake.js:60 sender=[object Object]
module.js:154 MMM-ImagesPhotos received a module notification: HOTWORD_PAUSE from sender: MMM-AssistantMk2
newsfeed.js:340 newsfeed - received notification: HOTWORD_PAUSE
newsfeed.js:391 newsfeed - unknown notification, ignoring: HOTWORD_PAUSE
MMM-Hotword.js:58 MMM-Hotword notification HOTWORD_PAUSE received
MMM-Hotword.js:75 MMM-Hotword socket notification NOT_PAUSED received
module.js:154 clock received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 calendar received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
MMM-SleepWake.js:58 sleep-wake in notificationReceived
MMM-SleepWake.js:59 notification='HOTWORD_LISTENING'
MMM-SleepWake.js:60 sender=[object Object]
module.js:154 MMM-ImagesPhotos received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
newsfeed.js:340 newsfeed - received notification: HOTWORD_LISTENING
newsfeed.js:391 newsfeed - unknown notification, ignoring: HOTWORD_LISTENING
module.js:154 clock received a module notification: ASSISTANT_UNDERSTOOD from sender: MMM-AssistantMk2
module.js:154 calendar received a module notification: ASSISTANT_UNDERSTOOD from sender: MMM-AssistantMk2
MMM-SleepWake.js:58 sleep-wake in notificationReceived
MMM-SleepWake.js:59 notification='ASSISTANT_UNDERSTOOD'
MMM-SleepWake.js:60 sender=[object Object]
module.js:154 MMM-ImagesPhotos received a module notification: ASSISTANT_UNDERSTOOD from sender: MMM-AssistantMk2
newsfeed.js:340 newsfeed - received notification: ASSISTANT_UNDERSTOOD
newsfeed.js:391 newsfeed - unknown notification, ignoring: ASSISTANT_UNDERSTOOD
MMM-Hotword.js:58 MMM-Hotword notification ASSISTANT_UNDERSTOOD received

arecord no longer running  assistant voice bubble shows 'show map'

**Comment by sdetweil** [comment]
this time, heard 'john mayer' , something popped up some info on screen... with his pic, and sguuestions of additional speech items.. that window eventually went away.... but now hung.. arecord not running,
speech bubble shows 'john mayer'

**Comment by eouia** [comment]
You should have "[AMK2] Conversation Completed" in the log on normal conversation. but not. It means I think, you have an abnormal termination of player program. What are you using? mpg321?

**Comment by sdetweil** [comment]
yes mpg321  .. ok, my fault.. I commented out part of play response to save mp3 files and didn't get the () on cb()... working now.. will close
