### ISSUE TITLE
Help with enabling screen on and off commands

### ISSUE THREAD

**Issue by pourchris** [eouia/MMM-AssistantMk2#139]
I dont know if this is the correct place to ask, but im looking for help for using the screen on and off commands. As someone with 0 programming knowledge or experience I can not figure out how to enable these commands. I'm sure it is perfectly explained in the set up but im just not sure what i need to do. Everything else is working perfectly.
Thank You

**Comment by eouia** [comment]
Monitor on/off depends on user's environment, so there could be a different way with my suggestion.
First, which command could be available for your environment.
I'll assume `vcgencmd display_power 0` could be available for your display off. And your MMM-AssistantMk2 is updated to latest version.
If so;
```sh
cd ~/MagicMirror/modules/MMM-AssistantMk2/scripts
chmod +x *.sh
```
Then, add or modify below into configuration.
```js
recipes:["screen_onoff.js"],
```

It will accept two voice commands "wake up" and "go to sleep".

**Comment by eouia** [comment]
I'll close this issue, coz there is no other feedback.
