### ISSUE TITLE
Doesn’t respond during Youtube video 

### ISSUE THREAD

**Issue by jasb1011** [eouia/MMM-AssistantMk2#140]
Hello again, the problem that I currently seem to be having is that every time I try to get the YouTube video to pause the assistant doesn’t respond, and when ever I get an video error , the smart Mirror doesn’t automatically go back to the home screen, I have to manually do it. Please help

**Comment by eouia** [comment]
What kind of video error? If video loading fails, it will be terminated after some secs. But if you mean API or JS error, the termination won't be done.
If you want to activate Hotword(and AMK2), you can set `pauseOnYoutube` to false. But I will not recommend. Unless you have far-away mic, the audio of youtube playing will activate your Hotword, and stop the video. It will prequently happen, and will make some annoying.

Anyway, I'll drop off YT player feature on next version. That feature too often be interrupted by front-end error of other modules or itself. Originally it is not included Assistant SDK. Maybe I can offer alternatives, however That feature will not be included by default.

**Comment by omaralomar** [comment]
when i set pauseOnYoutube to false , it only open youtube on a song but not playing it , 
how i can play it without exiting youtube window ? 

also it's important for example when video is playing and saying stop 
could recognize "Stop" word so it cancel the youtube video and go back

**Comment by matrix98053** [comment]
> 
> 
> when i set pauseOnYoutube to false , it only open youtube on a song but not playing it ,
> how i can play it without exiting youtube window ?
> 
> also it's important for example when video is playing and saying stop
> could recognize "Stop" word so it cancel the youtube video and go back

Hi, I noticed if pauseOnYoutube is set to false, the video will stop and close if you just say the Hotword again.

**Comment by eouia** [comment]
I'll close this issue. guys, wish a good luck.
