### ISSUE TITLE
AssistantMk2 is not reacting to Hotword

### ISSUE THREAD

**Issue by Xavi1x7** [eouia/MMM-AssistantMk2#141]
Hey, I have a problem with AssistantMk2 and MMM-Hotword,

MMM-Hotword is detecting the hotword but MMM-AssistantMk2 isn't reacting.

https://hastebin.com/azugaxonik.cs (The console output)
https://hastebin.com/esobotobet.php (The config.js)

**Comment by eouia** [comment]
You've missed on redefining notification.
```
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
```
NOT `ASSISTANT_ACTIVATE`. (Yes. that is the common trap. sorry.)

**Comment by Xavi1x7** [comment]
Yeah that was the problem thanks, but I already have the next problem, I tried to use the GAssistant with the Google Home App, but my device doesn't appear in the App (already done that: https://github.com/eouia/MMM-AssistantMk2/wiki/Usage#register-your-mirror-as-google-assistant-related-device).

The console output doesn't show anything.

**Comment by eouia** [comment]
> The console output doesn't show anything

what it means? 

If there was no error during process, I have no idea at this time.

**Comment by Xavi1x7** [comment]
I meant no errors, is there a other possibility to install skills to this device?

**Comment by eouia** [comment]
this is not the alternative real google home. Some features of real google home are blocked, limited, or not implemented yet by google itself (broadcasting, news, timer, podcasting and music. and some of 3rd party actions)
The purpose of the sdk which is used on this module is to give voice command ability with assistant. 
But most of public actions would be available on this sdk also. (the concept of google action is slightly different with skill of alexa). You can make your custom device action by yourself.

**Comment by eouia** [comment]
I'll close this issue, coz there is no other feedback. Wish a good luck.
