### ISSUE TITLE
Modudules overlap this one tried z-index

### ISSUE THREAD

**Issue by dxfan227** [eouia/MMM-AssistantMk2#144]
Both the assistant response window and youtube videos are not "on top" of my other modules. The z-index doesn't seem to work. I was able to put a black background on by using the div id of .assistant-main-cards   what is the equivalent for the youtube player? how do I get it "on top"

**Comment by eouia** [comment]
Which region did you put your module on? And Which modules are overlayed over Assistant?

**Comment by dxfan227** [comment]
Center region

**Comment by dxfan227** [comment]
Sorry I think I fixed it somehow... I changed the z index of something like assistant.cards

**Comment by eouia** [comment]
Due to tricky MagicMirrors region system, `center` is not so good position for dynamic width-variable modules like this. I recommend you use `fullscreen` or `bar` region instead `center`.
Anyway, the structure of CSS will be changed on next updates to avoid this issue.
