### ISSUE TITLE
show_hide_modules

### ISSUE THREAD

**Issue by matrix98053** [eouia/MMM-AssistantMk2#145]
I am not so familiar with programming.
I want to show and hide diffrent modules and I saw recipes to do that in the default configuration.
Can you maybe send me the recipes file to show and hide currentweather module?

Thanks

**Comment by eouia** [comment]
This is an example for **Hiding CurrentWeather**

```
command: {
  "HIDEWEATHER": {
    moduleExec: {
      module:(params, key)=>{
        return ["currentweather"] 
      },
      exec: (module, params, key) => { 
        module.hide()
      }
    }
  },
},

transcriptionHook: {
  "HOOK_HIDE_WEHATER": {
    pattern: "hide weather",  // When you say "hide weather",
    command: "HIDEWEATHER" // command "HIDEWEATHER" will be executed
  },
}
```
I believe you can expand.
