### ISSUE TITLE
youtube

### ISSUE THREAD

**Issue by matrix98053** [eouia/MMM-AssistantMk2#146]
Thanks for the great work!!!
Is it possible to play youtube in a frame and not fullscreen?

Thanks

**Comment by eouia** [comment]
Adjust CSS. Copy belows into your `custom.css` then adjust as what you need. 
https://github.com/eouia/MMM-AssistantMk2/blob/859d27622e71ef8005e0aa31f93592eadfb2fdd6/MMM-AssistantMk2.css#L34-L64


but I'll remove this feature on next update.

**Comment by matrix98053** [comment]
Thank you very much! 
Works perfect.
Why are you removing youtube feature?

**Comment by eouia** [comment]
Youtube playing feature is not included in original SDK. I added it for just convenience and showing possibility of this module, not so serious main feature. This module(and SDK based on) is not designed to be alternative real Google Home device. The purpose was controlling device with voice command, not being youtube machine. But many issues from this feature makes me somewhat annoying. Even though myself don't use this feature at all.
RPI has not such a good device for playing YT video. And not experienced audio setup could make audio crash on this module when playing YT. Anyway, RPI is not my main device for MM anymore.

However, I'll leave the interface for YT for someone who wants to make his own YT Player module controllable by voice command. Anyway, playing itself on this module will be dropped.
