### ISSUE TITLE
Formatting is a tiny bit off in the assistant window

### ISSUE THREAD

**Issue by dxfan227** [eouia/MMM-AssistantMk2#147]
Please see the photo below. As you can see the photo of Mr Bill Gates is cut off and in a slightly strange place. This is true for any photo I ask about. 

https://pasteboard.co/IbpKkgw.jpg

**Comment by eouia** [comment]
Just your width of screen is not so wide for Assistant Screen Response. Adjust `screenZoom` of MMM-AssistantMk2 configuration.
```
config: {
...
   screenZoom: "70%", // Add this into your MMM-AssistantMk2 configuration section and adjust it.
...
}
```

https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration#full-detailed-version-dont-panic-detailed-information-will-be-followed

**Comment by dxfan227** [comment]
Thank you. Was able to fix by setting width higher
