### ISSUE TITLE
asking for images

### ISSUE THREAD

**Issue by matrix98053** [eouia/MMM-AssistantMk2#148]
I notices when i ask for pictures of eg. a Lion. It looks like a Google seach result link that displays. It does not display the images itself.

Thanks

**Comment by eouia** [comment]
Google Assistant SDK has a limitation still. It is beta stage currently. That feature is served for only which can browse url additionally like SmartTV or Lenovo smart screen at this time.

**Comment by matrix98053** [comment]
Hi, just checking... Is there a solution yet? I want to say: Computer - show me some pictures of lion and then see the images, but instead i get a response: sure, here are some pictures of lion, but it only displays a link. If i ask Computer - how fast is a lion, i get the answer read out to me and i can read it on the screen myself and there is an image of a lion displayed. Thanks in advance

**Comment by eouia** [comment]
Check @bugsounet 's addon `Assistant2Display`.
https://github.com/bugsounet/MMM-Assistant2Display

**Comment by matrix98053** [comment]
Thank you very much, it is working perfect!
