### ISSUE TITLE
Show transcript from other devices

### ISSUE THREAD

**Issue by ferferga** [eouia/MMM-AssistantMk2#149]
Good afternoon

I have been trying to setup many different assistant modules in my Magic Mirror without success in what I want to achieve, so I would like to ask first before installing if it's not much of a problem, as I couldn't find anything about this in this project either.

I would like the mirror to show the transcript of the text and play the animation whenever I activate my Google Home or phones in the same network. I basically got stuck in my other attempts while trying to setup a mic and an speaker, which is useless for what I'm trying to do as I just want the visual feedback of announcements and queries (which is something that's possible with Google SDK as far as I know)

Thank you very much in advance for stopping at my issue :).

**Comment by eouia** [comment]
It's not possible. Transcription(And the response) will be returned only to origin. Conversation itself is not transferrable. Of course, some additional result will be transferred to your real Google Assistant App, because your Google Home (or any other Assistant device) cannot handle some response data by limitation of device feature. But basically, you cannot get transcription from other devices with SDK.

But I don't know why you need this. I think it's not the real final goal which you really want. I think you might need some google action for doing something on Mirror when you say something. Unfortunately, I have no good idea at this moment.

**Comment by ferferga** [comment]
My goal is to have a visual and animated hint for visitors and family that the room where the mirror will be located has an active Assistant device working. 
As you said, I was guided by the experience of asking something to my home and having the visual output of the transcript and media in my phone and other devices. I tested it making sure my phone's microphone could hear me, but not well, and my phone made a different query from the Google Home, so it seems that the transcript you can see in other devices is just a transcript of what they listened.

I suppose it's not possible as well to know if another device was activated in the network, right? So, to have it clear, it's only possible to know what media is being casted into other devices (if the device's settings are set to announce it), right? Because I would like to also show the song that it's being casted in my network, just like you can see it in the Home App or Home Hub device. 

I know for sure from the Assistant docs that it's possible to send media, pause and resume it from the Python SDK, but nothing about retrieving the song data (I just found the specific API for this in Android and it's called MediaReceiver)

**Comment by eouia** [comment]
As far as I know, this `Assistant SDK for device(service - grpc)` has no feature to receive other conversation(or stream) data from outside of the device. Maybe you saw `Assistant SDK for device(library - python)` and it might be possible on that.(I don't know exactly) But grpc SDK has no spec about that. So it cannot have the features -`broadcasting`, `alarm`, `streaming music`,... which real Google Home has.

I think you'd better to purchase `Lenovo Smart Display`. :D

**Comment by eouia** [comment]
Additionally, The real google home implementation is not performed with only this SDK. there are many extra APIs to implement features. Anyway, I have no idea to get other conversation data with this SDK.

**Comment by ferferga** [comment]
> As far as I know, this `Assistant SDK for device(service - grpc)` has no feature to receive other conversation(or stream) data from outside of current conversation. Maybe you saw `Assistant SDK for device(library - python)` and it might be possible on that.(I don't know exactly) But grpc SDK has no spec about that. So it cannot have the features -`broadcasting`, `alarm`, `streaming music`,... which real Google Home has.
> 
> I think you'd better to purchase `Lenovo Smart Display`. :D

Yes, I looked at Python SDK, my fault. Buying a Lenovo Display is the easy way, but not the challenging and customised one :D. I suppose I will need to look deeper into this and try to make my own module.

Thank you very much for your replies! 👍 :)
