### ISSUE TITLE
Potential Security Issue With Module

### ISSUE THREAD

**Issue by dxfan227** [eouia/MMM-AssistantMk2#150]
Hello:

I am using the module and really like it. I do however have a potential security issue I would like to bring up. I used my personal google account when setting up the device/api etc..etc.. 

The module seems to be linked to my personal data with this, for example if I ask to "show me a photo of the sunset" it actually serves up my personal photos on google photos. Is there any way to break this link so it does not do that?

**Comment by eouia** [comment]
Make an additional account on Google just for using Assistant, then use it.

**Comment by dxfan227** [comment]
Hmm ok. I will try. Don’t want to mess it all up since I just got it all working lol.

**Comment by eouia** [comment]
I'll close this issue. Wish a good luck!
