### ISSUE TITLE
How do i get started?

### ISSUE THREAD

**Issue by krismaelo** [eouia/MMM-AssistantMk2#151]
Hi, i'm sorry for ask this kind lf thing but think of me as a firstimer, i already git cloned the MMM-AssistantMk2 to the modules folder in MagicMirror folder, and installed everything i saw in the readme and edited the config.js, but it doesn't work and i want to make it from 0 but i dont even know how to get started, can you Help me? Thanks

**Comment by eouia** [comment]
What is shown on MM screen? And what is shown also in your log?
You can contact me on real time with Telegram (Telegram Id : @eouia). Convenient time would be 10am ~ 06pm on Berlin timezone.

**Comment by krismaelo** [comment]
Ok, i'll talk to you
