### ISSUE TITLE
Assistant Won't Fully Boot Up

### ISSUE THREAD

**Issue by DopeEthiop** [eouia/MMM-AssistantMk2#152]
When I boot up my MagicMirror, everything else runs except for the Assistant module. I have my mic and speaker connected and the config lines are the defaults ones from the configuration guide. Below is the terminal output after running "npm start".

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: MMM-OpenmapWeather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Remote-Control
Initializing new module helper ...
Module helper loaded: MMM-Screencast
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Remote-Control
Starting node helper for: MMM-Remote-Control
Connecting socket for: MMM-Screencast
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
MMM-Hotword started
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/xxxxxxx%40gmail.com/private-9c9743762fc9079e395b37fba457c612/basic.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[HOTWORD] begins listening.
DIAL Server is running on PORT 8569
[AMK2] Temporal storage directory is clearing.

**Comment by DopeEthiop** [comment]
It continues to stay at this output until I stop the MagicMirror from running.

**Comment by eouia** [comment]
Log says nothing wrong. HOTWORD seems being waiting your wake words.
To check HOTWORD is working, set configuration `testMic:true` on MMM-Hotword config section.
And try again.

**Comment by DopeEthiop** [comment]
I set `testMic:true` both on the MagicMirror config file and the MMM-Hotword.js config file, but I am still receiving the same problem as before.

**Comment by eouia** [comment]
but which problem? your log says nothing wrong. so what is your problem? describe your problem more clearly

**Comment by DopeEthiop** [comment]
The problem is the output code stops at "[AMK2] Temporal storage directory is clearing." instead of showing that Hotword is activated and currently listening. I posted below of sample output from when it used to work. It would constantly be be detecting silence, then detect a sound, detect the trigger word, and continue on to the process of capturing the command and outputting something through Assistant.



Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ...
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
MMM-Hotword started
Sockets connected & modules started ...
Launching application.
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins listening.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] << jarvis >> is detected.
[HOTWORD] stops listening
[HOTWORD] Still Silence.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response:
[AMK2] Transcription: what --- Done: false
[AMK2] Transcription: what's --- Done: false
[AMK2] Transcription: what's 2 --- Done: false
[AMK2] Transcription: what's 2 + --- Done: false
[AMK2] Transcription: what's 2 + --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: what's 2 + 2 --- Done: false
[AMK2] Transcription: what's 2 + 2 --- Done: false
[AMK2] Transcription: what's 2 + 2 --- Done: true
{ requestId: '5ca6984e-0000-24d4-9e29-089e08251004' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5ca6984e-0000-24d4-9e29-089e08251004' }
[AMK2] Assistant Text Response:
[AMK2] Conversation Completed
[HOTWORD] begins listening.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[HOTWORD] Still Silence.
[HOTWORD] Sound Captured.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.
[HOTWORD] Sound Captured.
[HOTWORD] Sound Captured.
[HOTWORD] << jarvis >> is detected.
[HOTWORD] stops listening
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response:
[AMK2] end-of-utterance
[AMK2] Transcription: what --- Done: false
[AMK2] Transcription: what's --- Done: false
[AMK2] Transcription: what's the --- Done: false
[AMK2] Transcription: what's the cat --- Done: false
[AMK2] Transcription: what's the capital --- Done: false
[AMK2] Transcription: what's the capital --- Done: false
[AMK2] Transcription: what's the capital of --- Done: false
[AMK2] Transcription: what's the capital of --- Done: false
[AMK2] Transcription: what's the capital of --- Done: true
{ requestId: '5ca69077-0000-2a0f-98bd-089e0822ae80' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5ca69077-0000-2a0f-98bd-089e0822ae80' }
[AMK2] Assistant Text Response:
[AMK2] Conversation Completed
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response:
[AMK2] Transcription: miss --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: missy --- Done: false
[AMK2] Transcription: Michigan --- Done: false
[AMK2] Transcription: Michigan --- Done: true
{ requestId: '5ca69b62-0000-203c-9312-94eb2c1f78f0' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5ca69b62-0000-203c-9312-94eb2c1f78f0' }
[AMK2] Assistant Text Response:
[AMK2] Conversation Completed
[HOTWORD] begins listening.
[HOTWORD] Still Silence.
[HOTWORD] Still Silence.

**Comment by eouia** [comment]
Hmmm. Can you send me your configuration? (eouia0819@gmail.com)

**Comment by DopeEthiop** [comment]
I just sent it to you.

**Comment by eouia** [comment]
Very weird, Nothing special seems wrong.
Anyway, We need to check things one-by-one. First, we should confirm MMM-Hotword working.
1) Disable all the modules except `MMM-Hotword` (Even MMM-AssistantMk2). You can add `disabled:true` or just comment out.
2) Then, add this into your MMM-Hotoword config section.
```
record: {
        recordProgram : "arecord",  
        device        : "plughw:0",
        verbose : true, // < - Add this into `record` section
 },
```
Then, Let's see what's going on.

**Comment by eouia** [comment]
One more thing. Check your mic device. Is it really `plughw:0` ? Usually, default RPI sound card is using `CARD:0` so, if you atattched USB mic, it will usually have `CARD:1` (plughw:1). You can check it by `arecord -l`

**Comment by DopeEthiop** [comment]
I checked to make sure it was the right soundcard at it is "card 0". I added the line of code to the config file while deleting all the other modules except Hotword. I ran it and below is the terminal output before closing the MagicMirror.

> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-Hotword
MMM-Hotword started
Sockets connected & modules started ...
Launching application.
Recording 1 channels with sample rate 16000...
[HOTWORD] begins listening.
End Recording: 463.585ms

**Comment by eouia** [comment]
ok. at least we are advanced. try to use other program - "rec" instead "arecord".

**Comment by DopeEthiop** [comment]
I changed the recordProgram to "rec" and below is the terminal output I received after starting the MagicMirror.

> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-Hotword
MMM-Hotword started
Sockets connected & modules started ...
Launching application.
Recording 1 channels with sample rate 16000...
[HOTWORD] begins listening.
End Recording: 355.671ms

**Comment by DopeEthiop** [comment]
Wow, I just fixed my problem. I went into my "PulseAudio" app settings, went into my "configuration" tab and then turned off my Microphones profile. After doing that and resetting the MagicMirror with the original config file, everything works. Thanks again for the help! I really appreciate you taking the time out of your day to help me with this issue.

**Comment by eouia** [comment]
Nice to hear it!
