### ISSUE TITLE
Google assistant react to other word

### ISSUE THREAD

**Issue by bastos5** [eouia/MMM-AssistantMk2#154]
Hello Hello,

its stange because Google assistant react to my hotword but when i speak with friends. It react also to other word other than my hotword. ( the sound to start speaking is played).

Also, i have another question. It is possible to add an hotword just to allow google assistant to work. Like this sequence :  "Hotword", google assistant is allowed to start recording "Hotword" google is allowed to listen, "hotword" google stop listening. 

Im not sure if im clear. But anyway,
Have a good afternoon,

Bastien

**Comment by DanielSchacht129** [comment]
same problem for me :)

**Comment by eouia** [comment]
That is not AMK2 issue. Hotword detector depends on Snowboy(http://snowboy.kitt.ai). The universal models ("smart mirror" or "jarvis") are made for anonymous voices universally. (so it is called as Universal model).
So sometimes it could make unintended mis-behaviors when you says similar words or even not similar at all. (I have no idea which algorithm they use to detect various vocal pattern).
Solution could be;
1) Adjust sensitivity. warning; too high or too low sensitivity makes problem of not-detected. Find your own best values for your environment by trying many times.
2) Or, make your own personal model (.pmdl) to fit your voice. You can find the way how to make in snowboy website.

Second Issue;
That is not a good approach. In that case, all noise or other's speech also be transferred to Google Server. Trust me. It could make more confusing situation.
Besides, if Google think some continuous conversation be needed, it will ask you and you can answer without hotword. (`continuousConversation` feature) You can test it by `create event to my calendar` phrase. It will ask title and time, and you can converse without hotword.

Anyway, I'll add some feature - `chance to ask again without hotword` on next update. It will be released a few days or weeks.

**Comment by bastos5** [comment]
Thank you very much :).

Bastien.
