### ISSUE TITLE
Vocal spotify command issue

### ISSUE THREAD

**Issue by bastos5** [eouia/MMM-AssistantMk2#155]
Hello hello,

Each time i use this pattern below, the command works but the module spotify begins to disapear like its inactive (i have the same problem with Spotify_pause and spotify_search, the few i have created). And unfortunaly no command work anymore after. 

have you an idea ? thank you

`var recipe = {
  transcriptionHook: {
    "SPOTIFY_PLAY": {
      pattern: "lance spotify",
      command: "SPOTIFY_PLAY"
    }
  },
  command: {
	  "SPOTIFY_PLAY": {
            notificationExec: {
              notification: "SPOTIFY_PLAY"
							  }
                     }
	       }	
}

exports.recipe = recipe // Don't remove this line.`

Thanks,
bastien

**Comment by eouia** [comment]
I've sent a mail.

**Comment by eouia** [comment]
I'll close this issue.
