### ISSUE TITLE
Custom voice responses

### ISSUE THREAD

**Issue by KinsoKei** [eouia/MMM-AssistantMk2#156]
Hi, 
I am searching for a way to make custom responses to my recipes.
The recipe itself is working (Turn screen off, etc.) but how can you make it speak out a text?

I've found ASSISTANT_SAY... is this the right way? Or just a notification? And how can I implement this?

Thank you in advance.

**Comment by eouia** [comment]
If you are using `google custom action` to make your command, simple voice response is available. but if you are using `transcriptionHook`, it is not supported. Of course you can use `ASSISTANT_SAY` but that is some tricky way not trustable. Or you can make your module to say something with TTS modules(MMM-TTS, MMM-GoogleTTS) but that is out of range of this module.

**Comment by KinsoKei** [comment]
I'm using the custom actions then.
Thanks for the quick response

**Comment by KinsoKei** [comment]
Hey it's me again..
I just got a working action (with a .json file) for the online google testing environment but I have no clue how to integrate it to the gAction of the mirror. Maybe you can help me with a quick hint on how the gAction files work.

[Vorstellungsintent.txt](https://github.com/eouia/MMM-AssistantMk2/files/3177844/Vorstellungsintent.txt)

**Comment by eouia** [comment]
Original gAction is somewhat difficult to handle. It needs Google cloud server, and deploy environment.
Fortunately, current `Google Asistant SDK for device` has a feature of `custom action for device`. It can handle custom traits and fulfilment. By simple registering custom action, your assistant on this device(MagicMirror) can interact with your custom order.

Here is custom action sample;
https://github.com/eouia/MMM-AssistantMk2/blob/master/gaction/actions.json
And How to handle.
https://github.com/eouia/MMM-AssistantMk2/wiki/gAction

**Comment by eouia** [comment]
And this is another tutorial : https://github.com/eouia/MMM-AssistantMk2/wiki/Tip:Making-Timer-with-gAction

*Warning:* 
- custom action cannot make complex conversation. It is just one-time Request-Response. (By example; "Do this"-"Yes" then finished)
- custom action cannot make dynamic runtime fulfilment(response). Only fixed static response is available. (By example, It cannot response like "it is 12:34")

**Comment by eouia** [comment]
Or you can use original regular action for Assistant, but trust me. That is not so easy to make and to deploy. If you tell me exactly what do you need with real use-case scenario, I could help.
