### ISSUE TITLE
Mic disconnection after first recognition 

### ISSUE THREAD

**Issue by gongda0e** [eouia/MMM-AssistantMk2#157]
Hi, I both installed MMM-HotWord and MMM-AssistantMk2 and it seemed worked well at fist.
However, when I restart Magic Mirror Google assistant only recognize my voice one time and mic disconnected automatically after one interaction.

Before starting magic mirror, 'arecord -l' returns me
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

but after I quit magic mirror, 'arecord -l' returns me with
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0

How can I solved this problem? 
My config.js is below like this.
<img width="774" alt="스크린샷 2019-05-19 오후 7 22 49" src="https://user-images.githubusercontent.com/32336040/57980873-b8153e00-7a6b-11e9-9e05-c21eab7de58f.png">

Thanks

**Comment by eouia** [comment]
It's somewhat weird. Is there any suspicious errors or messages in your backend-log? 
It seems your mic had a trouble when it is activated. Unfortunately I'm not an expert of that kind of issues. Anyway, I should see the log first.
set `testMic:true` on MMM-Hotword configuration and `verbose:true`(this is another thing with that of `record` setup) on MMM-AssistantMk2. You can get more detailed log.

**Comment by gongda0e** [comment]
Actually, I tried another usb mic but the results are the same.
And what I think is weird is that when I first speak "smart mirror" , I can hear double sounds from the assistant. Whenever it sounds twice, then the mic does not respond from that time.
Below is my command line. I don't know how I can check log, Thanks.
<img width="227" alt="스크린샷 2019-04-21 오후 6 35 22" src="https://user-images.githubusercontent.com/32336040/57981187-80a89080-7a6f-11e9-9ba4-6dc6e931c1e7.png">

**Comment by eouia** [comment]
Well, Which environment are you using? somewhat unfamiliar. 
At least that error shows you are running duplicated instances of MM at a same time. If you heard the beep sound twice, this could be the reason of your issue. Solve your multi-instances running first.

**Comment by gongda0e** [comment]
I am using Rasberry Pi3b+, Raspbian!
So, how can I turn off multi instances running? ㅜㅜ

**Comment by eouia** [comment]
Well, I think you are using `pm2` to manage MM's running. 
First, check `pm2 list`
and you can kill process of pm2 with `pm2 stop PROCESSNAME` (like `pm2 stop MagicMirror`)

**Comment by gongda0e** [comment]
OH..After I killed pm2, and it worked. Thank a lot Eouia! You are amazing! Thanks again for your efforts to help me. Have a wonderful day:)

**Comment by eouia** [comment]
Nice to hear it. Have a nice day.
