### ISSUE TITLE
gAction Timer is not working

### ISSUE THREAD

**Issue by leve0001** [eouia/MMM-AssistantMk2#159]
Hi,
I tried implementing the gActions Timer like on your page (I followed all instructions) but it still wont start. It just answers with the google results of "one minute timer" or "alert after 10 seconds". I pasted my _config_ code here and the _actions.json_ is identical to yours. The assistant is german by the way but unterstands the english command. Maybe you have an idea.

`		{

			  module: "MMM-AssistantMk2",
			  position: "lower_third",
			  config: {
	
			    deviceLocation: {
			      coordinates: { 
			        latitude: 49.24686, 
			        longitude: 7.36977, 
			      },
			    },
			
			    defaultProfile: "default", 
			
			    profiles: {
			      "default" : { 
			        profileFile: "default.json",
			        lang: "de-DE"
			      },
			    },
			
			    record: { // Full values are in `FOR EXPERTS` section.
			      recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
			      device: ""          // recording device (e.g.: "plughw:1")
			    },
			
			    play: { // Full values are in `FOR EXPERTS` section.
			      playProgram: "mpg321", // recommended.
			    },
			
			
			    // --- OPTIONAL / not important but customizable for your usage
			
			
			    responseVoice: true, // If available, Assistant will response with her voice.
			    responseScreen: true, // If available, Assistant will response with some rendered HTML
			    responseAlert: true, // If available, Assistant will response with Alert module of MM
			    // Sometimes, any response might not be returned. responseAlert is useful for displaying error.
			
			    screenZoom: "70%", // Adjust responseScreen to your mirror size.
			    screenDuration: 0, // milliseconds. How long responseScreen will be shown after speech.
			    //If you set 0, Screen Output will be closed after Response speech finishes ASAP.
			
			    youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.
			    pauseOnYoutube:false, //If set as true, You cannot activate Assistant during youtube playing. Recommended for the performance (Because permanent hotword detecting might make performance lower)
			
			    youtubePlayerVars: { // You can set youtube playerVars for your purpose, but should be careful.
			      "controls": 0,
			      "loop": 1,
			      "rel": 0,
			    },
			    youtubePlayQuality: "default", //small, medium, large, hd720, hd1080, highres or default
			
			    useWelcomeMessage: "", //Try "brief today" as this value. You can use this value to check module working when MM is starting.
			
			    onIdle: {
			      //timer: 1000*60*30, // if you don't want to use this feature, just set timer as `0` or command as ""
			      //command: "HIDEMODULES",
			      timer: 0,
			      command: null,
			    },
			
			    onActivate: {
			      timer: 0,
			      //command: "SHOWMODULES"
			      command: null,
			    },
			
			
			    // --- FOR EXPERTS / For development, debug or more
			
			
			    verbose:false, // You can get error or some logs when this value is set as true.
			    ignoreNoVoiceError: true, //To avoid some annoying youtube stop bug.
			
			    startChime: "connection.mp3", // you can use `mp3` to play chime when your mic is ready. It should be playable with your `play.playProgram`
			    noChimeOnSay: false, // When using the `ASSISTANT_SAY` trigger, you can prevent the chime from being played before your words
			
			    auth: { // I believe you don't need to change this.
			      keyFilePath: "./credentials.json"
			    },
			
			    record:  { // Full version
			      sampleRate    : 16000,      // audio sample rate
			      threshold     : 0.5,        // silence threshold (rec only)
			      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
			      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
			      silence       : 1.0,        // seconds of silence before ending
			      verbose       : false,      // log info to the console
			      recordProgram : "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
			      device        : ""        // recording device (e.g.: "plughw:1")
			    },
			
			    play: { // Full version
			      encodingOut: "MP3", //'MP3' or 'WAV' is available, but you might not need to modify this.
			      sampleRateOut: 24000,
			      playProgram: "mpg321", //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
			      playOption: [],
			      // If you need additional options to use playProgram, describe here. (except filename)
			      // e.g: ["-d", "", "-t", "100"]
			    },
			
			    useGactionCLI: true, // If set as true, you can update your gAction when MM is rebooted.
			    projectId: "mirasamarta", // Google Assistant ProjectId (Required only when you use gAction.)
			    deviceModelId: "", // It should be described in your config.json. In most of case, you don't need to this.
			    deviceInstanceId: "", // It should be described in your config.json. In most of case, you don't need to this.
			
			    recipes:["hide_and_show_all_modules.js", "reboot.js", "screen_onoff.js", "shutdown.js","bildaus.js","bildan.js"],
			    transcriptionHook: {},
			    action: {
					"com.example.commands.TIMER" : {
						command: "TIMER",
					  },
					}, // You can catch your gAction command.
			    command: {
				  "TIMER": {
					moduleExec: {
					  module: ["MMM-AssistantMk2"],
					  exec: (module, params, key) => {
						var delay = 0
						if (params["unit"] == "HOUR") delay = params["delay"] * 3600000
						if (params["unit"] == "MIN") delay = params["delay"] * 60000
						if (params["unit"] == "SEC") delay = params["delay"] * 1000
						setTimeout(()=>{
						  module.sendNotification("SHOW_ALERT", {message:"It's time you've set.", timer:3000})
						}, delay)
					  }
					}
				},
				}, // You can catch transcription hook and be able to make your own `COMMAND` with this.
			    //See the `transcriptionHook` section.
			    action:{}, // You can make your own MM command for gAction and transcriptionHook
			    //See the `command` section.
			
			    notifications: { // You can redefine these notifications to communicate with specific modules.
			      ASSISTANT_ACTIVATE: "ASSISTANT_ACTIVATE",
			      ASSISTANT_DEACTIVATE: "ASSISTANT_CLEAR",
			      ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
			      ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
			      ASSISTANT_ACTION: "ASSISTANT_ACTION",
			      ASSISTANT_UNDERSTOOD: "ASSISTANT_UNDERSTOOD",
			      ASSISTANT_RESPONSE_END: "ASSISTANT_RESPONSE_END",
			      DEFAULT_HOOK_NOTIFICATION: "ASSISTANT_HOOK",
			      TEXT_QUERY: "ASSISTANT_QUERY",
			      SAY_TEXT: "ASSISTANT_SAY",
			    }
			  }
		},`

**Comment by eouia** [comment]
First, you don't need these full configuration because those fields are already default. What you have to do is just to redefine when modification is needed.
Now see the code. You've described `action` twice. the latter `acton:{}` cancels your previous definition of `action` for `com.examples.commands.TIMER`.

**Comment by leve0001** [comment]
That makes sense... I deleted it but it still wont work. Any other recommendations? Is it possible that the language may be a problem?

**Comment by eouia** [comment]
Have you register your action.json to Google Cloud server? Isn't there any errors?
The next thing to check is, when you speak the command, what log says? can you show me the log of that point?

**Comment by eouia** [comment]
I'll close this action, because there is no more feedback.
