### ISSUE TITLE
Error: 14 UNAVAILABLE: Service unavailable

### ISSUE THREAD

**Issue by leScepter** [eouia/MMM-AssistantMk2#16]
After clicking the Microphone button, I got this error

`assistant ready
Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:235:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:213:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1290:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:614:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1110:18
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Service unavailable.' }`

Can you help me?
Thank you.

**Comment by eouia** [comment]
Good luck to you.

**Comment by vijayrraut** [comment]
Hello @leScepter : I am getting the same error, how did you resolved it, Please help
Thank you.

**Comment by leScepter** [comment]
@vijayrraut My problem was that the module did not recognize my mic dongle, so I have to add 

```
record: {
		sampleRate    : 16000,      // audio sample rate
		threshold     : 0.5,        // silence threshold (rec only)
		thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
		thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
		silence       : 1.0,        // seconds of silence before ending
		verbose       : false,      // log info to the console
		recordProgram : "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
		device        : "plughw:CARD,DEVICE"        // recording device (e.g.: "plughw:1") <-----------------------------
},
```

Good Luck.

**Comment by vijayrraut** [comment]
Thanks @leScepter, I did the changes as you suggested in MMM-AssistantMk2.js but still the same thing, I thing something wrong with my mic setting, when I do arecord getting below:
Please help

pi@raspberrypi:~ $ arecord -d 10 test.wav & aplay test.wav
[1] 2609
arecord: main:788: audio open error: No such file or directory
test.wav: No such file or directory
[1]+  Exit 1                  arecord -d 10 test.wav

**Comment by leScepter** [comment]
I assume you know to replace **CARD** and **DEVICE** in "plughw:**CARD**,**DEVIC**E". If you don't then run `arecord -l`. Here's a sample outout:

```
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```

Then check your recording device using:
```
arecord --device=hw:CARD,DEVICE --format S16_LE --rate 44100 -c1 test.wav
aplay --device=plughw:CARD,DEVICE test.wav
```

**Comment by vijayrraut** [comment]
Thank you so much..
It's working  :)

Vijay

**Comment by leScepter** [comment]
No problem. Glad I can help.

**Comment by harveyyoyo** [comment]
This help me as well. thanks so much
