### ISSUE TITLE
Bluetooth audio playback

### ISSUE THREAD

**Issue by ruhulayaan** [eouia/MMM-AssistantMk2#160]
I connected my bluetooth speak to my rpi, its working fine with speaker-test, but when i open my magicmirror its not routing MMM-AssistantMk2 audio through the speaker. It is going through the 3.5 mm jack how to change it to use Bluetooth speaker. Thanks

**Comment by eouia** [comment]
On your Raspbian Desktop, you can see volume icon. Right-click then you can select option to use BT speaker.

**Comment by ruhulayaan** [comment]
I have selected that but no luck, its playing through 3.5mm jack

**Comment by eouia** [comment]
Sorry I'm not an expert of that kind. I cannot help you about that thing.

**Comment by eouia** [comment]
I'll close this issue, because there is no more feedback. Wish a good luck.
