### ISSUE TITLE
음성명령으로 "~재생시" 유튜브는 켜지는데, 재생이 안돼요!

### ISSUE THREAD

**Issue by hannam12** [eouia/MMM-AssistantMk2#162]
유튜브는 켜지는데 자동 재생이 안돼는데 방법이 없을까요..

**Comment by eouia** [comment]
흠.. 에러 로그를 봐야 왜 그런지 알 수 있는데요..
일단 가장 일반적인 이유는, 해당 영상이 유튜브 밖에서 재생되지 않도록 저작권자가 설정한 경우입니다.
두번째는, 유효하지 않은 영상입니다. 블록되었다거나...
세번째는 에러가 있을 경우인데, 무슨 에러인지는 로그를 봐야 알겠는데요.

음.. 그런데 유튜브 기능은 곧 릴리즈될 다음 버전에서는 삭제될 겁니다. (최소한 별도 모듈로 분리시킬까 생각중입니다.) 애초에 이 모듈 만들 때 유튜브 재생을 위해서 만든 게 아니라 그건 정말 부가 기능이었는데, 여러가지 골치아픈 질문들이 죄다 여기에서 비롯되어서. 그래서 삭제될 예정이에요.

**Comment by hannam12** [comment]
FRONT LOG
MMM-EmbedYoutube received a module notification: ASSISTANT_UNDERSTOOD from sender: MMM-AssistantMk2
module.js:154 MMM-AirQuality received a module notification: ASSISTANT_UNDERSTOOD from sender: MMM-AssistantMk2
newsfeed.js:344 newsfeed - received notification: ASSISTANT_UNDERSTOOD
newsfeed.js:403 newsfeed - unknown notification, ignoring: ASSISTANT_UNDERSTOOD
www-widgetapi.js:99 Unrecognized feature: 'picture-in-picture'.
mb @ www-widgetapi.js:99
X @ www-widgetapi.js:87
Y @ www-widgetapi.js:108
playYoutubeVideo @ MMM-AssistantMk2.js:790
conversationEnd @ MMM-AssistantMk2.js:680
socketNotificationReceived @ MMM-AssistantMk2.js:270
(anonymous) @ module.js:246
(anonymous) @ socketclient.js:25
r.emit @ index.js:83
r.onevent @ index.js:83
MMSocket.self.socket.onevent @ socketclient.js:19
r.onpacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.ondecoded @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
a.add @ index.js:83
r.ondata @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
(anonymous) @ index.js:83
r.emit @ index.js:83
r.onPacket @ index.js:83
r.onData @ index.js:83
ws.onmessage @ index.js:83
module.js:154 clock received a module notification: HOTWORD_RESUME from sender: MMM-AssistantMk2
module.js:154 calendar received a module notification: HOTWORD_RESUME from sender: MMM-AssistantMk2
module.js:154 MMM-EmbedYoutube received a module notification: HOTWORD_RESUME from sender: MMM-AssistantMk2
module.js:154 MMM-AirQuality received a module notification: HOTWORD_RESUME from sender: MMM-AssistantMk2
newsfeed.js:344 newsfeed - received notification: HOTWORD_RESUME
newsfeed.js:403 newsfeed - unknown notification, ignoring: HOTWORD_RESUME
module.js:154 clock received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 calendar received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 MMM-EmbedYoutube received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
module.js:154 MMM-AirQuality received a module notification: HOTWORD_LISTENING from sender: MMM-Hotword
newsfeed.js:344 newsfeed - received notification: HOTWORD_LISTENING
newsfeed.js:403 newsfeed - unknown notification, ignoring: HOTWORD_LISTENING
MMM-AssistantMk2.js:748 Youtube player: on ready.
MMM-AssistantMk2.js:786 youtube status: -1
MMM-AssistantMk2.js:786 youtube status: 3
MMM-AssistantMk2.js:786 youtube status: -1
//

BACK LOG
> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: MMM-EmbedYoutube.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
No helper found for module: compliments.
No helper found for module: MMM-AirQuality.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics - Interval: 3600000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
Create new news fetcher for url: http://world.kbs.co.kr/rss/rss_news.htm?lang=k - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: smart_mirror
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Transcription: u2  --- Done: false
[AMK2] Transcription: 유튜브  --- Done: false
[AMK2] Transcription: 유튜브에  --- Done: false
[AMK2] Transcription: 유튜브에서  --- Done: false
[AMK2] Transcription: 유튜브에서 봄  --- Done: false
[AMK2] Transcription: 유튜브에서 뽐뿌  --- Done: false
[AMK2] Transcription: 유튜브에서 뿜뿜  --- Done: false
[AMK2] Transcription: 유튜브에서 뿜뿜  --- Done: false
[AMK2] Transcription: 유튜브에서 뿜뿜 제  --- Done: false
[AMK2] Transcription: 유튜브에서 뿜뿜 재생  --- Done: false
[AMK2] Transcription: 유튜브에서 뿜뿜 재생해  --- Done: false
[AMK2] Transcription: 유튜브에서 뿜뿜 재생해 줘  --- Done: false
[AMK2] Transcription: 유튜브에서 뿜뿜 재생해 줘  --- Done: false
[AMK2] Transcription: 유튜브에서 뿜뿜 재생해 줘  --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: 유튜브에서 뿜뿜 재생해 줘  --- Done: true
{ requestId: '5cf00faf-0000-2386-b1f5-089e082f40f4' } { profileFile: 'default.json', lang: 'ko-KR' }
[AMK2] Device Action: { requestId: '5cf00faf-0000-2386-b1f5-089e082f40f4' }
[AMK2] Assistant Text Response: 
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: smart_mirror
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Transcription: 100  --- Done: false
[AMK2] Transcription: 백제  --- Done: false
[AMK2] Transcription: 백지영  --- Done: false
[AMK2] Transcription: 백지영의  --- Done: false
[AMK2] Transcription: 백지영의 뭐  --- Done: false
[AMK2] Transcription: 백지영의 목  --- Done: false
[AMK2] Transcription: 백지영의 목사  --- Done: false
[AMK2] Transcription: 백지영의 목소리  --- Done: false
[AMK2] Transcription: 백지영의 목소리지  --- Done: false
[AMK2] Transcription: 백지영의 목소리 집  --- Done: false
[AMK2] Transcription: 백지영의 목소리 재생  --- Done: false
[AMK2] Transcription: 백지영의 목소리 재생 해  --- Done: false
[AMK2] Transcription: 백지영의 목소리 재생해 줘  --- Done: false
[AMK2] Transcription: 백지영의 목소리 재생해 줘  --- Done: false
[AMK2] Transcription: 백지영의 목소리 재생해 줘  --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: 백지영의 목소리 재생해 줘  --- Done: true
[AMK2] video found: Y3R-5MyPoPY
{ requestId: '5d21fd90-0000-26a8-92c7-94eb2c1cb9ca' } { profileFile: 'default.json', lang: 'ko-KR' }
[AMK2] Device Action: { requestId: '5d21fd90-0000-26a8-92c7-94eb2c1cb9ca' }
[AMK2] Assistant Text Response: 
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: newsfeed
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Hotword

**Comment by hannam12** [comment]
위에가 front로그고
아래가 back end 로그입니다!
유튜브는 켜지는데 자동재생이 되지않습니다.

**Comment by hannam12** [comment]
혹시 유튜브 자동 재생을 한 번 더 실행하게 하거나 몇초 뒤에 하는 법도 있을까요?

**Comment by eouia** [comment]
현재 모듈로서는 불가능하구요. 곧 업데이트 예정이긴 한데 고려해보겠습니다.

**Comment by James-Kim-1979** [comment]
제가 생각하는 문제점은 네트워크 문제라고 생각되네요.  저도 처음에 끊기거나 멈추는 현상이 발생했어요.  제대로 설치되셨다면... 네트워크 ... 와이파이 설정에서 power management off 와 네트워크 끊김 현상을 제거해보시는걸 추천합니다.   sudo iwconfig wlan0 power off  && sudo  iw reg set US 국가는 US로 고정하시고... 라즈베리파이 네트워크 문제가 많다고 나왔더라구요.

**Comment by Jeongseongwon** [comment]
https://forum.magicmirror.builders/topic/10556/youtube-autoplay 이거 한 번 해보세요
