### ISSUE TITLE
Error Code 14 Service unavailable

### ISSUE THREAD

**Issue by friedleif** [eouia/MMM-AssistantMk2#164]
Hi,

after upgrading MM to 2.7.1 and all modules to the latest version,
the assistant is not working anymore.

Shell output:

>[HOTWORD] Detector starts listening.
[RCREPO] modules.json is updated.
[HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response:

And after about 60 seconds:

>[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-Assist                                                         antMk2/node_modules/grpc/src/common.js:87:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-As                                                         sistantMk2/node_modules/grpc/src/client.js:235:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-Assis                                                         tantMk2/node_modules/grpc/src/client.js:213:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/nod                                                         e_modules/grpc/src/client_interceptors.js:1290:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-Assistan                                                         tMk2/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-As                                                         sistantMk2/node_modules/grpc/src/client_interceptors.js:614:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/clien                                                         t_interceptors.js:1110:18
  code: 14,
  metadata:
   Metadata { _internal_repr: { 'content-disposition': [Array] } },
  details: 'Service unavailable.' }

Configuration:

>		{
>			module: "MMM-Hotword",
>			position: "top_right",
>			config: {
>				mic: {
>					recordProgram : "arecord",
>					device        : "plughw:1,0"
>					},
>				recipes: [],
>				models: [
>					{
>					hotwords: "smart_mirror",
>					file: "smart_mirror.umdl",
>					sensitivity: "0.5",
>					},
>					{
>					hotwords: "computer",
>					file: "computer.umdl",
>					sensitivity: "0.6",
>					},
>					{
>					hotwords: "snowboy",
>					file: "snowboy.umdl",
>					sensitivity: "0.5",
>					},
>					{
>					hotwords: ["jarvis", "jarvis"],
>					file: "jarvis.umdl",
>					sensitivity: "0.8,0.8",
>					},
>					],
>				commands: {},
>				defaultCommand: {
>					notificationExec: {
>					notification: "ASSISTANT_ACTIVATE",
>					payload: function (detected, afterRecord) {
>					return {profile:"default"};
>					}
>					}
>					},
>				useDisplay: true,
>				iconify: "https://code.iconify.design/1/1.0.2/iconify.min.js",
>					//iconify: null,
>					//When you use this module with `MMM-CalendarExt2`, `MMM->Spotify` or any other `iconify` used modules together, Set this to null.
>				icons: { //https://iconify.design/icon-sets/
>					detected: "uil-comment-exclamation",
>					finished: "uil-comment-dots",
>					},
>					afterRecordLimit:0,
>					restart:false,
>				},
>		},
>		{
>			module: "MMM-AssistantMk2",
>			position: "top_right",
>			config: {
>			deviceLocation: {
>				coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
>				latitude: 48.114933, // -90.0 - +90.0
>				longitude: 11.581323, // -180.0 - +180.0
>						},
>					},
>			youtubeAutoplay: false,
>			screenDuration: 5000,
>			defaultProfile: "default", // If you have several profiles and want to set one of them as default profile, describe here.
>			profiles: {
>				"default" : { // profile name.
>				profileFile: "default.json", // profile file name.
>				lang: "de-DE"
>						},
>				},
>			onIdle: {
>				timer: 0, // if you don't want to use this feature, just set timer as `0` or command as ""
>				command: "HIDEMODULES"
>				},
>			onActivate: {
>				timer: 0,
>				command: "SHOWMODULES"
>				},
>			record: {
>				recordProgram : "arecord",
>				device        : "plughw:1,0",
>				},
>			notifications: {
>				ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
>				ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
>				},
>			recipes:["hide_and_show_all_modules.js", "reboot.js", "screen_onoff.js", "shutdown.js"],
>			transcriptionHook: {
>				"PAGEFORWARD": {
>					pattern: "eine Seite vor",
>					command: "PAGEFORWARD"
>					},
>					},
>			command: {
>				"PAGEFORWARD": {
>					notificationExec: {
>					notification: "PAGE_INCREMENT",
>					}
>					},
>				},
>				}
>		},

Any ideas?
Thanks!

**Comment by eouia** [comment]
From Hotword 2.0, Structure is changed. you need new configuration about Hotword.
Your issue came from `defaultCommand`. It will try to activate AMK2, but you've missed stoping Hotword itself. So during activation of AMK2, Hotword also restarts. It makes collison of mic device.
Add `restart:false` to `defaultCommand`.
Read the command.md of MMM-Hotword
