### ISSUE TITLE
My assistant keeps sleeping/disabling. Errors included below. Please help, thanks.

### ISSUE THREAD

**Issue by jod98** [eouia/MMM-AssistantMk2#165]
Hi,

I am having an issue with setting the setting up of AssistantMk2 and Hotword. I have configured my audio devices, examined the console for errors, reinstalled both modules and tried many more things.

This is the error I keep getting. I have no idea why. Can you help please???

As you can see it detects when I say 'smart mirror' but it just sleeps/disables after that and I cannot command anymore. 

All help is appreciated, thanks.

![HELP SMART MIRROR](https://user-images.githubusercontent.com/36043248/58345797-2170c480-7e51-11e9-860b-d376763989cd.PNG)

**Comment by eouia** [comment]
Have you set position of module's position? If you don't want to show hotword displaying, set `useDisplay:false` instead not setting position of module.

**Comment by jod98** [comment]
If you mean set position of module like 'top right', yeah I did. I don't mind if hotword is displaying, it just keeps sleeping/disabling after it hears 'smart mirror'.

I am very confused.

I just followed install guide for both modules on your Github page but not working.

**Comment by eouia** [comment]
But your error log says when module position is not set properly. Give me your configuration about MMM-Hotword.

**Comment by jod98** [comment]
My configuration is just this. Its the configuration file you have uploaded on your Github page. 

![Screenshot_20190524-190155](https://user-images.githubusercontent.com/36043248/58347862-dce82780-7e56-11e9-96cb-88f70dc7ed43.jpg)

**Comment by eouia** [comment]
You didn't set the position of MMM-Hotword.

**Comment by jod98** [comment]
OK sorry, how do I set the position of the M M-Hotword. I am new to this magic mirror thing.

**Comment by eouia** [comment]
```js
{
  module: "MMM-Hotword",
  position: "top_right",
  config: {
...
```

**Comment by jod98** [comment]
Thanks, I will try it on Monday, I'm am away from it at the moment.

**Comment by jod98** [comment]
Hi, I forgot to ask. Do I need any other third party modules to make this work like notification trigger? Do I need notification trigger module to make 'smart mirror' call to work?

Thanks

**Comment by eouia** [comment]
no. frankly said, amk2 could work by itself. hotword acts just as activator. if you have other method to wake(e.g. hw button or some kind of sensors), you can use it instead hotword

**Comment by eouia** [comment]
I'll close this issue because there is no more feedback. Wish a good luck.
