### ISSUE TITLE
Can I control Google home devices?

### ISSUE THREAD

**Issue by LeonCWChan** [eouia/MMM-AssistantMk2#166]
Hi, can I control smart lights straight away? Or is Google home supported? Thank you so much! Great module btw!

**Comment by eouia** [comment]
If you register on same network, it will work like real Google Home. or if the light can support IFTTT, that way also will work.

**Comment by YooSangBeom** [comment]
eouia님 항상 감사하게 모듈 사용하고 있습니다. 
어떤 개발쪽 공부하면 개발자님처럼 스마트미러 모듈을 개발할수있나요? 정말 배워보고 싶습니다.
수고하세요~!!

**Comment by eouia** [comment]
I'll close this issue because there is no more feedback. Wish a good luck!

**Comment by LeonCWChan** [comment]
Thank you eouia and YooSangBeom for replies! Yes seems worked straight away :)
