### ISSUE TITLE
How to override assistant CSS styles?

### ISSUE THREAD

**Issue by Oesoto** [eouia/MMM-AssistantMk2#167]
I've seen the module dynamically creates a template 'temp.html' which is later loaded via iframe and it contains all the Google Assistant stuff inside.

I want to make permanent changes to some of the styles.

How can I achive that?

![Screen Shot 2019-05-31 at 5 49 38 PM](https://user-images.githubusercontent.com/1323321/58738931-753d5980-83cd-11e9-8b41-e944c39018e2.png)

**Comment by eouia** [comment]
Not easy, because every class and id of screen output htmnl would be changed dynamically. You cannot guess what it would be.

**Comment by eouia** [comment]
I'll close this issue because there is no more feedback. Wish you a good luck.
