### ISSUE TITLE
I have a problem.. 링크로 질문했나보네요. 

### ISSUE THREAD

**Issue by James-Kim-1979** [eouia/MMM-AssistantMk2#168]
안녕하세요.  라즈베리파이로 한글이 안써져서.. 질문을 남겼는데.. 다른곳에다가 쓴거 같네요. 아직 깃허브에 대한 올바른 사용법은 아직 숙지하지 못해서.. 다시 질문드려요. 

2018년 10월 경에 나온 버전이 뭔지 모르지만...(그당시 정상작동됨) 새로 업데이트 되서 다시 설치해볼려고 했는데.. 구글 어시스트 연동이 안되네요.  한 20번은 메뉴얼대로 깔았다 지웠다...수정했다 한거 같은데... 

npm install 문제라고 지적해주셨는데....  정말 많이 깔고 지우고 해봤거든요...  그 전에는 음성인식도 다되고 그랬는데.. ;;  반복적으로 모듈을 찾을수 없다고 매직미러상에 표시가 됩니다. 

hotword는 정상작동되는거 확인되구요.  
pm2 가 전혀 실행이 안되는 현상은 어떻게 해결해야하는지도 모르겠습니다.  

![aaa](https://user-images.githubusercontent.com/51309928/58786332-43710080-8622-11e9-8174-1cb5e53d4da4.jpg)

**Environment:**
 - Device : [e.g. RPI 3b+]
 - OS: [e.g. Raspbian Stretch]
 - Node Version : 최신 업데이트 완료
 - Etc.

**Comment by James-Kim-1979** [comment]
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ node auth_and_test.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'google-assistant'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/auth_and_test.js:7:25)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

**Comment by eouia** [comment]
`npm install`에서 여러 에러가 보입니다. 원인은 여러가지일 수 있는데, 일단 npm 자체에 문제가 있는 것 같아요.
1) AMK2 디렉토리에서 `npm cache clean --force` 를 실행해서 npm cache를 정리해주고 다시 `npm install` 해보세요.
2) 그래도 안된다면 `sudo npm install -g npm` 로 npm을 다시 설치한 후 다시 `npm install` 해주세요. 아마 여러번 설치하고 지우고 하면서 npm 환경일부가 변형된 것 같습니다.

**Comment by James-Kim-1979** [comment]
> `npm install`에서 여러 에러가 보입니다. 원인은 여러가지일 수 있는데, 일단 npm 자체에 문제가 있는 것 같아요.
> 
> 1. AMK2 디렉토리에서 `npm cache clean --force` 를 실행해서 npm cache를 정리해주고 다시 `npm install` 해보세요.
> 2. 그래도 안된다면 `sudo npm install -g npm` 로 npm을 다시 설치한 후 다시 `npm install` 해주세요. 아마 여러번 설치하고 지우고 하면서 npm 환경일부가 변형된 것 같습니다.

npm cache clean --force 를 실행하니... 처음으로 매직미러가 오류가 안뜨고 화면에 표출되었습니다. 감사합니다.  이제 config.js 와 씨름해서 연동되게 해야겠네요.  smart_mirror 나 jarvis 는 인식이 되는데.. 대답을 안하는 문제가 발생했네요. ^^;;

**Comment by James-Kim-1979** [comment]
![20190605_222431](https://user-images.githubusercontent.com/51309928/58960916-16b81700-87e3-11e9-9526-941bc6b2e9bd.jpg)

개발자님 덕분에 스마트미러를 멋지게 완성했습니다!  다만 .. 음성인식이 1M 이상에서는 잘 못하더군요.   값을 조절해봤는데... 어떤 수치가 더 민감하게 받는지 모르겠네요.  그리고 Youtube 재생시 다시 recall 하는게 안되더군요.  1시간짜리 음악을 끝까지 들어야하는 단점이... mic 민감도와 Youtube 재생시 다시 hotword를 불러오는 기능이 되면 좋겠습니다.  오늘도 수고하세요.

**Comment by eouia** [comment]
축하드립니다.
1) 마이크는... 비싼거 쓰세요. ^^;;;
2) `pauseOnYoutube:false` 로 하시면 유튜브 재생중에도 핫워드 웨이킹이 되면서 핫워드 인식시 유튜브 재생이 자동으로 멈춥니다. 단점은... 유튜브 비디오에서 나오는 소리도 핫워드로 인식되는 경우가 있어서 그럴 때에도 의도치 않게 끊기는 단점이... 진짜 구글홈이나 알렉사 등은 마이크를 Array-Mic를 써서 가까이서 나는 소리와 멀리서 나는 소리를 구별해서 자기 자신이 내는 소리에는 반응하지 않도록 되어 있는데요, 뭐... 그것까지 구현하기는 좀...
3) center Region에서 깨지는 건, 원래 MM이 center Region의 CSS에 transform을 써서 그렇습니다. 별로 좋은 방식이 아닌데 레거시가 그렇게 되어 있다보니... `css/custom.css`  에서 center영역을 transform을 쓰는 대신 고정값으로 width를 주면 해결되긴 하는데요, 그런건 필요에 따라 사용자가 직접 수정하면 될 것 같아서 굳이 건드리지는 않았습니다. (center를 쓰는 다른 모듈들이 영향을 받을 수도 있고...)

- 다음 버전에서는 center 영역을 쓰더라도 screenOutput이 영향받지 않도록 구조를 바꾸는 중입니다.
- 다음 버전에서는 유튜브 기능은 삭제될 예정입니다. ^^; (별도로 MMM-YouTube 라든가 다른 유튜브 관련 모듈이 쓸 수 있도록 구조를 바꾸는 중입니다.)
