### ISSUE TITLE
I can't register as Google Assistant related device

### ISSUE THREAD

**Issue by JohnB7777** [eouia/MMM-AssistantMk2#169]
Hello,

I try to register this module to use on google home app but I have some errors.
When I tap "curl -s -X POST -H "Content-Type: application/json" \
-H "Authorization: Bearer $ACCESSTOKEN" -d @deviceInstance.json \
https://embeddedassistant.googleapis.com/v1alpha2/projects/YOUR_PROJECT_ID/devices/"

I have this error :
{
  "error": {
    "code": 403,
    "message": "The request is missing a valid API key.",
    "status": "PERMISSION_DENIED"
  }
}

I don't understand, and maybe I'm wrong on id and "YOUR_MODEL_ID" ?
On google cloud platform, I have "Project name", "Project ID" and "Project number".
What are the usefull informations ?

Thanks for the help !

**Comment by eouia** [comment]
I think you've missed or failed something on previous step - about ACCESSTOKEN. Recheck it and try again.
And YOUR_MODEL_ID should be registered on https://github.com/eouia/MMM-AssistantMk2/wiki/Installation#get-devicemodelid-and-deviceinstanceid step.

**Comment by JohnB7777** [comment]
Thanks for the link but when I go to register a model, there is no button "Register model" on the website "Action on Google". There is my project, I click on it but no way to register.
I think google forgot to update their pages, so I don't know how register... :/

Maybe to register manually with this link https://developers.google.com/assistant/sdk/reference/device-registration/register-device-manual#get-access-token ?
But I have to install google-assistant-sdk, like you said on your tutorial, right ?
apt-get install google-assistant-sdk ?

Thanks again

**Comment by JohnB7777** [comment]
Oh, I found the page using another link !
I try to create a model and I let you know.

**Comment by JohnB7777** [comment]
Ok, I have a model ID, I have a project ID, I have the token, and I follow your tutorial here https://github.com/eouia/MMM-AssistantMk2/wiki/Installation#get-devicemodelid-and-deviceinstanceid but it doesn't work.
The error is not the same that previously :

{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Expected a value.\n“mmm-assistant-fd6\n^",
    "status": "INVALID_ARGUMENT"
  }
}

**Comment by eouia** [comment]
That error says you have some wrongs in your `deviceInstance.json`. Can you show your json file?

**Comment by JohnB7777** [comment]
yes :

{
    "id": “mmm-assistant-fd631”,
    "model_id": “mmm-assistant-fd631-jarvis-v4qqxg”,
    "nickname": “Jarvis”,
    "client_type": "SDK_SERVICE"
}

**Comment by eouia** [comment]
Hmmm..
1) Why did you name `id` as `mmm-assistant-fd631`? It seems Project ID. right? `id` is `instanceId` and you can name it as your wish like "MY_FIRST_MIRROR" or "MirrorOnKitchen" or anything else.

2) Did you properly execute command? If `mmm-assistant-fd631` be `Project ID`, the command would be like this.
```sh
curl -s -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $ACCESSTOKEN" -d @deviceInstance.json https://embeddedassistant.googleapis.com/v1alpha2/projects/mmm-assistant-fd631/devices/
```

**Comment by JohnB7777** [comment]
1. Yes, it's project ID. Ok, I didn't know I can named as I want
2. Yes, I replace my project id's name on the url. So I don't understand...

**Comment by eouia** [comment]
Wait. It might sound somehow ridiculous, but... look at the quotation mark.
`"` is right quotation mark. `“` is wrong. Check it.

**Comment by eouia** [comment]
My doc has wrong syntax. hhhh... I'll fix it.

**Comment by JohnB7777** [comment]
I corrected the file and I have a new error :

{
  "error": {
    "code": 401,
    "message": "Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.",
    "status": "UNAUTHENTICATED"
  }
}

**Comment by eouia** [comment]
Have you done this?

<img width="821" alt="test" src="https://user-images.githubusercontent.com/1720610/58979894-5b39b780-87cf-11e9-8ab1-621546e90e92.png">

If so, Your token might be outdated, try those steps again to apply new token.

**Comment by eouia** [comment]
Anyway, This is not so easy, isn't it? I feel somehow shamefulness and regretfulness about why I have made this module. Sorry for insufficient instruction.

**Comment by eouia** [comment]
For caution's sake, Not `ACCESSTOKEN=<your token>`. Omit `<` and `>` like `ACCESSTOKEN=ya29.Glu...`

**Comment by JohnB7777** [comment]
I did that again, I restart the mirror and my mirror is on my phone app !
Thanks ! :D

Yes, it wasn't so easy but I don't know how you can be shame. Maybe you have to improve your tutorial and the way to explain sometimes but you are strong to do this ! 
Fortunately, you are here to help us (and you are quick)
Develop a program is beyond my skills and I am rather impressed. It's good work and I wish you to continue like this!

**Comment by eouia** [comment]
:) Have a nice day. Feel free to leave another issue. I'll be here for you. :D

**Comment by JohnB7777** [comment]
Thanks a lot ! :D
Have a nice day too :)
