### ISSUE TITLE
Stuttering sound when assistant reacts on a request

### ISSUE THREAD

**Issue by NightFalcon650** [eouia/MMM-AssistantMk2#17]
I've installed MMM-AssistantMk2, MMM-Hotword and MMM-NotificationTrigger. It al works well, i can do a request and the request gets send to google assistant. The answer is return and played bij the pi.
Unfortianaly the answer is choppy and stutters.
I removed the wifi dongle and connected the pi with a lan cable. Even then it stil plays the answer choppy. 
The sound is played through the jack plug and for the recording i use a usb mic.

arecord and aplay works fine:
_arecord --format=S16_LE --duration=5 --rate=16000 --file-type=raw out.raw && 
aplay --format=S16_LE --rate=16000 out.raw_

This works well and also the playback is without stuttering.

My /home/pi/.asoundrc file is:

_pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}_

aplay -l and arecord -l results:

_pi@MagicMirror2:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 ALSA [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@MagicMirror2:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
pi@MagicMirror2:~ $_ 

lsmod result:

_pi@MagicMirror2:~/MagicMirror $ lsmod
Module                  Size  Used by
fuse                  106496  3
cfg80211              573440  0
rfkill                 28672  2 cfg80211
joydev                 20480  0
ads7846                20480  0
hwmon                  16384  1 ads7846
snd_bcm2835            32768  1
spi_bcm2835            16384  0
i2c_bcm2835            16384  0
fixed                  16384  0
uio_pdrv_genirq        16384  0
uio                    20480  1 uio_pdrv_genirq
evdev                  24576  8
snd_usb_audio         172032  0
snd_hwdep              16384  1 snd_usb_audio
snd_usbmidi_lib        32768  1 snd_usb_audio
snd_rawmidi            32768  1 snd_usbmidi_lib
snd_seq_device         16384  1 snd_rawmidi
snd_pcm                98304  2 snd_usb_audio,snd_bcm2835
snd_timer              32768  1 snd_pcm
snd                    69632  10 snd_hwdep,snd_usb_audio,snd_timer,snd_rawmidi,snd_usbmidi_lib,snd_seq_device,snd_bcm2835,snd_pcm
i2c_dev                16384  0
ip_tables              24576  0
x_tables               32768  1 ip_tables
ipv6                  434176  22_

What is causing the stutter? 
And what do i have to change to get rit of the stutter?
Am i the only one with this problem.. Hoping you could help me.

Greetz

**Comment by eouia** [comment]
There could be many reasons for that case.
Maybe too many modules or too many front-end refreshing or animating, too many background process or anything else, even including internet speed.
I cannot point specific reason at this moment.
Anyway in my device, I use BT speaker and I have no problem about that. Sorry.
