### ISSUE TITLE
node auth_and_test.json error

### ISSUE THREAD

**Issue by yassineaqejjaj** [eouia/MMM-AssistantMk2#170]
Hi ! 
I have an issue  after moving the credentials : 
`pi@raspberrypi :~/MagicMirror/modules/MMM-Assistantmk2 $ mv ~/Dowloads/code_secret_client_...googleusercontent.com.json credentials.json
pi@raspberrypi :~/MagicMirror/modules/MMM-Assistantmk2 $ node auth_and_test.js 
internal/modules/cjs/loader.js:638
   throw err;
   ^

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/credentials.json'
   at Function.Module._resolveFilename (internal/modules/cjs/loader.js
...`

Thank you

**Comment by eouia** [comment]
Is there `credentials.json` in `MMM-AssistantMk2` directory? The error says there is no `credentials.json` in that directory. Check it again.

**Comment by yassineaqejjaj** [comment]
Hi eouia ! 
Thanks for ur help. 
I renamed it into : credentials.json and it works well. 
I still have an issue with the usb mini microphone which is not detected. 
The speakers works well but not the usb

**Comment by eouia** [comment]
I'll close this issue because there is no more feedback. you can reopen or post new issue anytime, feel free. Wish you a good luck.
