### ISSUE TITLE
Utility to have the mirror on Google Home App ?

### ISSUE THREAD

**Issue by JohnB7777** [eouia/MMM-AssistantMk2#171]
Hello,

I open a issue juste because I have a question.
Since yesterday and like you know (^^), I have the mirror on my google home app.
But, I can't do anything with this, except changing the room of the mirror and dissociate the service. So, I was wondering what is the utility to do that ?

Thanks :)

**Comment by eouia** [comment]
Frankly said, rarely useful.  
If you have some IoC devices like Philips HUE in same Google Home Network, you might control that device with this AssistantMk2. Anyway it should be registered and activated already by Real Google Home. And if you query something on AssistantMk2, additional info of result might be pushed to your Google Home App to get more information like external web link.
But that's all.
Unlike Real Google Home, It cannot be used as Receiver - like casting or alarms. That is limit of this Assistant SDK. The purpose of this SDK is not to make alternative Google Home but give a vocal command feature to specific custom device.

**Comment by JohnB7777** [comment]
Ok, thanks for the explanation :)

**Comment by JohnB7777** [comment]
And I would like to know if it's possible to call someone with this ?
I think no (because I try and Google assistant respond me it cannot take a call yet) but I would like to know if it's also because of SDK limitation ? Or if it might be possible in the future

Thanks

**Comment by eouia** [comment]
Do you mean phone call(or some voice talk like facetime)? Absolutely no. I don't believe it could be possible in near days. As I've said the purpose of this SDK is not being an alternative of Google Home.

You can use IFTTT. you can set your Assistant as `THIS` automatically. For `THAT` as Mirror, you need additional module which can be a receiver of IFTTT. As far as I know, Remote-Control module could receive from IFTTT. And my `MMM-NotificationTrigger` could be `THAT`. https://github.com/eouia/MMM-NotificationTrigger/blob/master/README.md#usewebhook

**Comment by JohnB7777** [comment]
For phone call, I mean for example : "Jarvis, call Mom please"
=> Google Assistant use the connexion of your phone, and the contact registered on it to call "Mom".
And the voice come out the speakers and you can use micro to speak.

Ok, IFTTT is very new for me so I will read that and having fun ! ^^

**Comment by eouia** [comment]
![ifttt1](https://user-images.githubusercontent.com/1720610/59135339-dee5d680-897e-11e9-8b7b-86471b2dad4e.png)
This is an example of IFTTT.(Especially about "THIS")
`IFTTT` is IF `THIS` THEN `THAT`. In this case, the first applet shows `if I say "execute order 66"`, this applet will be activated.
Making `THIS` is easy. Just describe **Which phrase I will say**. then describe also **What to be done** as `THAT`. You can see second applet which will send SMS.

However, Making `THAT` for controlling MagicMirror is another issue. MagicMirror should be reachable by IFTTT server and can receive data from IFTTT. That is not the business of Assistant or MagicMirror itself by default. So additional feature to receive data from internet is needed.

**Comment by JohnB7777** [comment]
Ok, thanks for your answer (I read this message 3 days ago but I forgot to answer you, sorry).
What is the additional feature to receive data ? Remote-control module, as you said previously, for example ?

I have another question. I made a reminder but google assistant don't do anything to remind... Is this normal ?

**Comment by eouia** [comment]
1) Let's think. IFTTT will send some data or message like "Turn off screen" as `THAT` to your Mirror, but how? IFTTT should know your mirrors address (IP or domain) and some URL where to send.
And that kind of URL is not provided by Mirror itself by default. Some modules like MMM-NotificationTrigger  or MMM-Remote-Control  could serve the URL for that kind of purpose.  I meant it.

2) As I've said,(Have I? hmmm), there is some limitation for comparison with real Google Home. Reminder or alarming or broadcasting is not supported by SDK level.

**Comment by eouia** [comment]
I'll close this cause there is no more feedback. I wish a good luck to you. Have a nice day.
