### ISSUE TITLE
Rebuild %0 Stuck

### ISSUE THREAD

**Issue by followarcane** [eouia/MMM-AssistantMk2#173]
Hello, when i use the command line below

./node_modules/.bin/electron-rebuild

My raspi stuck at %0 and after like 20-30 min. It freeze. No fail message or anything just freeze.

i've already tried 
1-use grpc-js instead grpc
2-downgrade grpc to v1.13

Can you please help me?

I'm using Raspi 3.

**Comment by eouia** [comment]
electron-rebuild will take a very long time. almost over 30min - 1 hours. (depends on hw)

**Comment by eouia** [comment]
I'll close this issue because no more feedback. Wish a good luck. Have a nice day.
