### ISSUE TITLE
setTimeout in recipes

### ISSUE THREAD

**Issue by leve0001** [eouia/MMM-AssistantMk2#174]
Is there a problem with using "setTimeout" in recipes?
The following code completely kills all my custom interactions... No errors without it.

Desperatly trying to make a timer work, even with a custom timespan. I just dont get the gAction timer to work so I tried something else.

````javascript
var recipe = {
  transcriptionHook: {
    "INTRODUCTION": {
      pattern: "10 Sekunden Timer",
      command: "INTRODUCTION"
    },
  },
  command: {
    "INTRODUCTION": {
      setTimeout(function() {
              notificationExec: {
        notification: "SHOW_ALERT",
          payload: {
              message: "10 Sekunden sind rum!",
              timer: 2000
            }
          }
      }, 10000),
    }
  }
}

exports.recipe = recipe // Don't remove this line.

**Comment by eouia** [comment]
Your code will not work. Try this instead.

```js
"INTRODUCTION": {
  moduleExec: {
    module: ["MMM-AssistantMk2"], // Or any other module name is ok.
    exec: (module, params, key) => {
      setTimeout(()=>{
        module.sendNotification("SHOW_ALERT", {message:"test", timer:2000})
      }, 10000)
    }
  }
},
```

**Comment by leve0001** [comment]
Hey thank you,
it doesn't crash now. But the notification is not showing up after the 10 sec timer is over

**Comment by eouia** [comment]
Show your configuration about `transcriptionHook` and `commands`

**Comment by leve0001** [comment]
This is in the config file. The recipe above is in "reboot.js". The transcriptionHook is unchanged. I hope its what you are asking for

```
 recipes:["hide_and_show_all_modules.js", "reboot.js", "screen_onoff.js", "shutdown.js","bildaus.js","bildan.js"],
transcriptionHook: {},
action: {}, 
command: {}
```

**Comment by eouia** [comment]
Then, show me `reboot.js`.

**Comment by leve0001** [comment]
```

var recipe = {
  transcriptionHook: {
    "INTRODUCTION": {
      pattern: "Testlauf",
      command: "INTRODUCTION"
    },
  },
  command: {
    "INTRODUCTION": {
      moduleExec: {
        module: ["MMM-AssistantMk2"], 
        exec: (module, params, key) => {
        setTimeout(()=>{
        module.sendNotification("SHOW_ALERT", {message:"test", timer:2000})
                        }, 10000)
                      }
                  },
                } 
      }
}

exports.recipe = recipe // Don't remove this line.

```

**Comment by eouia** [comment]
First, check whether your `pattern` was transcribed rightly. Your backend log would have left related messages.
If SHOW_ALERT would be emitted, your frontend log also would have left some logs about that notification.

**Comment by leve0001** [comment]
Okay.... I tried to check the logs (and got some by exec `pm2 logs MagicMirror`) but I dont think its quite the things I'm looking for.
Sorry to ask you so many questions but how do I see the logs I need to see?

**Comment by eouia** [comment]
Disable all other modules.
Stop the `pm2` (`pm2 stop MagicMirror`)
Then `npm start dev` in MagicMirror directory.

**Comment by leve0001** [comment]
[MagicMirror.log](https://github.com/eouia/MMM-AssistantMk2/files/3281163/MagicMirror.log)
 Here is the log. I think the Assistant gets the transcriptionHook but nothing happens after

**Comment by eouia** [comment]
This is front end log. How's the backend log? it would be shown on your terminal when you execute MM with `npm start dev`.

**Comment by leve0001** [comment]
> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.


This is shown in the terminal... After executing the reboot.js, it says nothing like it would get the right one but nothing happens. Not in the log and not on the screen.

**Comment by eouia** [comment]
add `verbose:true` to MMM-AssistantMk2 configuration then try again.

**Comment by leve0001** [comment]
Ahhh thats better

```terminal
> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Recipe is loaded: bildaus.js
[AMK2] Recipe is loaded: bildan.js
[AMK2] Temporal storage directory is clearing.
[AMK2] GAction action package updates: Pushing the app for the Assistant for testing...
Your app for the Assistant for project mirasamarta is now ready for testing on Actions on Google enabled devices or the Actions Web Simulator at https://console.actions.google.com/project/mirasamarta/simulator/
 
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Transcription: test  --- Done: false
[AMK2] Transcription: Tesla  --- Done: false
[AMK2] Transcription: Testlauf  --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: Testlauf  --- Done: true
{ requestId: '5d00cf6e-0000-2066-96d2-089e08231b04' } { profileFile: 'default.json', lang: 'de-DE' }
[AMK2] Device Action: { requestId: '5d00cf6e-0000-2066-96d2-089e08231b04' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed

```

**Comment by eouia** [comment]
Hmmmm.. very weird. Your transcription seems to be caught normally.

Can you modify node_helper.js temporally?

From:
https://github.com/eouia/MMM-AssistantMk2/blob/859d27622e71ef8005e0aa31f93592eadfb2fdd6/node_helper.js#L361-L364

To:
```js
          if (conversationResult.foundHook.length > 0) {
            console.log("[AMK2_TEMP]", conversationResult.foundHook)
            console.log("[AMK2] Conversation Completed")
            this.sendSocketNotification("CONVERSATION_END", conversationResult)
          } else {
```

Then test again. Check wheter `[AMK2_TEMP] blah blah....` would be shown.

**Comment by leve0001** [comment]
Yeah the following is shown now:

```terminal
[AMK2] Transcription: Testlauf  --- Done: true
{ requestId: '5d0037e4-0000-23d5-bf6d-94eb2c1e6564' } { profileFile: 'default.json', lang: 'de-DE' }
[AMK2] Device Action: { requestId: '5d0037e4-0000-23d5-bf6d-94eb2c1e6564' }
[AMK2] Assistant Text Response: 
[AMK2_TEMP] [ { key: 'INTRODUCTION',
    match:
     [ 'Testlauf', index: 0, input: 'Testlauf', groups: undefined ] } ]
[AMK2] Conversation Completed

```

By the way I (or we are 3 dudes on the project) really really appreciate your help, thank you

**Comment by eouia** [comment]
It shows your `INTRODUCTION`(Testlauf) is registered properly and be caught by AMK2 rightly also.
Next we will check whether frontend(MMM-AssistantMk2.js) could have a problem.

From:
https://github.com/eouia/MMM-AssistantMk2/blob/859d27622e71ef8005e0aa31f93592eadfb2fdd6/MMM-AssistantMk2.js#L586-L592

To:
```js
  doCommand (hooked, param, key) {
    console.log("[AMK2_TEMP]", hooked, param, key)
    var hook
    if (this.config.command.hasOwnProperty(hooked.command)) {
      hook = this.config.command[hooked.command]
    } else {
      return
    }
```

Then test it. Check whether added console.log would be executed and could be seen on Frontend dev-console log.

**Comment by leve0001** [comment]
[MagicMirror.log](https://github.com/eouia/MMM-AssistantMk2/files/3281390/MagicMirror.log)

Seems like it gets executed

**Comment by eouia** [comment]
Ok. almost done. Let's test some more finally. 

From:
https://github.com/eouia/MMM-AssistantMk2/blob/859d27622e71ef8005e0aa31f93592eadfb2fdd6/MMM-AssistantMk2.js#L619-L633

To:
```js
if (hook.hasOwnProperty("moduleExec")) { 
  console.log("Valid Entry Point?")
  var me = hook.moduleExec 
  var m = me.module 
  if (typeof me.module == 'function') { 
    m = me.module(param) 
  } 
  console.log("Module Array", m)
  if (Array.isArray(m)) { 
    MM.getModules().enumerate((module)=>{ 
      if (m.length == 0 || (m.indexOf(module.name) >=0)) { 
        console.log("Module found", module.name)
        var payload = Object.assign({}, param) 
        me.exec(module, payload, key) 
      } 
    }) 
  } 
} 
```

And one more thing; open your recipe and ...
```js
"INTRODUCTION": {
  moduleExec: {
    module: ["MMM-AssistantMk2"], // Or any other module name is ok.
    exec: (module, params, key) => {
      console.log("TEST", module.name, params, key)
      setTimeout(()=>{
        console.log("CHECK_TIMEOUT", module.name)
        module.sendNotification("SHOW_ALERT", {message:"test", timer:2000})
      }, 10000)
    }
  }
},
```

**Comment by leve0001** [comment]
Here is the backend log:

```terminal
[AMK2] Assistant Text Response: 
[AMK2] Transcription: das  --- Done: false
[AMK2] Transcription: test  --- Done: false
[AMK2] Transcription: Tesla  --- Done: false
[AMK2] Transcription: Testlauf  --- Done: false
[AMK2] end-of-utterance
[AMK2] Transcription: Testlauf  --- Done: true
{ requestId: '5d00e857-0000-2bf4-ad63-089e0822f32c' } { profileFile: 'default.json', lang: 'de-DE' }
[AMK2] Device Action: { requestId: '5d00e857-0000-2bf4-ad63-089e0822f32c' }
[AMK2] Assistant Text Response: 
[AMK2_TEMP] [ { key: 'INTRODUCTION',
    match:
     [ 'Testlauf', index: 0, input: 'Testlauf', groups: undefined ] } ]
[AMK2] Conversation Completed
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

and the frontend, seems like the command wont be executed:
[MagicMirror.log](https://github.com/eouia/MMM-AssistantMk2/files/3281511/MagicMirror.log)

**Comment by eouia** [comment]
Thanks for your patience. I've found what's wrong, but not so simple to FIX it at this time. But you can avoid this by put your recipe to configuration (as `transcriptionHootk` and `command`). It will work. I'll patch about this on next update.

```js
config: {
  transcriptionHook: {
          "INTRODUCTION": {
            pattern: "Testlauf",
            command: "INTRODUCTION"
          },
        },
        command: {
          "INTRODUCTION": {
            moduleExec: {
              module: ["MMM-AssistantMk2"],
              exec: (module, params, key) => {
                setTimeout(()=>{
                  module.sendNotification("SHOW_ALERT", {message:"test", timer:2000})
                }, 10000)
              }
            },
          }
        },
  ...

**Comment by leve0001** [comment]
We have to thank you. The workaround works well! We'll now try to add a mp3 sound to the notification :)

Thank you again and have a nice day.
