### ISSUE TITLE
스마트미러에 AssistantMk2 update 문구 안생기게 하는 법

### ISSUE THREAD

**Issue by dbwns373** [eouia/MMM-AssistantMk2#176]
안녕하세요 라즈비안으로 스마트미러를 사용하다가(실행중) 자동으로 업데이트 하라는 문구가 발생하는 걸 확인 하였습니다 
문구 내용 : update available for MMM-AssistantMk2 module.
              The current installation is 1 commit behind on the master branch

업데이트 하는 방법이 있지만 업데이트 후 오류 발생으로 오랜기간 사용하지 못한 경우가 있어서
 
스마트미러에 메세지를 출력하지 않고  수동으로 업데이트 하는 방법을 알고싶습니다.

감사합니다

**Comment by eouia** [comment]
`updatenotification` 모듈을 사용하고 있으셔서 그렇습니다. 해당 모듈을 disabled 시키거나 config에서 빼주세요.
