### ISSUE TITLE
Speaker Error : 1 There was an uncaught exception ! 

### ISSUE THREAD

**Issue by maqlhr** [eouia/MMM-AssistantMk2#177]
Hello guys.
the problem is that the control of the speaker is not released by google assistant / MMM-AssistantMk2 .. it happens mostly when adding a calendar entry through a series of back n forth google assistant conversation. It says ok tell me the title of event. and than you respond. Than GA says, what date is the event ? than you respond. Again GA says, are u sure u want to save this ? than you respond... 
basically in b/w these back n forth conversation. most of the time speaker will get haulted or something. MMM-AssistantMk2 togather with HOTWORD icon will stop blinking. The error in the logs will be as below.

 [AMK2] end-of-utterance
0|mm  | { requestId: '5d0653a7-0000-29e7-92b2-f4f5e8058ebc' } { profileFile: 'default.json', lang: 'en-US' }
0|mm  | [AMK2] Device Action: { requestId: '5d0653a7-0000-29e7-92b2-f4f5e8058ebc' }
0|mm  | [AMK2] Assistant Text Response: 
0|mm  | Speaker error: 1
0|mm  | Whoops! There was an uncaught exception...
0|mm  | 1
0|mm  | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm  | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

I feel that the control of the speaker is not released so the HOTWORD and ASSISTANCE doesnt blink or accept any more Listening... 

Single question / answers through GA is mostly fine but can sometimes give speaker error as well .. however, back n forth repeated questions can cause speaker error more frequently.

I am using speaker through 3.5mm Jack. and a USB mic. 

I will also add, that sometimes the calendar entry will succeed all the way ... but 7 out 10 times it will crash the assistant.. and the only way is to press CTRL - Q so magic mirror can restart again...

**Comment by eouia** [comment]
You're right. There could be unstable speaker releasing issue in this version. I've tried to solve that symptom but it was hard to represent continuously, so at this moment, I cannot catch the exact point to fix. 
My conclusion  to avoid this kind of problem is, dependency for external sound output program(like mpg321) should be eliminated. Sometimes it fails to stop and not be released on right time, that could make some issues.

I'm newly building new module independent from external dependencies, using HTML5 default sound output. but it is not ready yet. Sorry, wait for a while.

**Comment by rvkaki** [comment]
Hi, I'm having the same problem but it happens when music is playing through the speakers and I interact with the assistant. What do you mean with "dependency for external sound output program(like mpg321) should be eliminated"  ?
Thanks

**Comment by eouia** [comment]
@rvkaki 
Your issue is not ideally same with the original post.
Your issue is, two processes(Your music player and AssistantMk2) would try to use same speaker at once, but default ALSA setup of RPI is not allowed to mix multiple output stream.
To solve this;
- Use different speaker per each output. (sounds silly but absolutely confirmable)
- Stop/Hold other process when one process try to use speaker. (It could be done by notifications)
- Config your ALSA setup to use mixer (Sorry, I don't know how to do), or Use another Audio framework like PulseAudio.

**Comment by alexanderkreule** [comment]
_Config your ALSA setup to use mixer"_
Does anyone have an howto or an link for this?

**Comment by cavoixanha** [comment]
```
[AMK2] Transcription: how are you  --- Done: true
{ requestId: '5d87a46a-0000-22a3-b2f6-089e0831764c' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5d87a46a-0000-22a3-b2f6-089e0831764c' }
[AMK2] Assistant Text Response: 
Speaker error: 1
Whoops! There was an uncaught exception...
1
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```
the same error when I use:
+ 1 USB for the speaker (speaker is configured and  work with youtube but with mk2 don't output to USB speaker) (don't use 3.5 and HDMI for sound)
+ 1 USB for ps3 eye

**Comment by eouia** [comment]
@cavoixanha `Speaker error: 1` is usually occurred when;
- Your speaker is already occupied by other process (other background program or other module)
- Or at least, it is not released yet after using.
- Or you've missed or failed something on installation of sound player program(e.g. your system is missing `mpg321` and not installed.)

**Comment by cavoixanha** [comment]
mpg321 Is already install success
How check speaker is release or not ( i use usb Speaker dont use hdmi and 3.5)
You can help me!

**Comment by eouia** [comment]
@cavoixanha give me telegram(@eouia) We can diagnose together on real-time. But i live in Germany, so please contact me between 10am-5pm of European timezone.

**Comment by cavoixanha** [comment]
thank you, I check with library ```play-sound``` of nodejs  cause of the problem because mpg321 is error when play mpeg 2.0
```
Playing MPEG stream from 1567948453770.mp3 ...
MPEG 2.0 layer III, 32 kbit/s, 24000 Hz mono
Can't find a suitable libao driver. (Is device in use?)
```
because driver `libao` can relative `MPEG 2.0 layer III, 32 kbit/s, 24000 Hz mono` is don't work, but `MPEG 1.0 layer III, 128 kbit/s, 44100 Hz stereo` is working. I think usb card don't compatible with raspi should solve by use mplayer is resolve all
```
                                play: { // Full values are in `FOR EXPERTS` section.
                                  //playProgram: "mpg321", // recommended.
				  playProgram: "mplayer",
                                },
```

**Comment by eouia** [comment]
Nice to hear it.
