### ISSUE TITLE
MMM-Hotword Not working

### ISSUE THREAD

**Issue by vijayrraut** [eouia/MMM-AssistantMk2#18]
Hello,

I installed MMM-AssistantMK2, MMM-Hotword, everything compiled without errors, but when I start MagicMirror, Hotword starts but when I say "Smart mirror" or "Snowboy" nothing happens. I also tried removing all the modules and kept only Hotword module in config, still its not working.
Please help me.

pi@raspberrypi:~/MagicMirror $ npm start
> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-Hotword
MMM-Hotword started
Sockets connected & modules started ...
Launching application.
[HOTWORD] begins listening.

**Comment by eouia** [comment]
I think the module itself has no problem. Check your sound environment (ALSA or PulseAudio) Setup.
You should be able to record your voice and play it with this command

arecord -d 10 test.wav & aplay test.wav
Search RPI sound setup with Google.
