### ISSUE TITLE
How to hide google icon & text (your question) from the screen?

### ISSUE THREAD

**Issue by Ryan792** [eouia/MMM-AssistantMk2#180]
Is it possible to hide google icon & text? For example, if i ask "how's the weather" is it possible to hide text (how's the weather), microphone & speaker icon? 

I was wondering if it could work same as echo show or nest hub google without showing your question on the screen..:)

**Comment by eouia** [comment]
Unfortunately, current version has no feature about it. Maybe on next major update, I'll consider to add that feature.
