### ISSUE TITLE
Trigger Not Working

### ISSUE THREAD

**Issue by wahajmurtaza** [eouia/MMM-AssistantMk2#181]
My AssistantMk2 works fine when I click on it, I am using Hotword and seems to detect my command just fine, but it does not trigger the google assistant.

I am using the following lines in the config file

`
{
      module: "MMM-NotificationTrigger",
      config: {
        triggers:[
          {
            trigger: "HOTWORD_DETECTED",
            fires: [
              {
                fire:"HOTWORD_PAUSE",

              },
              {
                fire:"ASSISTANT_ACTIVATE",
		delay: 200,
                payload: function(payload) {
                  return {
                    "profile": payload.hotword
                  }
                }
              },
            ]
          },
          {
            trigger: "ASSISTANT_DEACTIVATED",
            fires: [
              {
                fire:"HOTWORD_RESUME"
              }
            ]
          },
        ]
      }
},

{
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1,0",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },

  {
  module: "MMM-Hotword",
  config: {
    mic: {
      recordProgram : "arecord",  
      device        : "plughw:1",
    },
    models: [
      {
        hotwords    : "smart_mirror",
        file        : "smart_mirror.umdl",
        sensitivity : "0.5",
      },
{
  hotwords: ["jarvis", "jarvis"],
  file: "jarvis.umdl",
  sensitivity: "0.8,0.8",
},
    ],
    
autostart:true,
      onDetected: {

        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },

  },
},

This is the result I get when I say Jarvis.

![image](https://user-images.githubusercontent.com/51536041/60347223-461f0580-99d6-11e9-96c6-b8ad4303643b.png)

`
My google assistant seems to work fine when I click on it, And I have installed NotificationTrigger

**Comment by eouia** [comment]
You seems using very old configuration. probably 1 year ago.
You don't need MMM-NotificationTrigger any more with current stable versions.
And you Hotword configuration is for ver 1.x; Read docs of MMM-Hotword and MMM-AssitantMk2, adjust your config

**Comment by wahajmurtaza** [comment]
Thanks for the rply, I tried the config file in already the mmm-assisntantmk2 already but found no joy,

![image](https://user-images.githubusercontent.com/51536041/60438651-a73f1700-9c2a-11e9-8b8b-c6c8328a6730.png)


This is what I got, I am using the following config file, also I have to use model otherwise it says [no model] and does nothing

`
{
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      mic: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },

models: [
      {
        hotwords    : "smart_mirror",
        file        : "smart_mirror.umdl",
        sensitivity : "0.5",
      },
{
  hotwords: ["jarvis", "jarvis"],
  file: "jarvis.umdl",
  sensitivity: "0.8,0.8",
},
    ],


      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },




`

**Comment by eouia** [comment]
Your configuration about MMM-Hotword is wrong (old) as I've said.
Read the manual :  https://github.com/eouia/MMM-Hotword/tree/master/documents
Especially, Read documentation about config : https://github.com/eouia/MMM-Hotword/blob/master/documents/config.md#simple-configuration-example

**Comment by wahajmurtaza** [comment]
Thanks for helping, great project (y)
