### ISSUE TITLE
Multi pattern transcriptionHook

### ISSUE THREAD

**Issue by skillfr** [eouia/MMM-AssistantMk2#183]
**Hello,
is it possible to do?**

transcriptionHook: {
    "REBOOTMM": {
      pattern: "redémarre Magic",
      command: "REBOOTMM"
    },
    "ScreenoffMM": {
      pattern: ["éteins-toi", "va dormir", "ferme les yeux",],
      command: "ScreenoffMM"
    },
    "ScreenonMM": {
      pattern: ["allume-toi", "reveille-toi", "ouvre les yeux",],
      command: "ScreenonMM"
    },
	"STOP_PLAY": {
	 pattern: ["arrête la vidéo", "stop youtube",],
	 command: "STOP_VID"
   },
  },

**otherwise I have to do that**

  transcriptionHook: {
    "REBOOTMM": {
      pattern: "redémarre Magic",
      command: "REBOOTMM"
    },
    "ScreenoffMM": {
      pattern: "éteins-toi",
      command: "ScreenoffMM"
    },
    "ScreenoffMM": {
      pattern: "va dormir",
      command: "ScreenoffMM"
    },
    "ScreenoffMM": {
      pattern: "ferme les yeux",
      command: "ScreenoffMM"
    },
    "ScreenonMM": {
      pattern: "allume-toi",
      command: "ScreenonMM"
    },
	"ScreenonMM": {
      pattern: "reveille-toi",
      command: "ScreenonMM"
    },
	"ScreenonMM": {
      pattern: "ouvre les yeux",
      command: "ScreenonMM"
    },
	"STOP_PLAY": {
	 pattern: "arrête la vidéo",
	 command: "STOP_VID"
   },
   	"STOP_PLAY": {
	 pattern: "stop youtube",
	 command: "STOP_VID"
   },
  },

**thank you**

**Comment by eouia** [comment]
Well, concept is right. 

But `pattern` cannot have `Array`.  So,
```js
"ScreenoffMM": {
  pattern: ["éteins-toi", "va dormir", "ferme les yeux",],
  command: "ScreenoffMM"
},
```
is wrong.

And
```
"STOP_PLAY": {
  pattern: "arrête la vidéo",
  command: "STOP_VID"
},
"STOP_PLAY": {
  pattern: "stop youtube",
  command: "STOP_VID"
},
```
This has no error literally, but, latter definition will override prior. So, `"arrête la vidéo"` will not work.

You can use **Regular Expression** to define multi patterns. Not so easy but worth to study.

**Comment by skillfr** [comment]
ok thank you, it'll stay like this: D

**Comment by ji3537** [comment]
"STOP_PLAY": {
  pattern: "stop youtube",
  command: "STOP_VID"
},

I think you need to create a sh file in script folder to do this.
I do not know how.
Can you teach me?

**Comment by eouia** [comment]
@ji3537 This post is another's issue. It will be a good manner to post new topic for your own.
Anyway, at this moment, I cannot catch your point. Could you tell me more details?
