### ISSUE TITLE
Cant get this module installed any more

### ISSUE THREAD

**Issue by Gandohr** [eouia/MMM-AssistantMk2#184]
**Describe the problem**
Cant get this module installed any more

**To Reproduce**
New SD card with the full Raspian Buster
After first boot and setup install MagicMIrror either the manual or automated install.
first module to install is MMM-AssistantMk2
MM fails to load en MMM-Assistant keeps giving all sorts of grpc en electron messages.
tried the options mention in the link on the MMM-AssistantMk2 page, even as 300 other google search solutions, been at this for 2 days 8 hours a day. can't seem to figure out the problem

**Expected behavior**

**Screenshots**

**Environment:**
 - Device : [e.g. RPI 3b+]
 - OS: [e.g. Raspbian Stretch]
 - Node Version :
 - Etc.

**Before you post issue, try this first**
- Confirm you have completed installation with instruction. (If you have a problem on installation step, find other similar issues or follow instruction carefully. But if you failed again, post issue here.)
- To make things simple, disable or omit or outcomment other modules from config.js except MMM-AssistantMk2 and MMM-Hotword.
- Add `verbose:true` to MMM-Assistant `config:{}` and `testMic:true` to MMM-Hotword `config:{}`. 
- Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
- If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.

Then report me.

**Comment by eouia** [comment]
In `Raspbian Buster`, grpc couldn't be compiled for electron yet. Use `stretch` or just wait for dependencies being stable.

**Comment by Gandohr** [comment]
> In `Raspbian Buster`, grpc couldn't be compiled for electron yet. Use `stretch` or just wait for dependencies being stable.

Thanks, took me some time to find Stretch as they removed it from their site.
But I'm up and running again.

**Comment by kschneier** [comment]
Buster is now stable, but the installation still doesn't work; have there been any new updates to grpc?

**Comment by eouia** [comment]
@kschneier not yet. And I'm on vacation. I can look inside after this month. sorry.

**Comment by eouia** [comment]
I add an additional guide for Raspbian Buster. `grpc` is not properly rebuilt under gcc8 (default of Buster), so you need to downgrade to gcc7.
https://github.com/eouia/MMM-AssistantMk2/wiki/Installation#3-post-installation
