### ISSUE TITLE
Google assistant is not activated

### ISSUE THREAD

**Issue by MinKhant9747** [eouia/MMM-AssistantMk2#186]
Hello, 
In My Mirror, google assistant is not activated although hotword is detected. 

I installed everything step by step and I used the MMM-Hotword version 2. 
Since hotword is detected, It is not problem in mic. I could not find the problem.
 
Here is my config of MMM-AssistanMk2 and MMM-Hotword.
`
{
		  	module: "MMM-AssistantMk2",
	  		position: "top_right",
  			config: {
				verbose: true,
				useWelcomeMessage: "Hi there! How can I help?",	
    				record: {
      					recordProgram : "arecord",  
      					device        : "plughw:1,0",
    				},

    				notifications: {
      					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
      					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
    				},
  			}
		},
		{
  			module: "MMM-Hotword",
			position: "top_right",
  			config: {
    				chimeOnFinish:null,
				testMic: true,
    				mic: {
      					recordProgram : "arecord",  
      					device        : "plughw:1,0",
    				},
    				models: [
      				{
        				hotwords    : "computer",
        				file        : "/home/pi/MagicMirror/modules/MMM-Hotword/models/computer.umdl",
        				sensitivity : "0.5",
      				},
    				],
    				command: {
				 "computer": {
      					notificationExec: {
        					notification: "ASSISTANT_ACTIVATE",
        					payload: (detected, afterRecord) => {
          						return {profile: "default"}
        					}
      					},
      					afterRecordLimit:0,
      					restart:false,
    				}
			 }
  			}
		},
`

Here is my out put.
`
> magicmirror@2.8.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
Create new news fetcher for url: https://www.channelnewsasia.com/rssfeeds/8396082 - Interval: 300000
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Started with text query: Hi there! How can I help?
{ requestId: '5d4b11a5-0000-2cc3-8d2a-883d24f8e844' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5d4b11a5-0000-2cc3-8d2a-883d24f8e844' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[HOTWORD] Detected: computer
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'computer', file: null }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Hotword
Stopping module helper: newsfeed

`
Thanks.

**Comment by eouia** [comment]
Sorry for late reply. I was on vacation.
Can you try again without `useWelcomeMessage`? It seems some suspicious point on your log about the sequence of order.

**Comment by MinKhant9747** [comment]
Thank you so much. Now, my one is working. I deleted the module and reinstalled it. Then, I removed `useWelcomeMessage` . I did work. Thanks.

**Comment by eouia** [comment]
Nice to hear it. Have a great day.
