### ISSUE TITLE
CONVERSATION_ERROR does not release microphone capture

### ISSUE THREAD

**Issue by Sulunia** [eouia/MMM-AssistantMk2#187]
**Describe the problem**
Microphone is not released after a CONVERSATION_ERROR happens. Assistant can no longer be triggered after this.

**To Reproduce**
* Start the mirror
* Disconnect device from network
* Trigger the hotword (using MMM-Hotword)
* Assistant will give a "CONVERSATION_ERROR"
* Try triggering the hotword again, with no success.

**Expected behavior**
Triggering the hotword again should re-activate the assistant.

**Environment:**
 - Device : Dragonboard 410c
 - OS: Linaro-developer 528 release
 - Node Version : v10.16.0

After the conversation error happens, the microphone is not released, which results in MMM-Hotword being unable to grab the microphone for hotword listening. 

I have fixed it in my end by calling ```record.stop()``` on the CONVERSATION_ERROR handlers, on the ```node_helper.js``` line 335 and 393.

**Comment by eouia** [comment]
Good for your report. I'll consider it on next updates.
