### ISSUE TITLE
Empty Assistant Response

### ISSUE THREAD

**Issue by alexanderkreule** [eouia/MMM-AssistantMk2#189]
I have Hotword and the assistant up and running but after i trigger the hotword is always get an empty "[AMK2] Assistant Text Response: "
So the trigger works, the request seems to be oke but no matter what; no text response

(i have turned of Voice response because of an Also Mixer problem with my hardware)

**Comment by eouia** [comment]
Sorry for late reply.
- Can you give me more detailed log about AMK2? Is there other log besides empty Text Response?
- What was your voice query?

In many case, voice query usually only return voice response (with html response if exists), so if you are using voice query but with setting off voice response, there could be no response at all to use.
Text response will return when you query by text commonly.
