### ISSUE TITLE
Assistant Voice Reponse Cutoff

### ISSUE THREAD

**Issue by pwolfeb** [eouia/MMM-AssistantMk2#191]
**Describe the problem**
When I ask the assistant a question (in tandem with MMM-Hotword (latest version)), the last bit of the Assistant's voice answer gets cut off, like the last 2 digits of an Address when you ask "where am i?".

**To Reproduce**
Just asking it questions.

**Expected behavior**
The assistant should be expected to read out the answer in full, not cut off.

-------------------------------------------------------------------------------------

Here is my config file for clarity - I'm running on a Raspberry Pi 3 with Raspbian OS.
{
                  module: "MMM-AssistantMk2",
                  position: "top_right",
                  config: {
                     deviceLocation: {
                        coordinates: { 
                                latitude: 38.6877495, // -90.0 - +90.0
                                longitude: -77.3130169, // -180.0 - +180.0
                                     },
                                     },
                       record: { 
                        recordProgram: "arecord", 
                        device: "plughw:1"        
                                },
                            play: { 
                                playProgram: "mpg321", // recommended.
                                },
                        responseVoice: true,
                        responseAlert: true,
                        verbose: true,
                          } //end config
                },
                {
                        module: "MMM-Hotword",
                        position: "top_left",
                        config: {
                           chimeOnFinish: null,
                            mic: {
                              recordProgram: "arecord",
                              device: "plughw:1",
                              sampleRate    : 16000,  
                            },
                            models: [
                              {
                                hotwords    : "raspberry",
                                notificationExec: {
                                  notification: "ASSISTANT_ACTIVATE",
                                  payload: (detected, afterRecord) => {
                                    return {profile:"default"}
                                  }
                                },
                                restart:true,
                                afterRecordLimit:0
                              }
                            }
                          }
                  },

**Comment by eouia** [comment]
Are you using HDMI for sound output? Some HDMI output could be laggy.
Or, reinstall `mpg321` or use another output player program.

Anyway, I'll update this module in a few days. It will not be dependent to sound output program, then it will be resolved.(I hope.)

**Comment by pwolfeb** [comment]
I'm using the 3.5mm jack on my Pi 3 - ill try your solutions though. Cant wait for the update! :)

**Comment by yassineaqejjaj** [comment]
Hello ! 
I'm currently having the same problem, using a 3.5mm jack on my Pi3. 
@pwolfeb did u find a solution to your issue ? 
Thanks
