### ISSUE TITLE
USB Mic probelm

### ISSUE THREAD

**Issue by waterbom625** [eouia/MMM-AssistantMk2#192]
I use a Logitech web camera as the microphone input. I modified the config.js file to configure　the recording device. But sometimes the USB device boot up as card 1, sometimes boot up as card 2. It's so weird, I don't have any other USB devices connected to my Raspberry Pi.   Any idea about it?

**Comment by eouia** [comment]
I'm not that kind of expert, but I think it is possible to give a custom device name to fix devices in ALSA setup. But I don't know details. sorry.

**Comment by waterbom625** [comment]
Thank you. You have given me a hint to solve the problem. I'd like to share the solution in case somebody runs into the same problem.  I modified the configuration in the config.js file as the following, and the problem is gone. 

      record: {
        recordProgram : "arecord",
      //device        : "plughw:2",
        device        : "plughw:CARD=U0x46d0x8b1",
      },

I think the number U0x46d0x8b1 is the USB vendor ID and device ID that matches the Logitech camera I use. Just ran the command " arecord -L", and you will get the IDs.
