### ISSUE TITLE
[question] Can I use google assistant on my phone ??

### ISSUE THREAD

**Issue by vipk31** [eouia/MMM-AssistantMk2#194]
Can I use google assistant on my phone? 
Not use device microphone
If yes, please help me

**Comment by eouia** [comment]
It is a different issue.
If you want to control MM with your assistant app on your phone, You don't need MMM-AssistantMk2.
The easiest way is using IFTTT and MMM-NotificationTrigger(Or MMM-Remote-Control or other modules which can receive IFTTT webhook request)
The harder(but cool and natural) way is making custom actions on your own Server or clouds like Firebase, but too difficult for non-developers.

**Comment by eouia** [comment]
To know how to control MM with existing Google Home (or your smartphone Assistant app), See https://forum.magicmirror.builders/topic/10917/guide-control-mm-via-google-home
