### ISSUE TITLE
pauseOnYoutube false cause youtube video no sound

### ISSUE THREAD

**Issue by LeonCWChan** [eouia/MMM-AssistantMk2#195]
**Describe the problem**
I want to activate Google Assistant during youtube video is playing, so I can stop the video with my voice, as I dont have a touch screen, can only use my voice to stop it. But using pauseOnYoutube: false (so that assistant can be activated during the video), all video will have no sound, but once removed back to the original setting of true. The sound came back.

Thank you so much!

**Comment by eouia** [comment]
What are you using mic & speaker? I think both are using same device. right?

**Comment by LeonCWChan** [comment]
Hi, thank you for the reply! Yes I am, the respeaker 2-mic, i use it for mic and I connected a speaker on it.

**Comment by eouia** [comment]
If the both devices are using same device name in configuration, it could be interfere each other. However I'm not that kind of experts so not sure. 
My suggestion is;
- Change Mic and Speaker device name through ALSA setup (Or something proper... sorry I have no idea about it)

**Comment by LeonCWChan** [comment]
Sure no problem, i give a try thx :)
