### ISSUE TITLE
Can't Run MM because an async node module problem

### ISSUE THREAD

**Issue by delpaGOD** [eouia/MMM-AssistantMk2#196]
**The problem**
It seems like that the async module in the index.js of the open module does not actually work. i tried everything i could related to the node version and its compatibility with this module and nothing. now i have no idea if this is what actually causes the problem or it is another thing.

I've installed the Assistant before with the previos version of MM and have no issues. Looks like after updating MM everything falls apart.

**Screenshots**

![Annotation 2019-08-19 215931](https://user-images.githubusercontent.com/42010099/63309351-da1d9700-c2cc-11e9-9c72-aa895438395d.png)

For some reason i'm not able to see the front end log, sorry about that.
![Annotation 2019-08-19 215719](https://user-images.githubusercontent.com/42010099/63309350-da1d9700-c2cc-11e9-85a6-169711d61b65.png)

 - Device : RPI 3b+
 - OS: Raspbian Stretch
 - Node Version : 10.16.3

Thanks for your time.

**Comment by eouia** [comment]
Hmmm.. weird, you said your node version is 10.16, but the error message means your node version is quite low (under 8).

**Comment by delpaGOD** [comment]
Thanks for the reply.

Exactly. this is driving me crazy.

![Annotation 2019-08-20 102721](https://user-images.githubusercontent.com/42010099/63351216-387e6000-c335-11e9-868d-1e5226333f8a.png)

i'm thinking of maybe purge the actual node version that i have installed and make a fresh installation. perhaps there are files of an older version of node corrupting the run.

**Comment by eouia** [comment]
Try to clear node cache first. Sometimes you might have older version trash in your node environment.

**Comment by delpaGOD** [comment]
Ok!

i've tried it out and gave me some errors, it offers me to rerun using '--force'. should i proceed?

![Annotation 2019-08-20 111917](https://user-images.githubusercontent.com/42010099/63355493-98c4d000-c33c-11e9-8a35-8e42bea18dc0.png)

**Comment by eouia** [comment]
maybe yes. Anyway, in worst case, Just format and reinstall again. :D

**Comment by delpaGOD** [comment]
Did it without issues.

![Annotation 2019-08-20 113158](https://user-images.githubusercontent.com/42010099/63356443-2c4ad080-c33e-11e9-9845-38a0cfd2267f.png)

unfortunately, it doesn't worked. the original error keeps showing up.

**Comment by eouia** [comment]
Hmmm...
Put this into top of your `config/config.js`
```js
console.log(process.versions)
```
Then try to execute MM (with `npm start`), It will show your node version of MM runtime environment in terminal.

**Comment by eouia** [comment]
Wait, it could be totally different issue.
try this in your MMM-AssistantMk2 directory then start again.
```sh
npm install open
```

**Comment by delpaGOD** [comment]
Tried both suggestions!

i've updated the open module version, but it doesn't fix the conflict.

![Annotation 2019-08-20 115011](https://user-images.githubusercontent.com/42010099/63358253-20144280-c341-11e9-8218-7ed08fd9892c.png)

Then, printing the versions of the runtime enviroment in the terminal proves that i actually have an early version of node running with MM. that's nuts.

![Annotation 2019-08-20 115541](https://user-images.githubusercontent.com/42010099/63358544-9a44c700-c341-11e9-8c4b-848667975657.png)

**Comment by delpaGOD** [comment]
there is a way to update and fix this without having to format and reinstall node maybe?

**Comment by eouia** [comment]
`npm rebuild` on MM directory could work or not. sorry, I'm not that kind of expert. :(

**Comment by eouia** [comment]
Your Electron seems also too low for current MM version. It could be the future issue. I recommend to format and reinstall whole system.

**Comment by delpaGOD** [comment]
it's ok.
with the whole system you mean the raspbian OS or only the MM?

**Comment by eouia** [comment]
Whole Rasbian. (Current newest stable version is Raspbian Buster)

ps. Don't forget to downgrade your `gcc` version to 7 before install this module. (Read the Doc)

**Comment by delpaGOD** [comment]
oh man. ok then. 
i'll try a couple of things before formatting raspbian but thank you very much for your time.

Have a great day, or night. ;)

**Comment by eouia** [comment]
Good luck to you.
