### ISSUE TITLE
Electron Version Mismatch - pm2 start mm launches black screen

### ISSUE THREAD

**Issue by ItzAlwaysDNS** [eouia/MMM-AssistantMk2#198]
Hello,

I presume this was the result from updating my Pi this other day, and then restarting it today.

The issue: launching pm2 start mm launches the MagicMirror with a black screen. If I stop the service, I am returned to the desktop. The issue only appears to occur when running my customized "config.js". If I run the program with the sample config.js, it runs fine. 

Below are the Pm2 logs for starting both the “config.sample.js” (which works) and the “config.js” (which does not work)

SAMPLE CONFIG – WORKS
`
PM2      | App [mm:0] starting in -fork mode-
PM2      | App [mm:0] online
0|mm     | > magicmirror@2.8.0 start /home/pi/MagicMirror
0|mm     | > sh run-start.sh
0|mm     | Starting MagicMirror: v2.8.0
0|mm     | Loading config ...
0|mm     | Loading module helpers ...
0|mm     | No helper found for module: alert.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: clock.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: calendar
0|mm     | No helper found for module: compliments.
0|mm     | No helper found for module: currentweather.
0|mm     | No helper found for module: weatherforecast.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: newsfeed
0|mm     | All module helpers loaded.
0|mm     | Starting server on port 8080 ...
0|mm     | Server started ...
0|mm     | Connecting socket for: updatenotification
0|mm     | Connecting socket for: calendar
0|mm     | Starting node helper for: calendar
0|mm     | Connecting socket for: newsfeed
0|mm     | Starting module: newsfeed
0|mm     | Sockets connected & modules started ...
0|mm     | Launching application.
0|mm     | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|mm     | Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
0|mm     | Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
PM2      | Stopping app:mm id:0
0|mm     | Shutting down server...
0|mm     | Stopping module helper: updatenotification
0|mm     | Stopping module helper: calendar
0|mm     | Stopping module helper: newsfeed
PM2      | pid=5011 msg=failed to kill - retrying in 100ms
PM2      | pid=5011 msg=failed to kill - retrying in 100ms
PM2      | App [mm:0] exited with code [0] via signal [SIGINT]
PM2      | pid=5011 msg=process killed
`

NORMAL CONFIG.JS (does not work)
`PM2      | App [mm:0] starting in -fork mode-
PM2      | App [mm:0] online
0|mm     | > magicmirror@2.8.0 start /home/pi/MagicMirror
0|mm     | > sh run-start.sh
0|mm     | Starting MagicMirror: v2.8.0
0|mm     | Loading config ...
0|mm     | Loading module helpers ...
0|mm     | No helper found for module: alert.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: clock.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: calendar
0|mm     | No helper found for module: compliments.
0|mm     | WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm     | Expected directory: electron-v3.1-linux-arm-glibc
0|mm     | Found: [electron-v2.0-linux-arm-glibc, node-v64-linux-arm-glibc]
0|mm     | This problem can often be fixed by running "npm rebuild" on the current system
0|mm     | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
0|mm     | Loading module helpers ...
0|mm     | No helper found for module: alert.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: clock.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: calendar
0|mm     | No helper found for module: compliments.
0|mm     | App threw an error during load
0|mm     | Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm     | Expected directory: electron-v3.1-linux-arm-glibc
0|mm     | Found: [electron-v2.0-linux-arm-glibc, node-v64-linux-arm-glibc]
0|mm     | This problem can often be fixed by running "npm rebuild" on the current system
0|mm     | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:63:3)
0|mm     |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm     |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|mm     |     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
0|mm     |     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
0|mm     |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm     |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12)
0|mm     | Whoops! There was an uncaught exception...
0|mm     | { Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm     | Expected directory: electron-v3.1-linux-arm-glibc
0|mm     | Found: [electron-v2.0-linux-arm-glibc, node-v64-linux-arm-glibc]
0|mm     | This problem can often be fixed by running "npm rebuild" on the current system
0|mm     | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:63:3)
0|mm     |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm     |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|mm     |     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
0|mm     |     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
0|mm     |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm     |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }
0|mm     | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm     | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm     | Launching application.
0|mm     | ATTENTION: default value of option force_s3tc_enable overridden by environment.
PM2      | Stopping app:mm id:0
PM2      | pid=5206 msg=failed to kill - retrying in 100ms
PM2      | App [mm:0] exited with code [0] via signal [SIGINT]
PM2      | pid=5206 msg=process killed
`

I’m assuming from my own readings, it would appear that the Pi is expecting Electron-v3.1-linux-arm-glibc but that is not found. I tried rebuilding my /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules directory but ended up accidentally deleting the entire directory of node_module. 

So now the same applies, it’s expecting Electron-v3.1-linux-arm-glibc, however after trying to rebuild using "npm install", it shows “[node-v64-linux-arm-glibc]”. I’m assuming all I need to do is rebuild that node_modules directory and get it to Electron-v3.1-linx-arm-glibc?

Here is the below “pm2 logs” with the latest error after accidentally deleting the node_modules directory:

Here is the below “pm2 logs” with the latest error:

`
pi@raspberrypi:~ $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/pi/.pm2/pm2.log last 15 lines:
PM2        | 2019-08-24T15:11:15: PM2 log: pid=11133 msg=failed to kill - retrying in 100ms
PM2        | 2019-08-24T15:11:15: PM2 log: App [mm:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-08-24T15:11:15: PM2 log: pid=11133 msg=process killed
PM2        | 2019-08-24T15:12:36: PM2 log: App [mm:0] starting in -fork mode-
PM2        | 2019-08-24T15:12:36: PM2 log: App [mm:0] online
PM2        | 2019-08-24T15:16:18: PM2 log: Stopping app:mm id:0
PM2        | 2019-08-24T15:16:18: PM2 log: pid=11236 msg=failed to kill - retrying in 100ms
PM2        | 2019-08-24T15:16:19: PM2 log: App [mm:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-08-24T15:16:19: PM2 log: pid=11236 msg=process killed
PM2        | 2019-08-24T15:16:27: PM2 log: App [mm:0] starting in -fork mode-
PM2        | 2019-08-24T15:16:27: PM2 log: App [mm:0] online
PM2        | 2019-08-24T15:23:43: PM2 log: Stopping app:mm id:0
PM2        | 2019-08-24T15:23:43: PM2 log: pid=11476 msg=failed to kill - retrying in 100ms
PM2        | 2019-08-24T15:23:44: PM2 log: App [mm:0] exited with code [0] via signal [SIGINT]
PM2        | 2019-08-24T15:23:44: PM2 log: pid=11476 msg=process killed

/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       | Expected directory: electron-v3.1-linux-arm-glibc
0|mm       | Found: [node-v64-linux-arm-glibc]
0|mm       | This problem can often be fixed by running "npm rebuild" on the current system
0|mm       | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
0|mm       |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
0|mm       |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:63:3)
0|mm       |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm       |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm       |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|mm       |     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
0|mm       |     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
0|mm       |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm       |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm       |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }
0|mm       | ATTENTION: default value of option force_s3tc_enable overridden by environment.

/home/pi/.pm2/logs/mm-out.log last 15 lines:
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: updatenotification
0|mm       | No helper found for module: clock.
0|mm       | Initializing new module helper ...
0|mm       | Module helper loaded: calendar
0|mm       | No helper found for module: compliments.
0|mm       | Whoops! There was an uncaught exception...
0|mm       | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm       | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm       | Launching application.
0|mm       | Shutting down server...
0|mm       | Stopping module helper: updatenotification
0|mm       | Stopping module helper: calendar
0|mm       | Stopping module helper: updatenotification
0|mm       | Stopping module helper: calendar

PM2      | App [mm:0] starting in -fork mode-
PM2      | App [mm:0] online
0|mm     | > magicmirror@2.8.0 start /home/pi/MagicMirror
0|mm     | > sh run-start.sh
0|mm     | Starting MagicMirror: v2.8.0
0|mm     | Loading config ...
0|mm     | Loading module helpers ...
0|mm     | No helper found for module: alert.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: clock.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: calendar
0|mm     | No helper found for module: compliments.
0|mm     | WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm     | Expected directory: electron-v3.1-linux-arm-glibc
0|mm     | Found: [node-v64-linux-arm-glibc]
0|mm     | This problem can often be fixed by running "npm rebuild" on the current system
0|mm     | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
0|mm     | Loading module helpers ...
0|mm     | No helper found for module: alert.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: clock.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: calendar
0|mm     | No helper found for module: compliments.
0|mm     | App threw an error during load
0|mm     | Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm     | Expected directory: electron-v3.1-linux-arm-glibc
0|mm     | Found: [node-v64-linux-arm-glibc]
0|mm     | This problem can often be fixed by running "npm rebuild" on the current system
0|mm     | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:63:3)
0|mm     |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm     |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|mm     |     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
0|mm     |     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
0|mm     |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm     |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12)
0|mm     | Whoops! There was an uncaught exception...
0|mm     | { Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm     | Expected directory: electron-v3.1-linux-arm-glibc
0|mm     | Found: [node-v64-linux-arm-glibc]
0|mm     | This problem can often be fixed by running "npm rebuild" on the current system
0|mm     | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:63:3)
0|mm     |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm     |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|mm     |     at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
0|mm     |     at Function.Module._load (internal/modules/cjs/loader.js:551:3)
0|mm     |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm     |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm     |     at Object. (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }
0|mm     | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm     | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm     | Launching application.
0|mm     | ATTENTION: default value of option force_s3tc_enable overridden by environment.
PM2      | Stopping app:mm id:0
PM2      | pid=11675 msg=failed to kill - retrying in 100ms
PM2      | App [mm:0] exited with code [0] via signal [SIGINT]
PM2      | pid=11675 msg=process killed
`

Would it be easier to just delete the Mmm-assistantmk2 module and rebuild it from scratch since my config.js was working fine before updating the pi? Or it is possible to rebuild that node_module directory and get the expected electron version installed again?

Thank you!!

**Comment by ItzAlwaysDNS** [comment]
Also, I am posting this from mobile and won't be home until tonight. Sorry if formatting is messed up!

**Comment by eouia** [comment]
> 0|mm | Expected directory: electron-v3.1-linux-arm-glibc
0|mm | Found: [node-v64-linux-arm-glibc]
0|mm | This problem can often be fixed by running "npm rebuild" on the current system
0|mm | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.1-linux-arm-glibc/grpc_node.node'
0|mm | Loading module he

You might have missed or failed something on `electron-rebuild` step. do `electron-rebuild` step again.

**Comment by sy8282** [comment]
[AMK2] assistant ready
/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.9.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-10-25T11_45_50_286Z-debug.log

**Comment by sy8282** [comment]
mm starts i speak to the mirror it recognises what i say then crashes to desktop any ideas where i messed it up
