### ISSUE TITLE
GA without sound when with 'npm start', only with 'serveronly'

### ISSUE THREAD

**Issue by solomon-il** [eouia/MMM-AssistantMk2#199]
Hello,

When I start MM with 'npm start' it's looks good, but after I said 'smart mirror' I hear a BEEP (noisy) and said (for example) 'what is the time'? - it shows me what I just said, and it shows me the written answer at the bottom, but won't "speak". after the first time it have my answer, it wont listen any more. (I can say 'smart mirror' 100 times but nothing..)
If instead I start the MM with 'node serveronly' and go to '0.0.0.0:8080/', I can say 'smart mirror' I hear a BEEP (pleasant sound) I ask and get answers by voice and written. can repeat and it works great.

I expect the MM works the same with 'npm start' just like in 'serveronly'

Thank you for your time!

Info:
 - Device : RPI 3b
 - OS: Raspbian Stretch
 - Node Version : 10.16.3
 - MM version: 2.8
 - AssistantMk2 and HotWord are updated (29.08.19)

Logs:
-~-~-~-~-~-~-~-~-~-~-~
> FrontEnd Logs:
-~-~-~-~-~-~-~-~-~-~-~
main.js:454 Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/en.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/default/alert//alert.js
module.js:476 Module registered: alert
loader.js:150 Bootstrapping module: alert
loader.js:179 Load script: modules/default/alert/classie.js
loader.js:179 Load script: modules/default/alert/modernizr.custom.js
loader.js:179 Load script: modules/default/alert/notificationFx.js
loader.js:155 Scripts loaded for: alert
loader.js:194 Load stylesheet: modules/default/alert/ns-default.css
loader.js:194 Load stylesheet: vendor/css/font-awesome.css
loader.js:157 Styles loaded for: alert
translator.js:175 alert - Load translation fallback: translations/en.json
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
    protocols.This exposes users of this app to unnecessary security risks.
    Consider loading the following resources over HTTPS or FTPS. 
 - http://0.0.0.0:8080/css/main.css
- http://0.0.0.0:8080/fonts/roboto.css
- http://0.0.0.0:8080/socket.io/socket.io.js
- http://0.0.0.0:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://0.0.0.0:8080/js/defaults.js
- http://0.0.0.0:8080/config/config.js
- http://0.0.0.0:8080/vendor/vendor.js
- http://0.0.0.0:8080/modules/default/defaultmodules.js
- http://0.0.0.0:8080/js/logger.js
- http://0.0.0.0:8080/translations/translations.js
- http://0.0.0.0:8080/js/translator.js
- http://0.0.0.0:8080/js/class.js
- http://0.0.0.0:8080/js/module.js
- http://0.0.0.0:8080/js/loader.js
- http://0.0.0.0:8080/js/socketclient.js
- http://0.0.0.0:8080/js/main.js
- http://0.0.0.0:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://0.0.0.0:8080/translations/en.json
- http://0.0.0.0:8080/translations/en.json
- http://0.0.0.0:8080/modules/default/alert//alert.js
- http://0.0.0.0:8080/modules/default/alert/classie.js
- http://0.0.0.0:8080/modules/default/alert/modernizr.custom.js
- http://0.0.0.0:8080/modules/default/alert/notificationFx.js
- http://0.0.0.0:8080/modules/default/alert/ns-default.css
- http://0.0.0.0:8080/vendor/css/font-awesome.css
- http://0.0.0.0:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/all.min.css
- http://0.0.0.0:8080/vendor/node_modules/@fortawesome/fontawesome-free/css/v4-shims.min.css
    
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
      Policy set or a policy with "unsafe-eval" enabled. This exposes users of
      this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureCSP @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184
loader.js:159 Translations loaded for: alert
loader.js:179 Load script: modules/default/updatenotification//updatenotification.js
module.js:476 Module registered: updatenotification
loader.js:150 Bootstrapping module: updatenotification
loader.js:155 Scripts loaded for: updatenotification
loader.js:157 Styles loaded for: updatenotification
loader.js:159 Translations loaded for: updatenotification
loader.js:179 Load script: modules/MMM-Hotword//MMM-Hotword.js
module.js:476 Module registered: MMM-Hotword
loader.js:150 Bootstrapping module: MMM-Hotword
loader.js:179 Load script: https://code.iconify.design/1/1.0.2/iconify.min.js
loader.js:155 Scripts loaded for: MMM-Hotword
loader.js:194 Load stylesheet: modules/MMM-Hotword/MMM-Hotword.css
loader.js:157 Styles loaded for: MMM-Hotword
loader.js:159 Translations loaded for: MMM-Hotword
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:476 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: modules/MMM-AssistantMk2/vendor/serialize.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: modules/MMM-AssistantMk2/MMM-AssistantMk2.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: css/custom.css
alert.js:153 Starting module: alert
updatenotification.js:10 Start updatenotification
main.js:472 All modules started!
module.js:198 updatenotification is suspended.
MMM-AssistantMk2.js:333 [AMK2]  YouTube iframe API is ready.

-~-~-~-~-~-~-~-~-~-~-~
> BackEnd logs:
-~-~-~-~-~-~-~-~-~-~-~

pi@raspberrypi:~/MagicMirror $ npm start dev

magicmirror@2.8.0 start /home/pi/MagicMirror
sh run-start.sh "dev"

Starting MagicMirror: v2.8.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
Whoops! There was an uncaught exception...
TypeError: Cannot read property 'length' of undefined
    at Class.activate (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:102:28)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:72:16)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
ALSA lib pcm.c:8389:(snd_pcm_set_params) Channels count (1) not available for PLAYBACK: Invalid argument
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] Detected: smart_mirror
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'smart_mirror', file: null }
ALSA lib pcm.c:8389:(snd_pcm_set_params) Channels count (1) not available for PLAYBACK: Invalid argument
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Assistant Text Response: 
[AMK2] end-of-utterance
[AMK2] Transcription: please  --- Done: false
[AMK2] Transcription: what is the  --- Done: false
[AMK2] Transcription: please.  --- Done: false
[AMK2] Transcription: what is the time  --- Done: false
[AMK2] Transcription: what is the time  --- Done: true
{ requestId: '5d6***77-0000-***-***-08***0*****1a0' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5d6****7-0000-****-9***-089*********a0' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }

**Comment by eouia** [comment]
Show me your configuration also. (for Hotword and AMK2)

**Comment by eouia** [comment]
and your speaker and mic also. (What type of device are you using?)

**Comment by solomon-il** [comment]
Configuration for Hotword and AMK2 (or you want the js files of them?):
               {
			module: "MMM-Hotword",
			position: "top_left",
			config: {
				chimeOnFinish: "resources/ding.wav",
				mic: {
					recordProgram: "arecord",
					device: "plughw:1"
				},
				models: [
					{
						hotwords    : "smart_mirror",
						file        : "smart_mirror.umdl",
						sensitivity : "0.5",
					},
				],
				commands: {
					"smart_mirror": {
						notificationExec: {
							notification: "ASSISTANT_ACTIVATE",
							payload: (detected, afterRecord) => {
								return {profile:"default"}
							}
						},
						restart:false,
						afterRecordLimit:0
					}
				},
				testMic:true
			}
		},
		{
			module: "MMM-AssistantMk2",
			position: "top_right",
			config: {
				deviceLocation: {
					coordinates: {
						latitude: 32.815626, // -90.0 - +90.0
						longitude: 35.077363, // -180.0 - +180.0
					},
				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
				profiles: {
					"default" : {
						lang: "en-US"
					}
				},
				youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.
				pauseOnYoutube:false,
				screenDuration: 4000,
				verbose:true
				
			}
		},

**Comment by eouia** [comment]
first, modify `chimeOnFinish:null,` then try again.

**Comment by solomon-il** [comment]
my mic is a USB output to mic + speaker
Configurations:
from: /usr/share/alsa/alsa.conf :
defaults.ctl.card 1
defaults.pcm.card 1

and from nano ~/.asoundrc:
pcm.!default {
        type hw
        card 1
}

ctl.!default {
        type hw
        card 1
}

**Comment by solomon-il** [comment]
After modify chimeOnFinish:null
it's sound is now a pleasant "ding" and the answer is with sound and written. Great!
but again, won't listen more than one time only.
I can say again 'smart mirror' but nothing happen.
the log of the backend (after the first request) is:

[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
....

**Comment by eouia** [comment]
Your mic/speaker seems 2in1, right?
In that case, your identifier `plughw:1` indicates both devices at a same time. So, when the speaker(indicated by `plughw:1`) should be stopped, the mic be closed together, that makes your symptom;
```
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
```
Module try to use mic but it was closed by previous shutting-off speaker process.
Hmmm.
I'm not such kind of expert so not sure. But you should configure your ALSA setup to get different device name/id for mic and speaker. (But I can't help about it.)

**Comment by eouia** [comment]
Maybe they would be `plughw:1,0` and `plughw:1,1` by default.

**Comment by solomon-il** [comment]
didn't changed 'plughw', but restart my PI and now it's working! :)
Thank you very much!

**Comment by eouia** [comment]
Nice to hear it. Have a great day!
