### ISSUE TITLE
Not Really an Issue. Just a Question.

### ISSUE THREAD

**Issue by bryan411001** [eouia/MMM-AssistantMk2#2]
This isn't an issue. I'm new to Github and I didn't know where to ask these question. I currently set up my MagicMirror with Google Assistant on the Raspberry Pi 3 B+ through Google's AIY Voicekit .img, but I wanted to know the following:

1. Is your module different from the AIY Voicekit by Google? If so, how are they different?

2. My goal is to wake the MM's LCD screen with a command. Then, I want to use Google Assistant to perform tasks based on my voice while also having the ability to perform 3rd Party Module tasks. 
[ex: "Play my Study playlist"(uses GA and outputs to the Spotify module)] Should I change to your AssistantMk2 module in order to accomplish this? 

3. Just overall, is it better to use this module instead of Google's AIY Voicekit?

Also, I'm very new to this. If there's a much simpler way, please feel free to give suggestions.

Thank you,
Bryan

**Comment by eouia** [comment]
1. Yes. quite different. AIY is an awesome implement of Google Assistant. However, basically, it is a stand-alone program. You can run AIY and MM on one device, But those are just running at the same time, not working together.
My module is implemented on MM, so My module can communicate with MM.
And.. It works with visual response.

2. With AIY - AIY is basically identical with pure Google Home -, you might do that. But, you should have a GoogleAction which can control MM. Unfortunately, nobody made it. There are many reasons, but the 2 biggest issues are;
1) Google has not approved Action for private usage like your wish. Your GA might be used by only one person - you and it would target just only one device - your mirror. Currently, nobody can make private Action.
2) And your Mirror should have a `SERVER` for your action's fulfillments and communication for controlling. Your mirror couldn't be a `SERVER`, so you need at least Google Cloud, PubNub (or something similar). It could be a Too Big project for just shutting down the screen of Mirror.

Instead, Google's approach is `Assistant for device`. AIY  is just `Assistant`. 
If you want to control specific device with Assistant embedded on itself, (It is different with controlling specific device with normal external Assistant like Google Home) you should use `Assistant for device`. It can interact with a device directly.

By the conclusion, for question 2. Currently you can not do that as your wish with AIY,

3. Maybe or not. My module is somewhat more difficult than AIY. Is it worthy? I don't know.
If you want to get just Google Home, maybe buying one might be better.
But as I know, for controlling MM with only Assistant, mine is only one at the moment.
However, there are alternative ways using Assistant for controlling MM. Using IFTTT could be one.

**Comment by bryan411001** [comment]
Ohhh! I see now. Thank you so much. This helped a lot.

**Comment by eouia** [comment]
I don’t know exactly. But ’asym’ setting might need in your area config, but not sure.
