### ISSUE TITLE
Begging for help with some LED strip lights with the assistant.

### ISSUE THREAD

**Issue by delpaGOD** [eouia/MMM-AssistantMk2#200]
Hey! How's going?

I'm not having an actual issue with the assistant. he's working nice!

what i'm trying to achieve is to run a python script that lights up a LED strip when the assistant is active and turn off the strip when its not. just like Alexa, for example.

I've already done the circuit and tested the GPIOs of the Raspberry pi running a shell script that runs the `.py` program. 

I'm actually new with Js and nodejs and i don't quite get the hang of the enviroment.

What i've tried to do is to write a `recipe` that do the task without having to use the transcriptionHook and turn on the strip manually. So i've tried to integrate the `ASSISTANT_ACTIVATED` and `ASSISTANT_DEACTIVATED` notifications to run the `command` and execute the `.sh` file that opens the `.py` program.

As you know, it doesn't worked. 

First really bad coding attempt:

```
    notfications: {
      ASSISTANT_ACTIVATED: "ASSISTANT_ACTIVATED",
    "ASSISTANT_ACTIVATED": {
      command: "LIGHTSON"
    },
  },
  
  
  command: {
    "LIGHTSON": {
      shellExec: {
      exec: "~/APPI/modules/MMM-AssistantMk2/recipes/lights-control/lights.sh",
      options: null,
      }
    
    },
  }
```
 **(APPI is the name of the MM, i've changed it beacuse i'm working on this for a school project)**

Then i've tried to execute the script in the `config.js` file or others ways, like doing a ` switch(case)` using the same concept but every time i try something i get more confused haha.

I hope you can give me a hand ;)
Thanks for reading!

**Environment:**
 - Device : RPI 3b+
 - OS: Raspbian Buster

**Comment by eouia** [comment]
You can do your intention by `onIdle` and `onActivate` features.
```js
onIdle: {
      //timer: 1000*60*30, // if you don't want to use this feature, just set timer as `0` or command as ""
      //command: "HIDEMODULES",
      timer: 0,
      command: null,
    },

    onActivate: {
      timer: 0,
      //command: "SHOWMODULES"
      command: null,
    },
```

**Comment by delpaGOD** [comment]
YES! Great! it worked! partially...

The lights turn on as they're supposed to in the `onActivate` feature. but `onIdle` doesn't seems to work to turn off the lights when the assistant stops talking.

```
onIdle: {
      //timer: 1000*60*30, // if you don't want to use this feature, just set timer as `0` or command as ""
      //command: "HIDEMODULES",
      timer: 0,
      
      command: "LIGHTSOFF",
    },

    onActivate: {
      timer: 0,
      
      command: "LIGHTSON",
    },
  command: {
    "LIGHTSON": {
      shellExec: {
      exec: "~/APPI/modules/lights-control/LIGHTS_ON.sh",
      options: null,
      }
    },
    "LIGHTSOFF": {
      shellExec: {
      exec: "~/APPI/modules/lights-control/LIGHTS_OFF.sh",
      options: null,
      }
    },

```

I've manage to do the task inside `node_helper.js` with `shelljs` and execute the script when the conversation ends.

![Annotation 2019-09-01 113515](https://user-images.githubusercontent.com/42010099/64078055-b1be7100-ccac-11e9-869d-146585083009.png)

But... it seems to slow down the program and even prevents to quit the modules correctly when MM is stoped.

Any Suggestion?
Thank u.

**Comment by eouia** [comment]
You've set `timer` of `onIdle` as `0`. It will not executed. Give some small seconds like `1000` It means After 1 sec, `onIdle` will be activated.

**Comment by delpaGOD** [comment]
Thank u very much!

**Comment by Zpider23** [comment]
Could explain in detail how to did this? I'm trying to accomplish the same thing but I dont know much.

**Comment by Zpider23** [comment]
Could you please explain how to did this @delpaGOD 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
