### ISSUE TITLE
Continued conversation doesn't works

### ISSUE THREAD

**Issue by PierreB49** [eouia/MMM-AssistantMk2#202]
I'm using AssistantMk2 in conjunction with Hotword and it seems that the "Continued Conversation" feature of google assistant is not working. When the response is done I can't interact anymore withe the assistant.

Is this feature not (yet !) implemented or is there an issue with my configuration ?

Thank you for your answers.

**Comment by eouia** [comment]
Hmmm. I implemented that feature so it should be working, but.. there could be my mistake or not. (Sorry, too past to remember exactly) I'll inspect it.

**Comment by Zpider23** [comment]
Did you ever find out if it is working or not?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maximiliano2018** [comment]
Hi Eouia;

I have the same problem;
1) I say "Smart Mirror" (HotWord)
2) Then "Tell me the Forecast"
3) Google Assistant mentions it without problems
4) The conversation ends and it is no longer possible to speak to him again, it is as if from the second time he no longer detects the "HotWord"

The previous version of the Smart, used this version,
{
module: "MMM-Hotword",
config: {


 snowboy: [

{
hotwords: "smartmirror", // this will be sent to other module for distinguishing which hotword is detected.
file: "resources / models / smart_mirror.umdl",
sensitivity: '0.99',
  },
],

record: {
recordProgram: "arecord",
device: "plughw: 1",
},
autostart: true,
onDetected: {
notification: function (payload) {
return "ASSISTANT_ACTIVATE"
},
payload: function (payload) {
return {
profile: payload.hotword
}
}
},
},
},

That version worked perfect, allowing one query after another, however I fail to identify what is happening in this case.

Can you help us?
Thank you so much,

**Comment by dang1412** [comment]
I think the `Hotword` going to sleep after first time triggering assistant, we need somehow activate it again when assistant response done.

**Comment by eouia** [comment]
@maximiliano2018 
It is not the same issue. your issue might be come from the inappropriate config of MMM-AssistantMk2. You probably have missed HOTWORD_RESUME related notification configuration in MMM-AssistantMk2

**Comment by maximiliano2018** [comment]
My friend, you are absolutely right.
My apologies, my mistake.
Cordial Greetings
