### ISSUE TITLE
How to stop / close Youtube is playing

### ISSUE THREAD

**Issue by ExlLab** [eouia/MMM-AssistantMk2#203]
Hi,
After open a video on Youtube by command from Google Assistant, how to stop / close Youtube is playing? And how to can request other command to Google Assistant?
Thank you.

**Comment by eouia** [comment]
`pauseOnYoutube:false,` will make it. When you activate Assistant again(by calling hotword or other method), current youtube playing will stop. 
But frankly said, I don't recommend. There is such a possibility of unintentional recognition or misactivating by surrounded noises, talks or sound output from Youtube clip itself. 
Anyway, that feature is not a default provided function of Assistant SDK, so I implemented it but being regret. I will drop that feature(youtube playing) on next updates.

**Comment by ExlLab** [comment]
Thank you so much.
I set: `pauseOnYoutube:false` and it worked.
However, that is awesome if it have pause/ stop Youtube function.

**Comment by eouia** [comment]
I'll remove youtube related features in this module on next updates. It was not the main feature of this module but major trouble-maker. So I'll divide that feature as another independent module (Frankly it has been done already. MMM-Youtube is that)
