### ISSUE TITLE
audiosize is sometimes 0

### ISSUE THREAD

**Issue by Osmund** [eouia/MMM-AssistantMk2#204]
Sometimes the the audiosize is 0 in conversationResult.audioSize and I get no response from AssistantMk2. The google assistant service returns a screenOutput and it is written to temp.html in the tmp folder. 

I have changed the language to norwegian in the google assistant app and it transcribes correct when i talk.

Is there an easy way to show the screenOutput even if there is no audio.

**Comment by eouia** [comment]
Google is sometimes missing vocal response. It cannot be predictable or noticed when the response is missing. I have a headache about it. 

I'm building new version to solve that problem, but nowadays I have not enough time to finish it. sorry.

**Comment by ExlLab** [comment]
I am having the same issues when i ask about time and weather, or some short question.

**Comment by eouia** [comment]
@Osmund 
Maybe Norwegian language is not yet supported. 
https://developers.google.com/assistant/sdk/reference/rpc/languages

@ExlLab 
What language are you using? Some question might not be responded by vocal, but weather and time is very basic query so it should be responded. All your questions are not responded? Or just specific questions?

**Comment by Osmund** [comment]
@eouia I´m experiencing the same as ExlLab. Sometimes I get an audio response.  It seems that I always get a screenOutput. When she responds she speaks norwegian. My first thinking was that the response didn´t get enough time since there are a few settimeout in the code. 

A weird example is if I ask "Hvordan er været i dag" (How´s the weather today), audiosize is 0, but i get a correct screenOut which is written to Temp.html. If I ask "Hvem er været i dag" (Who is the weather today), I will get audio and the screenOut is displayed. 

When I read through the sdk documentation for the google sdk and the nodejs implementation they also link to this page: https://developers.google.com/actions/localization/languages-locales .

I get a language is not supportet error if I set nb-NO as the language code in config.js, but it seems that the google sdk uses the language setting in the google assistant app. 

In the documentation for Language_Code in DialogStateIn it says: 
> Required Language of the request in IETF BCP 47 syntax (for example, "en-US"). See Language Support for more information. If you have selected a language for this device_id using the Settings menu in your phone's Google Assistant app, that selection will override this value.

It would be nice to get audioresponse for everything, but if I just could display screenOut for those that don´t have audio, It would be really nice.

**Comment by eouia** [comment]
If you get a better solution, share your solution with PR. I'll accept it with pleasure.
