### ISSUE TITLE
auth_and_test.js Syntax Error

### ISSUE THREAD

**Issue by Zpider23** [eouia/MMM-AssistantMk2#205]
When I try and run auth and test it gives me this error
`pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ node auth_and_test.js

/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/open/index.js:29
		...options
		^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:6:14)
`

**Comment by eouia** [comment]
You probably updated(`git pull`) this module recently but didn't `npm install` to finish update process.

**Comment by Zpider23** [comment]
So I do npm install in the AssistantMk2 directory

**Comment by Zpider23** [comment]
v8

**Comment by Zpider23** [comment]
Should I upgrade

**Comment by Zpider23** [comment]
If I do need to upgrade to what version should I do?

**Comment by Zpider23** [comment]
I upgraded my node version to v10 but it still throws the syntax error

**Comment by Zpider23** [comment]
should I try reflashing?

**Comment by Zpider23** [comment]
>What is your node version? I think your node version seems too low to run this module.

@eouia I don’t know if this will help but in MMM-Assiatant, I got a syntax error as well. I’m also at the latest version of Raspbian. I wasn’t getting these errors when I was on Stretch. Should I try to downgrade back?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eouia** [comment]
Hmmm. `...` is `rest operator` and it was introduced and be stable from node version 8.6.0 So your system not have that error after update.
- There is a possibility of update fail.
- There is a possibility that your global node version is different with your running MM on runtime.

**Comment by Zpider23** [comment]
No errors popped up while I updated so I believe it is the second. Could you explain it more in detail and how to fix it?

**Comment by eouia** [comment]
open `config.js` and add this code to the 1st line of file.
```js
console.log("ENVIRONMENT:", process.versions)
```

Then execute MM (I recommend `npm start` instead of `pm2` method) and see the log. It will print out your environment of runtime.

**Comment by Zpider23** [comment]
The node version is actually too high. I'm going to reflash and I believe that is going to fix the problems I have.
