### ISSUE TITLE
Select playout device

### ISSUE THREAD

**Issue by alexanderkreule** [eouia/MMM-AssistantMk2#207]
i have been having the "speaker error" one and worked around it.
When i use an onboard soundcard module i always get the error. When using an usb soundcard for recording and the raspberry for playout it works fine (really cool and great :)

My question (and not an issue): can i set the playout device for the assistant?
My guess is that when i make the onboard sound the default playout but use the add-on module for the assistant (and usb for recording) it will work.

**Comment by eouia** [comment]
Unless you select specific speaker device, the default sound output channel will be selected to sound out.

You can assign specific device for sound-out of MMM-AssistantMk2 with this configuration.
```js
    play: {
      encodingOut: "MP3", //'MP3' or 'WAV' is available, but you might not need to modify this.
      sampleRateOut: 24000,
      playProgram: "mpg321", //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
      playOption: [], // If you need additional options to use playProgram, describe here. (except filename)
      // e.g: ["-d", "", "-t", "100"]
    },
```
`playOption` is that. if you can use `mpg321`(when you select it as playProgram) like this; `mpg321 -d plughw:1,0`, `playOption` would be `playOption: ["-d", "plughw:1,0"]`.

**Comment by alexanderkreule** [comment]
When i put
`play: {
playOption: [plughw:0,0"],
},`
I don't get the speaker error, thats one step ahead. But now i dont hear anything (with npm start dev i can see that every thing is working fine and with aplay/speaker-test there is sound)
Any clue?

**Comment by eouia** [comment]
I think `playOption: ["-d", "plughw:0,0"].` would be.  ("-d" is flag for device)

**Comment by alexanderkreule** [comment]
i can not get the playOption to work, somehow it won't play over the selectcard. I have now removed the hardware card en just use the raspberry output with and usb-card for the mic.
