### ISSUE TITLE
Questions about configuration

### ISSUE THREAD

**Issue by Zpider23** [eouia/MMM-AssistantMk2#208]
I’m using Hotword so I used the config thatbb be said Hotword v2. I also saw one the said full detailed version. Do I need both or does Hotword v2 already have the detailed version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eouia** [comment]
If you don't need detailed modification, just leave it as work. And you don't have to use entire "Full detailed" version. Just select what you need and use it in your configuration.

**Comment by Zpider23** [comment]
Ok Thanks.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
