### ISSUE TITLE
Virtual Output Issue 

### ISSUE THREAD

**Issue by maxwelllai** [eouia/MMM-AssistantMk2#21]
#1：The Module seems in normal working condition, But when I check my Google cloud console in the API request monitor section, it shows the message below with red color highlight.

Also, when I say" Give me a direction to xxx"
and It respond just like what it suppose to(Voice respond with virtual text output “Ok, getting you direction to xxxx”), but then I was expecting there should be some sort of Map pop out beside the text,But Its only showing text,  When I say show map of xxx, it pop out also text with link, but not map,(Ive already enable Google Map ApI) Other than this, everything looks normal. 

api/request_count:consumed_api:REDUCE_SUM

**Comment by eouia** [comment]
That is not your fault. 
ScreenOutput of Assistant SDK is not structured data, but almost hard-coded html. It was originally served for some specific devices (like LG Smart TV), So there is missed additional information for complete using. I wish next version of SDK would serve more detailed data for any extensions, but not currently.
