### ISSUE TITLE
Error updating actions on google console with action package

### ISSUE THREAD

**Issue by Zpider23** [eouia/MMM-AssistantMk2#210]
When I'm trying to register my device with gaction it throws this error.
`pi@raspberrypi:~ $ cd ~/MagicMirror/modules/MMM-AssistantMk2/gaction
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ wget hhttps://dl.google.com/gactions/updates/bin/linux/arm/gactions
hhttps://dl.google.com/gactions/updates/bin/linux/arm/gactions: Unsupported scheme ‘hhttps’.
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ wget https://dl.google.com/gactions/updates/bin/linux/arm/gactions
--2019-09-09 15:46:34--  https://dl.google.com/gactions/updates/bin/linux/arm/gactions
Resolving dl.google.com (dl.google.com)... 172.217.10.78, 2607:f8b0:4006:802::200e
Connecting to dl.google.com (dl.google.com)|172.217.10.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17540292 (17M) [application/octet-stream]
Saving to: ‘gactions’

gactions            100%[===================>]  16.73M   823KB/s    in 21s     

2019-09-09 15:46:56 (832 KB/s) - ‘gactions’ saved [17540292/17540292]

pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ chmod +x gactions
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./gactions update --action_package actions.json --project YOUR_PROJECT_ID
Error: Not logged in. Please run `gactions login` to login.
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./gactions update --action_package actions.json --project okg2-301cf
Error: Not logged in. Please run `gactions login` to login.
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ gactions login
bash: gactions: command not found
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./ gactions login
bash: ./: Is a directory
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./gactions login
Visit the URL to authorize access:

 https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&client_id=619137215474-jg0sfcio74m3o5523m0dav65j2gdbgvr.apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A37191&response_type=code&scope=openid+email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Factions.builder&state=state
 --disable-quic --enable-tcp-fast-open --disable-gpu-compositing --ppapi-flash-path=/usr/lib/chromium-browser/libpepflashplayer.so --ppapi-flash-args=enable_stagevideo_auto=0 --ppapi-flash-version=
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Opening in existing browser session.

Waiting for authorization...
Logged in.
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./gactions update --action_package actions.json --project okg2-301cf
Error: Error updating Actions on Google console with Action package
`

**Comment by eouia** [comment]
pi@raspberrypi:/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./gactions update --action_package actions.json --project YOUR_PROJECT_ID

replace "YOUR_PROJECT_ID" with your **real gooe project id**.

**Comment by Zpider23** [comment]
I did but it still through the error

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eouia** [comment]
show me your action file.
