### ISSUE TITLE
Help with LEDs

### ISSUE THREAD

**Issue by Zpider23** [eouia/MMM-AssistantMk2#211]
I saw that you helped @delpaGOD set up LEDs could you explain how you did that because I’m trying to replicate the same thing. Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zpider23** [comment]
I’m also new to programming on Pi so I don’t understand much 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eouia** [comment]
I didn't help LED related itself. My coaching was just how to execute external shell command/script. You need to have(or find) a script which can control your LEDs. If so, I can help how to use it with this module. Do you have?
