### ISSUE TITLE
Assistant replies are delayed...

### ISSUE THREAD

**Issue by bryan411001** [eouia/MMM-AssistantMk2#212]
**Describe the problem**
The whole module works perfectly fine. The hotword detects and everything runs smoothly. However, the response is always either delayed in the beginning, or it'll stutter a bit. Mainly, the delay in the beginning of the audio for about 0.5 sec. Small, but the assistant is always muted for the first word when replying. It doesn't sound very clean like how it should. 

**To Reproduce**
1: Say the hotword
2: Say the task
3: Response is delayed/cutoff 

**Expected behavior**
1: Say the hotword
2: Say the task
3: Response is clean and fluent

**Environment:**
 - Device : RPI 3b+
 - OS: Raspbian Stretch
 - Node Version : v9.11.2
 - Audio Output: HDMI
 - Mic: USB Microphone

**Comment by eouia** [comment]
Unfortunately, HDMI has audio output delay. It is not fixable with my ability.
