### ISSUE TITLE
Cannot find module './snowboy/lib/node/index.js'

### ISSUE THREAD

**Issue by jasb1011** [eouia/MMM-AssistantMk2#213]
Hello eouia, i found this problem with my smart mirror:

0|mm     | > magicmirror@2.8.0 start /home/pi/MagicMirror
0|mm     | > sh run-start.sh
0|mm     | Starting MagicMirror: v2.8.0
0|mm     | Loading config ...
0|mm     | Loading module helpers ...
0|mm     | No helper found for module: alert.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: clock.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: calendar
0|mm     | No helper found for module: compliments.
0|mm     | No helper found for module: currentweather.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: newsfeed
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: MMM-AssistantMk2
0|mm     | WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module './snowboy/lib/node/index.js'
0|mm     | Loading module helpers ...
0|mm     | No helper found for module: alert.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: clock.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: calendar
0|mm     | No helper found for module: compliments.
0|mm     | No helper found for module: currentweather.
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: newsfeed
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: MMM-AssistantMk2
0|mm     | App threw an error during load
0|mm     | Error: Cannot find module './snowboy/lib/node/index.js'
0|mm     |     at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
0|mm     |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|mm     |     at Function.Module._load (internal/modules/cjs/loader.js:528:25)
0|mm     |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm     |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm     |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
0|mm     |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:234:3)
0|mm     |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm     |     at Module.load (internal/modules/cjs/loader.js:620:32)
0|mm     | Whoops! There was an uncaught exception...
0|mm     | { Error: Cannot find module './snowboy/lib/node/index.js'
0|mm     |     at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
0|mm     |     at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
0|mm     |     at Function.Module._load (internal/modules/cjs/loader.js:528:25)
0|mm     |     at Module.require (internal/modules/cjs/loader.js:658:17)
0|mm     |     at require (internal/modules/cjs/helpers.js:20:18)
0|mm     |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
0|mm     |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:234:3)
0|mm     |     at Module._compile (internal/modules/cjs/loader.js:711:30)
0|mm     |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
0|mm     |     at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
0|mm     | MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
0|mm     | If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
0|mm     | Launching application.
0|mm     | ATTENTION: default value of option force_s3tc_enable overridden by environment.
0|mm     | Shutting down server...
0|mm     | Stopping module helper: updatenotification
0|mm     | Stopping module helper: calendar
0|mm     | Stopping module helper: newsfeed
0|mm     | Stopping module helper: MMM-AssistantMk2
0|mm     | Stopping module helper: updatenotification
0|mm     | Stopping module helper: calendar
0|mm     | Stopping module helper: newsfeed
0|mm     | Stopping module helper: MMM-AssistantMk2
PM2      | App [mm:0] exited with code [0] via signal [SIGINT]
PM2      | App [mm:0] starting in -fork mode-
PM2      | App [mm:0] online
0|mm     | > magicmirror@2.8.0 start /home/pi/MagicMirror
0|mm     | > sh run-start.sh
PM2      | Stopping app:mm id:0
PM2      | pid=18840 msg=failed to kill - retrying in 100ms
PM2      | App [mm:0] exited with code [0] via signal [SIGINT]
PM2      | pid=18840 msg=process killed

Please help me, thank you

**Comment by eouia** [comment]
Something was missed or failed on the installation of `MMM-Hotword`. Check MMM-Hotword installation again.

**Comment by jasb1011** [comment]
How do I check the installation

**Comment by eouia** [comment]
Did you follow this instruction?
https://github.com/eouia/MMM-Hotword/blob/master/documents/install.md
What has happened on installation?

**Comment by jasb1011** [comment]
Yes I did the installation correctly, I even properly rebuilt the electron

**Comment by eouia** [comment]
But your electron-rebuild seems not successful.

**Comment by jasb1011** [comment]
No it told me the electron build was successful

**Comment by eouia** [comment]
electron-rebuild were needed for both modules(MMM-Hotword & MMM-AssistantMk2) per each separately. On MMM-AssistantMk2 installation, you had to install it manually.
But on MMM-Hotword, it would be processed by `installer.sh` automatically. (unless you did it manually). So I have a doubt about how you could find it was successfully installed. 
```
Error: Cannot find module './snowboy/lib/node/index.js'
```
This error occurs when the installation of MMM-Hotword was not successful. You probably have met some error about this (especially `ts` be related). I need what you've met to figure out what happened.
