### ISSUE TITLE
2019-04-08-raspbian-stretch에서 설치하려면 어떻게 해야될까요?

### ISSUE THREAD

**Issue by limJ224** [eouia/MMM-AssistantMk2#215]
안녕하세요 저는
2019-04-08-raspbian-stretch
라즈베리파이3B+사용중입니다
현재 나와있는 설치방법 대로 하면될까요?
gcc-7으로 변경 해야할까요?도움 부탁드리겠습니다!

**Comment by eouia** [comment]
Raspbian Stretch면 아마 gcc가 6이거나 7일거라서 gcc 다운그레이드는 굳이 안하셔도 됩니다.
