### ISSUE TITLE
build MMM-AssistantMk2 Rebuild Failed

### ISSUE THREAD

**Issue by marion001** [eouia/MMM-AssistantMk2#218]
Hi everybody! I had problems building MMM-AssistantMk2 in MagicMirror version 2.9.0 using: ./node_modules/.bin/electron-rebuild
Who could possibly eat
In previous versions there was no error
full error: https://pastebin.com/raw/P9dZyBUn

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.4
gyp info using node@10.16.3 | linux | arm64
gyp info find Python using Python version 2.7.15 found at “/usr/bin/python”
gyp http GET https://electronjs.org/headers/v3.0.13/iojs-v3.0.13-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v3.0.13/iojs-v3.0.13-headers.tar.gz
gyp http GET https://electronjs.org/headers/v3.0.13/SHASUMS256.txt
gyp http 200 https://electronjs.org/headers/v3.0.13/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ ‘/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/gyp/gyp_main.py’,
gyp info spawn args ‘binding.gyp’,
gyp info spawn args ‘-f’,
gyp info spawn args ‘make’,
gyp info spawn args ‘-I’,
gyp info spawn args ‘/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/build/config.gypi’,
gyp info spawn args ‘-I’,
gyp info spawn args ‘/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/addon.gypi’,
gyp info spawn args ‘-I’,
gyp info spawn args ‘/home/pi/.electron-gyp/iojs-3.0.13/common.gypi’,
gyp info spawn args ‘-Dlibrary=shared_library’,
gyp info spawn args ‘-Dvisibility=default’,
gyp info spawn args ‘-Dnode_root_dir=/home/pi/.electron-gyp/iojs-3.0.13’,
gyp info spawn args ‘-Dnode_gyp_dir=/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp’,
gyp info spawn args '-Dnode_lib_file=/home/pi/.electron-gyp/iojs-3.0.13/

**Comment by the7reek** [comment]
Try 
npm install grpc@1.23
And rebuild electron again
It worked for me

**Comment by eouia** [comment]
newly leased grpc@1.24 has some issue on compiling for electron. Use grpc@1.23.3 instead, until the fix would be provided by grpc team
