### ISSUE TITLE
youtube 재생 시 화면 겹침

### ISSUE THREAD

**Issue by in3166** [eouia/MMM-AssistantMk2#226]
안녕하세요

유뷰브를 재생하면 날씨랑 기사 모듈이 화면 위로 올라오는데 어떻게 해야할까요?

z-index를 수정해봐도 적용이 안되네요..

**Comment by eouia** [comment]
글쎄요. 제가 만든 모듈들이 아니라면 잘 모르겠네요. z-index가지고 컨트롤 하는 거 뿐이라서.
