### ISSUE TITLE
recipes commands and youtube

### ISSUE THREAD

**Issue by bugsounet** [eouia/MMM-AssistantMk2#227]
hi eouia,

i have a problem my transcriptionHook pattern ordered a youtube video and my personnal command

can you make an exception on youtube,  if a transcriptionHook pattern is found?

**Comment by eouia** [comment]
sorry. I'm building a new version, but not finished (I have not enough time to do nowadays.. or just being losing interesting. :( )
At this moment, it is not possible. `transcriptionHook` is a somewhat tricky hack, so it is such limited.
If you make your commands as `action` instead `transcriptionHook`, Assistant will avoid the usual response.

**Comment by bugsounet** [comment]
ok, I'll look at it, lost time :)

**Comment by eouia** [comment]
I mean you can use `action` to get what you want. You can define the response and the payloads as your wish in `action`. The response of `action` will not activate youtube player.

**Comment by bugsounet** [comment]
in my case, it will not work because I call a notification.

humm ... i found !

> MMM-RemoteShoppingList received a module notification: ASSISTANT_UNDERSTOOD from sender: MMM-AssistantMk2
> MMM-AssistantMk2.js:662 !!!!!!!!!!!!!!! foundHook status : 1
> module.js:154 clock received a module notification: PAGE_CHANGED from sender: MMM-AssistantMk2

i will able to fix the bug
I rewrite `foundHook(payload)`, it return 0 or 1
0 > no hook found
1 > hook found

in `consersationEnd (payload)`
i will check foundHook status at the same time i execute it and 
place an exception with youtube
`if (!this.foundHook(payload.foundHook) && (payload.foundVideo || payload.foundVideoList)) {`


I will test if it works properly and If you want I give you the patch

if need help for the next version, I can support you

**Comment by himuura** [comment]
quick question, using recipes, how do i return a value from a script so that the assistant says it? Ex:
exec: "vcgencmd measure_temp" ---> returns temp=35ºC
How can i make the assistant speak "It's %%%% DEGREES CELCIUS" ??

**Comment by bugsounet** [comment]
something like that ?
replace >> vcgencmd measure_temp by ;
vcgencmd measure_temp | cut -c6-9 | sed 's/^/It is /' | sed 's/$/ DEGREES CELCIUS/'

result : It is 34.9 DEGREES CELCIUS

**Comment by himuura** [comment]
Not actually that mate but that will come in handy :) I just don't know how to make the assistant speak the value...like I say Computer, thermals. And the assistant says 35 degrees. What's the code to make the assistant say a value returned by a script? Something like speak: "It's %s degrees", where %s is the value returned by my exec: command.

**Comment by eouia** [comment]
There is no simple way to do that. SDK itself doesn't include dynamic fulfillment (your expecting response) on real time.

Solutions are;
1) You should make genuine Google Action for it. But that is a somewhat difficult task for non-expert and it needs additional Server(like FireBase) to handle action's fulfillment. So I don't recommend.

2) Or, you can use additional TTS(Text-To-Speech) Solution to make the voice response directly on RPI.
