### ISSUE TITLE
Get error while execute command "electron-rebuild"

### ISSUE THREAD

**Issue by pdnandakumargym** [eouia/MMM-AssistantMk2#229]
Raspberry pi 3b+
"Raspbian GNU/Linux 10 (buster)"

node -v v10.15.2
node-gyp -v v5.0.5

Magic Mirror v2.8.0

Installed MMM-AssistantMk2 module

$ cd ~/MagicMirror/modules/MMM-AssistantMk2
$ npm install --save-dev electron-rebuild
$ ./node_modules/.bin/electron-rebuild

Error : 

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.15.2 | linux | arm
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/gyp/gyp_main.py',

gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@5.0.5
gyp info using node@10.15.2 | linux | arm
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp info spawn /usr/bin/python
gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/

../deps/grpc/third_party/upb/upb/upb.h:27:10: fatal error: upb/port_def.inc: No such file or directory
 #include "upb/port_def.inc"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [grpc.target.mk:537: Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.o] Error 1
make: Leaving directory '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.75-v7+

**Comment by bugsounet** [comment]
Hi, it's an known issue.

[Try this](https://github.com/eouia/MMM-AssistantMk2#some-more-troubleshooting)

it is because of grpc@1.24
try : 
`cd ~/MagicMirror/modules/MMM-AssistantMk2`
`rm - rf node_modules`
`npm install`
`npm install --save-dev electron-rebuild`
`npm install grpc@1.23`
`./node_modules/.bin/electron-rebuild`

it will be correct :)

**Comment by pdnandakumargym** [comment]
> Raspberry pi 3b+
> "Raspbian GNU/Linux 10 (buster)"
> 
> node -v v10.15.2
> node-gyp -v v5.0.5
> 
> Magic Mirror v2.8.0
> 
> Installed MMM-AssistantMk2 module
> 
> $ cd ~/MagicMirror/modules/MMM-AssistantMk2
> $ npm install --save-dev electron-rebuild
> $ ./node_modules/.bin/electron-rebuild
> 
> Error :
> 
> ✖ Rebuild Failed
> 
> An unhandled error occurred inside electron-rebuild
> gyp info it worked if it ends with ok
> gyp info using node-gyp@5.0.5
> gyp info using node@10.15.2 | linux | arm
> gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
> gyp info spawn /usr/bin/python
> gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/gyp/gyp_main.py',
> 
> gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc
> gyp ERR! node -v v10.15.2
> gyp ERR! node-gyp -v v5.0.5
> gyp ERR! not ok
> 
> Failed with exit code: 1
> 
> Error: gyp info it worked if it ends with ok
> gyp info using node-gyp@5.0.5
> gyp info using node@10.15.2 | linux | arm
> gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
> gyp info spawn /usr/bin/python
> gyp info spawn args [ '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/gyp/gyp_main.py',
> gyp info spawn args 'binding.gyp',
> gyp info spawn args '-f',
> gyp info spawn args 'make',
> gyp info spawn args '-I',
> gyp info spawn args '/home/
> 
> ../deps/grpc/third_party/upb/upb/upb.h:27:10: fatal error: upb/port_def.inc: No such file or directory
> #include "upb/port_def.inc"
> ^~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [grpc.target.mk:537: Release/obj.target/grpc/deps/grpc/src/core/lib/security/credentials/alts/alts_credentials.o] Error 1
> make: Leaving directory '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/build'
> gyp ERR! build error
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack at ChildProcess.onExit (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack at ChildProcess.emit (events.js:189:13)
> gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
> gyp ERR! System Linux 4.19.75-v7+

Great, Its working fine, Thank you.

**Comment by pdnandakumargym** [comment]
Great, Its working fine, Thank you.
