### ISSUE TITLE
매직미러 npm start 에려

### ISSUE THREAD

**Issue by INMD1** [eouia/MMM-AssistantMk2#230]
Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: http://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] Temporal storage directory is clearing.
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js: symbol lookup error: /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.9.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-10-24T02_44_33_806Z-debug.log

이런에려가 뜨고 종료가 됨니다 어떻게하나요?

설치는 여기있는 가이드보고 했습니다

**Comment by eouia** [comment]
혹시 grpc@1.23.4 로 다운그레이드하고 electron-rebuild 하셨나요?

**Comment by INMD1** [comment]
어떻게 하나요?

**Comment by eouia** [comment]
https://github.com/eouia/MMM-AssistantMk2#some-more-troubleshooting

![image](https://user-images.githubusercontent.com/1720610/67473822-a6a41380-f653-11e9-9236-5db67fd23109.png)

**Comment by INMD1** [comment]
해보고 다시 연락 드리겠습니다

**Comment by INMD1** [comment]
네 지금 해결되었습니다. 구글 어시턴트 프리핑 투데이도 되고..
근데 지금 마이크 연결하고 해보니 안됨니다.
마이크는 테스트 해보니 정상적으로 작동을 합니다.
config.js
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "+"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "+"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
{
	module: "MMM-Hotword",
	position: "top_right",
	config: {
		chimeOnFinish: null,
		mic: {
			recordProgram: "arecord",
			device: "plughw:1"
		},
		models: [
			{
				hotwords    : "smart_mirror",
				file        : "smart_mirror.umdl",
				sensitivity : "0.5",
			},
		],
		commands: {
			"smart_mirror": {
				notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
					}
				},
				restart:false,
				afterRecordLimit:0
			}
		}
	}
},
{
	module: "MMM-AssistantMk2",
	position: "top_right",
	config: {
		deviceLocation: {
			coordinates: {
				latitude: 37.5650168, // -90.0 - +90.0
				longitude: 126.8491231, // -180.0 - +180.0
			},
		},
		record: {
			recordProgram : "arecord",  
			device        : "plughw:1",
		},
		notifications: {
			ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
			ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
		},
		useWelcomeMessage: "brief today",
		profiles: {
			"default" : {
				lang: "en-US"
			}
		},
	}
},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

pcm.!default{
  type asym
  playback.pcm{
    type hw
    card 0
  }
  capture.pcm{
    type plug
    slave.pcm "hw:1, 0"
  }
}

ctl.!default{
  type hw
  card 0
}

또 구글 클라우드 플레폼에 api 작동 현황을 보려 들어갔는데 
요청이 3번 들어오면 손실율이 100%라고 하더라고요....
이유가 뭘까요?

**Comment by eouia** [comment]
useWelcomeMessage는 일단 사용하지 말고 테스트해보시겠어요?
그리고 에러로그를 보면 무슨 문제인지 도움이 될 것 같습니다.
Hotword의 경우 micTest, AssistantMk2의 경우 verbose 옵션을 각각 true로 놓으면 좀 더 상세한 로그가 남습니다.

**Comment by INMD1** [comment]
음성 인식은 성공했는데 verbose 옵션은 어떻게 true로 바꾸나요?

**Comment by eouia** [comment]
- Hotword "volume_up" 은 제대로 인식되는 것 같네요. 그런데, 그 이후에 액션이 아무것도 안 찍힌 걸 보면, 
```js
commands: {
  "smart_mirror": {
     notificationExec: {
        notification: "ASSISTANT_ACTIVATE",
        payload: (detected, afterRecord) => {
           return {profile:"default"}
        }
    },
  }
},
```
이 부분을 그냥 두신 것 같네요. 저 부분의 뜻은 "smart_mirror"라는 이름의 Hotword가 인식되면 ASSISTANT_ACTIVATE notification을 통해 MMM-AssistantMk2를 작동시키라는 뜻입니다. 이 부분을 수정하시면 AMK2 액티베이팅 말고 다른 명령을 수행할 수도 있겠지요.
로그로 미루어보건데, 인식할 Hotword로는 "volume_up"을 등록하시고는, 그 Hotword가 인식되었을 때 수행될 command 정의를 안하신 듯 합니다. 뭐, 이건 전체 config을 봐야겠습니다만 아마 그렇게 되어 있을거에요.

- AssistantMk2에서 사용가능한 상세한 옵션들은 
https://github.com/eouia/MMM-AssistantMk2/wiki/Configuration#full-detailed-version-dont-panic-detailed-information-will-be-followed
여기에 설명되어있습니다.
여기에 있는 걸 그대로 복사해서 붙이시지 마시구요.. 어차피 저기 적혀 있는 값들은 모두 default로 지정되어 있는 겁니다. 설명 읽어보시고 필요한 옵션들만 추가해서 사용하세요.

**Comment by INMD1** [comment]
> config.js
> /* Magic Mirror Config Sample
> *
> 
> * By Michael Teeuw http://michaelteeuw.nl
> * MIT Licensed.
> * For more information how you can configurate this file
> * See https://github.com/MichMich/MagicMirror#configuration
> 
> */
> 
> var config = {
> address: "localhost", // Address to listen on, can be:
> // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
> // - another specific IPv4/6 to listen on a specific interface
> // - "", "0.0.0.0", "::" to listen on any interface
> // Default, when address config is left out, is "localhost"
> port: 8080,
> ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
> // or add a specific IPv4 of 192.168.1.5 :
> // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
> // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
> // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],
> 
> ```
> language: "en",
> timeFormat: 24,
> units: "metric",
> 
> modules: [
> 	{
> 		module: "alert",
> 	},
> 	{
> 		module: "updatenotification",
> 		position: "top_bar"
> 	},
> 	{
> 		module: "clock",
> 		position: "top_left"
> 	},
> 	{
> 		module: "calendar",
> 		header: "US Holidays",
> 		position: "top_left",
> 		config: {
> 			calendars: [
> 				{
> 					symbol: "calendar-check",
> 					url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
> 			]
> 		}
> 	},
> 	{
> 		module: "compliments",
> 		position: "lower_third"
> 	},
> 	{
> 		module: "currentweather",
> 		position: "top_right",
> 		config: {
> 			location: "New York",
> 			locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
> 			appid: "+"
> 		}
> 	},
> 	{
> 		module: "weatherforecast",
> 		position: "top_right",
> 		header: "Weather Forecast",
> 		config: {
> 			location: "New York",
> 			locationID: "5128581",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
> 			appid: "+"
> 		}
> 	},
> 	{
> 		module: "newsfeed",
> 		position: "bottom_bar",
> 		config: {
> 			feeds: [
> 				{
> 					title: "New York Times",
> 					url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
> 				}
> 			],
> 			showSourceTitle: true,
> 			showPublishDate: true,
> 			broadcastNewsFeeds: true,
> 			broadcastNewsUpdates: true
> 		}
> 	},
> ```
> 
> {
> module: "MMM-Hotword",
> position: "top_right",
> config: {
> chimeOnFinish: null,
> mic: {
> recordProgram: "arecord",
> device: "plughw:1"
> },
> models: [
> {
> hotwords : "smart_mirror",
> file : "smart_mirror.umdl",
> sensitivity : "0.5",
> },
> ],
> commands: {
> "smart_mirror": {
> notificationExec: {
> notification: "ASSISTANT_ACTIVATE",
> payload: (detected, afterRecord) => {
> return {profile:"default"}
> }
> },
> restart:false,
> afterRecordLimit:0
> }
> }
> }
> },
> {
> module: "MMM-AssistantMk2",
> position: "top_right",
> config: {
> deviceLocation: {
> coordinates: {
> latitude: 37.5650168, // -90.0 - +90.0
> longitude: 126.8491231, // -180.0 - +180.0
> },
> },
> record: {
> recordProgram : "arecord",
> device : "plughw:1",
> },
> notifications: {
> ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
> ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
> },
> useWelcomeMessage: "brief today",
> profiles: {
> "default" : {
> lang: "en-US"
> }
> },
> }
> },
> ]
> 
> };
> 
> /*************** DO NOT EDIT THE LINE BELOW ***************/
> if (typeof module !== "undefined") {module.exports = config;}


자료입니다.
commands: {
  "smart_mirror": {
     notificationExec: {
        notification: "ASSISTANT_ACTIVATE",
        payload: (detected, afterRecord) => {
           return {profile:"default"}
        }
    },
  }
},
이거만 추가하면 작동이 되겟죠>

**Comment by eouia** [comment]
네. 그러면 HOTWORD가 "smart_mirror"를 인식하면 AMK2를 구동시킬 거에요.

**Comment by eouia** [comment]
그리고, useWelcomeMessage는 일단 사용하지 마세요.

**Comment by INMD1** [comment]
어시턴트 까지 인식이되었습니다.
그리고 또 문제가 발생했습니다.
1.갤린더 설정해달라고 말한뒤 어시턴트가 이름을 말해달라고 하면 이름을 말해도 인식이 안됨니다.
2.유투브가 안됨니다. 유투브는 여기에있는 mmm-youtube 모듈 설치하면되죠?

**Comment by eouia** [comment]
1. 인식이 안될 때의 에러 로그를 보여주세요. (verbose:true 옵션을 MMM-AssistantMk2에 추가하시면 좀 더 상세한 로그가 나옵니다.)
2. 유튜브는... 원래 안됩니다. SDK레벨에서 지원하지 않습니다. MMM-Youtube 쓰시는 것과는 관계없고. 만약 검색쿼리의 응답이 유튜브 URL을 포함하는 경우에는 유튜브 플레이어를 띄우는 기능을 제가 추가로 만들어 넣었긴 한데, 그러니까 "유튜브 틀어줘" 뭐 이런 걸로 작동하는게 아니라, "마이클 잭슨 쓰릴러" 이런 식으로 검색했을 때 그 결과가 유튜브라면 작동하는 식입니다.
어차피 이 기능은 다음 버전에 빼버릴 거에요. 원래 제가 이걸 만든 의도는 매직미러를 음성으로 컨트롤하기 위함이지 유튜브 재생기로 쓰려는 게 아니라서요.

**Comment by INMD1** [comment]
1 verbose:true을 MMM-AssistantMk2에 어디에 추가하면 되나요. 

2. 아 그렇군요. 저도 개발자(웹)로서 이렇게 상위급 개발자들은 가끔 잘 답을 안래주던데..
늦은 밤까지) 답해 쥬셔서 감사합니다.

**Comment by eouia** [comment]
1. config: {} 안에 추가하시면 됩니다. 음... 사실 대부분의 내용은 이미 도큐먼트들에 다 언급되어 있으니까, 꼼꼼히 읽어봐주시면 좋겠습니다.

2. 저는 독일 살아서 지금은 저녁때긴 합니다만 괜찮습니다.

**Comment by INMD1** [comment]
네 해보고 자세한것은 다시 여기에 올리겟습니다.
