### ISSUE TITLE
cp MagicMirror/modules/MMM-AssistantMk2/credentials.json

### ISSUE THREAD

**Issue by sy8282** [eouia/MMM-AssistantMk2#232]
Register your Mirror as Google Assistant related device.
following the steps all seems fine until this one check the folder and my credentials.json is there and all working

(env) pi@raspberrypi:~ $ cp MagicMirror/modules/MMM-AssistantMk2/credentials.json
cp: missing destination file operand after 'MagicMirror/modules/MMM-AssistantMk2/credentials.json'
Try 'cp --help' for more information.

**Comment by eouia** [comment]
You've missed ` . ` in that command.
```
cp MagicMirror/modules/MMM-AssistantMk2/credentials.json .
```

**Comment by eouia** [comment]
`cp` command means **copy**. it needs 2 parameters, `source_from` and `destination_to`. Your trial was missing the last value.

**Comment by sy8282** [comment]
dammit i thought that wasnt part of the code stupid viewing angle on my monitor. all working now cheers
