### ISSUE TITLE
구글 어시턴트 일정오류

### ISSUE THREAD

**Issue by INMD1** [eouia/MMM-AssistantMk2#233]
[AMK2] Transcription: 일정 잡아 줘  --- Done: false
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] Transcription: 일정 잡아 줘  --- Done: false
[HOTWORD] Final Result: { detected: false }
[AMK2] Transcription: 일정 잡아 줘  --- Done: false
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[AMK2] end-of-utterance
[AMK2] Transcription: 일정 잡아 줘  --- Done: true
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
{ requestId: '5dc56abd-0000-243c-85d2-2405887fe884' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: '5dc56abd-0000-243c-85d2-2405887fe884' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 

이렇게 로그가 뜨는데 이유가 뭘까요?

**Comment by eouia** [comment]
음.. 영어로 할 때에는 Continuous conversation에 특별한 문제가 없는데.. 제가 나중에 테스트 해볼게요.

그리고, 

```
module : "MMM-AssistantMk2",
config: {
  verbose: true, // < - 이거 넣어주시면 좀 더 상세한 로그가 나올 겁니다.
  ...
```

**Comment by eouia** [comment]
아, 근데 그걸 떠나서 HOTWORD 로그가 이상한 걸 보면 뭔가 오류가 있긴 있는 것 같네요. 원래 AMK2 작동중에는 HOTWORD가 뜨면 안되거든요. 흠...

**Comment by INMD1** [comment]
module : "MMM-AssistantMk2",
config: {
  verbose: true, 
  ...

저렇게 둘다 넣어 준건데...

**Comment by INMD1** [comment]
module : "MMM-AssistantMk2",
config: {
  verbose: true, // < - 이거 넣어주시면 좀 더 상세한 로그가 나올 겁니다.
  ...

이거 넣어 줬는데 다시 봐야 겟군요

**Comment by eouia** [comment]
설치는 다시 할 필요 없고, 버그가 만약 있다면 어떤 종류인지 알 것 같습니다. 일단 제가 테스트를 해보고 제가 생각하는 문제라면 고치고 알려드릴게요. 다만 제가 요 며칠 바빠서 조금 늦게 처리될 수 도 있습니다.

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
