### ISSUE TITLE
wiki의 config는 어떤 파일에 붙여넣어야하나요?

### ISSUE THREAD

**Issue by LCH-511** [eouia/MMM-AssistantMk2#234]
초보라서 죄송합니다ㅠ

**Comment by eouia** [comment]
MagicMirror 디렉토리 아래 `config/config.js` 에 넣으세요, 다른 모듈들이 어떤 식으로 등록되어 있는지 보시고, 매직미러 자체 문서들도 읽어서 기본을 익히세요.
