### ISSUE TITLE
어떻게 해야 되죠?

### ISSUE THREAD

**Issue by majicjam1236** [eouia/MMM-AssistantMk2#236]
![error](https://user-images.githubusercontent.com/44740689/68217145-72eac580-0025-11ea-97eb-29314f4e2519.jpg)

**Comment by majicjam1236** [comment]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.12.1
3 info using node@v10.17.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.9.0~prestart: magicmirror@2.9.0
6 info lifecycle magicmirror@2.9.0~start: magicmirror@2.9.0
7 verbose lifecycle magicmirror@2.9.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror@2.9.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/MagicMirror/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle magicmirror@2.9.0~start: CWD: /home/pi/MagicMirror
10 silly lifecycle magicmirror@2.9.0~start: Args: [ '-c', 'sh run-start.sh' ]
11 info lifecycle magicmirror@2.9.0~start: Failed to exec start script
12 verbose stack Error: magicmirror@2.9.0 start: `sh run-start.sh`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:198:13)
12 verbose stack     at maybeClose (internal/child_process.js:982:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid magicmirror@2.9.0
14 verbose cwd /home/pi/MagicMirror
15 verbose Linux 4.19.75-v7l+
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v10.17.0
18 verbose npm  v6.12.1
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error magicmirror@2.9.0 start: `sh run-start.sh`
23 error spawn ENOENT
24 error Failed at the magicmirror@2.9.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by eouia** [comment]
electron-rebuild 과정 실패하신 것 같은데요. grpc@1.23 으로 다운그레이드 하셨나요?

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
