### ISSUE TITLE
How to make the assistant speak

### ISSUE THREAD

**Issue by himuura** [eouia/MMM-AssistantMk2#237]
It's not an issue per se but if you could shed some light, i would be most thankfull!
So, recipes. Great work! I mean it really simplifies the whole process and it's way more clean. My question is, using the reboot.js as an example, i'm trying to build a recipe to make the assistant speak the SoC temperature of the Pi. On the exec i use "vcgencmd measure_temp" but i don't know how to make the assistant speak the given value from the exec command. Can you give me a hand?
Thanks in advance mate! Again, tremendous job!! Oh and by the way, is it possible to use hotword with multiple devices? i mean like a MM running in server mode (like a pi4) and 2 others (zero W) with mic dongles attached running in client mode? For instance, i have 2 MM, kitchen and living room, will they both be listening when i say the hotword? Just out of curiosity mate.

**Comment by eouia** [comment]
1. I wrote that answer on your other post.

2. Hmmm. I didn't test, but the main process would be working on `Server`, so you cannot share the module. I can only guarantee it will work on a standalone device.

**Comment by himuura** [comment]
Will take note @eouia !! Thanks for you reply! Closed!
