### ISSUE TITLE
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.

### ISSUE THREAD

**Issue by YounhJunJin** [eouia/MMM-AssistantMk2#238]
Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: calendar_monthly.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
No helper found for module: compliments.
No helper found for module: MMM-AirQuality.
Initializing mm-music-player module helper ...
Module helper loaded: mm-music-player
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: mm-music-player
Sockets connected & modules started ...
Launching application.
Create new news fetcher for url: https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=03&plink=RSSREADER - Interval: 300000
Create new news fetcher for url: https://world.kbs.co.kr/rss/rss_news.htm?lang=k - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 14,
  metadata:
   Metadata { _internal_repr: { 'content-disposition': [Array] }, flags: 0 },
  details: 'Service unavailable.' }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: newsfeed
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Hotword
Stopping module helper: mm-music-player

얼마전까지 잘 됐는데 갑자기 이런에러가 뜨는데 무슨 문제가 있는걸까요?
스피커, 마이크 잘 작동하는데 도움받고 싶습니다.

**Comment by YounhJunJin** [comment]
var config = {
  address: "localhost",
  port: 8080,
  ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"],
  language: "ko",
  timeFormat: 12,
  units: "metric",

  modules: [
    {
      module: "alert",
    },
    {
      module: "updatenotification",  //업데이트 알림 모듈
      position: "top_bar" // 모듈 위치 (변경 가능합니다)
    },
    {
      module: "clock",  //시계 모듈
      position: "top_left", // 모듈 위치 (변경 가능합니다)
      config: {
        dateFormat: "LL dddd",
      }
    },
   {
	module: 'calendar_monthly',
	position: 'top_left',
	config: {
		// The config property is optional
		// Without a config, a default month view is shown
		// Please see the 'Configuration Options' section for more information
		}
	},
			
    {
      module: "currentweather", //현재 날씨 모듈
      position: "top_right", // 모듈 위치 (변경 가능합니다) 현재 설정된 위치는 인천입니다. API 키를 입력하셔야 작동합니다.
      config: {
        location: "Changwon, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.
        locationID: "1843564",
        appid: "ea6718101be4ff91239783e1139008c0" //openweathermap.org의 API key를 입력하세요.
      }
    },
    {
      module: "weatherforecast", // 날씨예보 부분 모듈
      position: "right", // 모듈 위치 (변경 가능합니다) 현재 설정된 위치는 인천입니다. API 키를 입력하셔야 작동합니다.
      header: "Weather Forecast",
      config: {
        location: "Changwon, KR", //https://openweathermap.org/ 에서 지역을 찾으세요.
        locationID: "1843564",
        appid: "ea6718101be4ff91239783e1139008c0" //openweathermap.org의 API key를 입력하세요.
      }
    },
    {
      module: "newsfeed", // 뉴스피드 모듈
      position: "bottom_bar", // 모듈 위치 (변경 가능합니다)
      config: {
        feeds: [
                {
                  title: "SBS 뉴스",
                  url: "https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=03&plink=RSSREADER",
                },
                {
                  title: "KBS 뉴스",
                  url: "https://world.kbs.co.kr/rss/rss_news.htm?lang=k"
                },
		
               ]
      }
    },

    {
      module: "MMM-AssistantMk2",  // 어시스턴트 기본 모듈
      position: "top",
      config: {
        record: {
          recordProgram : "arecord",  
          device        : "plughw:1",
        },
        notifications: {
          ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
          ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
        },
        deviceLocation: {
          coordinates: {
            latitude: 35.233093,
            longitude: 128.6580541
          }
        },
        profiles: {
          "default": {
           lang: "ko-KR"
          }
        }
      }
    },

    {
      module: "MMM-Hotword",   // 어시스턴트 호출 명령 인식 모듈
      config: {

        chimeOnFinish:null,
        mic: {
          recordProgram : "arecord",  
          device        : "plughw:1",
        },
        models: [
          {
            hotwords    : "smart_mirror",
            file        : "smart_mirror.umdl",
            sensitivity : "0.5",
          },
	{
	  hotwords: ["jarvis", "jarvis"],
	  file: "jarvis.umdl",
	  sensitivity: "0.8,0.8",
	},
        ],
        defaultCommand: {
          notificationExec: {
            notification: "ASSISTANT_ACTIVATE",
            payload: (detected, afterRecord) => {
              return {profile:"default"}
            }
          },
          afterRecordLimit:0,
          restart:false,
        },
      },
    },

    {
      module: "compliments",  // 문구 표시 모듈
      position: "middle_center",  // 모듈 위치 (변경 가능합니다) 아래의 문구들 중 아무 때나, 아침, 오후, 저녁을 제외하고는 제가 생각나는 대로 추가해봤습니다. 자유롭게 수정하셔도 됩니다. - 윤솔
      config: {
        compliments: {
          anytime: [ //아무 때나
            "오늘도 좋은 하루!"
          ],
          morning: [ //아침
            "좋은 아침!",
            "힘찬 아침!",
            "잘 잤나요?"
          ],
          afternoon: [ //오후
            "안녕하세요!",
            "멋져요!",
            "잘 지내고 있나요!"
          ],
          evening: [ //저녁
            "와우! 잘 지냈나요?",
            "멋져보이네요!",
            "반가워요!"
          ],
          day_sunny: [//맑은 낮
            "하늘이 맑아요."
          ],
          day_cloudy: [//흐린 낮
           
          ],
          cloudy: [//흐림
            "흐린 날이네요."
          ],
          cloudy_windy: [//흐리고 바람
            "바람이 조금 불어요."
          ],
          showers: [//소나기
            "갑자기 비가 와요."
          ],
          rain: [//비
            "우산 챙기세요!"
          ],
          thunderstorm: [//천둥번개
            "번개가 무서워요!"
          ],
          snow: [//눈
            "하늘에서 눈이 내려와요~"
          ],
          fog: [//안개
            "안개가 자욱해요."
          ],
          night_clear: [//맑은 밤
            "오늘 밤은 하늘이 맑아요."
          ],
          night_cloudy: [//흐린 밤
            "별이 잘 안 보여요."
          ],
          night_showers: [//소나기 밤

          ],
          night_rain: [//비오는 밤
            "창문 닫고 자요."
          ],
          night_thunderstorm: [//천둥번개 밤
            "오늘 밤은 시끄럽겠어요."
          ],
          night_snow: [//눈오는 밤
            "아침에 눈이 쌓여 있을까요?"
          ],
          night_alt_cloudy_windy: [//흐리고 바람부는 밤

          ],
        }
      }
    },
    {
	module: 'MMM-AirQuality',
	position: 'bottom_right', // you may choose any location
	config: {
	  location: 'korea/gyeongnam/changwon-si/myeongseo-dong/', // the location to check the index for
	lang: "kr"
	}
},
{
	module: 'mm-music-player',
	position: 'bottom_left',
	config: {
		startingVolume: 20,
		fadeDuriation: 2000
	}
},
 /*{
            module: 'MMM-Carousel',
            position: 'bottom_bar',  // Only required to show navigation
            config: {
		transitionInterval: 0,
                showPageIndicators: true,
                showPageControls: true,
                ignoreModules: ['clock', 'alert'],
                mode: 'slides',
                slides: {
                    main: ['calendar', 'currentweather', 'MMM-AssistantMk2', 'MMM-Hotword'],
                    "Slide 2": ['weatherforecast','compliments', 'newsfeed'],
                    "Slide 3": ['mm-music-player']
                // See below for configurable options
            }
		}
        },*/
	
  ]
};




/*************** DO NOT EDIT THE LINE BELOW 아래는 편집하지 마십시오. ***************/
if (typeof module !== "undefined") {
  module.exports = config;
}

**Comment by eouia** [comment]
혹시 MMM-Carousel의 서브 페이지에 넣으시면 안됩니다.

**Comment by YounhJunJin** [comment]
MMM-Carousel이건 주석처리 한거구
원인이 LCD모니터 연결하니까 에러뜨고 모니터 빼니까 인식은 또 잘되네요...
모니터를 바꿔야 될거같네요... 감사합니다

**Comment by eouia** [comment]
LCD 모니터 HDMI로 연결하시나요? 그런 경우 사운드 아웃풋 세팅이 바뀔 수 있습니다.

**Comment by YounhJunJin** [comment]
네 HDMI로 연결하고 있습니다.
LCD 화면 연결하고 부르면 띵동 소리가 나면서 동시에 화면이 잠시 꺼졋다 켜지는데 아웃풋 세팅과 관계가 있을까요?

**Comment by eouia** [comment]
HDMI로 사운드 아웃풋을 바꿨다면 Mic 인풋에 대한 ALSA 세팅도 바뀌었을 수 있습니다. plughw:1 이 아닐 수도 있다는거죠. 일단 ALSA 셋업은 제가 잘 모르는 관계로 HDMI 사용시 입출력 셋업을 어떻게 해야 하는지 제가 도움드리긴 어렵습니다.

**Comment by YounhJunJin** [comment]
한번 찾아보겠습니다. 감사합니다.
