### ISSUE TITLE
usage 부분에서 custom설정 할려는데 막히는게 있습니다..

### ISSUE THREAD

**Issue by eregos96** [eouia/MMM-AssistantMk2#239]
질문: usage에서 Register your Mirror as Google Assistant related device 파트의 model id 지원이(model registeration) 중단된거 같습니다. 모델id를 생성할려고 보니깐 옛날 다른 분 포스팅 한것을 봤는데 그 때처럼 따로 모델 등록하는 탭이 없네요. 현재로써 다른 방법이 있을까요? 또한 구글 home app 에서는 따로 설정할 필요가 없나요?

command와 transcription hook에서 모두 영어로된 hotword를 인식해서 모듈이든 shellexec든 동작시키는거 같은데 한국어 설정으로 구글 어시스턴스를 사용하고 있는데 영어로 hotword로 적어도 같은 의미의 한국어로 자동으로 음성인식이 되나요? 아니면 따로 코드를 추가해줘야 하는 부분이 있나요? 예를 들어 command나 transcription hook에서는 hi라고 코드를 써도 구글 어시스턴스에서 "안녕"이라고 말해도 hi의 hotword가 인식이 되서 쭉 제가 설정한 command를 수행하나요?? 

다른 분 코드(이분은 MK2를 쓰지 않으셨습니다) 보니깐 custom명령어 줄 때 영어 hotword를 다 한국어로 번역하셨길래 MK2에서도 마찬가지인가 싶어서 질문드립니다.

**Comment by eouia** [comment]
1) 
![image](https://user-images.githubusercontent.com/1720610/68870627-7522e300-06fb-11ea-975d-227f9a2a489e.png)
UI가 좀 바뀌긴 했습니다만, 모델 등록이 안되면 안되죠. ^^;;;;

2) Hotword라고 표현하시니 헷갈리네요.  transcription은 어시스턴트가 사용자로부터 받은 음성 쿼리에 대해 어시스턴트가 이해한 문장입니다. 영어로 하면 영어로 나오고, 한국어로 세팅하고 한국어로 말하면 한글로 나옵니다.... 인데 조금 복잡합니다. 왜냐하면 어시스턴트가 "이해한" 문장이거든요. 그러니까. 영어로 말하든 한국어로 말하든 어시스턴트가 뭐로 이해했느냐에 따라 다를 수 있습니다. 기본적으로는 세팅한 언어를 우선으로 하긴 합니다만.
말씀하신 사례는 전혀 가능할 것 같지는 않은데, 반대로 이런 식은 가능할 수 있습니다. (사용자나 설정에 따라 다른 결과가 나올 수 있습니다.)
발음 : " one plus one" => transcription : "1+1"
발음 : " twice what is love" => transcription : "트와이스 왓이스러브"
발음 : "헬로 월드" => transcription : "hello world"
그런데, 이게 어떤 법칙이 있다기 보다는, AI 어시스턴트가 수많은 사용자의 사용패턴으로부터 뽑아낸 사례들과 또 사용자의 개인화에 맞춰 결정되는 거라 딱 이렇다 말씀드리기 어렵네요.

어쨌든 transcription 자체는 프라임 언어를 Korean으로 설정하면 대개의 한국어 명령은 한글로 나옵니다. 그러므로 transcriptionHook에서 후킹할 패턴으로 한글을 쓰셔도 됩니다.

command와 transcriptionHook을 헷갈리시는 것 같은데, transcriptionHook은 사용자가 발화한 transcription에서 특정 패턴을 뽑아내는 거고, 패턴이 있는 경우 실행되는 건 command입니다. 그러니까 command 자체는 언어와 아무 상관없습니다. 

```js
var recipe = {
  transcriptionHook: {
    "REBOOT": {
      pattern: "reboot yourself",
      command: "REBOOT"
    },
  },
  command: {
    "REBOOT": {
      shellExec: {
        exec: "sudo reboot now"
      }
    }
  }
}
exports.recipe = recipe
```
이런 recipe가 있다고 할 때, transcriptionHook은 만약 사용자의 발음 중 "reboot yourself"로 이해되는 transcription이 있다면, `REBOOT`라는 command를 실행하라는 거고, `REBOOT`라는 command는 특정 shell 명령어를 실행하는 식이죠.

개인적으로는 간단한 명령어라면 transcriptionHook을 쓰는게 쉽긴 하지만, side-effect때문에 가능하면 IFTTT나 customAction을 쓰는 걸 추천드립니다.

3) 다른 분의 사례가 뭘 말하는지 모르겠네요. 아마 MMM-Hotword 단독으로 쓰시는 것 같은데, 사실 미러 컨트롤을 위해서라면 굳이 AI 어시스턴트 필요없이 MMM-Hotword만 쓰시는 게 더 나을 수도 있습니다. 해당 코드를 보여주시면 해석해보겠습니다.

**Comment by eregos96** [comment]
써주신 댓글 잘 봤습니다. 첫번째 질문인 model ID는 만들수가 없어서 방법이 없어 보이네요.. 
1. 써주신 내용중에 transcription 자체는 프라임언어를 korean으로 설정한다는게 config.js에서 language를 ko로 설정한 후 transcription hook에 pattern을 한국어로 입력한다는 거죠?? 

2. default로 있는 레시피들 reboot.js , screenonoff.js 등등 을 실행 해봤는데 아무것도 실행이 안되네요.. 패턴에서 화면 켜 줘, 화면 꺼 줘, 재부팅 해줘 이 정도는 영어로 해석했을때 어시스턴스가 이해해서 잘 실행될수 있다고 생각했는데 안되네요.. MK2 config 부분이랑 수정한 레시피 코드 올려드릴게요.

3. 그리고 transcription은 직접 수정을 못하나요? 

4. MK2 config 부분에서 레시피를 사용하면 welcomemessage 부분이 작동을 안하네요..

config.js 파일의 MK2 모듈 부분 코드입니다.

{
          module: "MMM-AssistantMk2",  // 어시스턴트 기본 모듈
          position: "top_bar",
          config: {
              record: {
                  recordProgram: "arecord",
                  device: "plughw:1",
              },
              play: { // Full values are in `FOR EXPERTS` section.
                  playProgram: "mpg321", // recommended.
              },
              notifications: {
                  ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
                  ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
              },
              deviceLocation: {
                  coordinates: {
                      latitude: 37.610006,
                      longitude: 126.997600
                  }
              },
              profiles: {
                  "default": {
                      profileFile: "default.json",
                      lang: "ko-KR"
                  }
              },
              responseVoice: true, // If available, Assistant will response with her voice.
              responseScreen: true, // If available, Assistant will response with some rendered HTML
              responseAlert: true, // If available, Assistant will response with Alert module of MM

              screenZoom: "80%", // Adjust responseScreen to your mirror size.
              
              //유트브 재생 관련 설정
              youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.
              pauseOnYoutube: false, //If set as true, You cannot activate Assistant during youtube playing. Recommended for the performance (Because permanent hotword detecting might make performance lower)

              youtubePlayerVars: { // You can set youtube playerVars for your purpose, but should be careful.
                  "controls": 0,
                  "loop": 1,
                  "rel": 0,
              },
              youtubePlayQuality: "hd1080", //small, medium, large, hd720, hd1080, highres or default

              useWelcomeMessage: "brief today", //Try "brief today" as this value. You can use this value to check module working when MM is starting.
		
	      recipes: ["reboot.js", "show_and_hide_all_modules.js", "screen_onoff.js", "reboot.js", "shutdown.js"]

          }
      },

수정한 레시피 코드입니다.

var recipe = {
  transcriptionHook: {
    "HIDE_ALL_MODULES": {
      pattern: "모듈 숨겨 줘",
      command: "HIDEMODULES"
    },
    "SHOW_ALL_MODULES": {
      pattern: "모듈 보여 줘",
      command: "SHOWMODULES"
    },
  },
  command: {
    "HIDEMODULES": {
      moduleExec: {
        module:()=>{
          return []
        },
        exec: (module, params, key) => {
          module.hide(1000, null, {lockString:"AMK2"})
        }
      }
    },
    "SHOWMODULES": {
      moduleExec: {
        module:()=>{
          return []
        },
        exec: (module, params, key) => {
          module.show(1000, null, {lockString:"AMK2"})
        }
      }
    },
  },
}

exports.recipe = recipe
-------------------------------------------------------------
var recipe = {
  transcriptionHook: {
    "REBOOT": {
      pattern: "재부팅 해 줘",
      command: "REBOOT"
    },
  },
  command: {
    "REBOOT": {
      shellExec: {
        exec: "sudo reboot now"
      }
    }
  }
}

exports.recipe = recipe // Don't remove this line.
---------------------------------------------------------
var recipe = {
  transcriptionHook: {
    "SCREEN_ON": {
      pattern: "화면 켜 줘",
      command: "SCREENON"
    },
    "SCREEN_OFF": {
      pattern: "화면 꺼 줘",
      command: "SCREENOFF"
    },
  },
  command: {
    "SCREENON": {
      shellExec: {
        exec: (params, key) => {
          return "~/MagicMirror/modules/MMM-AssistantMk2/scripts/screenon.sh"
          //return "ls -al"
        },
        options: (params, key)=> {
          return ""
        },
      }
    },
    "SCREENOFF": {
      shellExec: {
        exec: "~/MagicMirror/modules/MMM-AssistantMk2/scripts/screenoff.sh",
        options: null,
      }
    },
  }
}

exports.recipe = recipe // Don't remove this line.
-------------------------------------------------------------
var recipe = {
  transcriptionHook: {
    "SHUTDOWN": {
      pattern: "시스템 꺼 줘",
      command: "SHUTDOWN"
    }
  },
  command: {
    "SHUTDOWN": {
      shellExec: {
        exec: "sudo shutdown now"
      }
    }
  }
}

exports.recipe = recipe // Don't remove this line.
----------------------------------------------------------
마지막 질문에 대한 다른 분 코드 입니다. 링크로 드릴게요 링크안에 깃허브 링크도 있어요.
[https://jeongchul.tistory.com/m/439](url)

제가 원하는건 이런 방식이였습니다. 이것도 그 분 코드입니다.
commad.js

var COMMANDS  = { "en" : {
  "voice" : "UK English Female",
  "default" : 'Say "What can I say?" to see a list of commands...',
  "hi" : 'Hi, sexy!',
  "whois" : "Who are you?",
  "whatcanisay" : 'What can I say',
  "home" : 'Go home',
  "sleep" : 'Go to sleep',
  "wake" : 'Wake up',
  "debug" : 'Show debug information',
  "map" : 'Show map',
  "locaiton" : 'Show (me a) map of *location',
  "zoomin" : '(map) zoom in',
  "zoomout" : '(map) zoom out',
  "zoomvalue" : '(map) zoom (to) *value',
  "zoomreset" : '(map) reset zoom',
  "playyoutube" : 'play *term youtube',
  "ytbplaylist" : '*term playlist',
  "stopyoutube" : 'stop youtube',
  "subway" : 'show me *linenumber info at *station',
  "musicplay" : "play music",
  "musicstop" : "stop music",
  "info" :  "Here is a list of commands...",
  "news" : "Show me news",
  "photo" : "Take a photo",
  "video" : "Take a video",
  "lighton" : "Light on",
  "lightoff" : "Light off"
},
  "ko" : {
    "voice" : "Korean Female",
    "default" : '"메뉴"라고 말해 보세요',
    "hi" : '안녕 정출',
    "whatcanisay" : '메뉴',
    "whois" : "너는 누구니",
    "home" : '홈으로',
    "sleep" : '잘자 미러',
    "wake" : '안녕 미러',
    "debug" : '디버그',
    "map" : '지금 어디 야',
    "locaiton" : '*location위치 보여 줘',
    "zoomin" : '지도 확대',
    "zoomout" : '지도 축소',
    "zoomvalue" : '*value값으로지도 설정',
    "zoomreset" : '지도 리셋',
    "playyoutube" : '*term 동영상 (재생)(켜 줘)(플레이)(틀어 줘)(보여 줘)',
    "ytbplaylist" : '*term 플레이어 (재생)(켜 줘)(플레이)(틀어 줘)(보여 줘)',
    "stopyoutube" : '동영상 (꺼 봐)(꺼 줘)(정지)(중지)(그만)(꺼져)',
    "subway" : '*station역 *linenumber(호)선 *updown',
    "musicplay" : "음악 (재생)(켜 줘)",
    "musicstop" : "음악 (꺼 봐)(꺼 줘)(정지)(중지)(꺼져)",
    "info" : "다음은 사용 가능한 질문입니다",
    "news" : "뉴스 보여 줘",
    "photo" : "사진 촬영",
    "video" : "비디오 촬영",
	"lighton" : "불 켜",
	"lightoff" : "불 꺼"
  }
};
--------------------------------------------------------------------------------
function-servic.js

var FUNCTIONSERVICE = {
	defaultHome : function($scope) {
		console.debug("Ok, going to default view...");
        if(responsiveVoice.voiceSupport()) {
          responsiveVoice.speak("홈으로 이동합니다.","Korean Female");
        }
        $scope.focus = "default";
	},
	whoIsSmartMirror : function($scope) {
		console.log("Who is Smart Mirror");
		if(responsiveVoice.voiceSupport()) {
	          responsiveVoice.speak("저는 음성 인식이 가능한 스마트 미러입니다.","Korean Female");
        }
		$scope.focus = "whoissmartmirror";
	},
	goSleep : function($scope){
		console.debug("Ok, going to sleep...");
        if(responsiveVoice.voiceSupport()) {
          responsiveVoice.speak("자러 갈게요. 다음에 봐요!","Korean Female");
        }
        $scope.focus = "sleep";
	},
	wake : function($scope) {
		console.debug("Wake up...");
		if(responsiveVoice.voiceSupport()) {
            responsiveVoice.speak("안녕하세요. 미러에요!","Korean Female");
          }
    	$scope.focus = "default";
	},
	whatCanISay : function($scope){
		console.debug("Here is a list of commands...");
        if(responsiveVoice.voiceSupport()) {
          responsiveVoice.speak("다음은 이용 가능한 메뉴입니다.","Korean Female");
        }
        $scope.focus = "commands";
	},
	map : function($scope,GeolocationService,MapService) {
		console.debug("Home map ...");
        GeolocationService.getLocation({enableHighAccuracy: true}).then(function(geoposition){
            console.log("Geoposition", geoposition);
            $scope.map = MapService.generateMap(geoposition.coords.latitude+','+geoposition.coords.longitude);

            $scope.focus = "map";
        });
        if(responsiveVoice.voiceSupport()) {
          responsiveVoice.speak("현재 위치 입니다.","Korean Female");
        }
	},
	location : function(location,$scope,GeolocationService,MapService) {
		console.debug("Getting map of", location);
        $scope.map = MapService.generateMap(location);
        if(responsiveVoice.voiceSupport()) {
          responsiveVoice.speak(location + "의 지도입니다.","Korean Female");
        }
        $scope.focus = "map";
	},
	news: function($scope) {
		console.debug("News..");
		
		if(responsiveVoice.voiceSupport()) {
            responsiveVoice.speak("실시간 뉴스입니다.","Korean Female");
          }
		
		$('#news-div').load('https://news.google.co.kr/news?pz=1&zx=muklwsp2gkt0 .section-toptop .esc-lead-article-title .titletext',function(){
  			console.log('news loaded.');
  		});
		$scope.focus = "news";
	},
	playYoutube : function(term,$scope,$sce,YoutubeService) {
		console.log("Play Youtube");
		
		if(responsiveVoice.voiceSupport()) {
        	responsiveVoice.speak("유튜브를 동영상을 재생합니다.","Korean Female");
        }
		YoutubeService.getYoutube(term,'video').then(function(){
			if(term){
	            var videoId = YoutubeService.getVideoId()
	            $scope.focus = "youtube";
	            $scope.youtubeurl = "http://www.youtube.com/embed/" + videoId + "?autoplay=1&enablejsapi=1&version=3&playerapiid=ytplayer"
	            $scope.currentYoutubeUrl = $sce.trustAsResourceUrl($scope.youtubeurl);
            }
        });
	},
	stopYoutube : function($scope) {
		console.debug("Stop Youtube");
		
		if(responsiveVoice.voiceSupport()) {
        	responsiveVoice.speak("유튜브를 동영상을 정지합니다.","Korean Female");
        }
		
		var iframe = document.getElementsByTagName("iframe")[0].contentWindow;
        iframe.postMessage('{"event":"command","func":"' + 'stopVideo' +   '","args":""}', '*');
        $scope.focus = "default";
	},
	subway : function(station,linenumber,updown,$scope,SubwayService) {
		console.debug("subway");
		SubwayService.init(station).then(function(){
            SubwayService.getArriveTime(linenumber,updown).then(function(data){
              if(data != null){
                $scope.subwayinfo1 = data[1].ARRIVETIME + "에 " + data[1].SUBWAYNAME + "행 열차";
                $scope.subwayinfo2 = data[2].ARRIVETIME + "에 " + data[2].SUBWAYNAME + "행 열차";
                $scope.subwayinfo3 = data[3].ARRIVETIME + "에 " + data[3].SUBWAYNAME + "행 열차";
                $scope.subwayinfo4 = data[4].ARRIVETIME + "에 " + data[4].SUBWAYNAME + "행 열차";
         
                if(responsiveVoice.voiceSupport()) {
                	responsiveVoice.speak(data[1].ARRIVETIME + "에 " + data[1].SUBWAYNAME + "행 열차가 있습니다. 이어서,"+data[2].ARRIVETIME + "에 " + data[2].SUBWAYNAME + "행 열차가 있습니다.","Korean Female");
                }
              }else{
                $scope.subwayinfo = "운행하는 열차가 없습니다.";
                if(responsiveVoice.voiceSupport()) {
                	responsiveVoice.speak("운행하는 열차가 없습니다.","Korean Female");
                }
              }
              $scope.focus = "subway";
            });
          });
	},
	photo : function(PHOTO_INDEX) {
		console.debug("Take a Photo ...");
		
		if(responsiveVoice.voiceSupport()) {
			responsiveVoice.speak("사진 촬영을 시작합니다.","Korean Female");
		}
		
		/* 카메라 프로세스 */
		var exec_photo = require('child_process').exec;
	
		/* 카메라 저장될 위치 설정 */
		var photo_path = __dirname+"/public/photo/"+"photo"+PHOTO_INDEX+'.jpg';
		
		/* 라즈베리 카메라 촬영 명령*/
		var cmd_photo = 'raspistill -o '+photo_path;
		exec_photo(cmd_photo, function(error, stdout, stderr){
			console.log('Photo Saved : ',photo_path);
			require('./js/mailer').sendEmail(photo_path);
		});
		
		// 4초 후 음성 합성 출력
		setTimeout(function() {
			if(responsiveVoice.voiceSupport()) {
				responsiveVoice.speak("사진 촬영이 끝났습니다.","Korean Female");
			}
		}, 4000);
		
		

	},
	video : function(VIDEO_INDEX) {
		console.debug("Take a Video ...");
		
		if(responsiveVoice.voiceSupport()) {
            responsiveVoice.speak("비디오 촬영을 시작합니다.","Korean Female");
        }
		
		/* 비디오 프로세스*/
		var exec_video = require('child_process').exec;
		/* 비디오 저장될 위치 설정*/
		var video_path = __dirname+"/public/video/"+"video"+VIDEO_INDEX+'.h264';
		/* 라즈베리 카메라 비디오 명령*/
		var cmd_video = 'raspivid -o '+video_path+' -t 4000';
		
		/* 라즈베리 카메라 비디오 촬영 및 이메일 전송*/
		exec_video(cmd_video, function(errror, stdout, stderr) {
			console.log('Video Saved : ',video_path);
			require('./js/mailer').sendEmail(video_path);
		});
		
		// 4초 후 음성 합성 출력
		setTimeout(function() {
			if(responsiveVoice.voiceSupport()) {
				responsiveVoice.speak("비디오 촬영이 끝났습니다.","Korean Female");
			}
		}, 4000);
		
	},
	lightOn : function() {
		console.debug("led on...");
		
    	if(responsiveVoice.voiceSupport()) {
            responsiveVoice.speak("등을 켭니다.","Korean Female");
        }
		
		/* Light on 프로세스*/
		var exec_lighton = require('child_process').exec;
		/* 커맨드 실행할 lightOn.js의 위치  */
		var cmd_path = "/home/pi/RelaySwitch/lightOn.js";
		/* 커맨드 명령*/
		var cmd_lighton = 'node '+cmd_path;
		
		exec_lighton(cmd_lighton, function(errror, stdout, stderr) {
			console.log('Start node lightOn.js');
		});
	},
	lightOff : function() {
		console.debug("led off...");
		
		if(responsiveVoice.voiceSupport()) {
            responsiveVoice.speak("등을 끕니다.","Korean Female");
        }
		
		/* Light off 프로세스*/
		var exec_lightoff = require('child_process').exec;
		/* 커맨드 실행할 lightOff.js의 위치  */
		var cmd_path = "/home/pi/RelaySwitch/lightOff.js";
		/* 커맨드 명령*/
		var cmd_lightoff = 'node '+cmd_path;
		
		exec_lightoff(cmd_lightoff, function(errror, stdout, stderr) {
			console.log('Start node lightOff.js');
		});
	}
};

항상 질문에 잘 응답해주셔서 감사합니다. 모듈도 물론 잘 쓰고 있습니다. ^^

**Comment by eouia** [comment]
1. Model ID를 만드실 수 없다는 게 무슨 의미인지 모르겠네요. 애초에 Model ID 없이는 프로젝트 auth 자체가 안될텐데요. 이 부분은 다시 뭘 어떻게 했는데 뭐가 안된다는 건지 좀 더 자세히 질문해주세요.

2. 딱히 코드가 잘못된 건 없어보이긴 하는데 (실행은 안시켜봤습니다. ^^;)
실제로 `pattern: "모듈 숨겨 줘",` 가 작동되려면 GA가 인식한 음성이 `모듈 숨겨 줘` 여야 합니다. 스페이스 포함이요. 아마 "모듈 숨겨줘" 등으로 인식된 거 아닌가요? 이런 부분을 세세하게 컨트롤하려면 정규식을 써줘야겠습니다만.
실제로 transcription이 어떻게 인식되는지 보시려면 `verbose:true` 옵션 주시고 백단로그를 보시면 됩니다. 좀더 단순하게는 pm2 구동을 중지하시고 `npm start dev` 로 실행시키면 터미널 창에서 바로 로그가 보입니다. 

3. transcription을 수정한다는게 무슨 뜻이지요?

4. useWelcomeMessage를 MMM-Hotword와 같이 쓰려면 MMM-Hotword의 start를 뒤로 늦춰야 하는데요.. 음.. 귀찮으니까 일단 사용안하시는 걸로 하시고, 나중에 다시 설명드릴게요.

5. 이건 MagicMirror 프로젝트와 전혀 상관없는 개인 자작 프로젝트네요. 전혀 호환되지 않습니다.

**Comment by eregos96** [comment]
1. 
![1](https://user-images.githubusercontent.com/55518797/68956398-53188600-080b-11ea-9af1-3fde0df400b5.JPG)
![2](https://user-images.githubusercontent.com/55518797/68956399-53188600-080b-11ea-9d44-33b4c3a7606b.jpg)

이렇습니다..

2.  말씀하신대로 음성인식 할 때 "모듈 숨겨 줘" 이렇게 인식 되길래 레시피 코드에도 똑같이 썼습니다. 그래도 안되서 질문 드린거였습니다.. 
로그 한번 보고 오겠습니다.

3. 아닙니다. 제가 잘못이해한 부분이 있었던것 같습니다.

4. ㅎㅎ 일단 useWelcomeMessage는 안쓰겠습니다.

**Comment by eouia** [comment]
1. 일단 우리가 쓰고 있는 SDK는  `Google Assistant Library for Python`이 아니고 `Google Assistant Service` 라서 첫번째 이미지는 상관없습니다. 
https://developers.google.com/assistant/sdk/guides/service/python/embed/register-device

**Comment by eregos96** [comment]
1. 현재 config.js에서 MK2부분에 recipes 부분을 주석치니깐 default로 있던 recipes들이 잘 동작하네요.. (???) 오히려 주석을 없앴을때는 동작을 안했습니다. 다만 screenonoff.js는 동작을 하지 않네요. 현재 라즈베리파이와 7인치 라즈베리파이 디스플레이스를 ffc케이블로 연결한 상태이고 screen saver기능이 아마 kiosk모드라서 default로 false(screensaver off)값일 것입니다. 일단 제 config.js 보여드릴게요.

{
          module: "MMM-AssistantMk2",  // 어시스턴트 기본 모듈
          position: "top_bar",
          config: {
              record: {
                  recordProgram: "arecord",
                  device: "plughw:1",
              },
              play: { // Full values are in `FOR EXPERTS` section.
                  playProgram: "mpg321", // recommended.
              },
              notifications: {
                  ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
                  ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
              },
              deviceLocation: {
                  coordinates: {
                      latitude: 37.610006,
                      longitude: 126.997600
                  }
              },
              profiles: {
                  "default": {
                      profileFile: "default.json",
                      lang: "ko-KR"
                  }
              },
              responseVoice: true, // If available, Assistant will response with her voice.
              responseScreen: true, // If available, Assistant will response with some rendered HTML
              responseAlert: true, // If available, Assistant will response with Alert module of MM

              screenZoom: "80%", // Adjust responseScreen to your mirror size.
              
              //유트브 재생 관련 설정
              youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.
              pauseOnYoutube: false, //If set as true, You cannot activate Assistant during youtube playing. Recommended for the performance (Because permanent hotword detecting might make performance lower)

              youtubePlayerVars: { // You can set youtube playerVars for your purpose, but should be careful.
                  "controls": 0,
                  "loop": 1,
                  "rel": 0,
              },
              youtubePlayQuality: "hd1080", //small, medium, large, hd720, hd1080, highres or default

              useWelcomeMessage: "brief today", //Try "brief today" as this value. You can use this value to check module working when MM is starting.
		
	      //recipes: ["reboot.js", "show_and_hide_all_modules.js", "screen_onoff.js", "reboot.js", "shutdown.js","ledonoff.js"]

          }
      },

2. 현재 led를 recipe를 이용해서 on/off하게 할려고 합니다. 템플릿 보고 ledonoff.js recipe를 만들고 lightOn.js와 lightOff.js 를 작성했습니다. 경로는 /home/pi/RelaySwitch 여기에 2개 파일 만들었습니다.
터미널에서 npm install onoff 명령어 쳐서 RelaySwitch 폴더에 설치했습니다. 
이후 실행시켜보면 LED가 동작을 안합니다 ㅜㅜ
![image](https://user-images.githubusercontent.com/55518797/68988515-22246980-087c-11ea-813a-bf48731d969b.png)


코드도 간단한데 왜 안되는지 모르겠습니다...

일단 lightOn.js ,lightOff.js 코드랑 recipe 파일 올릴게요.

 var Gpio = require("onoff").Gpio;

var led = new Gpio(18,'out');

led.writeSync(1);
-------------------------------------------------------
var Gpio = require("onoff").Gpio;

var led = new Gpio(18,'out');

led.writeSync(0);
-------------------------------------------------------
var recipe = {
    transcriptionHook: {
        "light_on": {
            pattern: "LED 켜 줘",
            command: "lighton"
        },

        "light_off": {
            pattern: "LED 꺼 줘",
            command: "lightoff"
        }
        // Describe your transcriptionHook here.
    },

    command: {
        "lighton": {
            shellExec: {
                exec: (params, key) => {
                    return "~/home/pi/RelaySwitch/lightOn.js"
                    //return "ls -al"
                },
                options: (params, key)=> {
                    return ""
                },
            }
        },
        "lightoff": {
            shellExec: {
                exec: "~/home/pi/RelaySwitch/lightOff.js",
                options: null,
            }
        },
    }
}

exports.recipe = recipe // Don't remove this line.

구글 어시스턴스가 이미 가지고있는 명령어를 주면 안된다고 해서 일부러 LED 켜 줘, LED 꺼 줘 이렇게  패턴을 줬습니다.

**Comment by eregos96** [comment]
var recipe = {
    transcriptionHook: {
        "light_on": {
            pattern: "LED 켜 줘",
            command: "lighton"
        },
        "light_off": {
            pattern: "LED 꺼 줘",
            command: "lightoff"
        }
        // Describe your transcriptionHook here.
    },

    command: {
        "lighton": {
            shellExec: {
                exec: (params, key) => {
                    return "node ~/RelaySwitch/lightOn.js"
                    //return "ls -al"
                },
                options: (params, key)=> {
                    return ""
                },
            }
        },
        "lightoff": {
            shellExec: {
                exec: "node ~/RelaySwitch/lightOff.js",
                options: null,
            }
        },
    }
}

exports.recipe = recipe // Don't remove this line.


ledonoff.js를 (레시피파일) 위에 처럼 바꿔보았는데도 안되네요 ㅠㅠ

**Comment by eouia** [comment]
`~/home/pi/RelaySwitch/lightOff.js`
터미널에서 이렇게 치면 명령어가 실행되나요?

**Comment by eouia** [comment]
일단 "LED 켜 줘" 가 제대로 hooking되는지 살펴봐야겠네요. 
관련된 파일들 전부 묶어서 메일로 좀 보내주시겠어요? eouia0819@gmail.com

**Comment by eregos96** [comment]
메일 보냈습니다.

**Comment by eregos96** [comment]
이상합니다... shutdown.js와 reboot.js 레시피 파일을 수정하여서 sudo shutdown 대신에 "node ~/RelaySwitch/lightOn.js",  훅에는 "LED 켜 줘" 고치고 말하면 잘 작동하네요. "LED 꺼 줘"도 마찬가지로 reboot.js 레시피를 수정하면 잘되네요.. 이상하게 커스텀하여서 만든 레시피 파일은 동작 자체를 안시키는 것 같습니다. config파일은 이상없습니다.  default로 있는 레시피파일만 작동하네요..

**Comment by eregos96** [comment]
알아서 해결했습니다. 다만 레시피 파일 불러오는게 이상하네요. default로 있는 레시피는 잘 읽어오는데 제가 만든 레시피는 읽어오는걸 자체를 못하네요.  터미널 창에서 log로 본 것 입니다. 레시피 파일 불러오는거 관련해서 코드 수정하셔야 될 것 같습니다.
