### ISSUE TITLE
news and spotify

### ISSUE THREAD

**Issue by diego12971** [eouia/MMM-AssistantMk2#241]
Is there a way of controlling spotify with the assistant and making the assitant say the news?

**Comment by eouia** [comment]
First, news features are not served by SDK. It is allowed to only Real Google Home devices. (There are some more feature not allowed - alarm, podcast, broadcasting through sibling devices)
Second. what kind of commands do you need for spotify?

**Comment by diego12971** [comment]
For spotify just simple commands like play of stop

**Comment by eouia** [comment]
I'll suggest some example and options but till Monday, I have not enough time to do. plz wait a while.

**Comment by diego12971** [comment]
ok thanks

**Comment by eouia** [comment]
```js
  transcriptionHook: {
    "START_SPOTIFY" : {
      pattern : "play music",
      command: "START_SPOTIFY"
    },
    "STOP_SPOTIFY" : {
      pattern : "stop music",
      command: "STOP_SPOTIFY"
    },
  },

  command: {
    "START_SPOTIFY": {
      notificationExec: {
        notification: "SPOTIFY_PLAY",
      }
    },
    "STOP_SPOTIFY": {
      notificationExec: {
        notification: "SPOTIFY_PAUSE"
      }
    },
  }
```
This code will work.  (Spotify should be activated before this command)

**Comment by diego12971** [comment]
Where i need to paste this code?

**Comment by eouia** [comment]
into the configuration of module, or you can make it as a recipe file,...
hmmm.. if u can't understand what and how to do, you'd better not use this code. sorry. this is a DIY module, not out-of-box-usable.

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
