### ISSUE TITLE
YouTube preferencies

### ISSUE THREAD

**Issue by chiccopeso** [eouia/MMM-AssistantMk2#243]
If a ask to listen some music in my Google home mini devices it takes some of my favorite song by YouTube. If I ask the same question to magic mirror it plays a random songs, as my Google account doesn't logged  in the YouTube service.
How can I solve?
Thanks

**Comment by eouia** [comment]
???
This module can play song?(even random?). Did you mean YouTube Clip? not the YouTube music?

Anyway, This module is not the alternative of real Google Home devices. Some features are not allowed on SDK level. playing music(from Google Play, YouTube, Spotify...) is one of them which are not allowed.

**Comment by chiccopeso** [comment]
Let me explain: I made a magic mirror for the bathroom, and I would like to
listen to music during the shower. Usually in my other GHM I listen to the
music by YouTube music, I thought that your module works the same way but
if it is impossible to let it work in that way it becomes totally useless
for my purpose.
If I ask "play some music" it start random music video, not taken from my
collection as GHM does.
Thank anyway for the fast replay.

Il lun 2 dic 2019, 10:43 Seongnoh Sean Yi <notifications@github.com> ha
scritto:

**Comment by eouia** [comment]
Streaming audio from Google Assistant SDK is not allowed by Google. Sorry, I can't help.
