### ISSUE TITLE
Magic Mirror is off immediately

### ISSUE THREAD

**Issue by Ulrick124** [eouia/MMM-AssistantMk2#244]
I put the module code of Google Assistant Mk2 to config.js. And after I run "npm start", magic mirror appears and immediately off. When I remove Mk2 module out of config.js, it works normally. What's wrong? Please help me. 
Here is the error in terminal:

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! magicmirror@2.9.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-12-02T07_44_57_268Z-debug.log

(( file debug was included):
[2019-12-02T07_44_57_268Z-debug.log](https://github.com/eouia/MMM-AssistantMk2/files/3910059/2019-12-02T07_44_57_268Z-debug.log)

**Comment by eouia** [comment]
Well, error log says MM has a problem to handle child process. it is not related to AMK2 module itself directly. Sorry, I have no idea about this information only.

**Comment by Ulrick124** [comment]
> Well, error log says MM has a problem to handle child process. it is not related to AMK2 module itself directly. Sorry, I have no idea about this information only.

Thank you for reply. That is some problems with gcc version.

**Comment by bugsounet** [comment]
to repair this : 
```
cd ~/MagicMirror
git checkout modules/node_modules/node_helper/index.js
npm start
```
it's a known bug in MagicMirror V2.90
