### ISSUE TITLE
custom respons

### ISSUE THREAD

**Issue by defiantlibra** [eouia/MMM-AssistantMk2#245]
hello the module works perfectly
I was wondering if there is a way to give and receive personalized answers. how could I do?
for example if I say "Jarvis say hello to Irene" he replies "hello Irene".
and last questions.. there is a way to reproduce spotify music on the mirror with a free account?

**Comment by eouia** [comment]
First, custom response is possible but somewhat limited.
One way is using IFTTT, and the other way is using `custom action` instead `transcriptionHook`. Read the docs on github.

Second, no way. audio-streaming is not allowed on this SDK by Google
