### ISSUE TITLE
MM freezes on playing YouTube

### ISSUE THREAD

**Issue by artomka** [eouia/MMM-AssistantMk2#246]
Hi, probably after a few wrong steps during configuration of MMMs, I cannot play any video with Google Assistant commands. MM freezes after ”Play a video” command. Other commands work correctly.

I have installed YouTube, Spotify and Chromecast modules. However, the behavior was the same even before the installation of these modules. 

Environment:
 - Device : RPI 4B
 - OS: Raspbian Stretch 

Logs:

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/pi/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-12-05T16_20_06_191Z-debug.log

_______________________________

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start', 'dev' ]
2 info using npm@6.13.1
3 info using node@v10.15.2
4 verbose config Skipping project config: /home/pi/.npmrc. (matches userconfig)
5 verbose stack Error: ENOENT: no such file or directory, open '/home/pi/packag$
6 verbose cwd /home/pi
7 verbose Linux 4.19.75-v7l+
8 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start" "dev"
9 verbose node v10.15.2
10 verbose npm  v6.13.1
11 error code ENOENT
12 error syscall open
13 error path /home/pi/package.json
14 error errno -2
15 error enoent ENOENT: no such file or directory, open '/home/pi/package.json'
16 error enoent This is related to npm not being able to find a file.
17 verbose exit [ -2, true ]

**Comment by eouia** [comment]
MMM-YouTube module is not compatible with current version of AMK2 yet. Don't use it together.
And your log says wrong errors, your error says just you executed `npm start dev` in wrong directory.

**Comment by artomka** [comment]
Sorry, this is the log:

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: MMM-chromecast.
Initializing new module helper ...
Module helper loaded: MMM-Spotify
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-Spotify
[SPOTIFY_AUTH] Token is fresh.
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Whoops! There was an uncaught exception...
{ Error: listen EADDRINUSE 0.0.0.0:8080
    at Server.setupListenHandle [as _listen2] (net.js:1330:14)
    at listenInCluster (net.js:1378:12)
    at doListen (net.js:1492:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:755:11)
    at startup (internal/bootstrap/node.js:241:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
  errno: 'EADDRINUSE',
  code: 'EADDRINUSE',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 8080 }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

I have already deleted the YouTube MMM, but it still the same. And now after saying hot word, it freezes.

**Comment by eouia** [comment]
```
{ Error: listen EADDRINUSE 0.0.0.0:8080
at Server.setupListenHandle [as _listen2] (net.js:1330:14)
at listenInCluster (net.js:1378:12)
at doListen (net.js:1492:7)
at process._tickCallback (internal/process/next_tick.js:63:19)
at Function.Module.runMain (internal/modules/cjs/loader.js:755:11)
at startup (internal/bootstrap/node.js:241:19)
at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)
errno: 'EADDRINUSE',
code: 'EADDRINUSE',
syscall: 'listen',
address: '0.0.0.0',
port: 8080 }
```
This error also be not related to my module. Usually this error will occur when you executed MM multiple-time. Reboot it simply.

**Comment by eouia** [comment]
Usually, this kind of error will happen in this situation;
- You've used `pm2` to manage the execution of MM, but without stopping it, tried `npm start dev`. It made double instances of MM.

**Comment by artomka** [comment]
Hi, I have completely reinstalled MM, so I can’t continue with this discussion. Sorry for this.
