### ISSUE TITLE
뒷부분 음성 짤림

### ISSUE THREAD

**Issue by nhpunch** [eouia/MMM-AssistantMk2#247]
구글어시스턴트 호출 후 명령어 내리면 음성으로 안내해주는데 짧은 안내를 하던 긴 안내를 하던 마지막 부분을 끝까지 말하지 않고 종료가 되어버리네요 어느 부분을 수정하면 되는건가요?

**Comment by eouia** [comment]
mpg321 업데이트 해보세요.

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
