### ISSUE TITLE
MM is continuously restarting with useWelcomeMessage

### ISSUE THREAD

**Issue by artomka** [eouia/MMM-AssistantMk2#248]
Hi, I have a fresh installation of MM, but I have a weird issue: When I have in a configuration file useWelcomeMessage, MM is continuously restarting, but without this line it works. However, when I say a hotword, MM restarts again. Can you help me, please?

 - Device : RPI 4B
 - OS: Raspbian Buster

**Comment by eouia** [comment]
Show me the log plz.

**Comment by artomka** [comment]
> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-Spotify
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-Spotify
[SPOTIFY_AUTH] Token is fresh.
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.....ics - Interval: 300000
Create new news fetcher for url: https://... - Interval: 300000
Create new news fetcher for url: https://....rss - Interval: 300000
Create new news fetcher for url: https://....rss - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.

**Comment by eouia** [comment]
```
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
...
```
If this logs happened in a short time repeatedly, Your mic setting seems wrong or has an issue to use.

**Comment by eouia** [comment]
And to make things simple, Remove or comment out all other modules except MMM-Hotword, MMM-AssistantMk2 and clock.

**Comment by artomka** [comment]
Yes, you’re right, but how can I fix the mic's issue? Is it possible to reset the audio settings? Do you want to see a new log just with Hotword and Mk2 modules?

**Comment by bugsounet** [comment]
to solve mic issue : 
in terminal type this : 
`arecord -l`

it will show all recorder aska MIC

pi@raspberrypi:~ $ arecord -l
**** Liste des Périphériques Matériels CAPTURE ****
carte 1: AK5371 [AK5371], périphérique 0: USB Audio [USB Audio]
  Sous-périphériques: 1/1
  Sous-périphérique #0: subdevice #0

there is an exemple : to set Mic config in MMM-Hotword
```
mic: {
recordProgram:"arecord",
device: "plughw:1",
verbose:false
},
```
plughw: number
the number of the card in arecord -l

**Comment by artomka** [comment]
Thanks, now the new log seems better:

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
________________________________________
However, when I bring back to the conf file useWelcomeMessage: "brief today", MM starts to restarting again. This is the log with useWelcomeMessage in conf file:

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-Spotify
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-Spotify
[SPOTIFY_AUTH] Token is fresh.
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https:....ics - Interval: 300000
Create new news fetcher for url: https:...- Interval: 300000
Create new news fetcher for url: https:...- Interval: 300000
Create new news fetcher for url: https:... - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] stops.
[AMK2] assistant ready
/home/pi/MagicMirror/node_modules/electron/dist/electron js/electron.js dev: symbol lookup error: /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! magicmirror@2.9.0 start: `sh run-start.sh "dev"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-12-09T12_10_02_209Z-debug.log
_____________________

Debug log:
  GNU nano 3.2                             /home/pi/.npm/_logs/2019-12-09T12_10_02_209Z-debug.log                                        

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start', 'dev' ]
2 info using npm@6.13.1
3 info using node@v10.15.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle magicmirror@2.9.0~prestart: magicmirror@2.9.0
6 info lifecycle magicmirror@2.9.0~start: magicmirror@2.9.0
7 verbose lifecycle magicmirror@2.9.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle magicmirror@2.9.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pi/Magi$
9 verbose lifecycle magicmirror@2.9.0~start: CWD: /home/pi/MagicMirror
10 silly lifecycle magicmirror@2.9.0~start: Args: [ '-c', 'sh run-start.sh "dev"' ]
11 info lifecycle magicmirror@2.9.0~start: Failed to exec start script
12 verbose stack Error: magicmirror@2.9.0 start: `sh run-start.sh "dev"`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at ChildProcess.emit (events.js:189:13)
12 verbose stack     at maybeClose (internal/child_process.js:970:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
13 verbose pkgid magicmirror@2.9.0
14 verbose cwd /home/pi/MagicMirror
15 verbose Linux 4.19.75-v7l+
16 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start" "dev"
17 verbose node v10.15.2
18 verbose npm  v6.13.1
19 error code ELIFECYCLE
20 error syscall spawn
21 error file sh
22 error errno ENOENT
23 error magicmirror@2.9.0 start: `sh run-start.sh "dev"`
23 error spawn ENOENT
24 error Failed at the magicmirror@2.9.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]

**Comment by eouia** [comment]
To use `useWelcomMessage`, you should invocate `HOTWORD_PAUSE` notification before MMM-AssistantMk2's activating. To make things simple, if you don't need absolutely, just don't use that feature.
(It will improve on next update)

**Comment by artomka** [comment]
Understood. However, the main problem isn't solved. When I say any Hotword, MM react properly (I mean the module is listening and the icon changes to listening type.), but immediately after that MM restarts. Any suggestion, please?

**Comment by eouia** [comment]
```
AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __atomic_store_8
```
says your installation was failed.
Check these;
- Did you downgrade your gcc version to 7 before installation?
![image](https://user-images.githubusercontent.com/1720610/70469309-17e73b00-1ac9-11ea-9309-62cd86486a6f.png)

- Did you downgrade grpc version to 1.23 on installation?
![image](https://user-images.githubusercontent.com/1720610/70469368-30efec00-1ac9-11ea-86cc-e7d9ab2caf08.png)

**Comment by artomka** [comment]
So, I have downgraded the grpc and rebuilt the electron. However, it is not still working. This is the new log:

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-Spotify
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-Spotify
[SPOTIFY_AUTH] Token is fresh.
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar....ics - Interval: 300000
Create new news fetcher for url: ... - Interval: 300000
Create new news fetcher for url: ...- Interval: 300000
Create new news fetcher for url: ... - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Started with text query: Hello
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
{ requestId: 'tzss56d-0000-2547-aedb-t89e0822f0b14' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: 'tzss56d-0000-2547-aedb-t89e0822f0b14'' }
[AMK2] Assistant Text Response: 
foundHook []
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[AMK2] Conversation Completed
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }

**Comment by eouia** [comment]
Your mic issue is not solved yet.
Show me your configuration and result of `arecord -l` and `aplay -l`

**Comment by artomka** [comment]
Here it is:

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.
Starting server on port 8080 ... 
You're using a full whitelist configuration to allow for all IPs
Server started ...
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Sockets connected & modules started ...
Launching application.
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Started with text query: Hello
{ requestId: 'tzss56d-0000-2547-aedb-t89e0822f0b14' } { profileFile: 'default.json', lang: 'en-US' }
[AMK2] Device Action: { requestId: 'tzss56d-0000-2547-aedb-t89e0822f0b14' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[HOTWORD] stops.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Assistant Text Response: 
[AMK2] end-of-utterance
[AMK2] Recorder Error: arecord has exited with error code 1.

Enable debugging with the environment variable DEBUG=record.
[AMK2] Assistant Text Response: 
foundHook []
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
__________________

**** List of CAPTURE Hardware Devices ****
card 1: Device [USB Advanced Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

_________________

**** List of PLAYBACK Hardware Devices ****
card 0: ALSA [bcm2835 ALSA], device 0: bcm2835 ALSA [bcm2835 ALSA]
  Subdevices: 7/7
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
card 0: ALSA [bcm2835 ALSA], device 1: bcm2835 IEC958/HDMI [bcm2835 IEC958/HDMI]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: ALSA [bcm2835 ALSA], device 2: bcm2835 IEC958/HDMI1 [bcm2835 IEC958/HDMI1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Device [USB Advanced Audio Device], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ HiFi pcm512x-hifi-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by artomka** [comment]
Config:

```
{
			module: "MMM-AssistantMk2",
			position: "bottom_right",
			config: {
				deviceLocation: {
					coordinates: {
						latitude: 50.1045184, // -90.0 - +90.0
						longitude: 14.5512354, // -180.0 - +180.0
					},
				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				youtubeAutoplay: true, //If set as true, found Youtube video will be played automatically.
			        pauseOnYoutube: false, //If set as true, You cannot activate Assistant during youtube playing. Recommended for the performance (Because permanent hotword detecting might make performance lower)
			        youtubePlayQuality: "hd1080", //small, medium, large, hd720, hd1080, highres or default
			        deviceModelId: "magicmirror-ak-2019-magicmirror-ak-0jqeks",
			        deviceInstanceId: "magicmirror-ak-2019", 
				useWelcomeMessage: "Hello",
				
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
				
				profiles: {
					"default" : {
						lang: "en-US"
					}
				},
			}
		},
		{
			module: "MMM-Hotword",
			position: "bottom_left",
			config: {
				chimeOnFinish: null,
				mic: {
				recordProgram:"arecord",
				device: "plughw:1",
				verbose:false
				},
				models: [
					{
						hotwords    : "smart_mirror",
						file        : "smart_mirror.umdl",
						sensitivity : "0.5",
					},
				],
				defaultCommand: {
				      notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
					  return {profile:"default"}
					}
				      },
				      afterRecordLimit:0,
				      restart:true,
				},
			},
		},
```

**Comment by bugsounet** [comment]
Ok, for me the configuration is ok for recorder.
You force useWelcomeMessage: "Hello"
so, do you hear something?

you have set smart mirror than a hotword. Do you test to says it ?

**Comment by artomka** [comment]
Yes, finally it works! Thank you so much for your time!
