### ISSUE TITLE
Not working after latest update 

### ISSUE THREAD

**Issue by tanvir586** [eouia/MMM-AssistantMk2#249]
I just update my AssistantMk2, but it's  not working now. It was working fine before update.  The issue is when i say smart mirror it active and deactivate straight away  and after few seconds it's shows conversation error. It does same if i click the button. 

My log

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: calendar_monthly.
Initializing new module helper ...
Module helper loaded: MMM-PrayerTime
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-MyScoreboard
Initializing new module helper ...
Module helper loaded: MMM-PIR-Sensor
Initializing new module helper ...
Module helper loaded: MMM-Screencast
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-DarkSkyForecast
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-PrayerTime
Starting node_helper.js for MMM-PrayerTime.
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: MMM-MyScoreboard
Starting node_helper for module [MMM-MyScoreboard]
Connecting socket for: MMM-PIR-Sensor
Connecting socket for: MMM-Screencast
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Connecting socket for: MMM-DarkSkyForecast
====================== Starting node_helper for module [MMM-DarkSkyForecast]
Sockets connected & modules started ...
Launching application.
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/en.uk%23holiday%40group.v.calendar.google.com/public/basic.ics - Interval: 2000
Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/qurashitanvir%40gmail.com/public/basic.ics - Interval: 2000
Create new news fetcher for url: http://www.walesonline.co.uk/?service=rss - Interval: 300000
Create new news fetcher for url: http://feeds.bbci.co.uk/bengali/rss.xml - Interval: 300000
Create new news fetcher for url: https://www.independent.co.uk/news/uk/rss - Interval: 300000
TypeError: record.record is not a function
    at GoogleAssistant.startConversation (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:394:22)
    at GoogleAssistant.emit (events.js:182:13)
    at GoogleAssistant.start (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js:38:10)
    at GoogleAssistant.assistant.on (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:414:17)
    at GoogleAssistant.emit (events.js:182:13)
    at Auth.GoogleAssistant.auth.on (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js:25:10)
    at Auth.emit (events.js:182:13)
    at saveTokens (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:32:10)
    at Auth.process.nextTick (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:92:35)
    at process._tickCallback (internal/process/next_tick.js:61:11)

[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._readsDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:199:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:698:15

  code: 14,
  metadata:
   Metadata { _internal_repr: { 'content-disposition': [Array] }, flags: 0 },
  details: 'Service unavailable.' }

**Comment by eouia** [comment]
how did you update? Your `node-record-lpcm16` node module seems not installed properly. 
If you don't need an updated feature, just leave it as it worked.

**Comment by eouia** [comment]
do `npm install` on `MMM-AssistantMk2` directory.

**Comment by spoutnikserv** [comment]
hello, 

I have the same problem after update with git pull. "record.record is not a function ..." 
I have tested npm install on MMM-AsssistantMk2 directory but the problem is always present.

I reinstalled the module completely and now I have an error : "sox has exited with error code 1"

Thank you for your help 

Best regards

**Comment by eouia** [comment]
@spoutnikserv 
```
"sox has exited with error code 1"
```
This means you might not configure your configuration properly. You probably are using RPI, in that case proper configuration would be `arecord` for mic device. check your configuration again.

**Comment by spoutnikserv** [comment]
Sorry, i checked my configuration and i do not see what's wrong. 
This config worked well before the new installation. I missed somethings ...

{
  module: "MMM-AssistantMk2",
  position: "top_left",
  config: {
	record: {
	  recordProgram : "arecord",  
	  device        : "plughw:0",
	},
	notifications: {
	  ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
	  ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
	},
  }
},
{
  module: "MMM-Hotword",
  position: "top_left",
  config: {
	chimeOnFinish:null,
	mic: {
	  recordProgram : "arecord",  
	  device        : "plughw:0",
	},
	models: [
	  { 
		  hotwords: ["jarvis", "jarvis"],
		  file: "jarvis.umdl",
		  sensitivity: "0.8,0.8",
	  },
	],
	defaultCommand: {
	  notificationExec: {
		notification: "ASSISTANT_ACTIVATE",
		payload: (detected, afterRecord) => {
		  return {profile:"default"}
		}
	  },
	  afterRecordLimit:2,
	  restart:false,
	},
  },
},

and always the same report : 

[HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
[AMK2] assistant ready
[AMK2] Conversation starts.
Whoops! There was an uncaught exception...
{ Error [ERR_UNHANDLED_ERROR]: Unhandled error. (sox has exited with error code 1.

Enable debugging with the environment variable DEBUG=record.)
    at Socket.emit (events.js:171:17)
    at ChildProcess.cp.on.code (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/node-record-lpcm16/index.js:51:11)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close [as _onclose] (net.js:596:12)
  context:
   'sox has exited with error code 1.\n\nEnable debugging with the environment variable DEBUG=record.' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
[AMK2] Assistant Text Response: 
[AMK2] Assistant Text Response: 
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._readsDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:199:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:698:15
  code: 14,
  metadata:
   Metadata { _internal_repr: { 'content-disposition': [Array] }, flags: 0 },
  details: 'Service unavailable.' }

**Comment by bugsounet** [comment]
humm ...
so hotword works and it's the same configuration:
recordProgram : "**_arecord_**"
{ Error [ERR_UNHANDLED_ERROR]: Unhandled error. (**_sox_** has exited with error code 1.

You set `arecord` in the config and the program call another recorder `sox`
Your config is good :)
I will inspect it ...

**Comment by bugsounet** [comment]
I fix it, let update and try :)

**Comment by tanvir586** [comment]
My AssistantMk2 working again.  
Had to reinstall the full module and rebuild.

Closing the issue.  Reopen if needed

**Comment by spoutnikserv** [comment]
Thank you for your help, it's work fine !
