### ISSUE TITLE
Ubuntu 18 trouble starting at auth. Downhill from there.

### ISSUE THREAD

**Issue by cr4zy5pacec0w80y** [eouia/MMM-AssistantMk2#25]
Running this all on a laptop Ubuntu 18, so if there are any dependencies that you have not listed what would they be?
I'll be more than happy to do a straight forward step by step writeup install guide for you if we can get this working properly by the way.
Also here is the version of java I'm running even though from what I gather Node.js is what's used??? Not sure, java is so confusing XD

rebecca@SmartMirror:~/MagicMirror/modules/MMM-AssistantMk2$ java -version
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)

Not using ssh. Using built in terminal.

So here is what I'm getting:

$git clone https://github.com/eouia/MMM-AssistantMk2.git
$cd MMM-AssistantMk2
$npm install

Output:
npm WARN MMM-AssistantMk2@1.0.1 No repository field.

****************** Googled this, I guess it's a non issue, just extra documentation::
It's just a check as of NPM v1.2.20, they report this as a warning.
However, don't worry, there are sooooooo many packages which still don't have the repository field in their package.json. The field is used for informational purposes.
In the case you're a package author, put the repository in your package.json, like this:
"repository": {
  "type": "git",
  "url": "git://github.com/username/repository.git"
}
****************

**I want to do KIOSK Mode, so you say build profile first?.. ok so continue on to get credentials.json
**(FYI  I already have built a project and enabled google assistant api and registered device by attempting to use this alternate module:::https://github.com/gauravsacc/MMM-GoogleAssistant   but have had no luck with it loading properly, so I'm trying your module which to be honest looks better anyways...)

**What do you mean by "But if you want to run your mirror as `KIOSK` mode, you should rebuild binaries to match with electron."?
I'm assuming you meant to run "NPM REBUILD" so I did and i got the output at the end of this message(it is a loooot of text)::

** Already have credentials.json copied to /home/rebecca/MagicMirror/modules/MMM-AssistantMk2/credentials.json

$ node auth_and_test.js
/home/rebecca/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:27
  const oauthClient = new OAuth2(key.client_id, key.client_secret, key.redirect_uris[0]);
                                     ^

TypeError: Cannot read property 'client_id' of undefined
    at new Auth (/home/rebecca/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/components/auth.js:27:38)
    at new GoogleAssistant (/home/rebecca/MagicMirror/modules/MMM-AssistantMk2/node_modules/google-assistant/index.js:21:16)
    at Object.<anonymous> (/home/rebecca/MagicMirror/modules/MMM-AssistantMk2/auth_and_test.js:60:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)

** Also it may be worth noting that the browser never opened a page to match up keys or whatever, but I have done that step previously when trying to set up the other module...
Do you think I need to make a separate project with google?

rebecca@SmartMirror:~/MagicMirror/modules/MMM-AssistantMk2$ npm install --save-dev electron-rebuild
npm WARN MMM-AssistantMk2@1.0.1 No repository field.
rebecca@SmartMirror:~/MagicMirror/modules/MMM-AssistantMk2$ ./node_modules/.bin/electron-rebuild
✔ Rebuild Complete
rebecca@SmartMirror:~/MagicMirror/modules/MMM-AssistantMk2$ 

after this I tried to re run the commands and got same result...
any advice or suggestions? I reaaally want to use this module vs the other.

**Comment by eouia** [comment]
1) Don't mind repository warning issue. I'm so lazy to fix it. :D

2) I think your `credentials.json` has a problem. It should be something like this;
```
{
  "installed": {
    "client_id":"833258677654-2rv97u3b2upq0flpfpsqkfhqq4s8v6bq.apps.googleusercontent.com",
    "project_id":"my-project",
    "auth_uri":"https://accounts.google.com/o/oauth2/auth",
    "token_uri":"https://accounts.google.com/o/oauth2/token",
    "auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
    "client_secret":"4WWZB4c2O063VXWxt4n5xLSN",
    "redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]
  }
}
```
(This is not a working credentials. Just see the format)
Your `credentials.json` may have wrong data. Consider to remove your projects and create new one.

**Comment by eouia** [comment]
And for dependencies, See belows;
- https://github.com/TooTallNate/node-speaker
- https://github.com/gillesdemey/node-record-lpcm16
But there could be something missing for Ubuntu. I'm not using that OS so I don't know what could be missed at this moment.

**Comment by cr4zy5pacec0w80y** [comment]
Thanks for all of that. Turns out it was ubuntu's version of node screwing with it. Don't have time now, but I'll fill you in on it more so you can add it to the main. Maybe even do a step by step for ubuntu 18 got the vanilla module to work. Now time for hotword and everything else. Thanks for the help! (btw had to uninstall and reinstall nodejs 8.10 from nodesource)

**Comment by eouia** [comment]
Sounds so good. I'll close this issue. Have a nice day.
