### ISSUE TITLE
New guy-How can I link my google account with the Assistant module? 

### ISSUE THREAD

**Issue by ghost** [eouia/MMM-AssistantMk2#250]
How can I link my google account with the assistant module? I want to be able to control my smart devices, play music and do the things that anyone would do with their google assistant. Ever so often if I ask it a question that requires an account to be linked, it will say "sign in using the menu", and then "Sign in with your phone" will pop up. I've followed all the steps about installing and setting it up, just nobody seems to ask about linking their google account, so im thinking i may have done something wrong. 

 - Device : Raspberry Pi 3 Model B
 - OS: Raspbian Stretch

**Comment by Shaw2** [comment]
Hi, I also have this problem. I passed this problem by using new google account but still have a question about it. I thought it was a problem that I didn't assign to google platform Free Trial. But it wasn't. Please solve this problem.

![image](https://user-images.githubusercontent.com/49862639/70583320-b9bd7380-1c00-11ea-9e6d-970f7334b129.png)

[Passed node_and_test.js]
![image](https://user-images.githubusercontent.com/49862639/70583191-2f750f80-1c00-11ea-9897-33dae83c8b87.png)

[Pop up : "Sign in with your Account"]
![image](https://user-images.githubusercontent.com/49862639/70583073-ecb33780-1bff-11ea-9657-96d41ca4bab2.png)

[My log]
![image](https://user-images.githubusercontent.com/49862639/70583199-356af080-1c00-11ea-9e2c-b7fa04f28797.png)

**Comment by eouia** [comment]
You guys need to be users of Google Assistant. Probably you are not the USER yet. download google assistant app on the smartphone and sign in the app.

**Comment by Shaw2** [comment]
Jesus, it works! Thank U.

But still I have a question. How it was worked with my sub google account??
That was also not the USER.

**Comment by eouia** [comment]
Each account to use Google Assistant should be a registered USER. resign in as a new user.

**Comment by Shaw2** [comment]
Nono, I mean my main account wasn't worked as I said.

However my sub account was worked. It's also not registered with Google Assistant for USER. So it is not a problem, just a question and curiosity.

If u know the reason, please let me know :)

**Comment by amuqeet352** [comment]
I have question, I am using this from a long time and it worked fine. recently I made a new user and downloaded credentials and pasted. when i enter node auth_and_test.js it pops up to sign in but its not signing in to my account. whenever i sign in, the sign in screen again reappears without taking me into code that i have to paste.

**Comment by eouia** [comment]
@amuqeet352
I think browser cookie should be reset. Or use other browsers.

**Comment by amuqeet352** [comment]
I've tried but still the same, not taking me into the code that i have to paste. Again and again login screen
![check](https://user-images.githubusercontent.com/59086734/71253982-411a8d80-234b-11ea-9c69-9db6db743ce5.png)

**Comment by amuqeet352** [comment]
I've tried but still the same, login screen reappears after every try but not taking me into code
![check](https://user-images.githubusercontent.com/59086734/71254067-96569f00-234b-11ea-8b9a-3decab0bc71f.png)

**Comment by eouia** [comment]
@amuqeet352 
Well, copy that url and try it in another brwoser on another pc.

**Comment by amuqeet352** [comment]
It worked.... Thank you. But I didn't get the problem, the Raspbian was new, cleared out cookies and history. but didnt worked on it

**Comment by eouia** [comment]
@amuqeet352 I have no idea about Raspberry Pi itself.

**Comment by amuqeet352** [comment]
@eouia well Thank you Brother. :)

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
