### ISSUE TITLE
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node. /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __cxa_pure_virtual

### ISSUE THREAD

**Issue by bao0720** [eouia/MMM-AssistantMk2#251]
Excuse me,I encountered the following problem after implementation but I don't know what to do.

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: compliments.
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node. /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __cxa_pure_virtual
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: compliments.
App threw an error during load
Error: Failed to load /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node. /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __cxa_pure_virtual
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:32:13)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:64:3)
Whoops! There was an uncaught exception...
Error: Failed to load /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node. /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node: undefined symbol: __cxa_pure_virtual
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:32:13)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:64:3)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

This is my configuration

/* Magic Mirror Config Sample
	 *
	 * By Michael Teeuw http://michaelteeuw.nl
	 * MIT Licensed.
	 *
	 * For more information how you can configurate this file
	 * See https://github.com/MichMich/MagicMirror#configuration
	 *
	 */

	var config = {
		address: "localhost", // Address to listen on, can be:
			              // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
			              // - another specific IPv4/6 to listen on a specific interface
			              // - "", "0.0.0.0", "::" to listen on any interface
			              // Default, when address config is left out, is "localhost"
		port: 8080,
		ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
			                                               // or add a specific IPv4 of 192.168.1.5 :
			                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
			                                               // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
			                                               // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

		language: "en",
		timeFormat: 24,
		units: "metric",

		modules: [
			{
				module: "alert",
			},
			{
				module: "updatenotification",
				position: "top_bar"
			},
			{
				module: "clock",
				position: "top_left"
			},
			
			{
				module: "compliments",
				position: "lower_third"
	},
	{
		module: "MMM-Hotword",
		position: "top_right",
		config: {
			chimeOnFinish: null,
			mic: {
				recordProgram: "arecord",
				device: "plughw:1,0",
			},
			models: [
				{
					hotwords    : "computer",
					file        : "computer.umdl",
					sensitivity : "0.5",
				},
			],
			commands: {
				"computer": {
					notificationExec: {
						notification: "ASSISTANT_ACTIVATE",
						payload: (detected, afterRecord) => {
							return {profile:"default"}
						}
					},
					restart:false,
					afterRecordLimit:0
				}
			}
		}
	},
	{
	  module: "MMM-AssistantMk2",
	  position: "top_right",
	  config: {
	    record: {
	      recordProgram : "arecord",  
	      device        : "plughw:1",
	    },

	    notifications: {
	      ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
	      ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
	    },
	  }
	},

		]

	};

	/*************** DO NOT EDIT THE LINE BELOW ***************/
	if (typeof module !== "undefined") {module.exports = config;}

**Comment by eouia** [comment]
Your installation seems not completed normally.
Check these two things then retry `electron-rebuild` step.
- downgrade `gcc` of your system to version 7.
- downgrade `grpc` to version 1.23
You can find related instructions on github docs. (README.md and Install.md)

**Comment by bao0720** [comment]
I have tried what you said to downgrade it then retry electron-rebuild step, but it still shows the same as above.
![2019-12-12-213634_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70716528-83c6df00-1d27-11ea-965d-ffa1c0a3dd9b.png)

**Comment by eouia** [comment]
What is the error message? The last error message is different from your previous one.

**Comment by bao0720** [comment]
![2019-12-12-214927_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70717456-554a0380-1d29-11ea-9aba-5ccd4ebc987c.png)

**Comment by eouia** [comment]
This is another different issue. Your MMM-Hotword seems not installed properly or broken for some reason.
Reinstall MMM-Hotword.

**Comment by bao0720** [comment]
Does this error affect my installation?
![2019-12-12-221654_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70719679-68f76900-1d2d-11ea-8020-761f2c3a41af.png)

**Comment by bao0720** [comment]
I have this error during installation, will it affect it?
![2019-12-12-221654_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70719754-89272800-1d2d-11ea-94f0-89ed12a8ab50.png)

**Comment by eouia** [comment]
The last 3 lines of log says installation completed. I think it is installed.

**Comment by bao0720** [comment]
But this error still appears after reinstalling
![2019-12-12-222427_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70720267-78c37d00-1d2e-11ea-951e-f37a0eeb7627.png)

**Comment by eouia** [comment]
Well, if you did these instructions without missing;
```
sudo apt update
sudo apt upgrade
sudo apt install libmagic-dev libatlas-base-dev sox libsox-fmt-all

cd ~/MagicMirror/modules
git clone https://github.com/eouia/MMM-Hotword.git
cd MMM-Hotword

chmod +x ./installer/install.sh
./installer/install.sh
```
But still you have a problem, Sorry, I have no idea any more. Maybe your system is corrupted but I don't know what exactly causes this error.

**Comment by bao0720** [comment]
![2019-12-12-224156_1920x1080_scrot](https://user-images.githubusercontent.com/58466331/70721531-b2958300-1d30-11ea-9c87-cd5deb266def.png)
If this is the case, is MK2 not installed?

**Comment by eouia** [comment]
Yes. error says something happens on MMM-AssistantMk2 directory.

**Comment by bao0720** [comment]
ok,I try again with mk2.

**Comment by bao0720** [comment]
Excuse me,Can mk2 use Chinese instead and ask it to answer in Chinese?

**Comment by eouia** [comment]
As far as I know, Chinese(Traditional or Simplified / Cantonese or 普通话 anything else) is not officially supported yet.
https://developers.google.com/assistant/sdk/reference/rpc/languages

**Comment by bao0720** [comment]
Ok! I know. Can it call other modules with voice assistant, for example: call Spotify to play music or next song

**Comment by eouia** [comment]
Possible. However, you should make your custom recipe for it by yourself. There is no ready-made-out-of-box thing. Anyway, the answer is absolute `yes`. The purpose of this module is that kind of control.

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
