### ISSUE TITLE
Problems ./gactions

### ISSUE THREAD

**Issue by L1a1337** [eouia/MMM-AssistantMk2#253]
Hy guys!

I rly need your help XD

I have installed the mm2 framework and the google assistant activated by hotword aso...
Now I am trying to set-up my specific (actions.js) commands f.e. swipe next page on carousel/page over ./gactions, so 

I have followed all instructions wich were given but now I am stuck at the ./gactions login

It opens the browser and with this message:

Registration with Google is temporarily deactivated for this app
The use of Google Log-in has not yet been confirmed for this app.

So at this point I need some help please. How do I activate the registration for this app?

**Environment:**
 - Device : [e.g. RPI 4b+]
 - OS: [Raspbian Buster]

And thanks for that fkn awesome projects!!!!!!!!!!!!!!! YOU ROCK!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by eouia** [comment]
remove your browser cache and try again.

**Comment by L1a1337** [comment]
first of all thx for your fast help but nope...

**Comment by L1a1337** [comment]
> remove your browser cache and try again.

first of all thx for your fast help but nope...

this was my console output:

./gactions login
Visit the URL to authorize access:

https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&client_id=619137215474-jg0sfcio74m3o5523m0dav65j2gdbgvr.apps.googleusercontent.com&redirect_uri=http%3A%2F%2F127.0.0.1%3A34819&response_type=code&scope=openid+email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloudplatformprojects.readonly+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Ffirebase+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Factions.builder&state=state
--disable-quic --enable-tcp-fast-open --ppapi-flash-path=/usr/lib/chromium-browser/libpepflashplayer.so --ppapi-flash-args=enable_stagevideo_auto=0 --ppapi-flash-version=
[10226:10357:1218/171605.481021:ERROR:object_proxy.cc(619)] Failed to call method: org.freedesktop.Notifications.GetCapabilities: object_path= /org/freedesktop/Notifications: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
[10272:10272:1218/171606.564125:ERROR:gl_surface_presentation_helper.cc(244)] GetVSyncParametersIfAvailable() failed for 1 times!
[10226:10226:1218/171624.476908:ERROR:gaia_auth_fetcher.cc(72)] Missing ID token on refresh token fetch response.

**Comment by eouia** [comment]
<img width="649" alt="tttt1" src="https://user-images.githubusercontent.com/1720610/71103487-8196d180-21ba-11ea-88de-84f0cc5f4b2f.png">

I can see the login page on that url. Try another browser with that url 
Anyway, Did I write `./gactions login` in my instruction? Hmmmm, I think login is not needed but my memory might be confusing.

**Comment by L1a1337** [comment]
it says i cannot commit bec. im not logged in, so I thougt it is necessary but it was not in your description and im trying firefox

**Comment by eouia** [comment]
Of course, at the first execution of `./gactions update` or `./gactions test`, auhorization is required. but not by `./gactions login`. That commands also will show url for auth. At that moment, you might need to login.
And if any credential related files on your directory where `gaction` locates, delete them.

**Comment by L1a1337** [comment]
bro i tried XD

this was my console output:

pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./gactions update --action_package actions.json --project magicl1a
bash: ./gactions: No such file or directory
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ll
total 20
drwxr-xr-x  2 pi pi 4096 Dec 18 17:00 .
drwxr-xr-x 12 pi pi 4096 Dec 17 19:58 ..
-rw-r--r--  1 pi pi 5822 Dec 17 19:58 actions.json
-rw-r--r--  1 pi pi   76 Dec 17 19:58 README.md
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ wget hhttps://dl.google.com/gactions/updates/bin/linux/arm/gactions
hhttps://dl.google.com/gactions/updates/bin/linux/arm/gactions: Unsupported scheme ‘hhttps’.
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ wget https://dl.google.com/gactions/updates/bin/linux/arm/gactions
--2019-12-18 17:33:17--  https://dl.google.com/gactions/updates/bin/linux/arm/gactions
Resolving dl.google.com (dl.google.com)... 172.217.20.14, 2a00:1450:400d:804::200e
Connecting to dl.google.com (dl.google.com)|172.217.20.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 17540292 (17M) [application/octet-stream]
Saving to: ‘gactions’

gactions                                                    100%[=========================================================================================================================================>]  16.73M  8.11MB/s    in 2.1s    

2019-12-18 17:33:20 (8.11 MB/s) - ‘gactions’ saved [17540292/17540292]

pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ chmod +x gactions
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./gactions update --action_package actions.json --project magicl1a
Error: Not logged in. Please run `gactions login` to login.

**Comment by eouia** [comment]
Ok. try `./gaction --h` or  `./gaction -V` to see the version.
It should show this;
```
eouia$ ./gactions --h

NAME:
   gactions - The Actions on Google command line interface that you can use to test and update your app for the Assistant.

USAGE:
   gactions [global options] command [command options] [arguments...]

VERSION:
   2.2.4

COMMANDS:
   init        Create a default action.json file
   test        Takes the specified app for the Assistant and makes it available for previewing/simulation
   update      Updates the draft action in the app for the Assistant for the given project
   list        List up to 10 recent versions of your app for the Assistant: in review, production, approved, etc
   get         Get the contents of a given version of your app for the Assistant
   selfupdate  Checks for updates for this tool
   help, h     Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --verbose, -v  Show more detailed output
   --help, -h     show help
   --version, -V  print the version
```

**Comment by eouia** [comment]
By the way, `gactions login` would make `creds.data` file on your directory (It would be the same result of authorization of `gactions update` or `gactions test`)
So I think, if you make a success on `gactions login`, that will work.

And if you cannot open that url in some browser, try another browser.

**Comment by L1a1337** [comment]
ok gactions says unknown flag: --h 

what is wrong with this gactions? XD

output: 

 ./gactions --h
Error: unknown flag: --h
Usage:
  gactions [flags]
  gactions [command]

Available Commands:
  channel     Display current or set new release channel for gactions.
  deploy      Deploy Action's fulfillment, NLU and console configuration.
  download    Download a Actions on Google sample.
  get         Get the contents of a given version of your Action.
  help        Help about any command
  init        Initialize a new project.
  list        List up to 10 recent versions of your app for the Assistant and their status.
  login       Login to gactions.
  logout      Log out of gactions.
  open        Open a Actions on Google related product.
  project     Display current or set new Google Project ID.
  selfupdate  This command will check for updates and perform a in-place upgrade if an update if found.
  test        Takes the specified Action for the Assistant and makes it available for previewing/simulation.
  update      Updates the draft action in the app for the Assistant for the given project.
  version     Prints the version of gactions.

Flags:
  -h, --help      help for gactions
  -v, --verbose   verbose output

Use "gactions [command] --help" for more information about a command.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55cf68]

goroutine 1 [running]:
github.com/actions-on-google/gactions/commands.Execute()
	/Users/matthewcarroll/dev/actions-on-google/cli/commands/root.go:54 +0x88
main.main()
	/Users/matthewcarroll/dev/actions-on-google/cli/main.go:24 +0x14

**Comment by eouia** [comment]
sorry, mistypo. :) `gactions -h` is right.

**Comment by eouia** [comment]
Hmmm. on version 2.2.4; `gactions --h` b also working. :O

**Comment by L1a1337** [comment]
./gactions -h
This interface allows you to authenticate once and then setup or update every aspect of Actions on Google stack (fulfillment, NLU, and Actions config) with a single simple command (`gactions deploy`).

Usage:
  gactions [flags]
  gactions [command]

Available Commands:
  channel     Display current or set new release channel for gactions.
  deploy      Deploy Action's fulfillment, NLU and console configuration.
  download    Download a Actions on Google sample.
  get         Get the contents of a given version of your Action.
  help        Help about any command
  init        Initialize a new project.
  list        List up to 10 recent versions of your app for the Assistant and their status.
  login       Login to gactions.
  logout      Log out of gactions.
  open        Open a Actions on Google related product.
  project     Display current or set new Google Project ID.
  selfupdate  This command will check for updates and perform a in-place upgrade if an update if found.
  test        Takes the specified Action for the Assistant and makes it available for previewing/simulation.
  update      Updates the draft action in the app for the Assistant for the given project.
  version     Prints the version of gactions.

Flags:
  -h, --help      help for gactions
  -v, --verbose   verbose output

Use "gactions [command] --help" for more information about a command.

**Comment by eouia** [comment]
maybe your `gactions` seems different with mine. weird. Try `./gactions selfupdate`

**Comment by L1a1337** [comment]
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/gaction $ ./gactions selfupdate
DEBUG 2019/12/18 17:57:56 Calling update server...
DEBUG 2019/12/18 17:57:56 Parsing update server response...
DEBUG 2019/12/18 17:57:57 Successfully parsed update server response
DEBUG 2019/12/18 17:57:57 Current version is 2.2.2
DEBUG 2019/12/18 17:57:57 Runtime: linux
DEBUG 2019/12/18 17:57:57 Arch: arm
DEBUG 2019/12/18 17:57:57 %+v &{    }
DEBUG 2019/12/18 17:57:57 No new updates
gactions is up to date.

**Comment by eouia** [comment]
try `./gactions --version` or `./gactions version`.

**Comment by L1a1337** [comment]
ohh not up to date XD

Actions on Google CLI 2.2.2

**Comment by eouia** [comment]
Anyway, try again `./gactions login`, and try the URL in broswer.

**Comment by L1a1337** [comment]
i did ... still same problem, but i found this:

https://github.com/googlesamples/assistant-sdk-python/issues/376

**Comment by L1a1337** [comment]
could you send me your working gactions?

**Comment by eouia** [comment]
Mine will not work on your RPI.(Mine is for Mac) As my reading that link, linux-arm version is outdated.
If you have another dev-machine - windows PC or x86_64 linux or OSX Mac, copy your actions.json to dev-machine then can do registration there.

**Comment by L1a1337** [comment]
clever idea!!!

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
