### ISSUE TITLE
Hotword not working

### ISSUE THREAD

**Issue by Corestorm** [eouia/MMM-AssistantMk2#254]
I'm activating the Mk2 Assistant, by using hotword "computer" It works fine when i use it for the first time after starting MagicMirror with npm start.  Mk2 module starts using the welcomeMessage and reads it. Then I give it a command like "computer what can you do" the command works and the mk2 module activates with hotword but when i attempt to say something again(the second time) for example "computer what time is it" The hotword module gets stuck showing the "hotword" that I just said and doesn't activate the Mk2 module.

**Comment by eouia** [comment]
Maybe your configuration is wrong. I think you've missed `notifications` part on `MMM-AssistantMk2`

**Comment by Corestorm** [comment]
Yeah that was what I've missed. I can't test if that'll fix it until monday but I'm pretty sure that was the issue, thank you!

**Comment by Corestorm** [comment]
Fixed.
