### ISSUE TITLE
Youtube not pausing.

### ISSUE THREAD

**Issue by Corestorm** [eouia/MMM-AssistantMk2#256]
I can play videos from youtube using "play bla bla" But can't pause it. I've tried making a command(recipe) to stop the video but couldn't figure it out. I don't want it to pause the video I want it to stop playing and go back to, MagicMirror screen. The video starts on fullscreen if I use the command so I need a way to stop playing the video and go back to MagicMirror screen.

**Comment by eouia** [comment]
" pauseOnYoutube:true," makes hotword can stop the video.

**Comment by Corestorm** [comment]
Do I have to add this to config ?

**Comment by eouia** [comment]
yes.

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
