### ISSUE TITLE
use a bluetooth microphone

### ISSUE THREAD

**Issue by MrJointMilano** [eouia/MMM-AssistantMk2#257]
Good morning.
Is it possible to use a bluetooth microphone instead of the usb one?

I tried the arecord command --format = S16_LE --duration = 5 --rate = 16000 --file-type = raw out.raw
and the audio is recognized and played with the aplay command --format = S16_LE --rate = 16000 out.raw

This is my .asoundrc file
   

pcm.! default {
type asym
playback.pcm {
type plug
slave.pcm "output"
}
capture.pcm {
type plug
slave.pcm "input"
}
}

pcm.output {
type hw
card 0
}

pcm.input {
type bluealsa
device "00: 11: 67: 11: 20: 6E"
profile "sco"
}

ctl.! default {
type hw
card 0
}

How can I make the assistantMk2 recognize it?
Thanks to anyone who will help me and apologize for my english.

**Comment by eouia** [comment]
I'm not that kind of expert, but as your description;
the recording device name might be `"input"`. Have you tried it?

**Comment by MrJointMilano** [comment]
Yes i do but it's wrong.

**Comment by eouia** [comment]
Sorry, I cannot help you about ALSA setup. You should find a proper `device id` on your environment.
