### ISSUE TITLE
custom response

### ISSUE THREAD

**Issue by defiantlibra** [eouia/MMM-AssistantMk2#258]
hi, it is already the second time I am writing to you, so thanks for your patience, but I continue to have problems to create personalized answers with mk2 assistant. I decided to use the transcription hooks inside the recipes, but i don't understand how to make assistant say something that i want. for example this is a recipe file that i have created for test, but it dont work.. can you help me please?

var recipe = {
  transcriptionHook: {
    "TEST": {
        pattern: "test", 
        command: "TESTCOMMAND"
        },
   },
   command: {
     "TESTCOMMAND": {
         notificationExec: {
         payload: (params) => {
                return {
                        message: "boss this is a test",  //this is what i want assistant say..
			timer: 5000,
                        }
                     }
                }
        },
    },
}
exports.recipe = recipe // Don't remove this line.

**Comment by eouia** [comment]
with `transcriptionHooks` itself, you cannot do. Hooking is just hooking. It intercepts normal flow of Google Assistant then do something, so you cannot make it as a natural response of GA.
Two solutions;
- use additional Speech solution like TTS.
- make google common action for assistant or google custom action for device. Unfortunately, not so easy for non-experienced-developer.

**Comment by bugsounet** [comment]
or 3rd solution:
wait for version 3 of AMk2 (soon in january)
maybe we will develop this ...

**Comment by defiantlibra** [comment]
It would be great😍

**Comment by bugsounet** [comment]
V3 is coming very very soon !
Look the preview video in AMk2 home.
And you will show that feature !

**Comment by eouia** [comment]
Released.

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
