### ISSUE TITLE
Freezes when using

### ISSUE THREAD

**Issue by racezx812** [eouia/MMM-AssistantMk2#259]
Hi all,

my module keeps freezing everytime i use it with the hotword. 
most of the time it will not finish a sentence (the sound will start to break off) and the widget also freezes on screen. When i reload the magicmirror, answers from the previous questions sometimes plays even without doing anything.

below is the code im using for the magicmirror config

{
	module: "MMM-Hotword",
	position: "top_right",
	config: {
		chimeOnFinish: null,
		mic: {
			recordProgram: "arecord",
			device: "plughw:1"
		},
		models: [
			{
				hotwords    : "smart_mirror",
				file        : "smart_mirror.umdl",
				sensitivity : "0.5",
			},
		],
		commands: {
			"smart_mirror": {
				notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
					}
				},
				restart:false,
				afterRecordLimit:0
			}
		}
	}
},
{
	module: "MMM-AssistantMk2",
	position: "top_right",
	config: {
		deviceLocation: {
			coordinates: {
				latitude: 37.5650168, // -90.0 - +90.0
				longitude: 126.8491231, // -180.0 - +180.0
			},
		},
		record: {
			recordProgram : "arecord",  
			device        : "plughw:1",
		},
		notifications: {
			ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
			ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
		},
		useWelcomeMessage: "brief today",
		profiles: {
			"default" : {
				lang: "en-US"
			}
		},
	}
},

**Comment by eouia** [comment]
first, remove `useWelcomeMessage`. And show me the logs.

**Comment by racezx812** [comment]
thanks for quick response!

I have attached the log file, not sure if its the correct one or the one you are looking for.
it had logs highlighted in red that was related to MMM-AssistantMk2.

thanks again!

[localhost-1578236987779.log](https://github.com/eouia/MMM-AssistantMk2/files/4023517/localhost-1578236987779.log)

**Comment by eouia** [comment]
After removing `useWelcomeMessage`, still have the issue?

**Comment by racezx812** [comment]
yes after removing `useWelcomeMessage` it still freezes after a few seconds.

**Comment by eouia** [comment]
Hmmm. for the exact inspection;
- Backup your current config.js then remove all modules from config.js except `clock` and `MMM-Hotwords`.
- Then execute again, then show me log about it.

**Comment by racezx812** [comment]
attaching clock & hotword log as well as hotword & assistant log.

[clock&hotword.log](https://github.com/eouia/MMM-AssistantMk2/files/4023572/clock.hotword.log)

[hotword&assistant.log](https://github.com/eouia/MMM-AssistantMk2/files/4023577/hotword.assistant.log)

**Comment by eouia** [comment]
Hotword seems working in the first log.

Your second log is somewhat short. Anyway, AMK2 looks like receiving the trigger from Hotword and at least success to enter `onActivate` status.

It means, your previous error might come from other reason. - error of other module could prevent or interrupt these both module.

**Comment by racezx812** [comment]
yeah the second log is short since i removed the clock from the config.
Even after removing all the modules except for hotword & AMK2, the problem still persist. 

i will try a fresh install of everything and see if the problem still exists.
thanks for your help dude!

**Comment by eouia** [comment]
Wait a sec before reinstall.
First, I should know the problem itself. your description is not so enough.

If you are using `pm2`, stop `pm2` first. then run `npm start dev` in your MM directory.
It will show the backside-log on terminal at real time.

**Comment by racezx812** [comment]
sure, i ll provide whatever info you need.

Im not using pm2. The logs i sent are from realtime backside-logs.
In the previous "hotword&assistant.log" - the log ends when the module freezed (as soon as i finished asking the question)

**Comment by eouia** [comment]
Frankly, that was logged on backend-side but not about backend. It was about frontend.   Try `npm start dev`. It will show the different log what I need.

**Comment by racezx812** [comment]
may i check if these are the logs you are looking for (from dev tools console which i saved as log files previously to send to you), if not, where do i find the backend logs?

<img width="880" alt="1" src="https://user-images.githubusercontent.com/59534186/71783237-c9bd4d00-301e-11ea-994e-4f20020e6aa6.png">

<img width="872" alt="2" src="https://user-images.githubusercontent.com/59534186/71783270-43553b00-301f-11ea-90aa-56c6be89a7a3.png">

**Comment by eouia** [comment]
no, this is front-end log. 
You can see back-end log at realtime on your terminal shell, (Ctrl+Tab to change window focusing)

**Comment by racezx812** [comment]
apologies, did not know about that.
please see below log from backend.

[new.log](https://github.com/eouia/MMM-AssistantMk2/files/4023704/new.log)

**Comment by eouia** [comment]
Hmmm. seems some suspicious things;
1. I don't know why, but your MMM-AssistantMk2 seems instance duplicated or executed twice. 
```
[00:43:00.575] [LOG]    [AMK2] Recipe is loaded: hide_and_show_all_modules.js
[00:43:00.586] [LOG]    [AMK2] Recipe is loaded: reboot.js
[00:43:00.594] [LOG]    [AMK2] Recipe is loaded: screen_onoff.js
[00:43:00.602] [LOG]    [AMK2] Recipe is loaded: shutdown.js
[00:43:00.684] [LOG]    [AMK2] Temporal storage directory is clearing.
...
[00:47:41.859] [LOG]    [AMK2] Recipe is loaded: hide_and_show_all_modules.js
[00:47:41.893] [LOG]    [AMK2] Recipe is loaded: reboot.js
[00:47:41.912] [LOG]    [AMK2] Recipe is loaded: screen_onoff.js
[00:47:41.919] [LOG]    [AMK2] Recipe is loaded: shutdown.js
[00:47:41.995] [LOG]    [AMK2] Temporal storage directory is clearing.
```

2. It makes your recording device working false. That would be main reason of your issue.

Hmmm. very weird symptom. At this moment, I cannot guess what makes this happened. Hmmm.

**Comment by racezx812** [comment]
sorry, that would be because i reloaded MM because AMK2 froze even before i said the hotword.

uploading a fresh log file (this log file contains from "npm start" until AMK2 froze after asking the first question) 
[new2.log](https://github.com/eouia/MMM-AssistantMk2/files/4023715/new2.log)

**Comment by eouia** [comment]
Ok. 
```
[AMK2] Recorder Error: arecord has exited with error code 1.
```
This would be the reason. But still, I cannot guess what happens. What kind of mic are you using?

**Comment by racezx812** [comment]
i see, im using a usb mic (the type that are made for raspberrypi).
just tried using a usb PnP mic, still the same problem persist.

**Comment by bugsounet** [comment]
Hi,

i see this in your log files:

[00:47:50.215] [LOG]    [HOTWORD] begins.
[00:47:50.219] [LOG]    [HOTWORD] Detector starts listening.
[00:47:50.396] [LOG]    [HOTWORD] Final Result: { detected: false }
[00:47:50.444] [LOG]    [HOTWORD] begins.
[00:47:50.449] [LOG]    [HOTWORD] Detector starts listening.
[00:47:50.557] [LOG]    [HOTWORD] Final Result: { detected: false }
[00:47:50.586] [LOG]    [HOTWORD] begins.
[00:47:50.591] [LOG]    [HOTWORD] Detector starts listening.
[00:47:50.730] [LOG]    [HOTWORD] Final Result: { detected: false }
[00:47:50.767] [LOG]    [HOTWORD] begins.
[00:47:50.775] [LOG]    [HOTWORD] Detector starts listening.
[00:47:50.889] [LOG]    [HOTWORD] Final Result: { detected: false }
[00:47:50.928] [LOG]    [HOTWORD] begins.
[00:47:50.930] [LOG]    [HOTWORD] Detector starts listening.
...
it means that your microphone configuration on Hotword is not correct
this explains why it freeze (loop on the microphone)

verify your mic configuration with `arecord -l` command
and correct your hotword configuration

**Comment by racezx812** [comment]
Thanks @bugsounet ! i managed to fix the whole issue by installing a fresh copy of raspbian. 
All is good now. 

Except, i tried changing the hotword to "Jarvis" but failed. As far as i know i just need to change the MM config to jarvis as below yea?

```{
	module: "MMM-Hotword",
	position: "top_right",
	config: {
		chimeOnFinish: null,
		mic: {
			recordProgram: "arecord",
			device: "plughw:1"
		},
		models: [
			{
				hotwords    : "jarvis",
				file        : "jarvis.umdl",
				sensitivity : "0.5",
			},
		],
		commands: {
			"jarvis": {
				notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
					}
				},
				restart:false,
				afterRecordLimit:0
			}
		}
	}
},```

thanks in advance!

**Comment by bugsounet** [comment]
in models section, try this :
```
  models: [
    {
      hotwords : ["jarvis","jarvis"],
      file : "jarvis.umdl",
      sensitivity : "0.7,0.7",
    },
  ],
```

**Comment by eouia** [comment]
AMK2 is now updated to v3. So this question is no more sense. I'll close this.
