### ISSUE TITLE
No respond 

### ISSUE THREAD

**Issue by VH-Tech** [eouia/MMM-AssistantMk2#26]
Hi,
A few days back I noticed your amazing module and was thrilled by it's amazing potential and thought of giving it a try.
I successfully setted up the hotword module and assistantmk2 module 
I also am able to run the MagicMirror software without any errors.
but, after the hortword is detected nothing happens. here are my logs:

npm start MagicMirror

> magicmirror@2.4.1 start /home/pi/MagicMirror
> sh run-start.sh "MagicMirror"

Starting MagicMirror: v2.4.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
No helper found for module: compliments.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-Hotword
MMM-Hotword started
Connecting socket for: MMM-AssistantMk2
MMM-AssistantMk2 started
Connecting socket for: updatenotification
Sockets connected & modules started ...
Launching application.
[HOTWORD] begins listening.
[HOTWORD] <<  jarvis  >> is detected.

And after that nothing happens 

I am using everything with default configuration only.

**Comment by cojovi** [comment]
im having the same problem as @VH-Tech .  
@eouia  can you go into a little more detail on what you mean?

thanks

**Comment by VH-Tech** [comment]
Sorry my bad .
I forgot to add MMM-NotificationTrigger module.
