### ISSUE TITLE
YouTube video unavailable

### ISSUE THREAD

**Issue by PiggiCZ** [eouia/MMM-AssistantMk2#260]
Hi,

Yesterday everything was working all right. Youtube video would start normally, but today when I ask for something to play for me I get the error **video unavailable!** I know there is an issue with some videos won't play outside the web browser. But that's not my problem I cannot play any video. Tried like 20 songs and still nothing. Maybe I'm just unlucky. Will try some more but if you have any idea why it is not playing please tell me.

Thanks

**Comment by PiggiCZ** [comment]
I thought about updating MMM-AsistantMk2 can this be an issue?

**Comment by PiggiCZ** [comment]
It also seems like it wants to start but then it will not. The loading circle starts to spin but then error pops

**Comment by eouia** [comment]
AMK2 is updated now, so native Youtube player feature is dropped.
