### ISSUE TITLE
Black screen after git pull

### ISSUE THREAD

**Issue by PiggiCZ** [eouia/MMM-AssistantMk2#262]
Hello,

I did git pull to update Mk2 but now I have black screen when trying to start my MagicMirror, I have confirmed that MMM-AssistantMk2 is causing the trouble. Someone with same issue? 

Thanks

**Comment by PiggiCZ** [comment]
![image](https://user-images.githubusercontent.com/31881825/72218294-ecc59080-3539-11ea-9c65-3b064b6100ed.png)

My config.js file where I added recipes

**Comment by PiggiCZ** [comment]
Pff, im stupid.. Did not put the recipes in config: { }.

**Comment by bugsounet** [comment]
hi, we updated to v3.0.0.
configuration file is not the same as v2.X

Readme tel you to do this :

## Update from 2.x
Not easy. Remove existence then reinstall fresh.
- You'd better backup your `credentials.json` and profiles.

## Installation & Guides
Read the docs in [wiki](https://github.com/eouia/MMM-AssistantMk2/wiki)

please do a fresh install with fresh config files and we help you ;)
@bugsounet

**Comment by PiggiCZ** [comment]
Ok, so far did:
sudo rm -rf MMM-AssistantMk2

Installed newly by these commands:
git clone https://github.com/eouia/MMM-AssistantMk2
cd MMM-AssistantMk2
npm install

now waiting for it to finish

**Comment by PiggiCZ** [comment]
grpc@1.23.4 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.23.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by PiggiCZ** [comment]
So installation wasn't a success

**Comment by bugsounet** [comment]
ok try this : 
`npm install grpc@1.23.4`

Give me backlog end after this command
what is your platform ?

**Comment by PiggiCZ** [comment]
My platform is Raspberry PI 3B+,
Thank you for helping, but I'll leave my version on 2.x cause I have this as a project for my school and I need it to be working till friday, after I have presented my project I will upgrade. 

But I have another question for you. Does MMM-Youtube work on version 2.X? Cause there was a native Youtube player included in MMM-AssistantMk2, but that doesn't work anymore cause of the update. So I'm trying to install module MMM-Youtube but can't get it working, have my recipes in the config file and MMM-Youtube module.

MMM-Youtube setup:

![image](https://user-images.githubusercontent.com/31881825/72224035-113f5e00-3576-11ea-9e15-6fb347c6d031.png)

MMM-AsistantMk2 setup:
![image](https://user-images.githubusercontent.com/31881825/72224042-2b793c00-3576-11ea-97e3-4d4596a32e05.png)

**Comment by bugsounet** [comment]
sorry, i'm developer of v3.x,
I don't known about v2.x code and i'm not sure @eouia will support again v2.x isssue

**Comment by PiggiCZ** [comment]
Ok, never mind. I'm going to make another issue next week with the npm install grpc@1.23.4 and will try updating to version 3.x.

Thank you very much,
Closing this issue.
