### ISSUE TITLE
screenon screenoff script

### ISSUE THREAD

**Issue by bigjojo** [eouia/MMM-AssistantMk2#263]
hello, there is no more script folder for screenon screenoff reboot etc ...
are they placed in another folder?
how to launch youtube video?

I find this version well accomplished.
thank you

**Comment by bugsounet** [comment]
hi, we just forgot to write it
I will do this soon !

For youtube, MMM-Youtube is needed and add with-MMM-Youtube.js recipe

if you have probleme, we can help you

@bugsounet

**Comment by bigjojo** [comment]
ok thanks for your responce.
post clotured.

**Comment by bugsounet** [comment]
hi, 

* This is reboot, restart, shutdown vocal script

```js
/**   Reboot, Restart, Shutdown, Screen  **/
/**   Vocal commands script              **/
/**   set pattern in your language       **/
/**   @bugsounet                         **/

var recipe = {
  transcriptionHooks: {
    "AMK2_REBOOT": {
      pattern: "reboot please",
      command: "AMK2_REBOOT"
    },
    "AMK2_RESTART": {
      pattern: "restart please",
      command: "AMK2_RESTART"
    },
    "AMK2_REBOOT": {
      pattern: "shutdown please",
      command: "AMK2_SHUTDOWN"
    },
  },
  
  commands: {
    "AMK2_REBOOT": {
      soundExec: {
        chime: "close",
      },
      shellExec: {
        exec: "sudo reboot now"
      } 
    },
    "AMK2_RESTART": {
      soundExec: {
        chime: "close",
      },
      shellExec: {
        exec: "pm2 restart 0"
      } 
    },
    "AMK2_SHUTDOWN": {
      soundExec: {
        chime: "close",
      },
      shellExec: {
        exec: "sudo shutdown now"
      }, 
    },
  }
  
}

exports.recipe = recipe // Don't remove this line.
```
modify pattern to your language and save this file to recipes directory as `Reboot-Restart-Shutdown.js"

of course add it in recipes AMk2 recipes config array

* If you want automatic turn ON/OFF screen, you can use [MMM-NewPIR](https://github.com/bugsounet/MMM-NewPIR) module with recipe `with-MMM-NewPIR.js`
Don't worry if you don't use PIR sensor, just set `useSensor: false,`
that will make : simply turn on screen when assistant activate and turn off after delay time (hide module and screen sleep)

@bugsounet

**Comment by bigjojo** [comment]
hi,
ok thanks.
is there a way to mute the sound when the keyword is captured so as not to have disturbance during a video or music to launch a pause or stop command.

**Comment by bugsounet** [comment]
@bigjojo 
[with-MMM-Youtube.js](https://github.com/eouia/MMM-AssistantMk2/blob/master/recipes/with-MMM-Youtube.js) was updated
[Reboot-Restart-Shutdown.js](https://github.com/eouia/MMM-AssistantMk2/blob/master/recipes/Reboot-Restart-Shutdown.js) is now added in recipes directory
[Wiki prepared recipes](https://github.com/eouia/MMM-AssistantMk2/wiki/Prepared-recipes) was updated too :)

try it by update AMk2
