### ISSUE TITLE
MMM-AssistantMk2 실행 문의

### ISSUE THREAD

**Issue by lee-B-H** [eouia/MMM-AssistantMk2#264]
유튜브에서 댓글 남긴 초심자입니다
구글에 나온 방법 대로 매직 미러 설치 및 모듈 설치를 진행을 했습니다
핫 워드 설치 후 구글 어시스턴트 모듈 설치(최신버전
) 후 매직 미러를 실행을 했는데 
핫 워드 아이콘만 깜박깜박 거리고 구글 어시스턴트 이미지? 같은 건 표시가 안되어서 잘못 설치한건지  문의 드립니다.
![KakaoTalk_20200116_010302282_02](https://user-images.githubusercontent.com/59602676/72449579-4361f180-37fc-11ea-9a18-18a9ddacdfa1.jpg)
![KakaoTalk_20200116_010302282_01](https://user-images.githubusercontent.com/59602676/72449585-452bb500-37fc-11ea-961d-a993a05d2c7a.jpg)

config.js를 다음 과 같이 작성을 하였습니다
		{
		module: "MMM-Hotword",
		position: "top_right",
		config: {
			chimeOnFinish: null,
			mic: {
				recordProgram: "arecord",
				device: "plughw:1"
			},
			models: [
				{
					hotwords    : "smart_mirror",
					file        : "smart_mirror.umdl",
					sensitivity : "0.5",
				},
			],
			commands: {
				"smart_mirror": {
					notificationExec: {
						notification: "ASSISTANT_ACTIVATE",
						payload: (detected, afterRecord) => {
							return {profile:"default"}
						}
					},
					restart:false,
					afterRecordLimit:0
				}
			}
		}
	},
	{
		module: "MMM-AssistantMk2",
		position: "top_right",
		config: {
			deviceLocation: {
				coordinates: {
					latitude: 37.5650168, // -90.0 - +90.0
					longitude: 126.8491231, // -180.0 - +180.0
				},
			},
			record: {
				recordProgram : "arecord",  
				device        : "plughw:1",
			},
			notifications: {
				ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
				ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
			},
			useWelcomeMessage: "brief today",
			profiles: {
				"default" : {
					lang: "ko-KR"
				}
			},
		}
	},

**Comment by eouia** [comment]
MMM-Hotword와 MMM-AssistantMk2 모두 바로 며칠 전에 업데이트 되어서,  최근 새로 설치하셨다면 기존 config으로는 작동하지 않습니다. 각 github 저장소의 문서들을 참조하셔서 새로 config 해주세요.
