### ISSUE TITLE
Youtube Recipe, Play Youtube playlists?

### ISSUE THREAD

**Issue by Steierer420** [eouia/MMM-AssistantMk2#266]
Hello Community :),

I Actually wanted to improve the Youtube recipe to be able to play playlists with the voice command. I actually already tried to Regex the Playlist links of YouTube and write a command line, but it's not working. I hope to get some help :) 

my Recipe atm:
```
var recipe = {
  responseHooks: {
    "FOUND_YOUTUBE": {
      where: "links",
      pattern: "https:\/\/m\.youtube\.com\/watch\\?v=(.+)$",
      command: "PLAY_YOUTUBE"
    },
    "FOUND_PlAYLIST": {
      where: "links",
      pattern: "https:\/\/m\.youtube\.com\/watch\\?list=(.+)$",
      command: "PLAY_PLAYLIST"
    }
  },
  commands: {
    "PLAY_YOUTUBE": {
      moduleExec:{
        module: "MMM-AssistantMk2",
        exec: (module, param, from)=>{
          module.sendNotification("YOUTUBE_LOAD", {type:"id", id:param[1]})
        }
      }
    },
    "PLAY_PLAYLIST": {
      moduleExec:{
        module: "MMM-AssistantMk2",
        exec: (module, param, from)=>{
          module.sendNotification("YOUTUBE_LOAD", {type:"playlist", listType: "playlist", id:param[1]})
        }
      }
    },
    "YOUTUBE_STOPPED": {
      moduleExec: {
        module: "MMM-AssistantMk2",
        exec: (module, param, from)=>{
          if (param.notification == "ENDED" && param.sender.name == "MMM-YouTube")
          console.log(param)
          // What to do? when video is ended???
        }
      }
    }
  },
  plugins: {
    //onBeforeNotificationReceived: "YOUTUBE_STOPPED"
  }
}

exports.recipe = recipe // Don't remove this line.

```

As you can see, my new response hook is FOUND_PLAYLIST and the command is PLAY_PLAYLIST but somehow it doesnt send notifications… maybe my pattern is wrong?

All regards, Steirer

**Comment by eouia** [comment]
Which phrase did you use for getting `playlist` as a response? I'll try to represent your case.

**Comment by Steierer420** [comment]
Like I say: Smart Mirror Youtube Playlist Billie ellish, then the Google Assistant response with a playlist link

**Comment by eouia** [comment]
Ok, I'll inspect it. But I have to something to do on my real life before this, wait a few hours. :)

**Comment by Steierer420** [comment]
ok Thanks for the fast response, I just need it till sunday, I have a school project ^^

**Comment by eouia** [comment]
I think I've found.

Your pattern was;
```
pattern: "https:\/\/m\.youtube\.com\/watch\\?list=(.+)$",
```

But the response was, 
```
links: [ 'https://m.youtube.com/playlist?list=PLWS9OqWtihkl9Fqi32EINMk85HnnkWX8K' ],
```

So, your pattern should be like;
```
pattern: "https:\/\/m\.youtube\.com\/playlist\\?list=(.+)$",
```

**Comment by bugsounet** [comment]
I will upgrade YouTube recipe file soon with your feature and more

Added : 
* stop video command (personlized vocal command)
* volume control on assistant activate
* volume turn back on finish
* search playlist

**Comment by bugsounet** [comment]
@Steierer420 

[with-MMM-Youtube.js](https://github.com/eouia/MMM-AssistantMk2/blob/master/recipes/with-MMM-Youtube.js) was updated
see wiki [prepared recipes](https://github.com/eouia/MMM-AssistantMk2/wiki/Prepared-recipes)

try to update AMk2 to use it !
