### ISSUE TITLE
MMM-AssistantMk2관련 문의 드립니다

### ISSUE THREAD

**Issue by lee-B-H** [eouia/MMM-AssistantMk2#268]
안녕하세요 
몇일 전에 관련 문의 드렸던 초심자입니다
말씀해주신데로 문서를 참고하여 config를 작성을 하였습니다.
매직 미러 상태에서 구글 어시스턴트를 실행하면 클라이언트 인증과 구글키를 안내 해주는 웹브라우저가 열려서 문의드립니다
![er4](https://user-images.githubusercontent.com/59602676/72715261-7cf77b80-3bb3-11ea-9286-1a569e10854f.PNG)
![er1](https://user-images.githubusercontent.com/59602676/72716151-196e4d80-3bb5-11ea-9e95-b51bcf8d739b.jpg)
![er2](https://user-images.githubusercontent.com/59602676/72715084-2e49e180-3bb3-11ea-892a-f771ac63ef51.PNG)
![er3](https://user-images.githubusercontent.com/59602676/72715091-2f7b0e80-3bb3-11ea-92c6-f17540463031.PNG)

작성한 config은 다음과 같습니다
			{
			module: "MMM-AssistantMk2",
			position: "top_left",
			config: {
				ui: "Fullscreen", // or "Classic", "Classic2"
				debug: true,
				assistantConfig: {
					latitude: 51.508530,
					longitude: -0.076132,
					},
		responseConfig: {
		useScreenOutput: true,
		useAudioOutput: true,
		useChime: true,
		timer: 5000,
		myMagicWord: false
		},
		micConfig: { // put there configuration generated by auto-installer
		recorder: "arecord",
		device: "plughw:1",
		},
		customActionConfig: {
		autoMakeAction: false,
		autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
		actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
		},
		recipes: [ "with-MMM-Hotword.js"],
		profiles: {
		"default": {
		profileFile: "default.json",
		lang: "en-US"
		}
		},
		},
		},
		{
		module: "MMM-Hotword",
		position: "bottom_left",
		config: {
		useDisplay: false,
		chimeOnFinish: null,
		recipes: ["with-AMk2v3_smart-mirror.js"],
		mic: {
		recordProgram: "arecord",
		device: "plughw:1",
		},
		},
		},
로그는 다음과 같습니다
0|MagicMirror  | > magicmirror@2.10.1 start /home/pi/MagicMirror
0|MagicMirror  | > ./run-start.sh
0|MagicMirror  | [18:21:53.594] [LOG]    
0|MagicMirror  | Starting MagicMirror: v2.10.1
0|MagicMirror  | [18:21:53.619] [LOG]    
0|MagicMirror  | Loading config ...
0|MagicMirror  | [18:21:53.647] [LOG]    
0|MagicMirror  | Loading module helpers ...
0|MagicMirror  | [18:21:53.652] [LOG]    
0|MagicMirror  | No helper found for module: alert.
0|MagicMirror  | [18:21:53.654] [LOG]    No helper found for module: clock.
0|MagicMirror  | [18:21:54.925] [LOG]    
0|MagicMirror  | Initializing new module helper ...
0|MagicMirror  | [18:21:54.926] [LOG]    
0|MagicMirror  | Module helper loaded: calendar
0|MagicMirror  | [18:21:54.928] [LOG]    No helper found for module: currentweather.
0|MagicMirror  | [18:21:54.929] [LOG]    No helper found for module: weatherforecast.
0|MagicMirror  | [18:21:54.931] [LOG]    No helper found for module: MMM-AirQuality.
0|MagicMirror  | [18:21:54.932] [LOG]    No helper found for module: compliments.
0|MagicMirror  | [18:21:55.044] [LOG]    
0|MagicMirror  | Initializing new module helper ...
0|MagicMirror  | [18:21:55.045] [LOG]    Module helper loaded: newsfeed
0|MagicMirror  | [18:21:58.278] [LOG]    Initializing new module helper ...
0|MagicMirror  | [18:21:58.280] [LOG]    Module helper loaded: MMM-AssistantMk2
0|MagicMirror  | [18:21:58.800] [LOG]    
0|MagicMirror  | Initializing new module helper ...
0|MagicMirror  | [18:21:58.801] [LOG]    Module helper loaded: MMM-Hotword
0|MagicMirror  | [18:21:58.802] [LOG]    All module helpers loaded.
0|MagicMirror  | [18:21:58.805] [LOG]    
0|MagicMirror  | Starting server on port 8080 ... 
0|MagicMirror  | [18:21:58.837] [LOG]    
0|MagicMirror  | Server started ...
0|MagicMirror  | [18:21:58.839] [LOG]    Connecting socket for: calendar
0|MagicMirror  | [18:21:58.842] [LOG]    
0|MagicMirror  | Starting node helper for: calendar
0|MagicMirror  | [18:21:58.843] [LOG]    
0|MagicMirror  | Connecting socket for: newsfeed
0|MagicMirror  | [18:21:58.845] [LOG]    
0|MagicMirror  | Starting module: newsfeed
0|MagicMirror  | [18:21:58.847] [LOG]    
0|MagicMirror  | Connecting socket for: MMM-AssistantMk2
0|MagicMirror  | [18:21:58.849] [LOG]    Connecting socket for: MMM-Hotword
0|MagicMirror  | [18:21:58.851] [LOG]    [HOTWORD] MMM-Hotword starts
0|MagicMirror  | [18:21:58.852] [LOG]    Sockets connected & modules started ...
0|MagicMirror  | [18:21:59.320] [LOG]    
0|MagicMirror  | Launching application.
0|MagicMirror  | [18:22:03.040] [LOG]    
0|MagicMirror  | Create new calendar fetcher for url: https://calendar.google.com/calendar/ical/ko.south_korea%23holiday%40group.v.calendar.google.com/public/basic.ics - Interval: 300000
0|MagicMirror  | [18:22:03.161] [LOG]    
0|MagicMirror  | Create new news fetcher for url: http://fs.jtbc.joins.com/RSS/newsflash.xml - Interval: 300000
0|MagicMirror  | [18:22:03.274] [LOG]    
0|MagicMirror  | [HOTWORD] Recipe is loaded: with-AMk2v3_smart-mirror.js
0|MagicMirror  | [18:22:03.287] [LOG]    
0|MagicMirror  | [AMK2] MMM-AssistantMk2 Version: 3.0.0
0|MagicMirror  | [18:22:03.298] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-Hotword.js
0|MagicMirror  | [18:22:03.299] [LOG]    [AMK2] NO_ACTION_TO_MANAGE
0|MagicMirror  | [18:22:03.355] [LOG]    
0|MagicMirror  | [AMK2] AssistantMk2 v3 is initialized.
0|MagicMirror  | [18:22:03.398] [LOG]    
0|MagicMirror  | [AMK2] tmp directory is now cleaned.
0|MagicMirror  | [18:22:03.498] [LOG]    
0|MagicMirror  | [HOTWORD] begins.
0|MagicMirror  | [18:22:03.500] [LOG]    [HOTWORD] Detector starts listening.
0|MagicMirror  | [18:22:49.490] [LOG]    
0|MagicMirror  | [HOTWORD] Detected: SMARTMIRROR
0|MagicMirror  | [18:22:49.867] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:49.969] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:50.115] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:50.219] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:50.365] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:50.470] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:50.615] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:50.719] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:50.865] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:50.969] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:51.114] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:51.219] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:51.370] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:51.462] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:51.597] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:51.712] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:51.847] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:51.962] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording: 4000
0|MagicMirror  | [18:22:53.081] [LOG]    
0|MagicMirror  | [HOTWORD] stops.
0|MagicMirror  | [18:22:53.090] [LOG]    
0|MagicMirror  | [HOTWORD] After Recording finised. size: 72050
0|MagicMirror  | [18:22:53.109] [LOG]    
0|MagicMirror  | [HOTWORD:B2W] WAV_FILE_CREATED: /home/pi/MagicMirror/modules/MMM-Hotword/temp/afterRecording.wav 72050
0|MagicMirror  | [18:22:53.112] [LOG]    
0|MagicMirror  | [HOTWORD] Final Result: { detected: true,
0|MagicMirror  |   hotword: 'SMARTMIRROR',
0|MagicMirror  |   file: 'temp/afterRecording.wav' }
0|MagicMirror  | [18:22:53.504] [LOG]    
0|MagicMirror  | [AMK2] QUERY: { type: 'WAVEFILE',
0|MagicMirror  |   profile: { profileFile: 'default.json', lang: 'en-US' },
0|MagicMirror  |   key: 'modules/MMM-Hotword/temp/afterRecording.wav',
0|MagicMirror  |   lang: null,
0|MagicMirror  |   useScreenOutput: true,
0|MagicMirror  |   useAudioOutput: true,
0|MagicMirror  |   session: 1579512173150,
0|MagicMirror  |   status: 'standby',
0|MagicMirror  |   secretMode: false,
0|MagicMirror  |   sayMode: false }
0|MagicMirror  | [18:22:53.521] [LOG]    
0|MagicMirror  | Opening OAuth URL. Return here with your code.
0|MagicMirror  | Paste your code:

**Comment by eouia** [comment]
AMK2 설치시에 https://github.com/eouia/MMM-AssistantMk2/wiki/Google-Assistant-Setup 이 과정을 빼먹으신 거 같네요.

**Comment by lee-B-H** [comment]
> AMK2 설치시에 https://github.com/eouia/MMM-AssistantMk2/wiki/Google-Assistant-Setup 이 과정을 빼먹으 신 거 같다 네요.

말씀하신 과정을 설치 시 진행을 했는데 이런한 문제가 발생했는데 다시 설치해서 진행을 해야 하나요?

**Comment by lee-B-H** [comment]
> AMK2 설치시에 https://github.com/eouia/MMM-AssistantMk2/wiki/Google-Assistant-Setup 이 과정을 빼먹으 신 거 같다 네요.

말씀하신 과정을 설치 중에 진행을 하였는데 이러한 문제가 발생했는데요
다시 설치를 진행을 해주면 되는건가요?

**Comment by eouia** [comment]
어떤 config의 문제인지는 잘 모르겠고, 역시 해당 케이스의 로그가 필요합니다.

**Comment by lee-B-H** [comment]
죄송합니다 영어로 해보니 동작되었습니다
구글 어시스턴트를 호출하는 단어 "smart mirror "를 한국어로(예시- 거울아) 변경 하고 싶은데 어디서 변경을 해야되나요?

**Comment by eouia** [comment]
https://github.com/eouia/MMM-Hotword/blob/master/documents/trainer.md
