### ISSUE TITLE
Unable to locate package gcc-7

### ISSUE THREAD

**Issue by ethanpartida** [eouia/MMM-AssistantMk2#276]
I am attempting to install the new AssistantMk3 on raspbian. In the instructions wiki, there is a step in which you are supposed to install gcc-7. While attempting the I receive the error "E: Unable to locate package gcc-7".

Here is what displays before it
```
~/MagicMirror/modules/MMM-AssistantMk2 $ sudo apt-get install gcc-7
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package gcc-7
```

**Comment by bugsounet** [comment]
hi, can you tell me more please
what is your platform ?

**Comment by eouia** [comment]
Ususally, `E: Unable to locate package ..` happens when your apt repository is out-of-dated or closed temporally or permanently. 
- Check your network status
- Try again after a while.
- `sudo apt update` and `sudo apt upgrade` might be needed before.

**Comment by ethanpartida** [comment]
Thank you guys for the response. I am using a raspberry pi 3B+ and gcc (Raspbian 6.3.0-18+rpi1+deb9u1) 6.3.0 20170516. I did try apt-upgrade and update but still encountered the same errors. I continued along, following your wiki and I'm pretty sure electron rebuilt correctly with the gcc I currently have.

I was later following along with your wiki page "Google Assistant Setup" and encountered another error which might be due to my lack of experience but was hoping you'd be able to advise. I was able to successfully run the script, `node auth_and_test.js`,  but after logging into my google account received the error: 
> 
> Error: restricted_client
> 
> A native application: project-873486797821
> 
> You can email the developer of this application at: unconfiguredapp@google.com
> 
> This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console.

I am not quite sure on how to configure so that OAuth requests are allowed. Some things that I have noticed: 

- When originally going to create a project in the Actions Console, there was no default project type so I selected the "Device Registration" option.
- I found a tab in the Actions Console which deals with account linking and OAuth but it requires having a Authorization URL and Token URL. I am not sure what I would put here.

**Comment by eouia** [comment]
1. Go to `Google Cloud Platform` (https://console.cloud.google.com)
2. Select your project
3. In navigation menu (Upper-left corner), Go to `APIs & Services` > `Credentials`
4. You can see your `OAuth 2.0 Client IDs`, but I think it would be corrupted or be made wrongly.
5. So Make new one with `+ CREATE CREDENTIALS` menu (around top area of the page)
6. Select `OAuth client ID`
7. Select `Other` then give a name,  then it will make a new one.

You don't need consent screen unless you use privately.

**Comment by ethanpartida** [comment]
I was able to create new credentials, but am still quite confused on where to go from there.  These steps only gave me a new client id and secret, no json file. Looking at the json file that is given from device registration there seems to be much more fields than these two things. I attempted to reuse my old credentials.json but with a replaced id and secret but was met with the same errors. 

> Authorization Error
> Error 403: restricted_client
> This app is not yet configured to make OAuth requests. To do that, set up the app’s OAuth consent screen in the Google Cloud Console.
> Learn more
> Request Details
> access_type=offline
> response_type=code
> client_id=616420904943-kupkk6ri7463ftul91q9ep88m87p436k.apps.googleusercontent.com
> redirect_uri=urn:ietf:wg:oauth:2.0:oob
> display=page
> scope=https://www.googleapis.com/auth/assistant-sdk-prototype

**Comment by eouia** [comment]
You can download your json file with this icon. (I made 3 examples on screenshot.)

![image](https://user-images.githubusercontent.com/1720610/73243868-e9bcd800-41a8-11ea-8e0a-4892399436f6.png)

**Comment by ethanpartida** [comment]
I apologize for not responding for a while. I tried downloading the file as shown in your photo. I still received the same error. The contents of my config file was as follows:

> {"installed":{"client_id":"958911742149-i8686e8loqqso5rvu945oddjm65pstgl.apps.googleusercontent.com","project_id":"magic-mirror-try-3","auth_uri":"https://accounts.google.com/o/oauth2/auth","token_uri":"https://oauth2.googleapis.com/token","auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs","client_secret":"cW0pwoNoeLOXnD0RmxGb_J2l","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}}

I have also included a photo of my google cloud platform screen, circling the button I clicked.
![Pi](https://user-images.githubusercontent.com/42383664/73619514-5abe1e80-45f3-11ea-922b-b3d978d7ec3c.PNG)

**Comment by eouia** [comment]
Well, if so, your credential would be fine.
But at this moment, I have no idea why your authentification wouldn't work.
Usually, `OAuth Consent Screen` is not needed on developing stage. (And we will not release the project publicly, so OCS will not be needed.)
The only suspicious point is; Your project is on the verification stage, In that case, OCS would be needed to be verified, so your project could be restricted until it is completed.
I suggest you try to create a new project.

**Comment by ethanpartida** [comment]
Ok, I will try doing that and then get back to you on it. I have tried a couple projects and received this error. I might try using a different google account to make the project. Should the google account for MMM-Assistant be different from the one which created the project?

**Comment by eouia** [comment]
> Should the google account for MMM-Assistant be different from the one which created the project?

I don't know about that; It's better to delete the old unused projects and to create one.

**Comment by ethanpartida** [comment]
I just tried both deleting my previous projects and making one with an entirely different google account, I received the same error. Any ideas on how I could work around this? Is there a way I can manually get the OAuth code?

**Comment by eouia** [comment]
That is not related to oAuth itself. Your symptom just says a lack of OCS(OAuth consent screen).  OCS usually be needed when you release the project publicly, but before that, OCS is not required on the dev stage. So, Still, I think you've missed or failed something on your project setup, but I don't know what it is exactly. sorry.

**Comment by Anonym-tsk** [comment]
There is no `gcc-7` in Stretch repos. Update to Buster.

**Comment by bugsounet** [comment]
A step is missing in wiki.
I remember when a I install AMk2 for a friend ...
I will create a new google account and test wiki

I test and I come back

**Comment by bugsounet** [comment]
confirmed : 
Erreur d'autorisation
Erreur 403 : restricted_client

**Comment by bugsounet** [comment]
@ethanpartida :
can you try this : 

in console.cloud.google.com > APIs & Services > OAuth consent screen
check : 
User type : External 

in next screen : 
Support email > `your email account`
and save

**Comment by ethanpartida** [comment]
It worked! Thank you so much for your help!

**Comment by bugsounet** [comment]
we upgrade [wiki](https://github.com/eouia/MMM-AssistantMk2/wiki/Google-Assistant-Setup#oauth-consent-screen-setup) for other user

**Comment by JohnB7777** [comment]
Hello,

I wanted to update both MMM-AssistantMk2 and MMM-Hotword but I had a lot of problems, so I erase both modules to start fresh and now, unable to locate package gcc-7.
I have updated and upgraded my raspberry pi but the error still there and I don't know what to do.

Thanks !
