### ISSUE TITLE
Recipes doesn't work or load

### ISSUE THREAD

**Issue by pitchx** [eouia/MMM-AssistantMk2#277]
Since the update The transcritionhook doen't work , it seems that the recipes are not loaded , I've tried to put mistake in the recipes and I ve no error in result 

Here i sa part of the config.js 
`
{
    module: "MMM-Hotword",
    position: "bottom_left",
    config: {
      useDisplay: true,
      chimeOnFinish: null,
      recipes: ["with-AMk2v3_Jarvis.js"],
      mic: {
        recordProgram: "arecord",
        device: "plughw:1",
      },
    },
  },		
			
{
  module: "MMM-AssistantMk2",
  position: "top_left",
  config: {
    ui: "Fullscreen", // or "Classic", "Classic2"
    assistantConfig: {
      projectId: "", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
		latitude: 48.845722, // -90.0 - +90.0
		longitude: 2.384756, // -180.0 - +180.0
    },
    responseConfig: {
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: false
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1",
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "fr-FR", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    recipes: [ "recipe.template.js","with-MMM-Hotword.js", "with-MMM-TelegramBot.js","test.js","with-MMM-Youtube.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "fr-FR"
      }
    },
  },
},		`

and here is my recipe.template.js 
`var recipe = {
  transcriptionHooks: {
  "RADIO_ON": {
				pattern: "allume la radio",
				command: "RADION"
		  	},
			"RADIO_OFF": {
				pattern: "éteins la radio",
				command: "RADIOFF"
		  	},
				
			"STOP_PLAY": {
            pattern: "arrête la vidéo",
            command: "STOP_VID"
          },
			
			"STOP_PLAY2": {
            pattern: "arrête youtube",
            command: "STOP_VID"
			 },
			"SCREEN_ON": {
				pattern: "wake up",
				command: "SCREENON"
		  	},
			
		  "SCREEN_OFF": {
				pattern: "go to sleep",
				command: "SCREENOFF"
		  	},
			"SCREEN_OFF2": {
				pattern: "éteins le miroir",
				command: "SCREENOFF"
		  	},
			"SCREEN_ON2": {
            	pattern: "réveille-toi",
            	command: "SCREENON"
          	},
			"SCREEN_ON3": {
            	pattern: "allume le miroir",
            	command: "SCREENON"
          	},
          "SCREEN_OFF3": {
            	pattern: "va dormir",
            	command: "SCREENOFF"
          	},
		  "VOLUME_UP": {
            	pattern: "augmente le volume",
            	command: "CMD_VOLUME_UP"
          	},
          "VOLUME_DOWN": {
            	pattern: "baisse le volume",
            	command: "CMD_VOLUME_DOWN"
          	},
          "SET_VOLUME": {
            	pattern: ".*volume à ([0-9]{1,2}[0]?|100)",
            	command: "CMD_VOLUME_SET"
          	}  // Describe your transcriptionHook here.
  },
  actions: {
    // Describe your custom Action here.
  },
  commands: {
  "TIMER": {
            moduleExec: {
              module: ["MMM-AssistantMk2"],
              exec: (module, params, key) => {
                var delay = 0;
                if (params["unit"] == "HOUR") delay = params["delay"] * 3600000;
                if (params["unit"] == "MIN") delay = params["delay"] * 60000;
                if (params["unit"] == "SEC") delay = params["delay"] * 1000;
                setTimeout(() => {
                  module.sendNotification("SHOW_ALERT", {
                    message: "It's time you've set.",
                    timer: 3000
                  });
                }, delay);
              }
            }
          },

          "STOP_VID": {
            moduleExec: {
              module: ["MMM-AssistantMk2"],
              exec: (module, params, key) => {
                module.assistant.subdom.youtube.innerHTML = ""; 
                module.assistant.subdom.youtube.style.display = "none";
                module.youtubePlaying = false;
              }
            }
          },
			  "HIDEMODULES": {
				moduleExec: {
				  module:()=>{
					return []
				  },
				  exec: (module, params, key) => {
					module.hide(1000, null, {lockString:"AMK2"})
				  }
				}
			  },
			 "SHOWMODULES": {
				moduleExec: {
				  module:[],
				  exec: (module, params, key) => {
					module.show(1000, null, {lockString:"AMK2"})
				  }
				}
			  },
			 "SCREENON": {
				shellExec: {
				  exec: (params, key) => {
					return "~/MagicMirror/modules/MMM-AssistantMk2/scripts/screenon.sh"
					//return "ls -al"
				  },
				  options: (params, key)=> {
					return ""
				  },
				}
			  },
			 "SCREENOFF": {
				shellExec: {
				  exec: "~/MagicMirror/modules/MMM-AssistantMk2/scripts/screenoff.sh",
				  options: null,
				}
			  },
			 "REBOOT": {
				notificationExec: {
				  notification: "SHOW_ALERT",
				  payload: {
					message: "You've ordered REBOOT. I'm showing just alert, but you can modify config.js to reboot really.",
					timer: 5000,
				  }
				},
				/*
				shellExec: {
				  exec: "sudo reboot now"
				}
				*/
			  },
			 "SHUTDOWN": {
				notificationExec: {
				  notification: (params, key) => {
					return "SHOW_ALERT"
				  },
				  payload: (params, key)=> {
					return {
					  message: "You've ordered SHUTDOWN. I'm showing just alert, but you can modify config.js to reboot really.",
					  timer: 5000,
					}
				  }
				},
				/*
				shellExec: {
				  exec: "sudo shutdown now"
				}
				*/
			  },
			 "CMD_VOLUME_UP": {
					notificationExec: {
            			notification: "VOLUME_UP"
            		}
          		},
			 "CMD_VOLUME_DOWN": {
            		notificationExec: {
              			notification: "VOLUME_DOWN"
            		}
          		},
			 "CMD_VOLUME_SET": {
            		notificationExec: {
              			notification: "VOLUME_SET",
              			payload: (params, key) => {
                			console.log("@", params);
                			return params[1];
              			}
            		}
          		},
		 	 "RADION": {
				shellExec: {
				  exec: "mpc play 1",
				  options: null,
				}
			  },
			 "RADIOFF": {
				shellExec: {
				  exec: "mpc stop",
				  options: null,
				}  // Describe your command here.
  },
  plugins: {
    // Describe your plugin callback functions here.
    //
  },
}

exports.recipe = recipe // Don't remove this line.
`

**Comment by eouia** [comment]
- How do you know recipes are not loaded? What backend(serverside) log says about that?
- All the recipes don't work? Or only some recipe doesn't work?
- You've included several recipes. are those not conflicted with each other? (You show me only `recipe.template.js`)  Check each recipe one-by-one.

**Comment by pitchx** [comment]
Thks for your rapid reply
I thought it didn't load because when I added errors to the recipes I didn't get an error message. 
But I add the debug:true in the config.js and now I've the complete information to help find the mistake
`[15:59:29.847] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-Hotword.js
[15:59:29.854] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-TelegramBot.js
[15:59:29.859] [LOG]    [AMK2] RECIPE_ERROR (recipe.template.js): Unexpected identifier
[15:59:29.865] [LOG]    [AMK2] RECIPE_LOADED: with-MMM-Youtube.js
`
It was just an error of missing '}' 

So now the transcritpion hook works, sorry for the dumb issue

I need now to make work the youtube recipes besause now nothing happen

**Comment by bugsounet** [comment]
ok on va regardera a ça, je suis français.

**Comment by pitchx** [comment]
[French]
Ok merci a vous deux pour le boulot !!! avec la V3 fini la galère des dépendance GCC et autres 
Je debug de mon coté pour les problèmes que j'ai en cours 
- transcriptionHooks "éteins la radio" fonctionne mais trigger aussi https://m.youtube.com/watch?v=OsakvGfOJAQ)\n---\nArtiste : Freaks Association Bremen.\\nAlbum : Eteins ta radio.\\nDate de sortie : 2012.'
- Pouvoir écouter les radios , pour le moment j'ai un contournement avec mpc play
- Afficher les résultats Youtube en V3

Ok thanks both of you for the job !!! with the V3, the issues of GCC and other depedencies are over !!! 
I'm debugging on my side for the problems I've got updating in V3. 
- TranscriptHooks "turn off the radio" works but also triggers https://m.youtube.com/watch?v=OsakvGfOJAQ)\n---\nArtist: Freaks Association Bremen.\nAlbum: "Turn off your radio." Release date: 2012.'
- To be able to listen to the radio, right now I use a workaround with mpc play.
- Show Youtube results in V3

**Comment by pitchx** [comment]
In the presentation video  the module MMM-youtube seems to be necessary but I'm dumb I don't find it. Is it MMM-YouTube-API ?

**Comment by bugsounet** [comment]
oui il est necessaire, desolé j'ai pas eu le temps de regarder a votre code hier soir, desolé.

[MMM-YouTube](https://github.com/eouia/MMM-YouTube)

**Comment by bugsounet** [comment]
je regarde a votre recipe :)

**Comment by bugsounet** [comment]
voila le code modifier que j'ai chargé:

```js
var recipe = {
  transcriptionHooks: {
    "RADIO_ON": {
      pattern: "allume la radio",
      command: "RADION"
    },
    "RADIO_OFF": {
      pattern: "éteins la radio",
      command: "RADIOFF"
    },
    "STOP_PLAY": {
      pattern: "arrête la vidéo",
      command: "STOP_VID"
    },
    "STOP_PLAY2": {
      pattern: "arrête youtube",
      command: "STOP_VID"
    },
    "SCREEN_ON": {
      pattern: "wake up",
      command: "SCREENON"
    },
    "SCREEN_OFF": {
      pattern: "go to sleep",
      command: "SCREENOFF"
    },
    "SCREEN_OFF2": {
      pattern: "éteins le miroir",
      command: "SCREENOFF"
    },
    "SCREEN_ON2": {
      pattern: "réveille-toi",
      command: "SCREENON"
    },
    "SCREEN_ON3": {
      pattern: "allume le miroir",
      command: "SCREENON"
    },
    "SCREEN_OFF3": {
      pattern: "va dormir",
      command: "SCREENOFF"
    },
    "VOLUME_UP": {
      pattern: "augmente le volume",
      command: "CMD_VOLUME_UP"
    },
    "VOLUME_DOWN": {
      pattern: "baisse le volume",
      command: "CMD_VOLUME_DOWN"
    },
    "SET_VOLUME": {
      pattern: ".*volume à ([0-9]{1,2}[0]?|100)",
      command: "CMD_VOLUME_SET"
    }
  },
  commands: {
    "TIMER": {
      moduleExec: {
        module: ["MMM-AssistantMk2"],
        exec: (module, params, key) => {
          var delay = 0;
          if (params["unit"] == "HOUR") delay = params["delay"] * 3600000;
          if (params["unit"] == "MIN") delay = params["delay"] * 60000;
          if (params["unit"] == "SEC") delay = params["delay"] * 1000;
          setTimeout(() => {
            module.sendNotification("SHOW_ALERT", {
              message: "It's time you've set.",
              timer: 3000
            });
          }, delay);
        }
      }
    },
    "STOP_VID": {
      moduleExec: {
        module: ["MMM-AssistantMk2"],
        exec: (module, params, key) => {
          module.assistant.subdom.youtube.innerHTML = ""; 
          module.assistant.subdom.youtube.style.display = "none";
          module.youtubePlaying = false;
        }
      }
    },
    "HIDEMODULES": {
      moduleExec: {
        module:()=>{
          return []
        },
        exec: (module, params, key) => {
          module.hide(1000, null, {lockString:"AMK2"})
        }
      }
    },
    "SHOWMODULES": {
      moduleExec: {
        module:[],
        exec: (module, params, key) => {
          module.show(1000, null, {lockString:"AMK2"})
        }
      }
    },
    "SCREENON": {
      shellExec: {
        exec: (params, key) => {
          return "~/MagicMirror/modules/MMM-AssistantMk2/scripts/screenon.sh"
        },
        options: (params, key)=> {
          return ""
        },
      }
    },
    "SCREENOFF": {
      shellExec: {
        exec: "~/MagicMirror/modules/MMM-AssistantMk2/scripts/screenoff.sh",
        options: null,
      }
    },
    "REBOOT": {
      notificationExec: {
        notification: "SHOW_ALERT",
        payload: {
          message: "You've ordered REBOOT. I'm showing just alert, but you can modify config.js to reboot really.",
          timer: 5000,
        }
      },
    },
    "SHUTDOWN": {
      notificationExec: {
        notification: (params, key) => {
          return "SHOW_ALERT"
        },
        payload: (params, key)=> {
          return {
            message: "You've ordered SHUTDOWN. I'm showing just alert, but you can modify config.js to reboot really.",
            timer: 5000,
          }
        }
      },
    },
    "CMD_VOLUME_UP": {
      notificationExec: {
        notification: "VOLUME_UP"
      }
    },
    "CMD_VOLUME_DOWN": {
      notificationExec: {
        notification: "VOLUME_DOWN"
      }
    },
    "CMD_VOLUME_SET": {
      notificationExec: {
        notification: "VOLUME_SET",
        payload: (params, key) => {
          console.log("@", params);
          return params[1];
        }
      }
    },
    "RADION": {
      shellExec: {
        exec: "mpc play 1",
        options: null,
      }
    },
    "RADIOFF": {
      shellExec: {
        exec: "mpc stop",
        options: null,
      }
    }
  }
}

exports.recipe = recipe // Don't remove this line.
```

par contre une partie du code ne fonctionnera pas (SCREENON / SCREENOFF)
le script n'exite plus

**Comment by pitchx** [comment]
thks to you every thing is working fine now !!! 

Now I' ll trying to develop or to make develop a mdolue to display [Paris Big data events](https://opendata.paris.fr/explore/dataset/que-faire-a-paris-/api/?disjunctive.category&disjunctive.tags&disjunctive.address_zipcode&disjunctive.address_city&disjunctive.access_type&disjunctive.price_type) : 

[French]

Merci beaucoup. Des modules [Eoulia](https://github.com/eouia?tab=repositories) ne sont pas visibles  dans le le [third party MM](https://github.com/MichMich/MagicMirror/wiki/3rd-party-modules) c'est pour ça que je ne trouvais pas.

**Comment by bugsounet** [comment]
parfait, je ferme cette Issue et n'hesite pas a revenir vers moi (si tu veux parler en français) ou nous :)
