### ISSUE TITLE
업데이트 알람 없애는 방법 문의

### ISSUE THREAD

**Issue by hongsee4** [eouia/MMM-AssistantMk2#278]
![Screenshot_20200127-113610_VNC Viewer](https://user-images.githubusercontent.com/60207596/73147223-e0286700-40f9-11ea-8eea-213c6f0f3a48.jpg)
안녕하세요.
최근에 V3 버젼으로 설치했는데 업데이트하라고 나오는데 방법을 모르겠습니다.
삭제하고 다시 설치해야 되나요?
추가로 알람 안 뜨게 하는 방법도 문의드립니다.

**Comment by eouia** [comment]
삭제하고 다시 설치하는게 가장 깔끔하긴 하죠. 최근 설치하셨다면 `git pull` 만으로 업데이트 가능합니다.
저 안내메시지는 `updatenotification` 모듈 이용시 나오는 거라 해당 모듈을 config에서 빼시면 됩니다.
