### ISSUE TITLE
Assistant response - localization  (Fahrenheit/Celsius)

### ISSUE THREAD

**Issue by sergge1** [eouia/MMM-AssistantMk2#283]
I am using Amk2. 
Google Assistant provides response for my inquiries uses Fahrenheit temperature measurement system instead my local Celsius.

Could you please advice me whether this is google-assistant config somewhere while getting api credentials or this is some settings within Amk2 module so that it sends inquiry to the google cloud  together with loc setting?
In my config.js I have set longitude and latitude correctly. 
MM weather/weatherforecast modules display the temperature in Celsius.

**Comment by eouia** [comment]
You can setup your locale and metric on `Google Assistant App` of your smartphone.

**Comment by sergge1** [comment]
got it. thanx
