### ISSUE TITLE
MMM-AssistantMk2 인스턴트 실행시 입력이 되지 않습니다.

### ISSUE THREAD

**Issue by dkfj556** [eouia/MMM-AssistantMk2#285]
MMM-AssistantMk2 인스턴트 실행시 입력이 되지 않습니다. 
안녕하세요. 스마트미러를 만들고 있는데.. 문제가 있어서 도움을 요청하고자 작성하여 봅니다.
우선 나머지는 메뉴얼 대로 설치를 잘 진행하여서 스마트 미러 라고 부르면 반응 까지는 하는데... 어시스턴트에서 부터 입력이 되지 않습니다. 혹시 문제가 있는 부분 조언좀 부탁드립니다. 또한 node 버젼과 
npm버젼 을 최신으로 했는데.. 이것도 버젼을 맞추어야 되는 문제인가요??

**Comment by eouia** [comment]
정확히 어떤 증상인지 로그 등이 없으면 답해드릴 수 없네요
