### ISSUE TITLE
Animated icons and CPU usage

### ISSUE THREAD

**Issue by sergge1** [eouia/MMM-AssistantMk2#286]
first of all, thanks to all contributors to this module.
One idea/wish - It would be nice to have an option in config to enable/disable animated icons (just to save CPU usage for those, who do not need animation)

**Comment by Anonym-tsk** [comment]
I have this problem too. RPI 3, FKMS driver. As workaround, i set static icons in custom.css

**Comment by eouia** [comment]
You can change the icon with your owns.

**Comment by Anonym-tsk** [comment]
It's better to have option `useAnimatedIcons: true/false`

**Comment by bugsounet** [comment]
good idea :)

**Comment by sergge1** [comment]
@Anonym-tsk @bugsounet 
here is my test of useStaticIcons ( i see that the parameter is named by `useStaticIcons ` insted of mentioned above `useAnimatedIcons`)
Environment: 

- MM 2.10.1+AMk2 dev current + Hotword.
- MM config: added `useStaticIcons: true,`

Test results:
- static icon is loaded for a few seconds during the MM start. Later it disappears by changing to animated one.

Video: https://youtu.be/C53PpuNMM0E

**Comment by Anonym-tsk** [comment]
@sergge1 please provide your config

**Comment by Anonym-tsk** [comment]
@sergge1 You have to add `useStaticIcons: true` to `responseConfig` section, not to config root

**Comment by sergge1** [comment]
> please provide your config

<details><summary>My config is here:</summary>
<p>

```
{
  module: "MMM-AssistantMk2",
  position: "top_right",
  disabled: false,
  config: {
  useStaticIcons: true,
    debug: true,
    verbose: true,
    ui: "Classic", // or "Classic", "Classic2"
    assistantConfig: {
      projectId: "XX-XX", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: XX.XX,
      longitude: XX.XX,
    },
    responseConfig: {
      useHTML5: false,
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: false,
      delay: 0.5,
      playProgram: "mpg321"
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1"
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    recipes: ["with-MMM-Hotword.js", "with-MMM-Youtube.js", "with-MMM-NewPIR.js"],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
  },
},

**Comment by sergge1** [comment]
>  You have to add `useStaticIcons: true` to `responseConfig` section, not to config root
Ok, will test right now.

However this config record does not relate to response itself so I think it would be logically to move it to the general section of module config

**Comment by sergge1** [comment]
>  You have to add `useStaticIcons: true` to `responseConfig` section, not to config root
@Anonym-tsk @bugsounet 
test results:

- `useStaticIcons: true,` - WORKS, staticiconf for all states;
- `useStaticIcons: "standby",` - WORKS, static for standby state, animated foa all other states;
- `useStaticIcons: false,` - WORKS, animated icons for all states.
