### ISSUE TITLE
 useWelcomeMessage not working 

### ISSUE THREAD

**Issue by chanapai** [eouia/MMM-AssistantMk2#287]
I am a newbie in MM and raspberry pi. I have installed MM and config serval modules e.g. Hotword, AssistantMk2 and so on. Its work fine but only one thing that doesn't work is that useWelcomeMessage in MMM-AssistantMk2 module. 

it doesn't have any welcome sound when I run the MM.
 
This is my config.
Thank you in advance.

 {
                        module: "MMM-AssistantMk2",
                        position: "top_left",
                        config: {
                                ui: "Classic2", // or "Classic", "Classic2"
                                verbose: true,
                                useWelcomeMessage: "brief today",

                                assistantConfig: {
                                        latitude: 13.81003,
                                        longitude: 100.53714,
                                },
                                responseConfig: {
                                        useScreenOutput: true,
                                        useAudioOutput: true,
                                        useChime: true,
                                        timer: 5000,
                                        myMagicWord: false
                                },

                                micConfig: { // put there configuration generated by auto-installer
                                        recorder: "arecord",
                                        device: "plughw:1",
                                },
                                recipes: [ "with-MMM-Hotword.js", "with-MMM-TelegramBot.js" ],
                               notifications: {
                                        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
                                        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
                                },
                                profiles: {
                                        "default": {
                                                profileFile: "default.json",
                                                lang: "en-US"
                                        }
                                },
                        },
                },

LOG 

[LOG]    Starting MagicMirror: v2.10.1
[LOG]    Loading config ...
[LOG]    Loading module helpers ...
[LOG]    No helper found for module: alert.
[LOG]    Initializing new module helper ...
[LOG]    Module helper loaded: updatenotification
[LOG]    No helper found for module: clock.
[LOG]    Initializing new module helper ...
[LOG]    Module helper loaded: MMM-Hotword
[LOG]    Initializing new module helper ...
[LOG]    Module helper loaded: MMM-AssistantMk2
[LOG]    No helper found for module: compliments.
[LOG]    All module helpers loaded.
[LOG]    Starting server on port 8080 ... 
[LOG]    Server started ...
[LOG]    Connecting socket for: updatenotification
[LOG]    Connecting socket for: MMM-Hotword
 [LOG]    [HOTWORD] MMM-Hotword starts
[LOG]    Connecting socket for: MMM-AssistantMk2
 [LOG]    Sockets connected & modules started ...
[LOG]    Launching application.
[LOG]    [HOTWORD] begins.
[LOG]    [HOTWORD] Detector starts listening.

**Environment:**
 - Device : [e.g. RPI 4]
 - OS: [e.g. Raspbian Stretch]
 - MMM-AssistantMk2 3.0.2 (2020-01-23)

**Comment by bugsounet** [comment]
hi, in AMk2 v3.X, `useWelcomeMessage` don't exist.
that's why it don't works :)

**Comment by chanapai** [comment]
Oh.. ok Thank you.
