### ISSUE TITLE
Google_beep_open.mp3, Google_beep_close.mp3

### ISSUE THREAD

**Issue by sergge1** [eouia/MMM-AssistantMk2#289]
First of all, thanks to the developers/contributors of this module.

Just realized, that my mirror does not reproduce `Google_beep_open.mp3` and `Google_beep_close.mp3`. Here is the last video I have taken https://www.youtube.com/watch?v=ZFMzyf7GUSY
I hear only Hotword's beep.

Any ides about the reason?

<details><summary>My config is here:</summary>
<p>

```
{
  module: "MMM-AssistantMk2",
  position: "top_right",
  disabled: true,
  config: {
    debug: true,
    verbose: true,
    ui: "Classic", // or "Classic", "Classic2"
    assistantConfig: {
      projectId: "XX-XX", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: XX.XX,
      longitude: XX.XX,
    },
    responseConfig: {
      useHTML5: false,
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: false,
      delay: 0.5,
      playProgram: "mpg321"
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1"
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    recipes: ["with-MMM-Hotword.js", "with-MMM-Youtube.js", "with-MMM-NewPIR.js"],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
  },
},
```
</p></details>

**Comment by bugsounet** [comment]
it's only used in recipes chime for hook :)

**Comment by Anonym-tsk** [comment]
Try to update from `dev` branch

**Comment by sergge1** [comment]
@bugsounet could you please explain - I should not hear these sounds while using recipes? Am I right?
@Anonym-tsk  I am already with `dev` branch (yesterday one without your today's update of animated icon. Will try with today's update.

**Comment by bugsounet** [comment]
[read this](https://github.com/eouia/MMM-AssistantMk2/wiki/commands#commands) and [this](https://github.com/eouia/MMM-AssistantMk2/wiki/commands#soundexec-command)

**Comment by sergge1** [comment]
Got is. 
Sorry, did not seen it before. I am closing this question as solved..
