### ISSUE TITLE
No respond after pasting token

### ISSUE THREAD

**Issue by kievu** [eouia/MMM-AssistantMk2#29]
I have managed to install this module with no errors. I try to invoke the assistance with MMM-KeyBindings, but I believe it doesn't matter what I use. Because I managed to trigger notifications that MMM-AssistantMk2 can listen to. 

So from the KeyBindings, I trigger the notification `ASSISTANT_ACTIVATE` and MMM-AssistantMk2 respond with prompting login for `GoogleAssitance` when on success gives a token to paste into the terminal. (Is this flow correct that I would get this prompt everytime I start the module?

However, after entering the token. Nothing happens. Am I triggering the flow in the wrong order?

**Comment by kievu** [comment]
I assume that I have followed the steps for setting up auth and credentials, because if I run `node auth_and_test.js` I get prompted to enter request and the assistance do answer if I ask for the weather forecast.

And for `deviceModelId` and `deviceInstanceId`, do I need those even though I don't use MMM-GAction?

**Comment by eouia** [comment]
If you already execute auth_and_test.js, you might have `tokens.json`. You should copy and rename it into `profiles` directory. did you?
And at this moment, `deviceModelId` and `deviceInstanceId` are not needed normally.

**Comment by kievu** [comment]
I renamed it to `default.json` and moved it to `/profiles` yes

**Comment by eouia** [comment]
Well, The only thing I can figure is your `default.json`(token.json) is not match with the values of `config.js`. The auth process should be done once when you execute `auth_and_test.js` then the result, `tokens.json`(renamed as `default.json` or whatever else) should be used as the key of further auth process when you execute real Assistant. If you get the auth requesting page on the browser, It might mean your `tokens.json`(`default.json`) would not be proper.
Check you have multi-projects in your Google Console. Sometimes, somebody had made mistakes confusing several projects.

**Comment by kievu** [comment]
I deleted whole `MagicMirror` repo and installed `MMM-AssistantMk2` with the tutorial. It works now, so probably I did something wrong along the way.

Now my application runs, but when I press the mic-button and it gets white-highlighted. It crashes with `
assistant ready
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! magicmirror@2.5.0 start: `sh run-start.sh`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the magicmirror@2.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dashboard\AppData\Roaming\npm-cache\_logs\2018-10-08T11_38_05_998Z-debug.log
`

Is this something you are familiar with?

**Comment by eouia** [comment]
Ah. you are not running MM on RPI, on Windows machine? I have no experience about that. I made this for RPI or ATB or *nix machines.
Anyway,
`npm ERR! code ELIFECYCLE`
It's basically saying it fails to spawn your process not due to permission but to an error in scripts. I think there could be a missing dependencies for Windows environment.  Due to the dependencies on some audio stuff that only works on *nix. 
Sorry.
