### ISSUE TITLE
Touch no longer working to activate assistant

### ISSUE THREAD

**Issue by jmehd** [eouia/MMM-AssistantMk2#293]
The touch activation used to work prior to the V3 update. Now, when using Classic or Classic2 UI, touch no longer activates the assistant. Touch is very useful for me because my household is sometimes noisy and the hotword gets picked up randomly, even when using the noisy recipes. Will touch support be coming soon (I hope so!).

**Comment by bugsounet** [comment]
Hi,
We will try to implement this on Classic/Classic2 UI

**Comment by jmehd** [comment]
That would be great! Thank you!

**Comment by bugsounet** [comment]
i have code it on `Classic` and `Classic2` ui :)
now, please wait next change on master version.

**Comment by bugsounet** [comment]
merged to master, enjoy change :)
