### ISSUE TITLE
Set Sensitivity in new Version of MMM-AssistantMk2 and Hotword

### ISSUE THREAD

**Issue by IntelliBR** [eouia/MMM-AssistantMk2#294]
How to set Sensitivity in new version of MMM-Hotword module ?

 {
    module: "MMM-Hotword",
    position: "bottom_left",
    config: {
      useDisplay: true,
      chimeOnFinish: null,
      recipes: ["with-AMk2v3_smart-mirror.js"],
      mic: {
        recordProgram: "arecord",
        device: "plughw:1,0",
      },

    },
  },

**Comment by bugsounet** [comment]
you can see your configuration in this file : 
`~/MagicMirror/modules/MMM-Hotword/recipes/with-AMk2v3_smart-mirror.js`

**Comment by IntelliBR** [comment]
> you can see your configuration in this file :
> `~/MagicMirror/modules/MMM-Hotword/recipes/with-AMk2v3_smart-mirror.js`

Thanks! Solved...
