### ISSUE TITLE
It is not really a mistake

### ISSUE THREAD

**Issue by timur87** [eouia/MMM-AssistantMk2#3]
It is not really a mistake

I just can not get it to work

I have followed all the steps also see the speech icon on the magicmirror but when I say "ok google" nothing happens

can it be related to the fact that I have to run both input and output via usb?

I try it for a long time help would be really good for me

Thank you

**Comment by eouia** [comment]
As I've said, "ok google" is not "hotword". Instead you can use "smartmirror", "snowboy", "jarvis" as hotword.
MMM-Hotword is using `snowboy` as Hotword-detector, it provide 3 universal voice model(.umdl) - "smart mirror", "snowboy", "jarvis" and plus one additional "alexa". "ok google" is not included.
Google Assistant has it's own hotword-detector and it is not opened. so, we cannot get "ok google" model.
If you want to use "ok google" as hotword, you should make your own private voice model(.pmdl). See snowboy.kitt.ai

**Comment by timur87** [comment]
ok sorry did not quite understand
because I do not speak english but german and work with google translator

now I understand it but me

then I will create a new topic in hotword because there is a problem there as well
