### ISSUE TITLE
MMM-AssistantMK2 stops responding after first conversation completes

### ISSUE THREAD

**Issue by alamodein** [eouia/MMM-AssistantMk2#30]
Eouia first thanks very much for your great work!!! This is the best Google Assitant module that I have used till now
However I am stuck with one weird issue
I am sorry if my issue is addressed before, but I searched a lot before writing this.

After MagicMirror starts  MMM-AssistantMK2 works fine and respond to my question very well.  My question appears on screen also next to Mic Icon
However once the conversion is marked completed, it stops working . Even the microphone stop ( Can see by its activity LED), and the Next conversation never works

Nothing appear in Terminal window after Conversation completed'
If I restart mirror again, it works again for one more time

I am using RP13b+ with Raspbian Stretch with MagicMirror 2.5.0
My MMM-AssistantMK2 installation and electron rebuild was clean without any issues

Also please excuse me for my knowledge as I don't know how to change the hotword, it only detects Jarvis

Here is text from the Terminal window after which it stops
[HOTWORD] <<  jarvis  >> is detected.
[HOTWORD] stops listening
assistant ready
Transcription: how  --- Done: false
Transcription: how's  --- Done: false
Transcription: how's the  --- Done: false
Transcription: how's the weather  --- Done: false
Transcription: how's the weather in  --- Done: false
Transcription: how's the weather in  --- Done: false
Transcription: how's the weather in  --- Done: false
Transcription: how's the weather in my  --- Done: false
Transcription: how's the weather in bed  --- Done: false
Transcription: how's the weather in band  --- Done: false
Transcription: how's the weather in Banbury  --- Done: false
Transcription: how's the weather in Bangalore  --- Done: false
Transcription: how's the weather in Bangalore  --- Done: false
Transcription: how's the weather in Bangalore  --- Done: false
end-of-utterance
Transcription: how's the weather in Bangalore  --- Done: true
Device Action: { requestId: '5bc6f360-0000-21cc-971e-f4f5e8047e1c' }
Assistant Text Response: 
Conversation Completed

Thanks in advance!!!

**Comment by alamodein** [comment]
My Config.js

My config.js

              },
                //MMM-NotificationTrigger
                {
                        module: "MMM-NotificationTrigger",
                        config: {
                                triggers:[
										{
                                                trigger: "HOTWORD_DETECTED",
                                                fires: [
                                                        {
                                                                fire:"HOTWORD_PAUSE",
                                                        },
                                                        {
                                                                fire:"ASSISTANT_ACTIVATE",
                                                                delay: 200,
                                                                payload: function(payload) {
                                                                return {
                                                                        "profile": payload.hotword
                                                                }
                                                        }
                                                        },
                                                        ]
                                        },
                                        { 
                                        trigger: "ASSISTANT_DEACTIVATED",
                                        fires: [
                                                {
                                                        fire:"HOTWORD_RESUME"
                                                }
                                        ]
                                        },
                                ]
                        }
                },
                        //MMM-Hotword
                { //Using MMM-Hotword for Assistant wakeup.
                        module: "MMM-Hotword",
                        config: {} //using default configuration.
                },
                {
                        module: "MMM-AssistantMk2",
                        position: "top_left",
                        config: {}
				},

**Comment by eouia** [comment]
I suspect one point. You might have a front-end error after execution.
To check, stop your pm2 (`pm2 stop mm`), then run `npm start dev` in your MM directory.

It will open a developer panel on your MM front-end, and there you can see the front-end error messages (in `console` tab, and error would be shown upper-right area with red color)

**Comment by alamodein** [comment]
ok thanks I will give it a try

**Comment by alamodein** [comment]
Hi Eouia, I see error in Dev Console after the conversation is completed in terminal 
I am also attaching full logs if you want to have a look

BIG Thanks again!
[0.0.0.0-1538989954841.log](https://github.com/eouia/MMM-AssistantMk2/files/2455351/0.0.0.0-1538989954841.log)



MMM-AssistantMk2.js:290 Uncaught TypeError: console.log is not a function
    at Class.socketNotificationReceived (MMM-AssistantMk2.js:290)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:133)
    at r.onevent (socket.js:270)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)
    at r.onpacket (socket.js:228)
    at r.<anonymous> (index.js:21)
    at r.emit (index.js:133)
    at r.ondecoded (manager.js:345)
socketNotificationReceived @ MMM-AssistantMk2.js:290
(anonymous) @ module.js:246
(anonymous) @ socketclient.js:25
r.emit @ index.js:133
r.onevent @ socket.js:270
MMSocket.self.socket.onevent @ socketclient.js:19
r.onpacket @ socket.js:228
(anonymous) @ index.js:21
r.emit @ index.js:133
r.ondecoded @ manager.js:345
(anonymous) @ index.js:21
r.emit @ index.js:133
s.add @ index.js:241
r.ondata @ manager.js:335
(anonymous) @ index.js:21
r.emit @ index.js:133
r.onPacket @ socket.js:456
(anonymous) @ socket.js:273
r.emit @ index.js:133
r.onPacket @ transport.js:145
r.onData @ transport.js:137
ws.onmessage @ websocket.js:147

**Comment by eouia** [comment]
You might be using AlexaPi and MMM-AssistantMk2 together, but I think it could not be work well.
And you'd better to remove(disable) other modules for easier check confirmation except suspicious modules.(MMM-Hotword/MMM-AssistantMk2/MMM-NotificataionTrigger)

**Comment by alamodein** [comment]
Thank you very much for your help
AlexaPi service was already stopped. I suspected it too so I disabled it before I logged the issue.
However just the module entry in Config.js was not disabled, I disabled it, but still the issue was there.
So as you guided, I disabled all the modules in config.js and started enabling one at a time and testing AssistantMK2. It was due to MMM-GoogleMapsTraffic module , AssistantMK2 stopped responding.
Disabling MMM-GoogleMapsTraffic resolves the issue.
 I guess I am using API key from same Google Project used for AssistantMK2 for Maps which is causing the issue. I will troubleshoot it .

If you don't any thoughts to share on it, you could mark the issue as resolved or I can close the issue

However before closing I would request one last help from you on AssistantMK2 (actually two  👍 ) )
1. How to change the default Hotword from Jarvis to like 'OK Google' or something else?
2. How to change its location, when I ask weather it shows of London by default

THANKS again for your help and such a nice and best Assistan module you made. Cheers!!!

**Comment by eouia** [comment]
1. You should understand this, first. 
MMM-AssistantMk2 has no `HOTWORD` functionality as default. There could be many `activating methods`like vocal hotword, button, programmable conditions, other sensors, etc. So MMM-AssistantMk2 itself has no fixed activating method.
`MMM-Hotword` is the real awakener of MMM-AssistantMk2. It would listen and catch your voice and activate MMM-AssistantMk2.
Now, Let's see MMM-Hotword. This module could catch your voice with `snowboy` - Hotword detection engine. Unfortunately, the default universal voice models(`.umdl`) which could be caught by `snowboy` are somewhat limited. But you can make your personal voice model(`.pmdl`) by yourself in https://snowboy.kitt.ai See the website. After getting `.pmdl` you can put that file into `MMM-Hotword/resources/models` directory then modify your config.js.

2. Modify your configuration value `deviceLocation`.
```
deviceLocation: { // (OPTIONAL)
			coordinates: { // set the latitude and longitude of the device (rf. mygeoposition.com)
				latitude: 51.5033640, // -90.0 - +90.0
				longitude: -0.1276250, // -180.0 - +180.0
			},
		},
```

**Comment by alamodein** [comment]
Thanks, I am aware Snowboy has default  limited options. My question was  meant with MMM- Hotword only and  was assuming this module has more wakeword option by default.

Thank you very much for guiding baiut personal voice model can be made and about default location

I appreciate  you took time in replying to my issue for this awesome module
