### ISSUE TITLE
chime 추가 방법을 알고 싶습니다.

### ISSUE THREAD

**Issue by dark594** [eouia/MMM-AssistantMk2#301]
안녕하세요
chime을 추가하고 싶어서 문의 드립니다.
일단 제가 시도한 방법은 
1. 파파고에서 입력한 문자를 mp3로 다운받아서 resources 폴더에 Light_Indoor.mp3로 저장하였습니다. (저장방법은 https://dol2156.tistory.com/580 에 나와 있었습니다.)
2. config.js 에 아래와 같이 굵은 글자를 추가했습니다.
    	responseConfig: {
      		useHTML5: true, // sound render by HTML5
      		useScreenOutput: true,
      		useAudioOutput: true,
      		useChime: true,
      		timer: 5000,
      		myMagicWord: false,
  		playProgram: "mpg321", //needed if you don't use HTML5 sound render
      		chime: {
			**indooron:"Light_Indoor.mp3",**
        		beep: "beep.mp3",
        		error: "error.mp3",
        		continue: "continue.mp3",
        		open: "Google_beep_open.mp3",
        		close: "Google_beep_close.mp3",
      		},
 		useStaticIcons: false
	},    

3. 테스트를 위해 with-MMM-Youtube.js 에 굵은 글자로 표시된 부분을 변경하였습니다.
var recipe = {
  transcriptionHooks: {
    "STOP_YOUTUBE": {
      pattern: **"영상 정지"**,
      command: "STOP_YOUTUBE"
    }
  },
commands: {
    "STOP_YOUTUBE": {
      moduleExec: {
        module: "MMM-AssistantMk2",
        exec: (module, param, from) => {
          module.sendNotification("YOUTUBE_CONTROL", {command: "pauseVideo"})
        }
      },
      soundExec: {
        chime: **"indooron"**
      }
    },
}

4. 테스트를 해보니 음성이 나오지 않아서 mpg321 로 테스트를 하니 하기와 같이 나왔습니다.
    error.mp3와 Light_Indoor.mp3를 실행시켜서 나온 메세지입니다.
    두 개의 파일 모두 소리가 정상적으로 나왔습니다.

pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/resources $ mpg321 error.mp3
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layer 1, 2, and 3.
Version 0.3.2-1 (2012/03/25). Written and copyrights by Joe Drew,
now maintained by Nanakos Chrysostomos and others.
Uses code from various people. See 'README' for more!
THIS SOFTWARE COMES WITH ABSOLUTELY NO WARRANTY! USE AT YOUR OWN RISK!

Playing MPEG stream from error.mp3 ...
MPEG 1.0 layer III, 128 kbit/s, 44100 Hz stereo
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM front
                                                                            
[0:00] Decoding of error.mp3 finished.
pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2/resources $ mpg321 Light_Indoor.mp3 
High Performance MPEG 1.0/2.0/2.5 Audio Player for Layer 1, 2, and 3.
Version 0.3.2-1 (2012/03/25). Written and copyrights by Joe Drew,
now maintained by Nanakos Chrysostomos and others.
Uses code from various people. See 'README' for more!
THIS SOFTWARE COMES WITH ABSOLUTELY NO WARRANTY! USE AT YOUR OWN RISK!

Playing MPEG stream from Light_Indoor.mp3 ...
MPEG 2.0 layer III, 64 kbit/s, 24000 Hz mono
                                                                            
[0:01] Decoding of Light_Indoor.mp3 finished.

어떻게 하면 스마트미러에서 해당 소리가 나오게 할 수 있을까요?
[Light_Indoor.mp3.zip](https://github.com/eouia/MMM-AssistantMk2/files/4163306/Light_Indoor.mp3.zip)

**Comment by eouia** [comment]
음.. 좀 어렵기도 하고, 답드리기 애매한 요청이네요.
AMK2의 원래 목적은 사용자의 음성명령을 받아서 그걸 MM에서 쓸 수 있는 형태로 바꿔서 각각의 다른 모듈에게 해당 명령을 전달해주도록 만든거입니다.
그러니까, 예를 들어, "불꺼줘"라는 명령을 받는다고, AMK2가 직접 불끄는 행위를 하기보단(하게 할 수는 있어요..) 불끄는 모듈에게 "불끄라신다..."라고 전달해주는 역할이거든요. 그에 필요한 정의들이 recipe고.
말씀하신 사운드 재생의 경우, 어찌어찌 recipe로 만들 수는 있을 것 같은데요. (정 안되면 shellExec로 강제로 shell에서 mpeg321 돌리는 방법같은 것도 있겠죠.), 
사실 그보다는 사운드 재생하는 모듈(이 있다면... 혹은 필요하다면 만들어서)에게 해당 요청을 전달해주는게 MagicMirror의 모듈구조와, 이 AMk2 모듈의 설계에 더 맞는 거겠죠.

어쨌든, 같이 개발하는 @bugsounet 님이 `addOn`을 이용해서 원하시는 기능이 AMK2에서 직접 가능할 지 확인해본다고 하니 좀 기다려보시겠어요.

**Comment by dark594** [comment]
말씀해 주신대로 shellExec에 mpg321을 사용하여  재생을 시켰습니다.
저도 이번 참에 MagicMirror 모듈개발을 시도해봐야 겠어요. 
회로설계와 C베이스의 펌웨어만 해봐서 파악에 시간은 좀 걸리겠네요.
어쨌은 이렇게 훌륭한 스마트미러를 만들수 있게 해주신 @eouia 님과 @bugsounet 님께 감사드립니다.
