### ISSUE TITLE
"Freeze" if the internet connection lost during the AMk2 conversation response receiving

### ISSUE THREAD

**Issue by sergge1** [eouia/MMM-AssistantMk2#304]
Current steps:
1. Run MM + AMk2 (internet connection active)
2. Ask for some inquiry from Google Assistant
3. Internet connection disappear during the AMk2's conversation response receiving (loading).

**Current behavior**
AMk2 stays in "loading" state. Looks like it freezed - AMk2's icon showing the receiving the conversation and could be resolved only by MM restart if still no internet connection.

**Expected behavior**
- **simple**: AMk2 resets to "listening" state after some timeout (pre-configured in config or hardcoded within its code say 60sec)
- **pro**:  simple + show the visual response  "internet connection lost, try again". Do not need any audio.

**Comment by sergge1** [comment]
addition:
if the internet becomes very slow, say 1byte per second - assistant will try to get the audio response and it will take a long time. So some timeout for this is needed to be set to resolve such situations.

**Comment by bugsounet** [comment]
AMk2 assume to require a stable internet connection. (like other module)
Actually we don't use timeout for this, maybe later we code this ...

**Comment by sergge1** [comment]
> like other module

exactly, but the other modules are not go to freez when connection disappear (for example, calendar has its timeout config and it reconnects to read the calendar data after this timeout when the connection is lost.

by the way, thank you for the answer.
