### ISSUE TITLE
My Google Assistant is working fine, but sometimes when I say "SMART MIRROR" it is being recognized as "smart_mirror" and doesn't respond. Also when "SMARTMIRROR" is being recognized , for some tasks it is asking me to sign into the menu which I didn't understand. Please helpp!!

### ISSUE THREAD

**Issue by samroshan1310** [eouia/MMM-AssistantMk2#309]
**Describe the problem**
A clear and concise description of what the problem you have.

**To Reproduce**
Steps to reproduce the behavior: (Describe what did you do)

**Expected behavior**

**Screenshots**

**Environment:**
 - Device : [e.g. RPI 3b+]
 - OS: [e.g. Raspbian Stretch]
 - Node Version :
 - Etc.

**Before you post issue, try this first**
- Confirm you have completed installation with instruction. (If you have a problem on installation step, find other similar issues or follow instruction carefully. But if you failed again, post issue here.)
- To make things simple, disable or omit or outcomment other modules from config.js except MMM-AssistantMk2 and MMM-Hotword.
- Add `verbose:true` to MMM-Assistant `config:{}` and `testMic:true` to MMM-Hotword `config:{}`. 
- Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
- If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.

Then report me.

**Comment by bugsounet** [comment]
from last time:
> In order to be able to help you, we need a minimum of information.
a simple sentence will unfortunately not guide us.
can you first give us the feedback of the console?

I still don't have a gift of clairvoyance

**Comment by samroshan1310** [comment]
My apologies.
Here, as I've mentioned when hotword "SMARTMIRROR" is detected, the Assistant is working fine. But for some actions, it is asking to login to the menu
![2020-02-13-000009_1280x720_scrot](https://user-images.githubusercontent.com/58909999/74368093-f4a67800-4df8-11ea-9d15-348f679ea222.png)

and the log for this is 
![2020-02-12-235921_1280x720_scrot](https://user-images.githubusercontent.com/58909999/74368523-d7be7480-4df9-11ea-80cb-c852d8bff593.png)

now the second case is when the hotword is detected as "smart_mirror". I have no idea why this happens.
![2020-02-13-000653_1280x720_scrot](https://user-images.githubusercontent.com/58909999/74368666-1d7b3d00-4dfa-11ea-8446-49ff63b55b01.png)
it keeps on detecting and says "I don't understand" at the end. and its log is this
![2020-02-13-000656_1280x720_scrot](https://user-images.githubusercontent.com/58909999/74368783-50253580-4dfa-11ea-8935-0e71cd4910bd.png)

**Comment by eouia** [comment]
1. download google assistant app on your phone, and complete to setup your account.
2. i think your hotword model recipe was long. show me your config

**Comment by samroshan1310** [comment]
Here's my Hotword config

{
	module: "MMM-Hotword",
	position: "bottom_left",
	config: {
		recipes: ["with-AMk2v3_smart-mirror.js"],
		chimeOnFinish: null,
		mic: {
			recordProgram: "arecord",
			device: "plughw:1"
		},
		models: [
			{
				hotwords    : "smart_mirror",
				file        : "smart_mirror.umdl",
				sensitivity : "0.5",
			},
		],
		commands: {
			"smart_mirror": {
				notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
					}
				},
				restart:false,
				afterRecordLimit:0
			}
		}
	}
},

**Comment by eouia** [comment]
`"with-AMk2v3_smart-mirror.js"` recipe is almost same with your 
```
		models: [
			{
				hotwords    : "smart_mirror",
				file        : "smart_mirror.umdl",
				sensitivity : "0.5",
			},
		],
		commands: {
			"smart_mirror": {
				notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
					}
				},
				restart:false,
				afterRecordLimit:0
			}
		}
```
So both makes some conflicts. use one. (I recommend to use `recipe`)

**Comment by samroshan1310** [comment]
I'm sorry I'm new to this and I did not understand. Can you please elaborate?

**Comment by eouia** [comment]
just remove that models and commands in your configuration.

**Comment by samroshan1310** [comment]
When I remove the Models and the Commands, the Hotword icon disappears from the Magic Mirror
![2020-02-13-133941_1280x720_scrot](https://user-images.githubusercontent.com/58909999/74414998-800b2200-4e68-11ea-82e3-5e05782774ef.png)

![2020-02-13-133919_1280x720_scrot](https://user-images.githubusercontent.com/58909999/74415005-839ea900-4e68-11ea-9e57-8b4c2f2d4743.png)

**Comment by eouia** [comment]
Did you remove `recipe` also?

**Comment by eouia** [comment]
Well, your configuration would be enough as this;
```js
{
	module: "MMM-Hotword",
	position: "bottom_left",
	config: {
		recipes: ["with-AMk2v3_smart-mirror.js"],
		chimeOnFinish: null,
		mic: {
			recordProgram: "arecord",
			device: "plughw:1"
		},
},
```

**Comment by samroshan1310** [comment]
That's working perfectly. Thank you so much. :)
And just one more help.
Can you please tell me how to integrate two modules? like controlling a module with google assistant?
and also can you suggest some modules to include to make it a bit complex? I'm doing this as my final year project, that's why.

**Comment by bugsounet** [comment]
explain to us, we will tell you if this is possible or not

we can integrate modules with addons

**Comment by samroshan1310** [comment]
Well, can I use Google assistant with the help of MMM-hideall to hide all the modules and show any specific module that I need? Also, how can I turn on and off the Magic Mirror using Google Assistant?

**Comment by eouia** [comment]
Do you mean `https://github.com/plumcraft/mmm-hide-all` ?
It has no way to be controlled from externs, furthermore, it has no method function to execute. 
But for just hide/show modules, you can make a recipe to hide/show modules easily. Read the docs and research other recipes codes.
And for turning off MagicMirror,  recipe `Reboot-Restart-Shutdown.js` would help, but espcially, for turning on, impossible. (unless if you have smart-power-outlet thing and connect it to IFTTT and you have another Google Assistant like Google Home)

**Comment by samroshan1310** [comment]
Can we play Music from the Smart Mirror using Spotify? instead of showing "Now Playing on Spotify"?

**Comment by eouia** [comment]
Install MMM-Spotify (and Raspotify, if you need Spotify playing on RPI directly), then make a proper recipe.

**Comment by samroshan1310** [comment]
Can you please elaborate? as I said I'm new to this and have inadequate knowledge about this.
Kindly reply

**Comment by samroshan1310** [comment]
And in some of the modules, they have mentioned a few dependencies. Are we supposed to install them??

**Comment by samroshan1310** [comment]
I've even installed MMM-NewPir module, the screen turns off, but doesn't turn on. Can we turn it on using Google Assistant?

**Comment by bugsounet** [comment]
For MMM-NewPIR module: use [this prepared recipe](https://github.com/eouia/MMM-AssistantMk2/wiki/Recipes#prepared-recipes)
It will turn off screen after delay defined and turn on screen when you call assistant
If any problem report to [MMM-NewPIR](https://github.com/bugsounet/MMM-NewPIR) module page

**Comment by samroshan1310** [comment]
Hey, I've installed the MMM-Simple-Swiper, it doesn't seem to work properly? can you help me with that, please?

**Comment by bugsounet** [comment]
again, ... please report your problem to MMM-Simple-Swiper page
