### ISSUE TITLE
Voice sounds slowly and with a lot of noice

### ISSUE THREAD

**Issue by juanmam5** [eouia/MMM-AssistantMk2#31]
Hello. I have followed all the steps and it seems to work for me. I'm using a raspberry pi 3 with the google AIY voice kit. We I ask something to the mirror, the sound of the voice answering sounds slow and with noice. When I play a youtube vide it sounds perfect and when I do a voice test it sounds good too, even my voice recorded. But when google assitant answers it sounds bad. Do you think it could be a configuration issue or a hardware issue? Thank you!

**Comment by eouia** [comment]
If you has some choppy sounds for sound result, try `MP3` option.
https://github.com/eouia/MMM-AssistantMk2#110---20181004

**Comment by juanmam5** [comment]
I've already tried with MP3 and it's the same. I have the thunder icon on my raspberry because of the insufficient power. Could it be the reason?

**Comment by eouia** [comment]
It could be reason. lower CPU cycle (by any reasons - insufficient power, system busy or heat...) might cause choppy sounds.

**Comment by eouia** [comment]
Have you still got this error? Currently I have no other solution to suggest, So I'll close this issue. Anyway, I'll research better performance. I wish we both good luck.
