### ISSUE TITLE
안녕하세요. google 인증후 token.json 파일이 생성되지 않습니다.

### ISSUE THREAD

**Issue by josooik** [eouia/MMM-AssistantMk2#311]
안녕하세요. AssistantM2 몇번 지웠다 설치했는데 안되서 문의드립니다.

1. npm install
2. npm install --save-dev electron-rebuild
3. ./node_modules/.bin/electron-rebuild
4. chmod +x ~/MagicMirror/modules/MMM-AssistantMk2/scripts/*.sh
빌드 후 scripts 폴더 생성되지 않는 문제 있습니다.

그리고  credentials.json 파일 생성 후  google 인증  다음 node auth_and_test.js 하고 코드 입력 하고나면 "Hello" 했을때 응답합니다. 그다음  token.json 파일이 생성되지 않습니다. 어떻게 해야되나요?

**Comment by eouia** [comment]
```
chmod +x ~/MagicMirror/modules/MMM-AssistantMk2/scripts/*.sh
```
이거 보니 옛날 버전으로 설치, 설정하고 계신 것 같습니다. AMK2 가 version 3으로 업데이트 되면서 이전 설치와 config은 (아마도 어딘가의 한글문서나 영상등에서의 설명을 보셨을 텐데) 모두 무효이니, github repository를 직접 참고하셔서 새로 설치, 설정하세요.  지금 하신 방법대로는 설치가 되지 않습니다.

**Comment by josooik** [comment]
https://github.com/eouia/MMM-AssistantMk2/wiki/Installation

여기 있는 방법대로 다시 설치했습니다. 

https://github.com/eouia/MMM-AssistantMk2/wiki/Google-Assistant-Setup

cd ~/MagicMirror/modules/MMM-AssistantMk2
node auth_and_test.js

후 코드 입력하고 
token.json 생기지 않는 이슈는 어떻게 해결해야될까요??

**Comment by eouia** [comment]
코드 입력하고 Ctrl+C로 프로그램 종료했는데 MMM-AssistantMk2 디렉토리에 token.json이 생성되지 않는다는 말씀이시지요? 혹시 특별한 에러나 메시지는 없던가요? 실행 화면을 캡춰하거나 사진 찍어서 보여주시겠어요?

**Comment by josooik** [comment]
넵 별다른 오류 없었습니다.
![gg](https://user-images.githubusercontent.com/7031071/74412546-06cbf900-4e81-11ea-8c1a-6d2c7ebd5ad2.jpg)

**Comment by eouia** [comment]
흠.. 이상하네요. token.json이 생성이 안될 이유가 없는데... 권한 문제도 아니고.

**Comment by eouia** [comment]
혹시 모르니 사용하고 계신 node version 알려주시겠어요? Raspbian은 Buster 쓰시나요?

**Comment by eouia** [comment]
흠... 저도 다시 설치해서 테스트해봤는데, token.json이 정상적으로 생성됩니다. 딱히 뭘 건드리신 것 같지도 않은데, 이유가 안집히네요.

**Comment by josooik** [comment]
node 버전 : 10.15.2
npm 버전 : 6.13.7
입니다.

혹시 삭제했다가 제설치할때 MMM-AssistantMk2 폴더 삭제하고 다시 다운받고 설치하면 되는거죠?

**Comment by josooik** [comment]
Raspbian Buster Lite 씁니다.

**Comment by eouia** [comment]
혹시 "git clone" 이라든가 하실 때 "sudo"쓰신거 아닌가요? 왠지 퍼미션 문제일 듯 한데.

**Comment by josooik** [comment]
관리자 계정에서는 git clone https://github.com/eouia/MMM-AssistantMk2.git
유저 계정에서 sudo git clone https://github.com/eouia/MMM-AssistantMk2.git

이렇게 썼습니다.

그리고 궁굼한게 있는데요.

node auth_and_test.js 할때  유저 계정에서는 웹페이지가 뜨는데
관리자계정으로 node auth_and_test.js  하면 웹페이지가 안뜹니다.

그래서 유저 게정으로 credentials.json 다운받고 진행했었습니다.

**Comment by eouia** [comment]
MagicMirror 와 모듈들 모두 기본 pi계정으로만 설치 실행 충분합니다. sudo를 쓰시면 permission 문제가 생겨요. 어디서부터 꼬였는지 추적해서 바로 잡거나... 간단하게는 포맷하고 os부터 재설치하는게 깔끔할겁니다.

**Comment by josooik** [comment]
일단 포멧을 하고 다시 세팅해보겠습니다.
감사합니다.

**Comment by josooik** [comment]
안녕하세요. 포멧하고 다시 설치후 똑같은 증상이 생기네요.
token.json이 안생기네요 ㅜ

**Comment by eouia** [comment]
1) MagicMirror 설치시 최초에 git clone 하실 때 (혹은 auto-installer로 설치하실 때), sudo 사용하셨나요? 만약 그랬다면 MagicMirror 전체를 지우고 다시 설치하셔야 합니다.
2) MMM-AssistantMk2 설치하실 때 sudo 사용하셨나요? 그러면 MMM-AssistantMk2 지우고 다시 설치하세요.
sudo는 apt upgrade/apt update 외에는 쓰실 일도 없고, 쓰시면 안됩니다.

**Comment by josooik** [comment]
안녕하세요. 몇일간 삽질끝에 AssistantMk2 잘 작동합니다. 원인이 제가 평소에 관리자 계정을 자주 써서 관리자 계정 상태로 설치해서 안됬던거같습니다.(왜 관리자계정에서는 설치가 제대로 안되는지 궁굼하네요.) 일단 원인은 해결했습니다. @eouia 개발자님 감사합니다.

그리고 한가지 더 여쭤볼게 있는데요. 구글 어시턴스 사용하면 CPU점유율이랑 RAM이 급속도로 올라가네요.  이러다 라즈베리파이 먹통되기도 합니다.

config 파일은 sample 파일 그대로 쓰고 있습니다.
{
  module: "MMM-AssistantMk2",
  position: "top_left",
  config: {
    debug: false,
    ui: "Fullscreen", // or "Classic", "Classic2"
    assistantConfig: {
      projectId: "", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: 51.508530,
      longitude: -0.076132,
    },
    responseConfig: {
      useHTML5: true, // sound render by HTML5
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: false,
      //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
      playProgram: "mpg321", //needed if you don't use HTML5 sound render
      chime: {
        beep: "beep.mp3",
        error: "error.mp3",
        continue: "continue.mp3",
        open: "Google_beep_open.mp3",
        close: "Google_beep_close.mp3",
      },
      // false - animated icons, 'standby' - static icons only for standby state, true - all static icons
      useStaticIcons: false
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1",
    },
    customActionConfig: {
      autoMakeAction: false,
      autoUpdateAction: false, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    recipes: [ "with-MMM-Hotword.js", "with-MMM-TelegramBot.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    addons: false,
  },
},

**Comment by eouia** [comment]
원래 좀 무거운 모듈이에요. 음성인식이니 여러가지가 있어서.
그렇긴 해도 그렇게 까지 높지는 않을텐데요. 흠.. useHTML5:false로 해보시겠어요?

**Comment by josooik** [comment]
안녕하세요. 스마트미러 한번 응답하고 무한 적으로 응답안하는 문제 있었는데 업데이트가 되었네요. 감사합니다. 생각했던 버그는 많이 해결된거같습니다.

감사합니다. 개발자님
