### ISSUE TITLE
how can i set my default location?(기본설정위치를 바꾸고 싶어요)

### ISSUE THREAD

**Issue by sangwoo-ryu** [eouia/MMM-AssistantMk2#312]
i want change my default location London to Cheonan
is it on the module or google cloud platform?

지금 기본 설정위치가 런던으로 되어 있는걸 천안으로 바꾸고 싶어요.
모듈에서 바꿔야 하나요 아니면 구글에서 바꿔야 하나요?

**Comment by bugsounet** [comment]
hi,
Your default location is defined by this block:
```
    assistantConfig: {
      latitude: 51.508530,
      longitude: -0.076132,
    },
```
change latitude and longitude value for your actual position
This [website](https://latitudelongitude.org/) can help you to determinate it

**Comment by sangwoo-ryu** [comment]
Thx

**Comment by bugsounet** [comment]
do not hesitate to come back to us in case of problems
