### ISSUE TITLE
Could this be used as stand alone?

### ISSUE THREAD

**Issue by damvanjohan** [eouia/MMM-AssistantMk2#313]
Hi, currently i'm investigating the options to run a magic mirror setup mainly for the Google Home/Assistent integration. With investigating this i found the Google Home Nest Hub but also found this project. I was wondering if this project could also run as a stand alone web app without the Magic Mirror integration. Or is it better to stick with MM and just remove all other modules?

**Comment by bugsounet** [comment]
i just try this:

I remove my all module in my dev environement, and just let AMk2 and snowboy (addons or MMM-Hotword)
it's works but in Fullscreen UI you have a black screen

i suppose in RPI environement, it's will be the same.

**Comment by eouia** [comment]
this is made for controlling MM not for being an alternative of real Google home/devices. SDK is limited and restricted than real device.
