### ISSUE TITLE
Home automation question

### ISSUE THREAD

**Issue by sudoreddyman** [eouia/MMM-AssistantMk2#315]
So I already have a Google Home and smart switches/lights in my house. I am able to control the smart switches using google assistant on my phone or via Google Home. 

Is there any simple way to do this with MMM-AssistantMk2? 
Would registering my Mirror as an Google Assistant related device make this feasible? 

Thank you

**Comment by bugsounet** [comment]
if you use the same account of your google home and phone
you can say the same command, AMk2 will do it

example: if you say: `turn on light` in google home or phone -> it's turn off light
it's the same in AMK2 just say: `smart mirror turn off light`

**Comment by sudoreddyman** [comment]
Ahh wonderful, you are correct. 

I was previously trying custom Google Home routines which it seems the smart mirror can't access but that is fine. That's a minor inconvenience since the scope of my commands will be small. 

Thank you!
