### ISSUE TITLE
Second Hotword doesnt work / Coordinates causing problems

### ISSUE THREAD

**Issue by DarkGalaxy519** [eouia/MMM-AssistantMk2#318]
-Describe the problem A clear and concise description of what the problem you have.
1. Second Hotword doesnt get detected.
After the SmartMirror reacts and answeres my first question it cant answere to a second question. 
Example; If i ask what time it is, it answeres. But then it just closes and i cant interact with the SmartMirror anymore, the second time i say the Hotword it doesnt get detected and next to the icon there ist permanetly a "SMARTMIRROR".

2. Changing the coordinates causes Problemes
If i change the coordinates and restart the MagicMirror, the SmartMirror says after the Hotword immediately "Sorry, I dont understand". But as soon as i put them about the default coordinates it will work fine (except of course Problem 1).

 -To Reproduce Steps to reproduce the behavior: (Describe what did you do)
I searched up some other issues here on github but couldnt find anything that helps me. And i just played a bit with the Config file. (I am very new and not experienced, but i am lerning).

 -Expected behavior A clear and concise description of what you expected to happen.
I hope you can help me by looking at my config:

 {
        module: "MMM-Hotword",
        position: "bottom_left",
        config: {
                recipes: ["with-AMk2v3_smart-mirror.js"],
                chimeOnFinish: null,
                mic: {
                        recordProgram: "arecord",
                        device: "plughw:1"
                },

               autostart: true,
               onDetected: {
                notification: function (payload) {
                        return "ASSISTANT_ACTIVATE"
                                },
                                payload: function (payload) {
                                return {
                                profile: payload.hotword
                }
                }
                },
                },
                },

{
        module: "MMM-AssistantMk2",
        position: "top_right",
        config: {
                deviceLocation: {
                        coordinates: {
                                latitude: 47.050167, // -90.0 - +90.0
                                longitude: 8.309307, // -180.0 - +180.0
                        },
                },
                record: {
                        recordProgram : "arecord",  
                        device        : "plughw:1",
                },
                notifications: {
                        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
                        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
                },
                useWelcomeMessage: "brief today",
                profiles: {
                        "default" : {
                                lang: "en-US"
                        }
                },
        }
 },

Thx for helping me :)

**Comment by eouia** [comment]
your hotword and amk2 configuration is for v2 version. read docs and reconfigure.
