### ISSUE TITLE
Assistant crashed

### ISSUE THREAD

**Issue by rihardiii** [eouia/MMM-AssistantMk2#32]
Whell my assistant crashed :p
Happened when played the video (which BTW is extremely laggy (the video itself)) than sais smart mirror again while the video was playing and it crashed...
Maybe some suggestions?

previously saw this message:

    `Transcription: find me some information about  --- Done: true
     Device Action: { requestId: '5bc529a4-0000-2743-9392-f403043c87d4' }
     Assistant Text Response:
     (node:15099) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish 
     listeners added. Use emitter.setMaxListeners() to increase limit
     Conversation Completed`

Below is the error message when crashed:

    `Transcription: Linkin Park In the End  --- Done: true
     video found: eVTXPUF4Oz4
     Device Action: { requestId: '5bb59e46-0000-237f-9186-089e082b1ec0' }
     Assistant Text Response:
     Conversation Completed
     [HOTWORD] begins listening.
     [HOTWORD] <<  smartmirror  >> is detected.
     [HOTWORD] stops listening
     assistant ready
     [../deps/mpg123/src/output/alsa.c:165] error: cannot open device default
     Error: open() failed: -1
         at Speaker._open (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/speaker/index.js:106:13)
         at Speaker._write (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/speaker/index.js:183:23)
         at doWrite (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/readable-stream/lib/_stream_writable.js:428:64)
         at writeOrBuffer (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/readable-stream/lib/_stream_writable.js:417:5)
         at Speaker.Writable.write (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/readable-stream/lib/_stream_writable.js:334:11)
         at Reader.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:285:11)
         at emitNone (events.js:111:20)
         at Reader.emit (events.js:208:7)
         at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/wav/node_modules/readable-stream/lib/_stream_readable.js:934:16
         at _combinedTickCallback (internal/process/next_tick.js:131:7)
     Some error happens. Try again.
     Whoops! There was an uncaught exception...
     TypeError: this.sendSocketNotification is not a function
         at Reader.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:294:14)
         at emitNone (events.js:111:20)
         at Reader.emit (events.js:208:7)
         at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/wav/node_modules/readable-stream/lib/_stream_readable.js:934:16
         at _combinedTickCallback (internal/process/next_tick.js:131:7)
         at process._tickCallback (internal/process/next_tick.js:180:9)
     MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
     If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

Now i know it says to open issue in magic mirror github, but i know that the crash happened while using assistant so that is why its here, or maybe im wrong than you maybe can help me to fix this :)

**Comment by rihardiii** [comment]
So yeah this error is replicated whenever i try to communicate with assistant when it is playing something through speakers.
can it be fixed somehow?

**Comment by eouia** [comment]
Do you mean all conversation has this error? or only after playing youtube?

**Comment by rihardiii** [comment]
the crash only after youtube for now
but the error:

    `(node:15528) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
repeats more than once.

**Comment by eouia** [comment]
That EventEmitter error could be ignore. (not urgent.)
For youtube playing, I'll research.

**Comment by rihardiii** [comment]
Thanks!

**Comment by eouia** [comment]
Sorry, I tried to represent your symptom, but failed. 
How is your sound(ALSA?) configuration? Mic & Speaker isn't the default device?

**Comment by Kris-014** [comment]
Hi There!,
Awesome module :-), but I experience exactly the same issue. This only happen if i interrupt a playing video and started since the last update released 1.1.0. Replying to your question, yes ALSA is default using a USB audio card.

**Comment by eouia** [comment]
I think there might be some collision after playing youtube, then it might not release control of speaker, but not sure. Since in my device I cannot represent the condition, currently I cannot catch the exact reason. 
Anyway, I'll patch some bypass to enable/disable some features, to check which point is exactly problem. Plz wait a while.

**Comment by rihardiii** [comment]
Actually i have seen this error whenever some other program is using speakers... like playing from spotify, vlc, youtube or whatever. if than i  start speaking with google, the assistant crashes..
Default is alsa using USB sound card the same as Kris-014

**Comment by eouia** [comment]
@rihardiii That is not bug, sorry. Raspbian mixer is not so smart like other User-convenient OS(windows, OSX...). When other module is using sound device, attempt to use the same device will cause the collision. Maybe there would be some way to mix multiple sound output in OS level, but I'm not an expert about that.

**Comment by Kris-014** [comment]
@eouia seems strange to me, did not have this issue before last pull i made for the released 1.1.0
Cheers!

**Comment by eouia** [comment]
I’m making new version to solve this crazy sound problem. I’m changing whole dependencies to avoid several issues. Please wait a few days, sorry.

**Comment by eouia** [comment]
I've updated new version. Try this. I wish you guys have a luck.
And I'll close this issue. If you have a problem, leave it to new thread.
