### ISSUE TITLE
Top_bar position not displaying in center.

### ISSUE THREAD

**Issue by radokristof** [eouia/MMM-AssistantMk2#320]
@bugsounet 

**Describe the problem**
If you use top_bar as your position it won't display the icon in center, but on the left side of the screen. See screenshot.

**To Reproduce**
Set up the module and set position to top_bar

**Expected behavior**
Show the icon centered, as other modules do in top_bar position.

**Screenshots**
![photo5956085940164342099](https://user-images.githubusercontent.com/36210568/75283318-ea31a880-5812-11ea-8521-21c6281a3e02.jpg)

**Environment:**
 - Device : Raspberry Pi 3B
 - OS: Raspbian Buster
 - Node Version :  v12.16.1

**Improvement:**
Also would be great if the icon could be changed something darker, for example the white background could be changed to grey.

**Comment by moaz300** [comment]
how to play YouTube in MMM-AssistantMk2 

this my a problem 

plees contact me

**Comment by bugsounet** [comment]
@radokristof : 

![Screenshot_20200225_221403](https://user-images.githubusercontent.com/30669209/75288238-333a2a80-581c-11ea-9679-ace0b61fdb73.png)

i set with top_bar position and i have not this problem, weired

@moaz300 : open your own issue please

**Comment by radokristof** [comment]
I know what the problem is, it is my custom.css.
What I want to (which I had with the previous version) is that it should be aligned vertically centered (the little icon) and the clock module should stay at the top.
![photo6044039659136331506](https://user-images.githubusercontent.com/36210568/75289265-30d8d000-581e-11ea-88a6-3baf301d6f13.jpg)

Something like this.
You can see that the clock module is aligned next to the Assistant icon.

**Comment by bugsounet** [comment]
![Screenshot_20200225_223621](https://user-images.githubusercontent.com/30669209/75289792-5914fe80-581f-11ea-91d2-4a7651e539af.png)
like this ?

**Comment by radokristof** [comment]
@bugsounet Exactly :)

**Comment by bugsounet** [comment]
set position to `position: "top_center"`
and make AMk2 config just after `modules: [` in config.js

**Comment by radokristof** [comment]
It works thanks :)
