### ISSUE TITLE
hi BRO 

### ISSUE THREAD

**Issue by moaz300** [eouia/MMM-AssistantMk2#321]
I need fix a problem 
how to play any video via voice command using MMM-assisantMKT 2020

**Comment by moaz300** [comment]
my number WhatsApp +905352548482

**Comment by bugsounet** [comment]
needed:
 * [MMM-YouTube](https://github.com/eouia/MMM-YouTube)
 * recipe : [with-MMM-youtube.js](https://github.com/eouia/MMM-AssistantMk2/wiki/Prepared-recipes#with-mmm-youtubejs)

**Comment by moaz300** [comment]
ok how to run ?? 
2 how to connect mmm-youtube to assistant

**Comment by moaz300** [comment]
what writ to config.js ???

**Comment by moaz300** [comment]
??

**Comment by moaz300** [comment]
my config.js
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",
	// serverOnly:  true/false/"local" ,
			     // local for armv6l processors, default 
			     //   starts serveronly and then starts chrome browser
			     // false, default for all  NON-armv6l devices
			     // true, force serveronly mode, because you want to.. no UI on this device
	
	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"					}
				]
			}
		},
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "New York",
				locationID: "",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581",  //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
		
		
		
		
		{
  module: "MMM-AssistantMk2",
  position: "top_left",
  config: {
    debug: false,
    ui: "Fullscreen", // or "Classic", "Classic2"
    assistantConfig: {
      projectId: "", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: 51.508530,
      longitude: -0.076132,
    },
    responseConfig: {
      useHTML5: true, // sound render by HTML5
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: true,
      //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
      playProgram: "mpg321", //needed if you don't use HTML5 sound render
      chime: {
        beep: "beep.mp3",
        error: "error.mp3",
        continue: "continue.mp3",
        open: "Google_beep_open.mp3",
        close: "Google_beep_close.mp3",
      },
      // false - animated icons, 'standby' - static icons only for standby state, true - all static icons
      useStaticIcons: false
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1",
    },
    customActionConfig: {
      autoMakeAction: true,
      autoUpdateAction: true, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    recipes: [ "with-MMM-Hotword.js", "with-AMk2v3-noisy_smart-mirror.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    addons: false,
  },
},
{
    module: "MMM-Hotword",
    position: "bottom_left",
    config: {
      useDisplay: false,
      chimeOnFinish: null,
      recipes: ["with-AMk2v3_smart-mirror.js"],
      mic: {
        recordProgram: "arecord",
        device: "plughw:1",
      },
    },
  },
  
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true,
				broadcastNewsFeeds: true,
				broadcastNewsUpdates: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by bugsounet** [comment]
1) install [MMM-YouTube](https://github.com/eouia/MMM-YouTube#installation) (click on the link for install guide)
2) just add `with-MMM-youtube.js` in AMk2 line `recipes []`

**Comment by moaz300** [comment]
love you bro ^_^ is a working wwwwwowoow 


		
		
		{
  module: "MMM-AssistantMk2",
  position: "top_left",
  config: {
    debug: false,
    ui: "Fullscreen", // or "Classic", "Classic2"
    assistantConfig: {
      projectId: "", // Required to use gaction.
      modelId: "", // (OPTIONAL for gaction)
      instanceId: "", // (OPTIONAL for gaction)
      latitude: 51.508530,
      longitude: -0.076132,
    },
    responseConfig: {
      useHTML5: true, // sound render by HTML5
      useScreenOutput: true,
      useAudioOutput: true,
      useChime: true,
      timer: 5000,
      myMagicWord: true,
      //Your prefer sound play program. By example, if you are running this on OSX, `afplay` could be available.
      playProgram: "mpg321", //needed if you don't use HTML5 sound render
      chime: {
        beep: "beep.mp3",
        error: "error.mp3",
        continue: "continue.mp3",
        open: "Google_beep_open.mp3",
        close: "Google_beep_close.mp3",
      },
      // false - animated icons, 'standby' - static icons only for standby state, true - all static icons
      useStaticIcons: false
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1",
    },
    customActionConfig: {
      autoMakeAction: true,
      autoUpdateAction: true, // in RPI, gaction CLI might have some trouble.(current version should be 2.2.4, but for linux-arm, Google haven't updated) so leave this as false in RPI. I don't know it is solved or not.
      actionLocale: "en-US", // At this moment, multi-languages are not supported, sorry. Someday I'll work.
    },
    recipes: [ "with-MMM-Hotword.js", "with-AMk2v3-noisy_smart-mirror.js","with-MMM-Youtube.js"],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    addons: false,
  },
},
{
    module: "MMM-Hotword",
    position: "bottom_left",
    config: {
      useDisplay: false,
      chimeOnFinish: null,
      recipes: ["with-AMk2v3_smart-mirror.js"],
      mic: {
        recordProgram: "arecord",
        device: "plughw:1",
      },
    },
  },
  {
module: "MMM-YouTube",
position: "fullscreen_above",
config: {
defaultQuality: "default",
showPlayingOnly: true,
}

	},
