### ISSUE TITLE
I need fix a problem  how to play any video via voice command using MMM-assisantMKT 2020

### ISSUE THREAD

**Issue by moaz300** [eouia/MMM-AssistantMk2#322]
need the assistant to play a YouTube via voice command using.  MMM-assisantMKT 
1.how to install MMM-YOUTUBE 
2.how to  connect mmm-youtube to MMM-assisantMKT 

please respond as  soon possible 
thanks for you bro

**Comment by bugsounet** [comment]
double issue, closing
