### ISSUE TITLE
Icon doesn't show on Magic Mirror

### ISSUE THREAD

**Issue by LAngus123** [eouia/MMM-AssistantMk2#323]
Hi, thanks for your instruction for adopting google assistant in MagicMirror, but some points that I would like you help to clear and make the project smooth:
1) I followed your instruction and try to "npm start",  but it does not work, so I run it by following code: "module: "MMM-AssistantMk2",
  position:"top_right",
  config:{usingWelcomeMessage:brief today} "   in config.js
but in the Magic Mirror screen, I could not find the icon of google assistant on Magic Mirror, can you give any advice of it ? 

also,
2) I try to use my speaker as sound output and input through Bluetooth, but the test could not configure it, could you please tell me how to configure it? 

thank you in advance!!

**Comment by eouia** [comment]
```
config:{usingWelcomeMessage:brief today} 
```
Hmmm.. It seems old version you are tried. AMK2 and Hotword was updated recently. So you need new configuration. Read the docs of github.

For the H/W, I have no idea. You need to find the method to activate your mic and speaker under normal Raspberry environment by yourself.

**Comment by LAngus123** [comment]
thanks for your reply, but actually I also using the code here, downloaded all package automatically, but at the end, when I used the code in basic structure writing in config, its also does not work, the magic mirror will show something like error layout or required configuration, can you give any advice about it？

**Comment by eouia** [comment]
Raspbian works somewhat weirdy with Bluetooth.
Check these first;
- Are your BT mic and speaker some kind of 2-in-1 device using A2DP Profile? As I know that kind of device needs additional things(like BlueZ, pulseaudio...) to be used as the duplex way(recording and playing at the same time), however, I don't know exactly how to do.
- Do your BT mic and speaker work on Raspbian directly? try this.
```sh
arecord --duration=5 test.wav
# Record your voice for 5 sec.
aplay test.wav
# Your recorded voice should be played.
```
All you need is that those tests should work on your environment(At least, with proper parameters to execute). 
Setting environment is out of this module's job.

**Comment by LAngus123** [comment]
thanks, let me try it again.

**Comment by ktvhn1** [comment]
Please help me, I got the same error as LAngus123
icon doesn't show on Magic Mirror

when stop smart mirror, I see picture 
![pic](https://user-images.githubusercontent.com/62001764/76279148-33c4cd80-62c0-11ea-9fb0-fa7adf965330.jpg)

**Comment by eouia** [comment]
@ktvhn1 Same? I'm not sure.
First, Your hotword has no model to load. Read the docs and make your config properly.
Second, GLib-GIO-... Error seems not belonging to our module. 
Suggestion:
Remove all other modules except MMM-Hotword and MMM-AssistantMk2 then execute and let's see the error happened again.

**Comment by ktvhn1** [comment]
Thank you for answering my questions!
Yes, GLib-GIO -... Error is not an error related to your module.
I reinstalled it from the beginning, following the instructions.
Remove all other modules except MMM-AssistantMk2 (now, I have not installed MMM-Hotword).
Configuration file as image, but  GA's ico still doesn't show on Magic Mirror.
![0](https://user-images.githubusercontent.com/62001764/76326125-c3976580-631a-11ea-970a-9adbe68907ec.jpg)
![1](https://user-images.githubusercontent.com/62001764/76326143-cbefa080-631a-11ea-8663-c76f86337f72.jpg)
![3](https://user-images.githubusercontent.com/62001764/76326171-d90c8f80-631a-11ea-8dfe-c0b0807b645e.jpg)

**Comment by eouia** [comment]
There is no `useWelcomeMessage` since V3 updates. Read the docs/wiki on github repository, follow the instruction to install and configure.

**Comment by ktvhn1** [comment]
Thank you so much, because I have not read your instructions carefully.
Let me ask, do I have a Sony CMU-BR100 Webcam that is compatible with GA?

**Comment by bugsounet** [comment]
hi, we don't test Sony CMU-BR100 Webcam, sorry

`useWelcomeMessage` is deprecied but we code it with AMk2 addons
Look at [addons repository](https://github.com/bugsounet/addons) for more informations

**Comment by ktvhn1** [comment]
Thank you so much for supporting me.
