### ISSUE TITLE
Assistant don't Respond

### ISSUE THREAD

**Issue by defiantlibra** [eouia/MMM-AssistantMk2#328]
Hi, i had Assistant ver 3.0 running on my mirror and he worked well.
Two days ago, in order to update the module, i have reinstalled the assistant and MMM-Hotword, and now it give me this error...
What can i do?
(i have correctly copied my crediental.Json and profile in the new version of assistant)

![{5DB053DF-2AE9-4CF6-BACD-5E94C459739D} png](https://user-images.githubusercontent.com/57544523/75656694-c6cc8a80-5c64-11ea-9616-20f9868b23ad.jpg)
![{5AA3874A-C967-46A3-8410-88B0AD826972} png](https://user-images.githubusercontent.com/57544523/75656762-efed1b00-5c64-11ea-9dee-e9df516efa46.jpg)

**Comment by artomka** [comment]
I have the same problem. V3 has never worked properly on my MM. In my case, the last working configuration was V2.

**Comment by eouia** [comment]
Auth error means your credentials has something wrong, invalid or expired.

**Comment by bugsounet** [comment]
@artomka : if you open your  own issue, we help you to configure it

**Comment by defiantlibra** [comment]
ok I understand thanks, although it is strange because until before the update it worked ..
i will try to reintsall all

**Comment by defiantlibra** [comment]
i have reinstalled everything and now it works! thanks you!
