### ISSUE TITLE
No sound output on the latest version

### ISSUE THREAD

**Issue by radokristof** [eouia/MMM-AssistantMk2#331]
**Describe the problem**
After upgrading to the latest version, the sound output is gone. There is no chime and no voice, but except the voice it works as it should, so I can see the output on the screen.

**To Reproduce**
Upgrade to the latest version.
When I disabled useHTML5 it worked, but the output was choppy and quality was also very low...

**Expected behavior**
Get sound output working again. Maybe some config needs to be changed?

**Environment:**
 - Device : RPI 3B
 - OS: Raspbian Buster

**Comment by bugsounet** [comment]
plz wait, i'm working around,

but ... we don't touch the sound code in the latest version

**Comment by radokristof** [comment]
I got it working. It was an issue with pulseaudio.

**Comment by bugsounet** [comment]
I have recoded audio output for mpg321 and others (v3.1.1-1)
Now there is no cutting sentence

**Comment by radokristof** [comment]
Thanks I will update it today!

I have found a small problem which may not be related to the module, but it makes the module rather unusable.
Sometimes on an RPi the USB bus hub crashes and the devices attached to it becomes unavailable and gets a new ID. I have seen this with my Webcam which generally available at /dev/video0. After some time it changes to video1, etc...
I think this happens also with the USB mic I'm using right now, that's why after some time the voice control is not working. However restarting MagicMirror is enough to solve this. Is it maybe somehow possible to re-request the currently available micDevice?

**Comment by radokristof** [comment]
Ps.: I will do deeper investigation on this... it seemes that the device is not available after some time (arecord -l returns 0 capture device...)

**Comment by bugsounet** [comment]
i have a +/- similar problem sometime my mic config change (USB mic) ... reboot don't solve probem. only shutdown.
RPI firmware bug ... sorry
I can't do anything
