### ISSUE TITLE
Google Assistant not responding.

### ISSUE THREAD

**Issue by JohnLucaJF** [eouia/MMM-AssistantMk2#334]
Hi, im hoping you can help

Sorry im not Linux expert but...
[back-end-log.txt](https://github.com/eouia/MMM-AssistantMk2/files/4298173/back-end-log.txt)
[front-end-log.txt](https://github.com/eouia/MMM-AssistantMk2/files/4298177/front-end-log.txt)

I have installed AssistantMK2 and HotWord. I know AssistantMK2 is able to talk to Google as it passes the node auth_and_test.js. I get a speech icon on Magic Mirror and it picks up when i say 
"Smart mirror" but then i get the google bar and doesnt pick up anything else. I just get the 4 dots on the google icon moving and the after a while a message saying "Im sorry i dont understand."

*Environment:**
 - Device : [e.g. RPI 3b+]
 - OS: [e.g. Raspbian Stretch]

I have checked config @ esprima.org and include front-end and backend -reports and Images 
![Ga-Sorry](https://user-images.githubusercontent.com/59516768/76082451-5a72c380-5fa3-11ea-9e98-52b54b34a1b9.jpg)
![GA-Try Screenshot](https://user-images.githubusercontent.com/59516768/76082452-5b0b5a00-5fa3-11ea-9476-9456b778047b.jpg)

of problem.
Hope this makes sense.

Thankyou.

**Before you post issue, try this first**
- Confirm you have completed installation with instruction. (If you have a problem on installation step, find other similar issues or follow instruction carefully. But if you failed again, post issue here.)
- To make things simple, disable or omit or outcomment other modules from config.js except MMM-AssistantMk2 and MMM-Hotword.
- Add `verbose:true` to MMM-Assistant `config:{}` and `testMic:true` to MMM-Hotword `config:{}`. 
- Copy your content of `config.js` and paste it into http://esprima.org/demo/validate.html to check whether you have syntax error or not. If there might be errors, usually your issue will be solved by fix those errors.
- If you are using `pm2` to execute MM, stop pm2 (`pm2 stop mm`) then execute `npm start dev` on your MagicMirror directory. It will show front-end log on dev-console of MM, and back-end log on your shell terminal. Both logs are needed to examine.

Then report me.

**Comment by eouia** [comment]
Your backend log is too short.
- To make things simple. remove all other modules from config(you can use `disabled:true`) except Hotword and AMK2. Then try again.
- Set `debug:true` option to AMK2 configuration. It will log more details.

**Comment by JohnLucaJF** [comment]
Ok I will and then I’ll send the backend log, thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JohnLucaJF** [comment]
[better-backend-log.txt](https://github.com/eouia/MMM-AssistantMk2/files/4298833/better-backend-log.txt)

Hope this is better, appears to be issue with mic, yet HotWord is detecting "smart mirror", I will have a play and see if i can work it out.  Thanks

**Comment by eouia** [comment]
Are you using recipe or your own code? Anyway your command seems wrong. It is calling `TEXT query` to AMK2. Read the docs. And we prepared `recipe` for this kind of user's mistakes. Use recipe.

**Comment by JohnLucaJF** [comment]
Put in the recipe and its now working. Thanks for the help..!!
