### ISSUE TITLE
MM-Hotword -> MMM-AssistantMk2 -> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by iwashere13** [eouia/MMM-AssistantMk2#335]
Hi,

after havin set up the newest version of MMM_AssistantMk2 v3.1.1-1 I have the following problem.
The hotword is detected, but then the google search bar freezes (waiting dots). The dev shows the following error:

```
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: spiegel
[HOTWORD] stops.
[HOTWORD] After Recording is too short
[HOTWORD] Final Result: { detected: true, hotword: 'spiegel', file: null }
Whoops! There was an uncaught exception...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1090:7)
    at new ASSISTANT (/home/pi/MagicMirror/modules/MMM-AssistantMk2/components/assistant.js:29:28)
    at Class.activateAssistant (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:92:22)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:37:14)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
```
In order to reproduce one just need to restart MM and continue with the hotwork recognition.
I would have expected the system not to freeze. It seems like the 'communication' between Hotword and Assistant has an issue.

 - Device : RPI 3b+
 - OS: Raspbian Stretch 
 - Node Version: v10.17.0

Eveything is installed and configured like the published default:

```
{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {
    ui: "Fullscreen", // or "Classic", "Classic2"
    assistantConfig: {
      latitude: 12.3456789, //anonymized
      longitude: 9.8765432, //anonymized
    },
    micConfig: { // put there configuration generated by auto-installer
      recorder: "arecord",
      device: "plughw:1",
    },
    recipes: [ "with-MMM-Hotword.js" ],
    profiles: {
      "default": {
        profileFile: "default.json",
        lang: "en-US"
      }
    },
    addons: false,
  }
},


  {
    module: "MMM-Hotword",
    position: "top_right",
    config: {
      useDisplay: false,
      chimeOnFinish: null,
      recipes: [ "with-AMk2v3_spiegel.js", "with-AMk2v3_smart-mirror.js" ],
      mic: {
        recordProgram: "arecord",
        device: "plughw:1",
      },
    },
  },
```
Changing the recipe of hotword did not have any effect. BTW: "with-AMk2v3_spiegel.js"
Iit is just a copy of the default replacing the default model with an individually trained model ("spiegel.pmdl").

```
var recipe = {
  models: [
    {
      hotwords    : "spiegel",
      file        : "Spiegel.pmdl",
      sensitivity : "0.7",
    },
  ],
  commands: {
    "spiegel": {
      notificationExec: {
        notification: "ASSISTANT_ACTIVATE",
        payload: (detected, afterRecord) => {
          var ret = {
            profile:"default",
            type: "MIC",
          }
          if (afterRecord) {
            ret.type = "WAVEFILE"
            ret.key = "modules/MMM-Hotword/" + afterRecord
          }
          return ret
        }
      },
      restart:false,
      afterRecordLimit: 7
    }
  }
}

exports.recipe = recipe // Don't remove this line.
```
I would be really glad if you have any idea and can fix that issue. I loved the old version of assistantMk2 and I think the new version will be even better.

Cheers

**Comment by bugsounet** [comment]
hi,
i can't reproduce your error.

You say you install AMk2 v3.1.1-1:
 * it's an update V3.x to V3.1.1-1 or it's clean install?
 * what it's the command do you use this update or install ?

**Comment by iwashere13** [comment]
Thanks for your reply. It is an update from the previous version 3.0.1 using the following commands: 
```
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm run update
```
If you cannot reproduce this issue, what would be your recommendation? Deinstall 'Hotword' and 'Assistant mk2' followed by a clean reinstall? If yes, what would be the best procedure to deinstall both? There are many dependencies and I am not quite sure how and if I can simply deinstall them?

**Comment by eouia** [comment]
I don't know why but your `node_helper.js` seems slightly different from the original.
```
at Class.activateAssistant (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:92:22)
at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:37:14)
```
https://github.com/eouia/MMM-AssistantMk2/blob/348a31e5f6065580935bf7148a955e16458ec451/node_helper.js#L92-L93
The error should happen on line 93, not 92.

https://github.com/eouia/MMM-AssistantMk2/blob/348a31e5f6065580935bf7148a955e16458ec451/node_helper.js#L37-L38
Here also, suspicious line should be 38, not 37.

**Comment by bugsounet** [comment]
@iwashere13 : please try `npm run clean`
and make electron rebuild

It will delete all sources and download fresh sources
for fresh build

**Comment by iwashere13** [comment]
Thanks @bugsounet. Whilst doing so I found out a possible reason: 
"You are using GCC 6, this is not compatible with this program. You have to downgrade to GCC 7."

I have tried to update to gcc7 with different tutorials, but always failed. E.g. https://askubuntu.com/questions/864893/update-gcc-to-the-6-3-version 

How can I update gcc? I am really out of ideas :-(

Also your update script did not work in case of gcc:
```

You must install missing dependencies before going further
Missing package: gcc-7
Attempt to automatically install the above packages? [Y/n] 
Your choice: 
Installing missing package...
Get:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease [15.0 kB]
OK:2 http://archive.raspberrypi.org/debian stretch InRelease
OK:3 https://dtcooper.github.io/raspotify jessie InRelease
OK:4 https://deb.nodesource.com/node_10.x stretch InRelease
A total of 15.0 kB was retrieved in 2 s (6,855 fps).
Packet lists are read...
Packet lists are read...
Dependency tree is built...
Status information is read...
E: Package gcc-7 cannot be found.
All Dependencies needed are installed !
```
Thanks a lot for your assistance!

**Comment by bugsounet** [comment]
i don't know how force GCC-7 in raspbian stretch,
i think best solution is update os to rapbian buster

after that you will have no configuration problem with this program and other new MMM module

**Comment by eouia** [comment]
GCC6 would not be the reason. In Stretch with GCC6 it will work. At least, it worked. (I might be wrong because I didn't test nowadays. I have no stretch now.)
Have you compared your `node_helper.js` and original github source line-by-line? I still suspect the line number mismatched.

**Comment by iwashere13** [comment]
Hi eouia,
Yes you are right I have installed GCC 7.5 now (if you like I can document a 'how to' somewhere), but no change of this issue. I have also checked node-helper.js (after having done a git pull). Now everything is equal to the original sources again. The error message stays the same, but the erroneous line has changed.

```
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: spiegel
[HOTWORD] stops.
[HOTWORD] After Recording is too short
[HOTWORD] Final Result: { detected: true, hotword: 'spiegel', file: null }
Whoops! There was an uncaught exception...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1090:7)
    at new ASSISTANT (/home/pi/MagicMirror/modules/MMM-AssistantMk2/components/assistant.js:29:28)
    at Class.activateAssistant (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:93:22)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:38:14)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by eouia** [comment]
I don't know why and how, but your configuration was corrupted.
Would you try this?
```js
assistantConfig: {
      latitude: 12.3456789, //anonymized
      longitude: 9.8765432, //anonymized
      credentialPath: "credentials.json" //<- Add this. This should be implemented by default automatically, but for some reason, it seems broken.
    },
```

**Comment by iwashere13** [comment]
Unfortunately it had no effect. The same issue apeared after this additional line in the config file.

**Comment by eouia** [comment]
Hmmm. try this.
This will not fix your issue but could help to what happened.
Open `components/assistant.js` and go line 27. 

https://github.com/eouia/MMM-AssistantMk2/blob/348a31e5f6065580935bf7148a955e16458ec451/components/assistant.js#L27-L30

Add this above `this.assistantConfig = {`.
```js
console.log("###", config)
```

Then execute it again.
When you may meet the error, `### { many properties ... }` will display also. Show us.

**Comment by bugsounet** [comment]
you should have something like this:

```js
[18:28:23.297] [LOG]    ##### {
  credentialPath: 'credentials.json',
  projectId: 'xxx',
  modelId: 'xxx',
  instanceId: 'Magic_Mirror',
  latitude: 50.0149,
  longitude: 4.05243,
  modulePath: '/home/bugs/MagicMirror/modules/MMM-AssistantMk2',
  debug: true,
  session: 1583774902591,
  lang: 'fr-FR',
  useScreenOutput: true,
  useAudioOutput: true,
  useHTML5: false,
  micConfig: { recorder: 'arecord', device: 'plughw:1', verbose: false }
}
```

**Comment by iwashere13** [comment]
Besides the mentioned log I now get also a "Connection failure". Does this mean, that there must be an issue with the google credentials?

```
[HOTWORD] Detector starts listening.
Connection failure
Connection failure
Connection failure
```

My assistant.js looks like this now (start of extract from line 19 until 31)

```
class ASSISTANT {
  constructor(config, tunnel = ()=>{}) {
    var debug = (config.debug) ? config.debug : false
    this.session = config.session
    this.modulePath = config.modulePath
    this.micConfig = config.micConfig
    this.useAudioOutput = config.useAudioOutput
    console.log("###", config)
    this.assistantConfig = {
      auth:{
        keyFilePath : path.resolve(config.modulePath, config.credentialPath),
      },
      conversationConfig : {
```
And the result of the log (I have anonymized my individual session ID):

```
### { debug: undefined,
  session: 1234567891011,
  lang: 'en-US',
  useScreenOutput: true,
  useAudioOutput: true,
  useHTML5: true,
  micConfig: undefined }
Whoops! There was an uncaught exception...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.resolve (path.js:1090:7)
    at new ASSISTANT (/home/pi/MagicMirror/modules/MMM-AssistantMk2/components/assistant.js:29:28)
    at Class.activateAssistant (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:93:22)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:38:14)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11)
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Connection failure
Connection failure
Connection failure
```
FYI: I have configurated and tested microphone and speakers succesfully during the wizard and in the config (even though the log shows micConfig: undefined)

**Comment by eouia** [comment]
Totally weird. We have no idea about Your connection error. It seems not belong to us.
And about your log, the logged things aren’t normally  expected. We can’t figure out what happened in your system. Tracking that config values reversely be needed to know where and why.

**Comment by eouia** [comment]
Last guessing;
We suspect your installation was done with root permission. Usually, MM doesn't need `sudo` to install. But you might have done. With `sudo`, permissions among MM and modules would make things broken.
Check this.
```sh
cd ~
ls -la | grep MagicMirror
```
It will show the owner and permissions.

**Comment by iwashere13** [comment]
Thanks. It is too long ago I did the setup. But I have checked:
`drwxr-xr-x 18 pi   pi     4096 Jan  1 20:20 MagicMirror`
-> it is chmod 755 and the owner is not root but my 'pi' user

What would be your suggestion how to proceed now as we all have no clue about a reason? With the previous version 2 everything was working fine for many months. The reinstall of v3 was exactly done as documented.

I think I will do the initial installation of v3 again from scratch step by step. But how can I delete everything related with assistante v3 (including credentials.json and so on)? I assume just deleting the folder in modules is not enough. Completely reinstall the whole raspberry pi and MagicMirror would be worst case, because I have spend many hours in this setup.

**Comment by eouia** [comment]
Give me your email. I'll send you test version for more tracking log. Reinstall would be the last things.

**Comment by iwashere13** [comment]
After awesome help it works now. Special thanks to @eouia and @bugsounet !

The root cause was: First: Somehow my files have been corrupted (even though git pull proceeded). Second: I have found out that the module MMM-GoogleTask causes this issue as well (https://github.com/jgauth/MMM-GoogleTasks). Do not run both modules in parallel.

Again: Many thanks!
