### ISSUE TITLE
Welcome Brief Today not playing

### ISSUE THREAD

**Issue by mudassarqureshi-sm** [eouia/MMM-AssistantMk2#338]
My Magic Mirror is installed perfect.
GoogleAssistant also working perfect. Picks up the voice and responds fine ! 

Only issue is , when the mirror loads up , it does not play weather brief.
I have default weather (openweathermaps) .. all showing up fine ! weather forecase displays fine.
GoogleAssitant is enabled.
useWelcomeMessage: "brief today", 
is also added in config.

As i said, there are no errors.. just that the daily brief not playing.. if i ask a question to Smart Mirror , it responds fine !! no issues...

**Comment by mudassarqureshi-sm** [comment]
my config file.

> {
		  module: "MMM-AssistantMk2",
		  position: "top_right",
		  config: {
		    ui: "Classic2",
		    assistantConfig: {
		      projectId: "smart-mirror-2-5fef7",
		      latitude: 74.343613,
		      longitude: 31.549721,
		    },
		    micConfig: { // put there configuration generated by auto-installer
		      recorder: "arecord",
		      device: "plughw:1",
		    },
		    recipes: ["with-MMM-Hotword.js"],
		    useWelcomeMessage: "brief today",
			notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
			},
		    profiles: {
			"default": {
			  
			  lang: "en-US"
		      }
		  },
		addons: false,
		}
	      },
		{
		    module: "MMM-Hotword",
		    position: "top_right",
		    config: {
		      chimeOnFinish: null,
		      useDisplay: false,
		      chimeOnFinish: null,
		      recipes: ["with-AMk2v3_smart-mirror.js"],
		      
		models: [
					{
						hotwords    : "smart_mirror",
						file        : "smart_mirror.umdl",
						sensitivity : "0.5",
					},
			],
			defaultCommand: {
				      notificationExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
					  return {profile:"default"}
					}
				      },
				      afterRecordLimit:0,
				      restart:true,
				},

		    },
		  },

>

**Comment by eouia** [comment]
useWelcomeMessage is deprecated since V3. You can make your own recipe for same effect.

**Comment by mudassarqureshi-sm** [comment]
can you please help out in creating this recipe ?
All i need is smart mirror playing out the daily brief at load up like it was doing an year ago ..
Please... If you can write the code notificationExec: what do i exactly play or which command .. 

I can include the recipe file in Module: googleassistantMK2.. but the actual recipe file, can you write that code ? 

Thanks & appreciated.

**Comment by eouia** [comment]
Hmm. Every morning are you reboot MM? I think you just say "brief today" to AMK2 in the morning. I regard useWelcomeMessage as a test for working of the module on startup. So before making recipe, What is your use-case scenario of that feature?

**Comment by bugsounet** [comment]
@eouia : I can prepare recipe for this for next AMk2 change

**Comment by mudassarqureshi-sm** [comment]
> Hmm. Every morning are you reboot MM? I think you just say "brief today" to AMK2 in the morning. I regard useWelcomeMessage as a test for working of the module on startup. So before making recipe, What is your use-case scenario of that feature?

use-case: When MM loads , it simply says Good Morning "My Name". today the weather is a bit breezy with mild rain blah blah blah ... 

Thats all i want. Right now, its silent at load up

**Comment by eouia** [comment]
@bugsounet gracefully implemented this feature already in his dev version. He will release it publicly soon (but not guaranteed when it opens. :) )

**Comment by bugsounet** [comment]
**notes:**
this feature help me for developing ;)
I use Yoda force for helping coding and YODA force is with me, ahahah
(turn on `developer:true` in AMk2 config for YODA force)

I will release a public version with full feature, just wait a while

**Comment by bugsounet** [comment]
@mudassarqureshi-sm: I be back, with good news :)

If you want brief Today, i code it with AMk2 addons.
Let's check [Respository addons](https://github.com/bugsounet/addons) for more informations ;)

**Comment by mudassarqureshi-sm** [comment]
> @mudassarqureshi-sm: I be back, with good news :)
> 
> If you want brief Today, i code it with AMk2 addons.
> Let's check [Respository addons](https://github.com/bugsounet/addons) for more informations ;)

OMG OMG OMG !! i spent days and days to get this to work and you are Da Man !! made it so easy ... Love you to bits.. if u were here, i would be hugging u :)

Thanks...

**Comment by mudassarqureshi-sm** [comment]
Btw yes it works.. it plays the daily brief now... just a curiosity .. it says Good Morning or Hello "My Name" and the time ... i am not mistaken it use to say the weather also and whether or not it will rain.. can that be added ? 
Alternatively, where is it picking this "daily brief" from ?

**Comment by bugsounet** [comment]
just use Google Assistant App in your smartphone and configure routine
