### ISSUE TITLE
Directions to phone

### ISSUE THREAD

**Issue by JohnLucaJF** [eouia/MMM-AssistantMk2#339]
When asking assistant for directions/google maps,  it displays them and says sent to phone , but they aren’t is there an option to get this working , I’m signed in with the same google account. 

Thank
John

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eouia** [comment]
Hmmm. Do you have a Google Assistant App on your smartphone? That will show the searching result. I think you have blocked the notification of that app. Check the app. That feature is not controllable by this module. It is the Entire Google Assistant Service level feature.

**Comment by JohnLucaJF** [comment]
That’s ok ,, didn’t think it was assistantmk2 causing problems , Yes I have app on phone and if go google maps on pc can send directions to my phone ok,  I think I may need to  register mirror as google assistant device, will test when I get home
Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by JohnLucaJF** [comment]
unable to get working, can turn hue lights on and off via AssistantMK2 so i know it can talk to google home. I wonder if anyone else has got this working.

**Comment by eouia** [comment]
Is your device registered as google home networked device?

**Comment by JohnLucaJF** [comment]
yes device shows in google home. strange one. As it must know about my phone otherwise it wouldnt say it was sending detail to it. As I say i can use MagicMirror to turn on and off lights , change temp on thermostat and they are all in google home.

**Comment by eouia** [comment]
Sorry, How it be handled is Google's job, not this module. I think Nothing additional to do remains.

**Comment by JohnLucaJF** [comment]
I agree ,  not issue with module, was just hoping to find someone could confirm it does work and then I could continue trying to work out. 
Thanks anyway


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
