### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by mattx38** [eouia/MMM-AssistantMk2#344]
Hello,

Google Assistant can answer a text querry (tested when using node auth_and_test.js), but doesn't response anything when asking a question using voice.

I'm on Raspberry 3+ and my microphone is working well.
When I say "smart mirror", it opens Google Assistant, I ask to know the weather or the time, and dots keep bouncing, then after a while, it write (in french) that it didn't understand, the screen goes back to Magic Mirror and next to the Hotword icon, it's written "smart mirror".
Then, it doesn't react anymore to the keyword, and I have to restart MMM.

What's wrong ??

**Comment by eouia** [comment]
show me your config and logs.

**Comment by mattx38** [comment]
Sorry, I just reinstalled everything and use the simple configuration sample and it works great !
Can you delete my issue ?

**Comment by mattx38** [comment]
Hello again,

I would like to thank you for your excellent job on this module. It’s great and my kids keep asking jokes to it ;-)

Do you know how to ask the assistant to add an appointement to a specific google agenda ?

Matt

**Comment by eouia** [comment]
If you mean add an event to calendar, just say "new event" or "new
appointment" or "add an event to my calendar" or ...

**Comment by mattx38** [comment]
Ok but how can I configuré it to add appointment to a specific calendar ?
We have a Google family calendar that is not on the Google account I used to configure Your MMM-Assistant. 

Matt

**Comment by eouia** [comment]
Generally, the calendar name might work, but not tested.
If the calendar is not owned by you, impossible. 
Anyway, that's Google Assistant Service's job, not this module.

**Comment by mattx38** [comment]
Ok. When I try to add an appointment to the agenda it ask me to open Google Assistant with my mobile. 

Matt

**Comment by eouia** [comment]
Hmmm.. usually for me, "new event" is enough to activate conversation. But only Google knows how to handle conversation. Sorry, that is not module's job.

**Comment by mattx38** [comment]
Ok I understand. 
I keep searching. 

Matt

**Comment by mattx38** [comment]
Hello again. 

If I could register my Mirror as a Google Assistant related device, I think I could fix my agenda issue. 


Matt
