### ISSUE TITLE
Setting an alarm works but does't sound an alarm

### ISSUE THREAD

**Issue by wilburforce83** [eouia/MMM-AssistantMk2#349]
**Describe the problem**
When you set an alarm using Assistant on the mirror, the alarm does not trigger.

**To Reproduce**
*hotword* set an alarm for 10 minutes.

Assistant replies with the alarm set time and confirmation

**Expected behavior**
An alarm should sound at the given time.

Is this just a feature which isn't integrated? many thanks!

**Comment by eouia** [comment]
Alarm and some native features are not supported in SDK level. Purpose of this SDK is not being an alternative of real Google Home devices.
https://developers.google.com/assistant/sdk/overview
![image](https://user-images.githubusercontent.com/1720610/77788903-5bf35100-7062-11ea-95b7-3c7d837b7a05.png)

**Comment by wilburforce83** [comment]
Thanks! Perfect, that's fine. I think might do a recipe for alarms and
timers as my mirror is in the kitchen it'll be perfect for cooking!

Got nothing better to do on lockdown lol!

Cheers

Will

**Comment by eouia** [comment]
Recipe for alarm is possible. But you need some knowledge of programming.
Have a good day.

**Comment by wilburforce83** [comment]
That's fine. I am a reasonable nodejs developer, I've built a number of
personal modules for MMM and develop electron apps too, so should be okay.
The recipe wiki seems pretty good on here too.

Thanks!
