### ISSUE TITLE
Error: /urs/lib/arm-linux-gnueabihf/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by sweup** [eouia/MMM-AssistantMk2#35]
When following the suggested commands - I got:

pi@raspberrypi:~ $ sudo apt-get install build-essentials
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package build-essentials

pi@raspberrypi:~ $ sudo apt-get install gcc-5
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package gcc-5

Any other way to make it work?

**Comment by eouia** [comment]
what is your device and the OS version?

**Comment by eouia** [comment]
First you can try this.
```
sudo apt-get update
sudo apt-get upgrade
```
Then, try again.

**Comment by sweup** [comment]
Thanks for reply eouia.

I followed your guide, including 
sudo apt-get update
sudo apt-get upgrade

My version and device below:

pi@raspberrypi:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by eouia** [comment]
Raspbian Jessie have missed some dependencies. It is somehow aged.(Stretch is latest.) My module depends on some latest dependencies which is not included in Jessie by default. Above “build-essentials” or “gcc-5” is needed. 
My recommendation is using Raspbian Stretch.

**Comment by sweup** [comment]
Thanks for reply, I updated to stretch this morning and now it seams go work, thanks

**Comment by eouia** [comment]
Sounds so good. I'll close this issue.
By the way, I'm making whole new update to fix some annoying issues with removal some complex dependencies. Plz wait a few days.
