### ISSUE TITLE
No reponse from Google Assistant

### ISSUE THREAD

**Issue by Bronno** [eouia/MMM-AssistantMk2#350]
**Describe the problem**
After some activities (perhaps changing the mirror from VGA connection to HDMI cable....) I do not get any answer anymore from Google Assistant. Starting with the question and understanding the question is going well: the question is visible on the mirror. After that no answer: sometimes waiting, sometimes as response:  "Sorry I dont know the answer"

**To Reproduce**
I started with the re-installation of MMM-AssistantMk2. That went all well. With auth_and_test.js I fill in the code. But after the questions, it ends without an answer: 

pi@raspberrypi:~/MagicMirror/modules/MMM-AssistantMk2 $ node auth_and_test.js
Opening OAuth URL. Return here with your code.
Paste your code: 4/yAE0xxxxxxxxxxxxxxxxxxxxxxxxxxxx
Type your request: what is the time
Assistant Response: 
Conversation Complete

Getting the permission and code from Google Assistant on the browser seems to go well

**Environment:**
 - Device : [e.g. RPI 4b+]
 - OS: [e.g. Raspbian Stretch]

**Before you post issue, try this first**
- MMM-Hotword seems to go well. I bypassed other problems by testing with auth_and_test.js. A second time again: no answer from GA

If you have an idea what could be the reason, that would be perfect. Thanks.

**Comment by eouia** [comment]
What language were you saying? And what phrase have you queried?
Usually, it happens when **GA CANNOT UNDERSTAND YOUR PHRASE REALLY**. and most case, it is caused by the misconfiguration of language.

**Comment by Bronno** [comment]
ok, It is solved with that. With auth_and_test.js it did not understand the question like: "what is the time", "what is the date". The reasion was not no connection. If I ask "what is your name"... I get response. And I had problems with the name of the file: defaults.json in stead of default.json. Thanks!!
