### ISSUE TITLE
How Can I Get It To Play beep.wav Instead Of ding.wav?

### ISSUE THREAD

**Issue by Isopod00** [eouia/MMM-AssistantMk2#36]
I have installed the newest MMM-AssistantMk2 update, and so far I am finding it extremely useful as far as the new "MP3" audio out option. I also like that it plays a sound effect when it is ready to be given a command. I just have one complaint, and it is that I find the default ding.wav to be very annoying, so I want to change it to something else. I saw that there are two other sounds included in the resources folder, and I really like the one named "beep.wav". The only problem is, if I get rid of ding.wav and rename beep.wav to ding.wav, or change the file mentioned in node_helper.js from ding.wav to beep.wav, it simply doesn't play a sound at all and won't listen for me to speak. And the weird thing is, even if I revert my changes and go back to the original ding.wav it still doesn't play any sounds anymore. Am I doing something wrong? How can I get it to play beep.wav instead?
Thanks

**Comment by eouia** [comment]
Well, about that issue, currently I have no idea.
Anyway, I’m making whole new update for fixing some issues - including your issue; Plz wait a few days.

**Comment by Isopod00** [comment]
Okay, sounds good. I’ll wait for the new update to come out. Thanks!
