### ISSUE TITLE
WARNING! Could not load config file. Starting with default configuration. (NODE_VERSION 64, 57)

### ISSUE THREAD

**Issue by Louienoh** [eouia/MMM-AssistantMk2#37]
Hi

First of all, i really appreciate your kind manual i've followed as well.

I've followed every steps without any problem, but i was pretty confuesd from the step 'CONFIGURATION'

i'd like to use it with default, so i just edit config.js like
"{
  module: "MMM-AssistantMk2",
  position: "top_left",
  config: {}
},"
only.
 But i got this error MSG, so could you please help me this problem?

WARNING! Could not load config file. Starting with default configuration. Error found: Error: The module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/speaker/build/Release/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by eouia** [comment]
Read this;
https://github.com/eouia/MMM-AssistantMk2#installation

**Comment by Louienoh** [comment]
> Read this;
> https://github.com/eouia/MMM-AssistantMk2#installation

Thank you genius!
I did these steps agian,
`cd ~/MagicMirror/modules/MMM-AssistantMk2
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild `

and it starts as well.

But i have no idea how i can wake up my Google Assistant.
Should i install 'hotword' and 'NotificationTrigger'?
Or can you tell me any phrase i can test it is working?

**Comment by eouia** [comment]
Which type do you want to use as a waking method?
- Voice Hotword (like "jarvis") : `MMM-Hotword` & `MMM-NotificationTrigger` are needed.
-  custom voice Hotword (like "My mirror") : above both modules and `snowboy personal voice model(.pmdl)` is also needed (https://snowboy.kitt.ai)
- Using touchscreen Or mouse : Just click the mic Icon (you don't need above 2 additional modules)
- H/W Button? Some kind of Sensors? : If exists, Control module for those device & `MMM-NotificationTrigger` are needed.

**Comment by Louienoh** [comment]
> Which type do you want to use as a waking method?
> 
> * Voice Hotword (like "jarvis") : `MMM-Hotword` & `MMM-NotificationTrigger` are needed.
> * custom voice Hotword (like "My mirror") : above both modules and `snowboy personal voice model(.pmdl)` is also needed (https://snowboy.kitt.ai)
> * Using touchscreen Or mouse : Just click the mic Icon (you don't need above 2 additional modules)
> * H/W Button? Some kind of Sensors? : If exists, Control module for those device & `MMM-NotificationTrigger` are needed.

So, i'm in the first one steps, so i'm downloading MMM-Hotword now.
But i got an issue again...

"
npm WARN MMM-Hotword@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-26T15_11_32_731Z-debug.log
"

I tired all the way of [https://github.com/eouia/MMM-Hotword](url), but it works on mine T-T...

Could you please help me with this problem?

**Comment by Louienoh** [comment]
> Which type do you want to use as a waking method?
> 
> * Voice Hotword (like "jarvis") : `MMM-Hotword` & `MMM-NotificationTrigger` are needed.
> * custom voice Hotword (like "My mirror") : above both modules and `snowboy personal voice model(.pmdl)` is also needed (https://snowboy.kitt.ai)
> * Using touchscreen Or mouse : Just click the mic Icon (you don't need above 2 additional modules)
> * H/W Button? Some kind of Sensors? : If exists, Control module for those device & `MMM-NotificationTrigger` are needed.

> Which type do you want to use as a waking method?
> 
> * Voice Hotword (like "jarvis") : `MMM-Hotword` & `MMM-NotificationTrigger` are needed.
> * custom voice Hotword (like "My mirror") : above both modules and `snowboy personal voice model(.pmdl)` is also needed (https://snowboy.kitt.ai)
> * Using touchscreen Or mouse : Just click the mic Icon (you don't need above 2 additional modules)
> * H/W Button? Some kind of Sensors? : If exists, Control module for those device & `MMM-NotificationTrigger` are needed.

So, i'm in the first one steps, so i'm downloading MMM-Hotword now.
But i got an issue again...

"
npm WARN MMM-Hotword@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-26T15_11_32_731Z-debug.log
"

I tired all the way of [https://github.com/eouia/MMM-Hotword](url), but it works on mine T-T...

Could you please help me with this problem?

**Comment by Louienoh** [comment]
> I think those logs are not the FIRST errors. There could be more, right?
> Tell me your Raspberry device name and Raspbian OS Version.

Yes sir, it is all of the msg contents
"
npm WARN deprecated hoek@2.16.3: The major version is no longer supported. Please update to 4.x or newer

> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.12.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.12.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at evalScript (internal/bootstrap/node.js:582:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:96:20)
    at Object.runInThisContext (vm.js:303:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at evalScript (internal/bootstrap/node.js:582:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 4.14.71-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v10.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
gyp ERR! configure error 
node-pre-gyp ERR! build error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
node-pre-gypgyp  ERR!ERR!  stack     at ChildProcess.emit (events.js:182:13)
stackgyp Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
 ERR!node-pre-gyp  stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
ERR! stack     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR!gyp  stackERR!     at ChildProcess.emit (events.js:182:13)
 Systemnode-pre-gyp Linux 4.14.71-v7+
 ERR! gyp stackERR!     at maybeClose (internal/child_process.js:962:16)
 commandnode-pre-gyp "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
 ERR!gyp stack      at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gypnode-pre-gyp  ERR!ERR!  Systemnode -v Linux 4.14.71-v7+
 v10.12.0
gypnode-pre-gyp  ERR!ERR!  commandnode-gyp -v v3.8.0
 "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
gyp node-pre-gyp ERR! ERR!not ok 
 cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
node-pre-gyp ERR! node -v v10.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
npm WARN MMM-Hotword@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-26T15_11_32_731Z-debug.log
"

and my Raspberry2 information:
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by Louienoh** [comment]
> Anyway, you can try this;
> 
> ```
> cd ~/MagicMirror/modules/MMM-Hotword/node_modules
> git clone https://github.com/Kitt-AI/snowboy
> cd snowboy
> npm install
> ./node_modules/node-pre-gyp/bin/node-pre-gyp clean configure build
> ```

I REALLY REALLY appreciate your kind help!
I'm doing the steps you gave,
Unfortunately I'm stuck again XP

It says below in npm install in snowboy dir.

"
> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> snowboy@1.3.1 prepublish /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> tsc --listFiles

/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/typescript/lib/lib.es6.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.ts
/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/node-pre-gyp.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/SnowboyDetectNative.d.ts
/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/node_modules/@types/node/index.d.ts
audited 288 packages in 36.355s
found 8 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
"

**Comment by Louienoh** [comment]
> ```shell
> cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> npm install electron-rebuild
> npm install nan
> ./node_modules/.bin/electron-rebuild   # It could takes dozens sec.
> ```

FINAILLY I MADE IT ALL,
IT'S ALL THANKS TO YOU I REALLY TOTALLY APPRECIATE(I'm almost crying now T-T)

I was just a NB so that i didn't know anything.
Sorry for i bordered you with too many and too basical questions, but you gave me really kind help so much.

I hope every NBs(like me) can follow this thread.

Thank you again sicerely.

**Comment by Louienoh** [comment]
> ```shell
> cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> npm install electron-rebuild
> npm install nan
> ./node_modules/.bin/electron-rebuild   # It could takes dozens sec.
> ```

One more quick question!

Can i set the name again?
Cuz it was set already through my bad Pronunciation lol

**Comment by eouia** [comment]
What name? Hotword? Unfortunately common universal models are “jarvis”, “smart mirror” and “snowboy”. If you want to use other custom hotword, go to https://snowboy.kitt.ai and make your own.

**Comment by Louienoh** [comment]
> What name? Hotword? Unfortunately common universal models are “jarvis”, “smart mirror” and “snowboy”. If you want to use other custom hotword, go to https://snowboy.kitt.ai and make your own.

Really appreciate again!!
