### ISSUE TITLE
Cannot play YouTube videos

### ISSUE THREAD

**Issue by felangga** [eouia/MMM-AssistantMk2#38]
Hello I just installed this modules on magicmirror. 
But when I want to play youtube videos, she said that she didn't know how to play that. 
I already put youtube true to the config file. Did I missing something ?

**Comment by eouia** [comment]
If she said "Sorry, I don't know how to do" or "I can't help you blah blah blah...", Check configuration `useScreen:true`. When `useScreen` is set as `false`, it cannot play youtube.

Anyway, I'm building this module whole newly again. Some issues will be solved with new version. Plz wait a few days.

**Comment by felangga** [comment]
Ohhh I see, yes I disabled the useScreen
Okay I'll wait, thanks great module :)
