### ISSUE TITLE
YouTube - No response audio is returned

### ISSUE THREAD

**Issue by Kris-014** [eouia/MMM-AssistantMk2#44]
Hi @eouia 
Thanks as usual for your big help and always prompt reply, after the latest update I cannot play anymore youtube videos, and a pop up jump on the mirror saying: No response audio is returned
I can actually listen to the assistance but it breaks only when i try to activate youtube.
My config is default with device: "plughw:1"

I got this random errors but might be not related:

Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
(node:27858) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'refs' of undefined
(node:27858) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:27858) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'refs' of undefined

**Comment by eouia** [comment]
Which query terms did you try to search video?
“No response audio...” means google assistant didn’t return any voice.
And then f you set useScreen:false or youtubeAutoplay:false, then youtube will not be played automatically

**Comment by Kris-014** [comment]
Same I always used, my query is:
YouTube $anything

Both value you mention are set to True.

On 9 Nov 2018, at 22:15, Seongnoh Sean Yi <notifications@github.com<mailto:notifications@github.com>> wrote:


Which query terms did you try to search video?
“No response audio...” means google assistant didn’t return any voice.
And then f you set useScreen:false or youtubeAutoplay:false, then youtube will not be played automatically

**Comment by Kris-014** [comment]
more infos.. seems it is able to match a video but it still go back to, NO RESPONSE AUDIO IS RETURNED

[AMK2] Transcription: YouTube video qualsiasi cosa  --- Done: true
[AMK2] video found: -zwngiVZJZ0
[AMK2] Device Action: { requestId: '5be494bd-0000-2ec7-b999-94eb2c1XXXac' }
[AMK2] Assistant Text Response: 
[AMK2] NO RESPONSE AUDIO IS RETURNED.

**Comment by eouia** [comment]
NO RESPONSE AUDIO IS RETURNED itself is not a problem. Sometimes Google do not respond voice data at all(Google dev team already know this issue)
If you don’t want this alert message, set “responseAlert:false” and “errorAlert:false”

YouTube not be played is another problem. Is there any front end error message? You can check with “npm start dev”

**Comment by Kris-014** [comment]
You are totally right i was only checking the alert on the screen, this is the errors I found on the front end as suggested:

=================
MMM-AssistantMk2.js:286 [AMK2]  [AMK2] Error:
=================
www-widgetapi.js:93 Error while parsing the 'allow' attribute: 'accelerometer;', 'autoplay;', 'encrypted-media;', 'gyroscope;', 'picture-in-picture' are invalid feature names.
Ya	@	www-widgetapi.js:93
W	@	www-widgetapi.js:81
Y	@	www-widgetapi.js:102
playYoutubeVideo	@	MMM-AssistantMk2.js:623
conversationEnd	@	MMM-AssistantMk2.js:573
socketNotificationReceived	@	MMM-AssistantMk2.js:222
(anonymous)	@	module.js:246
......
Looks like is complaining for this below code line is it?

function Ya(a,b){for(var c=document.createElement("iframe"),d=b.attributes,e=0,g=d.length;e<g;e++){var f=d[e].value;null!=f&&""!=f&&"null"!=f&&c.setAttribute(d[e].name,f)}c.setAttribute("frameBorder",0);c.setAttribute("allowfullscreen",1);c.setAttribute("allow","accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture");c.setAttribute("title","YouTube "+V(a.b,"title"));(d=V(a.b,"width"))&&c.setAttribute("width",d);(d=V(a.b,"height"))&&c.setAttribute("height",d);var n=a.u();n.enablejsapi=

**Comment by eouia** [comment]
I need both front-end error log and back-end error log together. Your last posting about front-end error is not matched with your prior post about back-end error.
Have you an account of Telegram? I can talk about this more detaily on Telegram. Mine is `@eouia`. Give me a talk anytime.

**Comment by eouia** [comment]
This issue is solved on last update(2.1.2). I'll close this issue.
