### ISSUE TITLE
Mic No Longer Detects Voice

### ISSUE THREAD

**Issue by Isopod00** [eouia/MMM-AssistantMk2#45]
Ever since the new update the assistant has not been able to respond to my voice. I am using the google aiy voice hat with the included microphone board. I suspect that this has something to do with the "device ID", because I have no idea whatsoever of what it is or how to find it. Help please?

**Comment by Isopod00** [comment]
Update: I think that the device ID might be"plughw:0", but I'm not sure because when i put that into the config it didn't work. Also for clarification, I'm trying to use the config with just mmm-assistant and mmm-hotword, no gactions yet

**Comment by eouia** [comment]
Find your device by ‘lsusb’, ‘arecord -l’ and ‘aplay -l’

**Comment by Isopod00** [comment]
Thanks. I solved the problem by using the config format from the old version with mmm-notificationtrigger. But I’m not sure if that will still work long term once I start incorporating gactions, so if I start having problems I’ll add the device ID for the mic.
