### ISSUE TITLE
auth_and_test.js

### ISSUE THREAD

**Issue by vaine4** [eouia/MMM-AssistantMk2#5]
Hi ! I'm a beginer and I'm trying to install this on a raspberry pi zero :D
Here is my node and npm version :3
```
node -v
    v10.6.0
npm -v
    6.2.0
```
So when I try to launch ``auth_and_test.js`` it just return me ``Illegal instruction``. Same when I launch the MM server with ``node serveronly`` 
```
node auth_and_test.js
    Illegal instruction
```

I'm new on git, I expect my formating is fine and that you've got enough information 
Thank you for your futures answers c:

**Comment by eouia** [comment]
I doubt pi zero could run, because some dependencies have possibility of not working properly.
First you can try to rebuild your node modules by

npm rebuild

**Comment by vaine4** [comment]
I still get this error :/ 
with both ``sudo npm rebuild`` and ``npm rebuild``

**Comment by eouia** [comment]
The only thing I've guessed from your Error, Pi zero has the too low architecture(armv6), and some of the dependencies should work on armv7 architecture (above Pi2).
I'm not an expert about that, thus at this moment the only thing I can suggest is, 

```
npm rebuild --build-from-source #It will take very long hours especially in Pi Zero.
```

If with this commands You couldn't get success, it seems no way except rebuilding all the node modules from source, but that is too difficult for a non-expert. Sorry.

**Comment by eouia** [comment]
Have you solved your problem? I'll close this issue.

**Comment by vaine4** [comment]
Hey, sorry for behing absent. I was very busy and I didn't had time to work on my MM 

Build from source took a very long time as you said and IT WORK !!! 
Thank you very much !

**Comment by eouia** [comment]
Good to you! It's my pleasure.

**Comment by sagunraul** [comment]
i dont have auth_and_test.js file plz help me bro how to fx this i have tried to install new snowboy but it shows same
