### ISSUE TITLE
MMM-AssistantMK2 stops recognizing hotwords after first conversation completed

### ISSUE THREAD

**Issue by schlaumeyer** [eouia/MMM-AssistantMk2#57]
First of all thank you for providing this great project! I am trying to get it work for a while now. Although I am close to success I still failed.

My current issue is that MMM-AssistantMK2 stops recognizing hotwords after my first conversation completed successfully. I tried two different microphones with same result.

I used "dev" mode but couldn't see the reason for failure. Can you help me with this? 

Below you can find my terminal output and chromium console output. The config I didn't add because I use the long version. But of course, if required I can send.

Thank you very much for your support in advance!

**terminal output**
[HOTWORD] begins listening.
[AMK2] Temporal storage directory is clearing.
[HOTWORD] <<  snowboy  >> is detected.
[HOTWORD] stops listening
[AMK2] assistant ready
[AMK2] Conversation starts.
Recording 1 channels with sample rate 16000...
Recording 44 bytes
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
[AMK2] Transcription: how  --- Done: false
[AMK2] Transcription: how's  --- Done: false
[AMK2] Transcription: how's the  --- Done: false
[AMK2] Transcription: how's the weather  --- Done: false
Recording 4000 bytes
Recording 4000 bytes
[AMK2] Transcription: how's the weather in  --- Done: false
Recording 4000 bytes
Recording 4000 bytes
[AMK2] Transcription: how's the weather in New  --- Done: false
[AMK2] Transcription: how's the weather in New  --- Done: false
[AMK2] Transcription: how's the weather in New  --- Done: false
Recording 4000 bytes
[AMK2] Transcription: how's the weather in New  --- Done: false
[AMK2] Transcription: how's the weather in New York  --- Done: false
Recording 4000 bytes
Recording 4000 bytes
[AMK2] Transcription: how's the weather in New York  --- Done: false
[AMK2] Transcription: how's the weather in New York  --- Done: false
Recording 4000 bytes
Recording 4000 bytes
[AMK2] Transcription: how's the weather in New York to  --- Done: false
Recording 4000 bytes
[AMK2] Transcription: how's the weather in New York tomorrow  --- Done: false
[AMK2] Transcription: how's the weather in New York tomorrow  --- Done: false
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
Recording 4000 bytes
[AMK2] Transcription: how's the weather in New York tomorrow  --- Done: false
Recording 4000 bytes
Recording 4000 bytes
[AMK2] end-of-utterance
End Recording: 3168.026ms
[AMK2] Transcription: how's the weather in New York tomorrow  --- Done: true
[AMK2] Device Action: { requestId: '5bfdf1c2-0000-2c80-a212-f403043e9204' }
[AMK2] Assistant Text Response:
[AMK2] Conversation Completed

**Chromium console output**
MMM-AssistantMk2 is resumed.
module.js:205 MMM-Hotword is resumed.
temp.html:60 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
Q @ temp.html:60
X @ temp.html:60
(anonymous) @ temp.html:64
temp.html:64 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
(anonymous) @ temp.html:64
temp.html:64 [Violation] 'load' handler took 217ms
[Violation] Forced reflow while executing JavaScript took 187ms

**Comment by eouia** [comment]
I think you've missed this configuration for MMM-AssistantMk2
```
notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
},
```

**Comment by schlaumeyer** [comment]
Thanks again! That was indeed the reason!

I added it to my configuration and it worked well.
