### ISSUE TITLE
Change YouTube video quality

### ISSUE THREAD

**Issue by mrronzy123** [eouia/MMM-AssistantMk2#58]
Hi. 
Firstly I'd like to thank you for making this module and hands down this is one of the best module for MM. The installation was fairly simple too. 
Is there any way that i can change the video quality of youtube? It defaults to 1080p which makes the video choppy. Whereas the videos which are max 480p works butter smooth on it.
Ps. using latest MM and AssistantMk2 on RPI 3b+.

**Comment by eouia** [comment]
It is automatically changed to match with your network staus and play environment, but I consider to add option for that.

**Comment by mrronzy123** [comment]
Awesome. Looking forward for amazing updates 😁
