### ISSUE TITLE
won't show in Google Home app

### ISSUE THREAD

**Issue by nickbeaulieu98** [eouia/MMM-AssistantMk2#59]
I've followed the directions in the documentation perfectly, but I cannot get my mirror to show up in my Google Home App on my phone.

**Comment by eouia** [comment]
Well, I have no idea about this. If there was no error, I have nothing to suggest.

**Comment by nickbeaulieu98** [comment]
it's showing now.

**Comment by eouia** [comment]
Nice to hear this. Have a nice day.
