### ISSUE TITLE
Adding a Profile

### ISSUE THREAD

**Issue by ThePflu** [eouia/MMM-AssistantMk2#6]
Hello there,
I can't ad a new Profile (the very firts one)
The Problem is that the Autificationpage doesn't work.
I have dubble checked it all and i can't find my mistake.
Pleas fix this (if it isn't my fault that it is not working).

**Comment by eouia** [comment]
Sorry, I cannot catch your words. Please tell me more details. Screenshot or error logs will be a help.

**Comment by ThePflu** [comment]
I'm sorry,
now i hae´ve figured out what my problem was.
I had made every time the same mistake while creating the project

I'm realy sorry 
but now its working ; )

**Comment by eouia** [comment]
Good luck to you.

**Comment by dvbit** [comment]
In the instructions there is a high level description . To allow google auth one shall access also google oauth screen page in the project details and set the mail at least (for me it was not set and generated a 500 error)
 After doing that all fine
