### ISSUE TITLE
Conversation Error

### ISSUE THREAD

**Issue by nickbeaulieu98** [eouia/MMM-AssistantMk2#60]
When I click the icon to start recognizing my voice it doesn't hear me and ends with a Conversation Error. I've confirmed that my mic works using arecord.

**Comment by eouia** [comment]
Conversation error usually means wrong mic setup. 
First check your mic device with `arecord -l`. You can see hw card and device no. Then setup the device in `record` section of configuration.

**Comment by nickbeaulieu98** [comment]
Thank you, that's what I was missing. That works now. :)
