### ISSUE TITLE
Icon not displayed

### ISSUE THREAD

**Issue by IgorUserowsky** [eouia/MMM-AssistantMk2#63]
Installed on Pi3b in kiosk mode with some difficulty. Had to rebuild electron with grpc 1.13 as suggested in readme.

The module does load and plays the google tone (two beeps) on startup, however the icon is not displayed at all. Since I didn't get hotword running yet, there is no way to interact.

mm-error.log
`
0|mm       | error: kann '.git/FETCH_HEAD' nicht öffnen: Keine Berechtigung

0|mm       | error: kann '.git/FETCH_HEAD' nicht öffnen: Keine Berechtigung

0|mm       | error: kann '.git/FETCH_HEAD' nicht öffnen: Keine Berechtigung

0|mm       | { Error: EACCES: permission denied, open '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/1544931585364.mp3'

0|mm       |   errno: -13,

0|mm       |   code: 'EACCES',

0|mm       |   syscall: 'open',

0|mm       |   path: '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/1544931585364.mp3' }

0|mm       | [AMK2] - temporal HTML creation fails. E: Error: EACCES: permission denied, open '/home/pi/MagicMirror/modules/MMM-AssistantMk2/tmp/temp.html'

0|mm       | 1

0|mm       | (node:7575) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: OAuth required

0|mm       | (node:7575) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

Do I have a permissions issue?

Thankful for any/all help

p.s.: the german phrase used in google for repeat after me is "Sprich mir nach:"

**Comment by eouia** [comment]
`Permission denied` means, you have wrong permission of your directories. How did you installed? I doubt you to have prepended `sudo` something to my instruction. Only `apt` related commands need `sudo`. If you did something with `sudo` which is not related to `apt`, could make this problem.

**Comment by IgorUserowsky** [comment]
thats probably the case.

any idea which parts i could chown /chmod?

or should i delete the folder and install fresh?

**Comment by IgorUserowsky** [comment]
did install from scratch, working fine now

thank you for your help!

p.S.: still dont know how to do the PR with changes, german phrase for repeat after me as requested in README is "Sprich mir nach:"

**Comment by eouia** [comment]
Nice to you.
Thank you. I'll add that in next patch.
