### ISSUE TITLE
Youtube not playing video

### ISSUE THREAD

**Issue by nagas88** [eouia/MMM-AssistantMk2#65]
Hello,
I installed the latest update and get the following message: "Sorry I can't help with that yet".
My input is: Play Linking Park In the End on Youtube.

THanks for a great module!!
Regards, Alex

**Comment by eouia** [comment]
I think, the main reason might be you are using `play`. It is reserved for playing "Google Music" or "Youtube Music" (or spotify, anything for playing music as default Application of Google Assistant) and this SDK doesn't support this feature (playing google music) yet.
Just try saying "Linkin Park in the End youtube" instead "play"

**Comment by nagas88** [comment]
should I have some other app installed for this? I have no other thing that might play it.
also she says now when I say without `play` the same answer :(

**Comment by eouia** [comment]
No app to be installed. Just it's unsupported feature yet. So, you just cannot use reserved keyword `play`.
Anyway, without `play` you cannot get same answer? Very weird. Your other query would work? (e.g. How is the weather? What time is it now?)
Just try `Linkin Park In the end`. Let's see what is going on. I can get the result with that sentence.
PS. What is your language setting of Assistant? English? or other?

**Comment by eouia** [comment]
Now I know what was wrong.

`responseScreen` is needed for getting Assistant Search result. By default, Assistant doesn't return Youtube search result (You cannot do that with REAL Google Home). Only SCREEN surface capable device - like Smart TV, Lenovo Smart Screen - can get extended features like youtube search. 
With `responseScreen:true`, this MMM-AssistantMk2 can get youtube search result too.

**Comment by nagas88** [comment]
thanks! now it works. It retrieves the video but it does not play it. It just keeps a black screen on and I have to restart mm.

do you happen to know what;s up?

**Comment by eouia** [comment]
I need frontend log for analyze. stop `pm2` (if you are using), then, execute `npm start dev` for MM. You can see frontend dev console in your MM screen. See the console tab, then you can find many messages. (To make things simple, disable or remove other modules from configuration). Capture or Take a snap and send me. (eouia0819@gmail.com or Telegram:@eouia)

**Comment by nagas88** [comment]
I have removed all modules and left only the clock.
The youtube video is playing. So it seems there is an issue with the overlapping of modules. The AssistantMk2 does not overlap other modules and youtube does not play?

sent you a screen  via email of the console.

**Comment by eouia** [comment]
I read your mail.
The fact - without other modules it works - means, there might be some frontend error in your other modules. Youtube player API seems to be interrupted by other module's error. Test with adding other module one-by-one could find which module has error.
Or you can put all your modules in config, then try `npm start dev` and which suspicious error or message happens.

**Comment by eouia** [comment]
Have you still got this issue? There seems no feedback anymore, so I'll close this issue. You can re-open or leave another issue here any time. Have a nice day.

**Comment by bachoo786** [comment]
hey @eouia how do I play youtube videos on mm using your assistantmk2? what is the set up?

**Comment by eouia** [comment]
just say "SONG TITLE and ARTIST" like "Linkin Park Crawling"
