### ISSUE TITLE
First part of audio response missing.

### ISSUE THREAD

**Issue by AndyC3108** [eouia/MMM-AssistantMk2#67]
Hi - hope you can help?

I'm using MMM-AssistantMk2 with MMM-Hotword.  All works great (many thanks) except that when I issue a voice command, the first couple of seconds are cut off from the response.  Don't know whether this is just a timing issue (cpu lag from the Pi), but is there a way of adding a small delay to the response to try and avoid missing the first part of the audio response?

Many thanks is advance...

Andy

**Comment by eouia** [comment]
What kind of sound play program are you using? ‘mpg321’? Change it to other program.

**Comment by AndyC3108** [comment]
Hi & thanks for the quick response.

I have tried mpg321 & omxplayer.

In the config.js file (in the MMM-AssistankMk2 config section) I have tried playProgram: "mpg321"  and also tried playProgram: "omxplayer", but neither makes any difference.  The audio clipping is the same every time (it always misses the first couple of seconds of the audio response).  In other words, the clipping is identical every time.

Many thanks...

**Comment by eouia** [comment]
Ok, test once more.
When Assistant is saying something(even though some secs are missed), Stop the MM.
Then you can find `XXXX.mp3` in your `MMM-AssistantMk2/tmp` directory. 
play it with `mpg321` or `omxplayer` in your terminal shell by manual. How it works? Still first some secs would be missed? In that case, my module might have something wrong.
But the original temp file has no missed part, Hmmmm.. I think this issue could be something related with system performance.

**Comment by AndyC3108** [comment]
Hi & thanks again for the quick reply.

I was just trying different audio outputs and thought about HDMI as you replied.  Indeed it is HDMI that is the issue (audio out via Pi output is fine).  Thanks for you help & kind regards...

**Comment by eouia** [comment]
I'll close this. Have a nice day.

**Comment by talving** [comment]
Just seems weird to me why the raspberry pi would cut of the beginning of the audio when using MMM-AssistantMk2 on HDMI but if you for example play a .mp3 file from VLC the audio is just fine?

I've tried mpg321 & omxplaye but that dosen't seem to affect the sound delay, this seems like a quite big problem since I would think about 50% is gonna wanna use the HDMI for sound and video.

**Comment by eouia** [comment]
@talving I'm building a updates to solve that problem by removing dependency to external audio player, but nowadays I have not enough time to finish. sorry.

**Comment by talving** [comment]
I understand, would gladly donate a couple bucks if this could help you with that update or so! 

I've tried doing a "bad quick fix" by just getting a "beep" sound go of for about 1-2 seconds before Google Assistant, just so the beep triggers the hdmi and then The Google Assistant starts talking. But got no luck so far..
