### ISSUE TITLE
MM set to imperial and Voice to en _GB but it changes output to metric

### ISSUE THREAD

**Issue by enduser001** [eouia/MMM-AssistantMk2#69]
I don't know if this is a bug or just the way it is. I wanted to have my voice with a British accent for my MM voice assistant. However, it changed all the values to metric. So when I ask for the weather, it outputs into celsius. Is there a way I can work around it?

**Comment by eouia** [comment]
For Celsius/Fahrenheit you can change it with your google assistant app on your phone. (In setting > weather)

**Comment by enduser001** [comment]
works. next challenge is getting this to work on armbian on tinkerboard.
