### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by tvaneynde** [eouia/MMM-AssistantMk2#7]
Hi

Is it possible to change the language to Dutch?

Tomas

**Comment by eouia** [comment]
By Google API docs,  Currently available languages are below;
  de-DE, en-AU, en-CA, en-GB, en-US, en-IN
   fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR
 https://developers.google.com/assistant/sdk/reference/rpc/languages
