### ISSUE TITLE
Unable to change YouTube video quality 

### ISSUE THREAD

**Issue by mrronzy123** [eouia/MMM-AssistantMk2#70]
Using youtubePlayQuality: "small", in my config does not affect the YouTube video quality. The video still shows up at 1080p and thus i get video buffer issue. I have pasted my config for AssistantMk2 below. Is there anything that i am doing wrong. 

{
    module: "MMM-AssistantMk2",
    position: "top_left",
    config: {
	deviceLocation: {
      coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
        latitude: 19.2459894, // -90.0 - +90.0
        longitude: 72.8456078, // -180.0 - +180.0
      },
    },
	profiles: {
      "default" : { // profile name.
        profileFile: "default.json", // profile file name.
        lang: "en-IN"
        //currently available (estimation, not all tested):
        //  de-DE, en-AU, en-CA, en-GB, en-US, en-IN
        // fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR
        // https://developers.google.com/assistant/sdk/reference/rpc/languages
      },
      
    },
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },
	pauseOnYoutube:false,
	youtubePlayQuality: "small",
      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  },

**Comment by eouia** [comment]
Nothing seems wrong. I'll check after holidays.  Merry holidays!

**Comment by eouia** [comment]
After research, I found these;
- Youtube API doesn't support changing playbackQuality any more. 
- It is deprecated API but not documented on it's manual.
- At my development stage, I tested. And I thought it seemed working but just coincidence.
Conclusion : That feature is not working. sorry.  I'll remove this feature at next update.
