### ISSUE TITLE
usb mic not picking up

### ISSUE THREAD

**Issue by enduser001** [eouia/MMM-AssistantMk2#71]
So close to getting this working on Armbian with a usb speaker/mic, however I am stuck.

HW profile: Tinkerboard, Armbian Stretch, Jabra USB 410 Speaker/Mic

arecord and aplay work. "plughw:1"

MMM-AssistantMk2 is communicating to google, tested with useWelcomeMessage: for weather and I get a response.

I just can't get it to respond to voice activation (not using MMM-hotword just yet). I did get this set up working on a Pi, but wanted the extra video performance of the TB.

I have used the expert settings for record config with device  : "plughw:1"
I have done an npm rebuild on both MM and this plugin, but for the life of me, it appears the mic is just not picking up.

**Comment by eouia** [comment]
Somewhat obvious question.
For activating by voice, you need MMM-Hotword also. After activating, you can ask query by voice with MMM-AssistantMk2. 
So, How did you activate MMM-AssistantMk2? (e.g: click the mic icon or extenal H/W button or PIR motion or any other things but vocal hotword.)

**Comment by enduser001** [comment]
Thank you for the quick reply. 

hm. sorry i thought ok google for voice. I did install MMM-hotword, clear NPM cache, rebuild electron and issue persists. Where is the log when verbose is enabled?

Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: MMM-Hotword
All module helpers loaded.

**Comment by enduser001** [comment]
i just recompiled snowboy in node modules of the MMM-Hotword. I have it working as a stand alone hotword to snowboy. 
Exited out of the env and  fired up MM, no errors, but she still doesn't seem to be responding to hotword in MM. I'll play with the MM config for Assistant and Hotword.

**Comment by eouia** [comment]
Show me your config and result of log. You need to adjust configuration to work both modules.

**Comment by enduser001** [comment]
Got it. I don't know what i did to get it, but it works now. Hooray! You sir are a gentleman and a scholar for helping figure this out. Thank you.

You can say this works on Tinkerboard with Armbian and USB mic!

**Comment by eouia** [comment]
Nice to you. I'll close this issue. Happy holidays.
