### ISSUE TITLE
Google Play Music or Spotify

### ISSUE THREAD

**Issue by RavixModz** [eouia/MMM-AssistantMk2#72]
First of all, I'd like to say that the assistant is working fine.
The only problem is that it's not possible to play music from Google Play Music or from a Spotify account that is connected to the Google account.
I don't think this is an issue with the module. 
When I say "play music" the response is "alright“ or „ok“ but is not starting to play any music.
How could I make the google assistant play music on the mirror?

Thanks for your help

**Comment by eouia** [comment]
Not supported on SDK level. Those features are allowed only to REAL GOOGLE HOME devices.
