### ISSUE TITLE
Youtube search, don't stop playing by next command

### ISSUE THREAD

**Issue by ratsplayer** [eouia/MMM-AssistantMk2#74]
Hi,

the youtube frame closes when i say the next command (for example "volume up"). 
Also it shows only the first result video.

Is there a way to have more youtube functionality?
I would like to have a youtube frame (maybe using additional module and control it with notifications) that does not stop when i say next command and where i maybe can choose betwen videos?
Of course i would like to say some youtube keywords and i would like to choose between the videos.

Maybe there is at least a configuration to not stop the video when saying the next command?

Thank you very much and Best Regards

Matthias

**Comment by eouia** [comment]
With `pauseOnYoutube:false`  your hotword will be stop the video.
Controlling video itself (like `volume up`) is not supported. Youtube Playing is not included in SDK. That is my implementation besides Original SDK
