### ISSUE TITLE
Add LED-like effect onscreen

### ISSUE THREAD

**Issue by Cr4z33** [eouia/MMM-AssistantMk2#75]
What if you include also a nice LED-like looking bar into the MM window?

It would be nice to see RGB lights (perhaps just the 4 typical Google colours) glowing or flashing when GA is speaking.

Considering that the screen is behind a spy glass they would look then like real LEDs, but they are just displayed on screen.

Four dots on a line (ie. center bottom) with green, blue, red and yellow mixing, moving or even bouncing would be cool, wouldn't they? 😃

**Comment by eouia** [comment]
I'll close this issue. thanks.
