### ISSUE TITLE
GA mk2 crashing

### ISSUE THREAD

**Issue by Koulouri** [eouia/MMM-AssistantMk2#78]
Followed the installation script, did the token thing but every time i add the assistant to the config.js, magicmirror starts, but with black screen (the only thing visible, is the backlight from my monitor). It is like it crashes. I wish i had more coding knowledge, so as to fix it myself. What should be the problem? (i have also installed hotword)

**Comment by eouia** [comment]
I think you didn't complete installation step (especially electron-rebuild).
But to examine details I need your error logs on crash and configuration.

**Comment by Koulouri** [comment]
Actually i didn't rebuild electron.. i will do so and let you know. Thanks
alot!!!

**Comment by Koulouri** [comment]
After rebuilding electron on both the Assistant and Hotword modules..
everything works like a charm! However, changing the position of the
Assistant module, doesn't allow the whole window to show (the one popping
up when assistant answers). Can i debug it somehow?

**Comment by eouia** [comment]
If you put module in `center` region(e.g: top_center), use other region.

**Comment by Koulouri** [comment]
worked! Thanks a lot!

**Comment by eouia** [comment]
Good to you. I'll close this issue.

**Comment by Koulouri** [comment]
Can i ask one last thing? Is it possible to control another module, like
NowPlayingOnSpotify? I would like to use commands like "next song"

**Comment by eouia** [comment]
Control other modules is possible. See the Usage.md
But As far as I know, there is no feature like `next song` on `NowPlayingOnSpotify`

**Comment by Koulouri** [comment]
ok, thanks

**Comment by Koulouri** [comment]
Hallo again! How are you? I encountered a "problem" recently, where all
magicmirror modules, apart from one, go extinct after some time. Basically,
it is like there is a screensaver enabled, but only one module, doesn't go
away. I don't want them to go away. Can you help me find the issue?

**Comment by Koulouri** [comment]
nevermind.. i think i fixed it xd.

**Comment by Koulouri** [comment]
Hallo, on which pins should i attach an LED, on my rpi, so that it lights
up when google assistant answers?

**Comment by eouia** [comment]
That is another issue. Anyway;
There is no feature to export signal to GPIO in this module by default. You can fork my repository into yours and modify it to do. But I'm not that kind of expert so I cannot help about that.

**Comment by Koulouri** [comment]
Ok then.. thanks a lot for your time!

**Comment by Koulouri** [comment]
hi there! i Hope you have been doing well. latelly, i noticed that the
MMM-Assistant module, shows an error when i try to update it (by using git
pull).
The error is saying:
error: "Your local changes to the following files would be overwritten by
merge: MMM-AssistantMk2.js
Please commit your changes or stash them before you merge.
Aborting"
The last time, i had to revert any changes to the assistant config file, so
that it updates. Can i update the module without reverting the changes?
Thanks a lot for helping me. I have learnt a lot from your advice so far!

**Comment by eouia** [comment]
Your local change makes merging issue between your version and original. You should resolve conflict between these two versions. Google about your issue - `git merge conflicts`
