### ISSUE TITLE
sound from hdmi delay to  start

### ISSUE THREAD

**Issue by costascontis** [eouia/MMM-AssistantMk2#79]
Iam using hdmi for sound out and the issue is that when Assisstant begin to answer a question i am losing the first word.Seems that module is leaving hdmi to fall to sleep when not using it so there is a sound delay a few millisecs when starting to speak.

**Comment by eouia** [comment]
Yes, I already know that. But It couldn't be fixed. HDMI is opened somewhat slowly, the first part of stream might be lost. If I open it permanently, other programs cannot use speaker because it is already occupied by Prior Assistant conversation. In PC, a mixer can mix sound-outputs from various sources, but I don't know how to config in RPI.
I recommend to use other output.

**Comment by eouia** [comment]
But youtube Player also need to use it. Too much modification is needed to do that.

**Comment by PREngineer** [comment]
Hey man (eouia)!  Thank you for this awesome application.

I was able to get an OrangePi running armbian to use it smoothly and I am facing this same issue reported by costas.

I have been researching what you said in the comment and I believe that it is possible to do what you mentioned in a RaspberryPi or OrangePi.

https://www.alsa-project.org/main/index.php/Asoundrc#Software_mixing

Both micro-computers have the alsamixer as far as I know.  Based on what I read in the link that I posted above, it seems likely that a virtual device can be created that merges both the HDMI and Analog outputs.  Now, will it still be affected by the delay in HDMI opening, I don't know.

I imagine that the configuration file can later refer to this virtual device like it does for the capture device.

I haven't tried it yet but I thought that maybe giving you a clue as to what I was thinking could help.  You seem to be more apt than me in understanding this part.

I will try to find a way in my spare time and if I can come up with a solution, I will post it here.

**Comment by eouia** [comment]
@PREngineer Yes, My thought is same to you.
Anyway, for configure device name, you can use `play.playOption`. My prior version was using internal playing modules but many ppl had a problem to install dependencies, so I have changed it to external program.

**Comment by eouia** [comment]
Can I close this issue? there is no other feedback for this issue. You guys can leave any issue this board. Wish a good luck.

**Comment by talving** [comment]
I have the exact same problem. Isn't it any way to delay the output sound like 1 second so the hdmi has enough time before the actual important sound comes out? 

That or if someone has gotten a solution?

**Comment by eouia** [comment]
@talving Sorry, it's out of my ability. How about change other player program instead `mpg321`? But not sure it could deduce the delay.
