### ISSUE TITLE
AssistantMk2 not work with sox on MAC 

### ISSUE THREAD

**Issue by hacaro** [eouia/MMM-AssistantMk2#81]
Hi, i've installed to test on my Mac the modules, i've manually installed dependencies instead of using the .sh . now the module start but it's not listen and after a bit it say me service unavailable. 

I've modified the config to use sox instead of arecord in config file, and tried a lot of combination for device: (none, plughw:1, plughw:0,hw:0, hw:1,0, 0,0 etc) but nothing, can you help me ? 

Thanks in advance and best Regards

**Comment by eouia** [comment]
Can you show me the log? (Error and stdout on the shell)
I've also tested on my Mac. The only problem was, electron-rebuild couldn't be done properly. If you run as `serveronly` mode, My module will work. But for `kiosk` mode, currently I can't solve the problem.

**Comment by eouia** [comment]
And This will work on `serveronly` mode.
```
record: {
          recordProgram : "sox",  
          device        : null      
        },
```

**Comment by hacaro** [comment]
sure, here my shell log

> sh run-start.sh

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-AssistantMk2
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Service unavailable.' }

**Comment by eouia** [comment]
```
Error: 14 UNAVAILABLE: Service unavailable.
```
This error usually come from invalid `record` configuration. Try my prior post about `record` configuration. And check whether other program is using default Mic also.

**Comment by hacaro** [comment]
also, if i user sox on terminal it works fine.

**Comment by hacaro** [comment]
I've tried your configuration but nothing it the same,  also if i run it in serveronly mode.

**Comment by eouia** [comment]
To test working, you can use `useWelcomeMessage:"what time is it"`.
Anyway, There is nothing more to activate Assistant. There seems not any special error except "Error 14" and that error would come when your voice is not recorded.

**Comment by hacaro** [comment]
ok, i've execute npm install and now works, but it not reply any answer, if I ask What time is it it show me the phrase "What time is it" into the mic but nothin happens and then i have samer error service unavailable.

**Comment by hacaro** [comment]
yes, i see the Phrase here the screenshot https://ibb.co/yVk6NfC

here the log 

> sh run-start.sh

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-AssistantMk2
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 14,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Array] } },
  details: 'Service unavailable.' }

**Comment by eouia** [comment]
Hmmm.. somewhat weird. You'd said `if I ask What time is it it show me the phrase "What time is it"` But your log says you just run MM and immediately meet the error. (I guess you have tried `useWelcomeMessage`)
You should get these messages if it is working;
```
➜  MagicMirror git:(master) ✗ node serveronly
Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ...
Server started ...                   #### < - Here you might open the browser
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...

Ready to go! Please point your browser to: http://localhost:8080
[AMK2] Temporal storage directory is clearing.  ###### <- Assistant module starts.
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Started with text query: what time is it
[AMK2] Device Action: { requestId: '5c52b3ae-0000-2bc5-a065-94eb2c1d2e34' }
[AMK2] Assistant Text Response:
[AMK2] Conversation Completed
```

**Comment by hacaro** [comment]
i know, but before the error, it remains in Listening for some second.  it show me the Phrase, see the screenshot.

**Comment by hacaro** [comment]
sorry, it remain in Launching Application before error (not listening) but it also receive my command and show the phrase, then after some second ti show the error

**Comment by eouia** [comment]
Set the `verbose:true` to examine.
```
module: "MMM-AssistantMk2",
config: {
        verbose: true,
...
```

**Comment by hacaro** [comment]
done, i've also add useWelcomeMessage, 

it start and gave me the welcome message then i ask What time is it, and here is the verbose mode log

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-AssistantMk2
Connecting socket for: updatenotification
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
[AMK2] Temporal storage directory is clearing.
Create new calendar fetcher for url: http://www.calendarlabs.com/templates/ical/US-Holidays.ics - Interval: 300000
Create new news fetcher for url: http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml - Interval: 300000
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Started with text query: brief today
[AMK2] Device Action: { requestId: '5c524297-0000-2650-8234-089e0827b390' }
[AMK2] Assistant Text Response: 
[AMK2] Conversation Completed
[AMK2] assistant ready
[AMK2] Conversation starts.
[AMK2] Transcription: what  --- Done: false
[AMK2] Transcription: what's  --- Done: false
[AMK2] Transcription: what time  --- Done: false
[AMK2] Transcription: what time is  --- Done: false
[AMK2] Transcription: what time is it  --- Done: false
[AMK2] Transcription: what time is it  --- Done: true
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
    at /Users/massimoscalia/MagicMirror/Monthewall/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 14,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Array] } },
  details: 'Service unavailable.' }

**Comment by hacaro** [comment]
N.B, after the last [AMK2] Transcription: what time is it --- Done: true
and he show me the right Phrese on screen it remain stuck 10 or 15 seconds, and then gave me the error and the "CONVERSATION ERROR" on Screen

**Comment by eouia** [comment]
Ok. there is nothing special problem on module itself.
Let's see other points.
Did you make proper credential? With my test, when credentials.json is not proper, that error could come also.

**Comment by eouia** [comment]
Common falls might be;
- You made wrong credentials on Google Project console.
- You confused wrong project from several similar projects.
- You didn't enable the API.

**Comment by hacaro** [comment]
Hi, i’ve checked, and all seems ok in terms of API , credentials and project, during the auth step i. The console all works fine, i give the code by browser, the inpast the code and intonthe clini ask what time is it and it answer right with the current hour, and geva me message conversation Complete.

**Comment by hacaro** [comment]
Ok, finally it works.  i don't know exactly what was going wrong, i think that probably there was something wrong with the node 8 version.  so, i've uninstalled the node 8 and Installed the latest version the 11 then, i've reinstalled  MM2 and the MMM-AssistantMk2. I've changed the config values for record: and play: and TADA ! all works fine now.

So, now i have a little question in order to make it more usable.

this is the example, if the phrase is found he give me the answer and all it's ok.  but, if i say "piopio", or another phrase that is not recognized it stop to work for 20 seconds and then give me th CONVERSATION ERROR OUTPUT.  there is a way to have a normal behaviour eg. he reply me "don't understand" and start to listen again ? because every time that he don't understand, he stuck for 20 second with the mic icon active until the CONVERSATION ERROR message.

Hope that my explanation clear.
Many many thanks for your support and for your time. 

Thanks for all

**Comment by eouia** [comment]
For your question;
Give me more example of not working? Is there any normal sample working? (How about "time" or "weather"?)
I tested "piopio" on my Mac but it return the usual result as expectation ("Pio Pio" ( www.piopio.com - https://www.piopio.com/ )\nThe best Peruvian restaurant in New York, Manhattan, Brooklyn, Bronx, Queens, specializing... ")

CONVERSATION ERROR itself will come the response from Google is not proper. Especially after long waiting, It might mean RESPONSE itself is not returned.

**Comment by eouia** [comment]
Can I close this issue If you have no other feedback for this issue. You can leave any issue (related with this or another) at any time on this board. Wish a good luck.

**Comment by dang1412** [comment]
```
[AMK2] Assistant Text Response:
[AMK2] Transcription: show  --- Done: false
[AMK2] Transcription: show me  --- Done: false
[AMK2] Transcription: show me the  --- Done: false
[AMK2] Transcription: show me the man  --- Done: false
[AMK2] Transcription: show me the money  --- Done: false
[AMK2] Transcription: show me the money  --- Done: true
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
```
Same here, after a while it shows the error. The welcomeMessage works fine
