### ISSUE TITLE
What is code: 14 ?

### ISSUE THREAD

**Issue by jasb1011** [eouia/MMM-AssistantMk2#82]
I have finished installing and doing everything that needs to be done for this module, but when I got to the point where it said “Type your request “, I typed hello it  showed “Conversation Error: { Error 14 UNAVAILABLE: connect Failed” and also “code: 14, “ near the bottom. Please tell me how to fix this problem

**Comment by eouia** [comment]
In authentification, your credentials.json seems not valid.
Check these;
- Sometimes, Google Server might have network problems. (Try it later)
- Check the internet. 
- When you have several projects in Google Console, Confirm same project which your credentials.json came from and you made its API enabled.

**Comment by jasb1011** [comment]
Thank you so much for responding because I got it to work!! But I ran into another problem, every time I try to put the configuration  code of the assistant (both the simple and full)into the magic mirror config and try to restart magic mirror, the mirror won’t show and I am just left with a blank screen. Please help

**Comment by eouia** [comment]
I need error messages and error log. Commonly configuration failures come from missing or exceeding some syntax like
 Comma and brackets.

**Comment by eouia** [comment]
> Quick question: do you think that the problem is that I don't have a mic and speaker set up, because I set this up without them, but I do get them later on this week. Anyway this is my config:

**Comment by jasb1011** [comment]
Ok but I’m still not sure what the problem is

**Comment by eouia** [comment]
That seems nothing special missed in your configuration. So I need detailed logs or error messages and exactly what is your problem - more than "Not working"

**Comment by jasb1011** [comment]
Ok, how do I find error logs ?

**Comment by eouia** [comment]
If you are using `pm2` for execution of MM, `pm2 show log`, Or instead `pm2`, to execute MM by `npm start dev` in your terminal shell.

**Comment by jasb1011** [comment]
Okay so I went into my log and this showed up:

/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       | { Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm       | Expected directory: electron-v2.0-linux-arm-glibc
0|mm       | Found: [node-v64-linux-arm-glibc]
0|mm       | This problem can often be fixed by running "npm rebuild" on the current system
0|mm       | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v2.0-linux-arm-glibc/grpc_node.node'
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:63:3)
0|mm       |     at Module._compile (module.js:642:30)
0|mm       |     at Object.Module._extensions..js (module.js:653:10)
0|mm       |     at Module.load (module.js:561:32)
0|mm       |     at tryModuleLoad (module.js:504:12)
0|mm       |     at Function.Module._load (module.js:496:3)
0|mm       |     at Module.require (module.js:586:17)
0|mm       |     at require (internal/module.js:11:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }


Then I tried "npm rebuild" and also tried updating it and it showed this:

npm ERR! path /usr/lib/node_modules/npm/node_modules/aproba
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules/npm/node_modules/aproba'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/lib/node_modules/npm/node_modules/aproba']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/lib/node_modules/npm/node_modules/aproba\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules/npm/node_modules/aproba' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

**Comment by eouia** [comment]
Well, you seem to have failed electron-rebuild step on installation and that came from wrong permission of directory.
Usually it happens when you have used ‘sudo’ for previous git clone or build something without carefulness. It prevents some jobs to access directory needed.

**Comment by jasb1011** [comment]
So what do I do

**Comment by eouia** [comment]
remove module and re-install again carefully. And, if you meet some errors or suspicious points on installation, tell me with the errors or symptoms.

**Comment by eouia** [comment]
That commands has no output. It would just change permission of files. If there is no other special error, it will print out nothing.

**Comment by jasb1011** [comment]
So could I copy and paste chmod +x *.sh into the MMM-AssistantMk2 scripts file

**Comment by eouia** [comment]
I can't understand your words.
>So could I copy and paste chmod +x *.sh into the MMM-AssistantMk2 scripts file

I think you did right in your previous trial.
>pi@raspberrypi:/MMM-AssistantMk2 $ cd scripts
pi@raspberrypi:/MMM-AssistantMk2/scripts $ chmod +x *.sh
pi@raspberrypi:~/MMM-AssistantMk2/scripts $

**Comment by jasb1011** [comment]
ok so I reinstalled it and it showed me the same error:

/home/pi/.pm2/logs/mm-error.log last 15 lines:
0|mm       | { Error: Failed to load gRPC binary module because it was not installed for the current system
0|mm       | Expected directory: electron-v2.0-linux-arm-glibc
0|mm       | Found: [node-v64-linux-arm-glibc]
0|mm       | This problem can often be fixed by running "npm rebuild" on the current system
0|mm       | Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v2.0-linux-arm-glibc/grpc_node.node'
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:63:3)
0|mm       |     at Module._compile (module.js:642:30)
0|mm       |     at Object.Module._extensions..js (module.js:653:10)
0|mm       |     at Module.load (module.js:561:32)
0|mm       |     at tryModuleLoad (module.js:504:12)
0|mm       |     at Function.Module._load (module.js:496:3)
0|mm       |     at Module.require (module.js:586:17)
0|mm       |     at require (internal/module.js:11:18)
0|mm       |     at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }

**Comment by eouia** [comment]
This is not SAME error with your previous.
First, permission problem is solved. So, you can finish ‘Electron-rebuild’ step completely. Try it.

**Comment by jasb1011** [comment]
OK I tried the rebuild step and it worked!!! thank you so much for helping me and being patient with me. I'm fairly new to coding and I'm so glad that you reached out to help me. My final question is that if I plan to use this with Hot word do i use the full configuration or do I use the on that says "with Hot word"

**Comment by eouia** [comment]
nice to you. I'll close this issue. Have a nice day.

**Comment by donamoha** [comment]
hello 
when i write npm start command this issue happed to 
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node'

**Comment by eouia** [comment]
@donamoha You didn't do `electron-rebuild` step on installation. Read the documents and try it again.

**Comment by TonyNgo510** [comment]
@eouia Hi there ! I'm student and I don't know what to change Mk2 speech Vietnamese, can you help me? Vietnamese Google Assistant worked ! But on my MagicMirror, I don't know how to setting :(( pls help

**Comment by bugsounet** [comment]
hi, just read wiki

I think I spend enough time writing the wiki.
Everything is on it
