### ISSUE TITLE
Magic mirror not loading

### ISSUE THREAD

**Issue by jasb1011** [eouia/MMM-AssistantMk2#84]
Hi again, ok so my problem is that i just install AssistantMk2 and Hotword successfully but every time i try to restart magic mirror it just says that I may have a configuration error. This is my error log:

PM2      | App [mm:0] starting in -fork mode-
PM2      | App [mm:0] online
0|mm     | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|mm     | > sh run-start.sh
0|mm     | Starting MagicMirror: v2.6.0
0|mm     | Loading config ...
0|mm     | WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
0|mm     | Loading module helpers ...
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: helloworld.
0|mm     | All module helpers loaded.
0|mm     | Starting server on port 8080 ... 
0|mm     | Server started ...
0|mm     | Connecting socket for: updatenotification
0|mm     | Sockets connected & modules started ...
0|mm     | Launching application.
0|mm     | Shutting down server...
0|mm     | Stopping module helper: updatenotification
PM2      | App [mm:0] exited with code [0] via signal [SIGINT]
PM2      | App [mm:0] starting in -fork mode-
PM2      | App [mm:0] online
0|mm     | > magicmirror@2.6.0 start /home/pi/MagicMirror
0|mm     | > sh run-start.sh
0|mm     | Starting MagicMirror: v2.6.0
0|mm     | Loading config ...
0|mm     | WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.
0|mm     | Loading module helpers ...
0|mm     | Initializing new module helper ...
0|mm     | Module helper loaded: updatenotification
0|mm     | No helper found for module: helloworld.
0|mm     | All module helpers loaded.
0|mm     | Starting server on port 8080 ... 
0|mm     | Server started ...
0|mm     | Connecting socket for: updatenotification
0|mm     | Sockets connected & modules started ...
PM2      | Stopping app:mm id:0
0|mm     | Launching application.
PM2      | pid=3454 msg=failed to kill - retrying in 100ms
PM2      | App [mm:0] exited with code [0] via signal [SIGINT]
PM2      | pid=3454 msg=process killed

And this is my configuration:

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
00 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "0.0.0.0", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1","192.168.1.13"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 12,
	units: "imperial",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		
                         }, {
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check",
						url: "https://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics"
					}, {  symbol: "My Calender",
						url: "https://calender.google.com/calender/ical/johnandrewbannister%40gmail.com/public/basic.ics"
					}

				]
			}
		},
		
		
		{
			module: "compliments",
			position: "lower_third"
		},
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Houston",
				locationID: "4699066",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "eb80d4b6206762aca994a25ac6a092ef"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Houston",
				locationID: "4699066",  //ID from https://openweathermap.org/city
				appid: "eb80d4b6206762aca994a25ac6a092ef"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "New York Times",
						url: "http://www.nytimes.com/services/xml/rss/nyt/HomePage.xml"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		 
},
{
  module: "MMM-NowPlayingOnSpotify",
  position: "bottom_left",

  config: {
    clientID: "3ef7a5ee1f074018a1bc50b5df4a5247",
    clientSecret: "08cc0c7887ab4ddfa6e2778f6e2e4975",
    accessToken: "BQDN6JoGSdgWOkewAM__A8Xxc9LmMY9seWA27sl1rVTVchrxxmUDy6J0LsnJ8nL7g-DNOU-gnfkfMnL7ZbKFreh_I4Wn6gBePOAbZcVLjwZny6vXLyVY3OHsOPOp3KinhdNxEsdMuRpz79UGNGBQpfYGIl-rAMGHCE4U",
    refreshToken: "AQAhun5ZjXD-KVZ9fTbwO-E8vHOMJvY4mgvAHhfbxGIuObmD40wB7TM-tUZAFu9ss5_opwjd2Ur4hVwQ5CXElsjh7P351qUVpWKs8CyTHEFv3RBIvx76ITr0POKu1kfWgz4I6A"
  }
}, {
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
  {
    module: "MMM-Hotword",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },
      autostart:true,
      onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }
        }
      },
    },
  }, 
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by eouia** [comment]
> WARNING! Could not validate config file. Please correct syntax errors. Starting with default configuration.

This means you made some mistake on configuration file. Usual common pitfalls are;
- missing comma after list of property
- missing bracket
- Or additional  unnecessary symbols.

Anyway, your post was ill-formatted so I cannot read. Can you send your config.js to me via email? my email address is eouia0819@gmail.com

**Comment by eouia** [comment]
I think you made another post about your issue, so I'll close this. Wish a good luck.
