### ISSUE TITLE
conversation error

### ISSUE THREAD

**Issue by icripps** [eouia/MMM-AssistantMk2#85]
when i start the smart mirror  and toggle the assistant, nothing happens and then it gives me CONVERSATION_ERROR
 below is the log
> magicmirror@2.6.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-AssistantMk2
Connecting socket for: calendar
Starting node helper for: calendar
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Launching application.
[AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Service unavailable.' }

here is my audio settings on the pi as well as the record configuration:#

settings on raspberry pi:
pcm.!default {
  type hw
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:1,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:1,0"
  }
}

pcm.!default {
        type hw
        card 1
}

ctl.!default {
        type hw
        card 1
}

settings in configuration file:
record: { // Full values are in `FOR EXPERTS` section.
			      recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
			      device: "plughw:1"       // recording device (e.g.: "plughw:1")
			    },

  record:  { // Full version
			      sampleRate    : 16000,      // audio sample rate
			      threshold     : 0.5,        // silence threshold (rec only)
			      thresholdStart: null,       // silence threshold to start recording, overrides threshold (rec only)
			      thresholdEnd  : null,       // silence threshold to end recording, overrides threshold (rec only)
			      silence       : 1.0,        // seconds of silence before ending
			      verbose       : false,      // log info to the console
			      recordProgram : "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
			      device        : "plughw:1"        // recording device (e.g.: "plughw:1")
			    },

**Comment by eouia** [comment]
I'm not expert of h/w setup on RPI, but As far as I know, you've set same device name(hw:1,0) to both of mic and speaker. It might be the reason of your problem.

**Comment by icripps** [comment]
i have set it so because , i am a using a usb sound card adapter that has both mic and speaker on it.
![image](https://user-images.githubusercontent.com/35995040/52565876-13cd8c80-2dd6-11e9-8270-9a8392f17324.png)

my set up works fine with the normal google assistant on the pi , i don't understand why the mirror keeps giving me "CONVERSATION_ERROR"

**Comment by eouia** [comment]
Can you record and play on the terminal shell with this command?
```
## Test recording with this command
arecord -D plughw:1 -d 10 test.wav

## Test playing with this command
aplay test.wav
```
Usually that error might come from invalid device setup.

To get more detailed log, try these in config.js

```
## For MMM-AssistantMk2 configuration
verbose: true,

## For MMM-Hotword configuration
testMic: true,

```

**Comment by icripps** [comment]
when i used `arecord  plughw:1 -d 10 test.wav` i was able to record and play the sound
but when i used `arecord -D plughw:1 -d 10 test.wav` i got the following message:
arecord: main:788: audio open error: Device or resource busy

**Comment by eouia** [comment]
-D option is to select PCM device by device name. So It should be work with this option. My module is using that option to select right device.
Anyway, if `arecord plughw:1 -d 10 test.wav` was working, your mic device might be default device. Perhaps `device : ""` could work but I'm not sure, try it.

**Comment by icripps** [comment]
hmm it does not work when i use   `device : ""`, am so sad right now. anymore suggestions?
please help me

**Comment by eouia** [comment]
or `device:null` ?

**Comment by icripps** [comment]
`device:null` yields the same results, when i toggle the assistant icon this is what i get from the console:
![image](https://user-images.githubusercontent.com/35995040/52584909-5eb0c980-2e01-11e9-8019-8a28e44248cf.png)

then the icon changes into this:
![image](https://user-images.githubusercontent.com/35995040/52585079-d252d680-2e01-11e9-9359-9b07816de358.png)

it remains like that for about 30secs and then changes into :
![image](https://user-images.githubusercontent.com/35995040/52585191-23fb6100-2e02-11e9-8209-1f7087b52e36.png)

upon qutting the mirror , i get the following int the terminal:
![image](https://user-images.githubusercontent.com/35995040/52585273-5907b380-2e02-11e9-8793-737cf13888a4.png)

**Comment by eouia** [comment]
```
## For MMM-AssistantMk2 configuration
verbose: true,

## For MMM-Hotword configuration
testMic: true,
```

Try this to get more detailed log.

**Comment by eouia** [comment]
All issues which have same problem of this module;
https://github.com/eouia/MMM-AssistantMk2/issues?utf8=%E2%9C%93&q=unavailable
All of solutions were setting proper device name.

**Comment by icripps** [comment]
> ```
> ## For MMM-AssistantMk2 configuration
> verbose: true,
> 
> ## For MMM-Hotword configuration
> testMic: true,
> ```
> Try this to get more detailed log.

this is what i got 
![screenshot 89](https://user-images.githubusercontent.com/35995040/52586226-f663e700-2e04-11e9-846a-0adca9825c54.png)

and this this is the configuration in my config.json  file


![image](https://user-images.githubusercontent.com/35995040/52586297-2317fe80-2e05-11e9-96cd-969478e7f340.png)

**Comment by icripps** [comment]
> All issues which have same problem of this module;
> https://github.com/eouia/MMM-AssistantMk2/issues?utf8=%E2%9C%93&q=unavailable
> All of solutions were setting proper device name.

okay i will read that

**Comment by eouia** [comment]
Now, I can get what was wrong. That's not mic problem.
https://github.com/eouia/MMM-Hotword#tip Read this section and modify your configuration.

**Comment by icripps** [comment]
still getting the same error `service unavailable` :(

**Comment by icripps** [comment]
![screenshot 91](https://user-images.githubusercontent.com/35995040/52587654-7b9ccb00-2e08-11e9-8e32-8e065c723910.png)

thats the new configuration

**Comment by eouia** [comment]
How about error logs? and remove `useWelcomeMessage`

**Comment by icripps** [comment]
hi , i fixed the issue: i realized that whenever i tried to use `arecord --device=hw:1,0 --format S16_LE --rate 44100 -c1 test.wav`

i got `device or resource busy`
i had installed https://github.com/shivasiddharth/GassistPi and had set it to HEADLESS AUTOSTART on BOOT SERVICE SETUP so it was always using my mic. so i had to stop the service using `sudo systemctl start gassistpi.service ` and now the hotword is working well with the AMK2.

my only problem now is, how do i get both AMK2 and GassistPi to use the same mic?
or i have to use two separate mic?

**Comment by eouia** [comment]
Well, If you can use GApi without problem, you don't need to use AMK2 on purpose. Almost the basic features for using Google Assistant of both applications are same.
Anyway, If you want to use both together, mine could be turned on/off by notification. read the manual.
Or 2 mic could be the solution.
However, I'm still believe, your sound setup is invalid. Ask the proper setup to linux communities.

**Comment by eouia** [comment]
Or.. just use another device like Anlaog speaker and USB Mic ...

**Comment by icripps** [comment]
i will like to use another device like a usb mic, but it is so difficult to find a usb mic down here, thats why i am using an adapter, maybe my best option is to buy a cam that comes with a mic.
btw below is my pi sound configuration:

`pcm.dsnooper {
    type dsnoop
    ipc_key 816357492
    ipc_key_add_uid 0
    ipc_perm 0666
    slave {
        pcm "hw:1,0"
        channels 1
    }
}

pcm.!default {
        type asym
        playback.pcm {
                type plug
                slave.pcm "hw:0,0"
        }
        capture.pcm {
                type plug
                slave.pcm "dsnooper"
        }
}
`

**Comment by eouia** [comment]
Maybe it could have worthy of trying to use “dsnooper” as device name. But not sure.

**Comment by icripps** [comment]
lol okay, will hit you up when i run into other problems
