### ISSUE TITLE
Using playOption in config-file doesn't work

### ISSUE THREAD

**Issue by ptrk95** [eouia/MMM-AssistantMk2#86]
So I changed the player in the config.js to e.g. "omxplayer" and added commandline options in the "playOptions" property but it just doesn't work. 

Fortunately I got a working solution but I can't do a Pull request because I've changed other stuff to my needs.
In your node-helper.js at line 24 in the "play" function. You should change:
````
...
const player = require('play-sound')()
...
````
to 
````
...
const player = require('play-sound')({player : command})
...
````
So the lib gets the right player and the "playOption"-options are working fine for at least omxplayer and mpg123, tested by myself on a raspberry pi.

**Comment by eouia** [comment]
Ah Thanks. I didn't test about it.
I'll modify.

**Comment by eouia** [comment]
I rolled back modification based on your suggestion. More test to apply  is needed. Anyway thanks. I'll close this issue at this moment.
Have a nice day.
