### ISSUE TITLE
Volume control with the assistant

### ISSUE THREAD

**Issue by ejay-ibm** [eouia/MMM-AssistantMk2#89]
Hello, 

I'd like to control the volume of my Pi ( let's say my audio output volume) using the voice assistant. 
I know that it is not implemented but I tried something and it did work. 
The issue is that I have good logic but very poor dev skills so please apologize if my code below looks ugly. But If you can implement this in a smarter way in a next release that would be really great. 
In the MMM-AssistantMk2.js file I have added some additional transcription hook like : 
 "VOL1": {
        pattern: "set volume to 1",
        command: "VOL1"
      },
 "VOL2": {
        pattern: "set volume to 2",
        command: "VOL2"
      },
 "VOL3": { etc...  till VOL10 

then in the command section, I used those commands : 

 "VOL1": {
        shellExec: {
          exec: "amixer sset 'PCM' 10%",
        options: null,
        }
      },
 "VOL2": {
        shellExec: {
          exec: "amixer sset 'PCM' 20%",
        options: null,
        }
      },
 "VOL3": { till VOL10 ... 

Yes it make the code long and not pretty at all . 

But here We have a common point here eg vol1 =volume to 10% , vol2 = volume to 20%  , where I think 1 , 2, 3 etc . could be set as a variable so that code could fit in 1 call per section ( not 10 in each ) Do you think it's possible ? 

The hard part here is how the assistant would interpret the command and replace the variable by the Given number in the code.  Maybe impossible and maybe why it's not supported / implemented . 
Could a transcription hook patterns contain  variables? 

In all case let me know what you think about it. I'll probably share the idea on the Forum . 

Thanks for the good work. 

EJ

**Comment by eouia** [comment]
Possible.
```
"VOL_HOOK": {
  pattern: "volume to ([0-9]+)",
  command: "VOL_COMMAND"
},
```
`([0-9]+)` is RegularExpression to define your dynamic variable pattern. it will be matched with "1" or "23", but not with "hello" or "max".
By example
`(abc)` is to be true with "abc", but not "def"
`(abc|def)` is to be true with "abc" or "def" but not "aef" or "xyz"
`([a-c]5)` is to be true with "aaaaa" or "cbcbc" but not true with "aaaa" or "aaaaaa" or "abcde". 
You can learn about Regular Expression by googling.

Then your command could be;
```
"VOL_COMMAND": {
  shellExec: {
    exec: "amixer sset 'PCM'",
    options: (params, key) => {
      return (params[1] * 10) + "%" 
    }
  }
}
```
`params` object (or array) will get the value from your RegularExpression match result from "VOL_HOOK" pattern. By example, if you were saying "Volume to 3", `params[1]` will get the `3` as its value. (The structure of  `params` will be dynamically defined as Regular Expression pattern, so you need to know understand basic concept of RE)

But there might be two further problems.
- "Volume" might be reserved word for Google Assistant, So it could make unexpected side effect when you use it on transcriptionHooking. If possible, use another pattern.
- transcription is the result of understanding of Google Assistant. So, When you say "One plus One", GA might understand it as "1 + 1", But, how about "No one"? it will not transcribed as "No 1".  So It is very ambiguous What you saying will be what to be transcribed. So you should define RE pattern very nicely and your shellExec callback function should be more complexed.


The best way is using gAction instead transcriptionHook. transcriptionHook is some kind of expedient to make things simple. gAction can understand your intention not the saying itself. However, understanding and making gAction properly is very harder than transcriptionHook.

**Comment by eouia** [comment]
I decide to implement volume function at this moment. But it will take some days to be released. (I have my real job to focus. :D)

**Comment by ejay-ibm** [comment]
Hey Very cool !
And thank you for taking time to share your knowledge . 
I completely get what you did and this was the exact smart way I knew to exist I wanted to implement. 

Indeed The transcription might be the tricky thing. and the word should not be something that could be used by the assistant: "set system sound to 1,2, 3..." ( I'm french so I'll use something else ;)
 
I'll run some testing with the code you gave and will report.

Going to work as well ;)

Thanks again 
EJ

**Comment by ejay-ibm** [comment]
Hmmm, 
Something goes wrong in the code now. 
The Hook is capture "set volume to 2"
Then the assistant get blocked with the following stack 

Uncaught TypeError: Cannot read property '1' of undefined
    at options (MMM-AssistantMk2.js:137)  Line 137 is ->> return (params[1] * 10) + "%"
    at AssistantHelper.doCommand (MMM-AssistantMk2.js:732)
    at AssistantHelper.foundHook (MMM-AssistantMk2.js:758)
    at AssistantHelper.conversationEnd (MMM-AssistantMk2.js:775)
    at Class.socketNotificationReceived (MMM-AssistantMk2.js:388)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.MMSocket.self.socket.onevent (socketclient.js:19)

It look like it doesn't like the [1] after the params ...

**Comment by eouia** [comment]
Sorry, there was a bug. I've patched. Retry it.

**Comment by ejay-ibm** [comment]
No worries, you fixed it quick! 
I now work like a charm!  I'm glad my question helped to fix a small bug in your code :)

One Last issue I need to manage ( and it has nothing to do with the module)  The percentage asked is not accurate on the system . Let say I'm asking volume at 5 , the command 50% is sent which is fine , but when you check the volume spot on the bar it's much lower than 50 % , even 7 is bellow the 50% .
Only 80% reach the middle of the bar. Again this is not a module issue as it can be reproduced with pure command line. 

In all case thank you as I can now control my Mirror pi volume with my voice and that's what I want to achieve. I have really appreciated your fast help and efficient response. 

I'll provide additional input if you are interested if I find a command to be executed that is more accurate and give a better match with the true system volume. 

Thank you

**Comment by eouia** [comment]
Nice to hear it. I don't know about RPI sound system (especially ALSA). Anyway, I wish you good luck.
I'll close this issue. Have a nice day.

**Comment by ejay-ibm** [comment]
No Worries: I found it out 
The -M switch do the trick ( versus Raw volume by default ) 

-R,--raw-volume Use the raw value (default)
-M,--mapped-volume Use the mapped volume

So the command like 

exec: "amixer sset -M 'PCM'",

Is perfect ! 

Thank you and have a good day too !

**Comment by eouia** [comment]
I’ll be happy if you share your experience with communities. Have a nice day.
