### ISSUE TITLE
News feed for MMM-AssistantMk2

### ISSUE THREAD

**Issue by rektart** [eouia/MMM-AssistantMk2#90]
Hi, firstly thanks for this assistant who works great! I was wondering if it was possible for the assistant to read some news from an RSS feed or whatever. Because when I ask him he tells me that this action is not activated.

**Comment by rektart** [comment]
Is TTS a module for MM?

**Comment by eouia** [comment]
No. TTS is concept of computer tech. There are so many Text-To-Speech application. But I don't know whether MM has that kind of module. 
My AMK2 has a simple TTS-like feature but news feed is too long text to handle by it's limited function. It needs extern TTS solution to do that.

**Comment by rektart** [comment]
And what about a feed rss audio is it possible to open it?

**Comment by eouia** [comment]
No. It can order other radio module(which can play audio whatever) to control, but not the radio module itself is this module.

**Comment by eouia** [comment]
Have you still got a problem? I'll close this issue once because there is no more feedback. You can ask me again anytime.
