### ISSUE TITLE
Issue with config file

### ISSUE THREAD

**Issue by NRVB** [eouia/MMM-AssistantMk2#91]
Hi!

When i paste in the module in my config file i get syntax error. Can't find what I have done wrong, just copied and paste it. It works fine if I only use the "test" module or if I only use that part for hotwords but i want to be able to set location. This is how my config file looks like:
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
			module: "alert",
                        
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "US Holidays",
			position: "top_left",
			config: {  
                        maximumNumberOfDays: 14,

                        
				calendars: [
					{
						symbol: "calendar",
						url: "https://calendar.google.com/calendar?cid=bmljbGFzYmp1" 
                                          },
                                          {
                                                symbol: "futbol",
											
                                               url: "https://calendar.google.com/calendar/ical/ov0dk4m6dedaob7oqse4nrda4s%40group.calendar.google.com/public/basic.ics" 
                                                },
                                                
                                              {  
                                                symbol: "calendar",
						 url: "https://calendar.google.com/calendar/ical/sv.swedish%23holiday%40group.v.calendar.google.com/public/basic.ics"
					},
				]
			}
		},
		
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Umeå",
				locationID: "602150",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "0255998d6db72efe4af482d6ccb69032"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "New York",
				locationID: "5128581",  //ID from https://openweathermap.org/city
				appid: "YOUR_OPENWEATHER_API_KEY"
			}
		},
{
		module: "MMM-ResRobot",
		position: "top_right",
		header: "Avgångar",
		config: {
			routes: [
				{from: "740045335", to: "740014017"},	// ResRobot Station IDs of starting and destination station(s). At least one route must be defined.
				{from: "740045335", to: "740045232"},	// "from" is required but "to" is optional (set "to" to empty string to indicate all destinations)
			],
			skipMinutes: 0,		// Skip departures that happens within the next <value> minutes.
			maximumEntries: 6,	// Number of departures to show on screen
			truncateAfter: 5,	// A value > 0 will truncate direction name at first space after <value> characters. 0 = no truncation
			apiKey: "e1ab55e4-6be8-4005-8be5-e1a50e699fc5"		// Your ResRobot apiKey
        }
    },

{
  module: "MMM-AssistantMk2",
  position: "top_right",
  config: {

    // --- ESSENTIALS / modifying for your environment might be needed.

    deviceLocation: {
      coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
        latitude: 51.5033640, // -90.0 - +90.0
        longitude: -0.1276250, // -180.0 - +180.0
      },
    },

    defaultProfile: "default", // If you have several profiles and want to set one of them as default profile, describe here.

    profiles: {
      "default" : { // profile name.
        profileFile: "default.json", // profile file name.
        lang: "en-US"
        //currently available (estimation, not all tested):
        //  de-DE, en-AU, en-CA, en-GB, en-US, en-IN
        // fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR
        // https://developers.google.com/assistant/sdk/reference/rpc/languages
      },
      /* Add your other profiles here, if exists.
      "other_profile" : {
        profileFile: "other.json",
        lang: "de-DE"
      }
      */
    },

    record: { // Full values are in `FOR EXPERTS` section.
      recordProgram: "arecord",  // Defaults to "arecord" - also supports "rec" and "sox"
      device: null        // recording device (e.g.: "plughw:1")
    },

    play: { // Full values are in `FOR EXPERTS` section.
      playProgram: "mpg321", // recommended.
    },
    
{
  module: "MMM-News",
  position: "bottom_bar",
  config: {
    apiKey : "1bb0b0c8303545a0bf13940716ecb114",
    type: "horizontal",
    query : [
      {
        country: "se",
       
      }
    ],
  }
},
		
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

**Comment by eouia** [comment]
Maybe you missed closing bracket for module configuration.
```
  play: { // Full values are in `FOR EXPERTS` section.
    playProgram: "mpg321", // recommended.
  },
}, //< - here
{
  module: "MMM-News",
```

**Comment by NRVB** [comment]
I've tried but doesn't make any difference. Tried reinstall everything too but still not working

**Comment by eouia** [comment]
I think one more closing braket is missed.
```js
    play: { // Full values are in `FOR EXPERTS` section.
      playProgram: "mpg321", // recommended.
    },
  }, //< - here
} // < - here also.
{
  module: "MMM-News",
```

You'd better to make arrangement of indentation to find easy this kind of syntax errors.

**Comment by eouia** [comment]
You  can use `http://esprima.org/demo/validate.html` to validate whether your config.js is wrong or not.

**Comment by eouia** [comment]
Have you still got a problem? I'll close this issue once because there is no more feedback. You can ask me again anytime.
