### ISSUE TITLE
Problems with config file

### ISSUE THREAD

**Issue by berazzi** [eouia/MMM-AssistantMk2#92]
I got everything installed and also installed Hotword with no problems, however after pasting into the config file my magicmirror says "Please create a config file".

I have tried with just the "basic with hotword copied directly from the bottom of the configuration.md and then tried fidling around with it for a while. While I am pretty sure it is something simple like a missing bracket I just cannot find it.

Any chance you can spot what it is?

/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "en",
	timeFormat: 24,
	units: "metric",

	modules: [
		{
		    module: "MMM-AssistantMk2",
		    position: "lower_third",
		    config: {
			deviceLocation: {
		        coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
		        latitude: 55.714198, // -90.0 - +90.0
		        longitude: 12.449332, // -180.0 - +180.0
			},
		      },
		      record: {
		        recordProgram : "arecord",  
		        device        : "plughw:0",
		      },
		    },
		      notifications: {
		        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
		        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
		      },
		    }
	 	 },
		  {
		    module: "MMM-Hotword",
		    config: {
		      record: {
		        recordProgram : "arecord",  
 		       device        : "plughw:1",
		      },
		      autostart:true,
		      onDetected: {
		        notification: function (payload) {
		          return "ASSISTANT_ACTIVATE"
		        },
		        payload: function (payload){
		          return {
		            profile: payload.hotword
		          }
		        }
		      },
		    },
		  },
		},
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Kommende helligdage",
			position: "top_left",
			config: {
				calendars: [
					{
						symbol: "calendar-check-o ",
						url: "https://calendar.google.com/calendar/ical/da.danish%23holiday%40group.v.calendar.google.com/public/basic.ics"
					}
				]
			}
		},
	
		{
			module: "currentweather",
			position: "top_right",
			config: {
				location: "Rødovre",
				locationID: "2614600",  //ID from http://bulk.openweathermap.org/sample/; unzip the gz file and find your city
				appid: "1079b6bf2f5681d16edc5866f7388460"
			}
		},
		{
			module: "weatherforecast",
			position: "top_right",
			header: "Weather Forecast",
			config: {
				location: "Rødovre",
				locationID: "2614600",  //ID from http://www.openweathermap.org/help/city_list.txt
				appid: "1079b6bf2f5681d16edc5866f7388460"
			}
		},
		{
			module: "newsfeed",
			position: "bottom_bar",
			config: {
				feeds: [
					{
						title: "Nyheder",
						url: "https://www.bt.dk/bt/seneste/rss"
					}
				],
				showSourceTitle: true,
				showPublishDate: true
			}
		},
	]

};

/*************** DO NOT EDIT THE LINE BELOW ***************/

**Comment by eouia** [comment]
There seems additional unmatched and unnecessary brackets existing. line 44 and line 70. remove them.

**Comment by eouia** [comment]
You  can use `http://esprima.org/demo/validate.html` to validate whether your config.js is wrong or not.

**Comment by berazzi** [comment]
Great tip! I found them and validated it. Seems to "work" now in the sense that it isnt complaining about the file anymore however now I just got a black screen. My code is syntactically valid according to esprima but just getting the black screen, however if I outcomment the 2 modules I get the MM back.

**Comment by eouia** [comment]
Can you show me your backend-log?
Before it, to make things simple.
- disable (or outcomment) other modules except my 2 modules.
- add `verbose:true` to AMK2 and `testMic:true` to Hotword. It can give you more detailed log.
- execute MM with `npm start dev` on MM directory instead using `pm2` (You should stop pm2 before it)

**Comment by berazzi** [comment]
Sorry kind newbish here, not sure how to do that.
I tried outcommenting the other modules, but nothing happened.
Not sure about "* add `verbose:true` to AMK2 and `testMic:true` to Hotword", is this set in the config?
Tried starting mm via npm start dev as mentioned and got this: 

pi@raspberrypi:~/MagicMirror $ npm start dev

> magicmirror@2.6.0 start /home/pi/MagicMirror
> sh run-start.sh "dev"

Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

Also, my screen turned to white instead of black with a smal msg saying DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect.

However whatever I did I could get the page to reload.

**Comment by eouia** [comment]
That is not your configuration syntax problem any more. 
You might have missed(or failed) `electron-rebuild` step on installation.

**Comment by berazzi** [comment]
You were correct! I went through the installation steps for MMM-Hotword, and while the only time electron rebuild was mentioned was related to when getting a certain error I tried going through it and it worked. I am gonna close this and continue working, thanks.
