### ISSUE TITLE
Disable a module from AMK2

### ISSUE THREAD

**Issue by rektart** [eouia/MMM-AssistantMk2#93]
Hello,
Is it possible to disable a module form a shellExce?
Indeed, I use AMK2 to start a webradio module and it works great. But now I add MMM-PIR-SENSOR and it works good as well. But when it turn off the monitor with by HDMI it turns off the audio signal aswell. So that’s the point, is there any way to disable the MMM-PIR-SENSOR with a shell exce when I start the webradio module?

**Comment by eouia** [comment]
"DISABLE" means very ambiguous. MM has no feature to "ENABLE" and "DISABLE" module after loading. Each module could only "SUSPEND" and "RESUME" its activation when the module itself support those features. And as far as I know, MMM-PIR-SENSOR has no such features. So my module(and any other module) cannot order those things without reboot. Ask module developer about that.
