### ISSUE TITLE
Add MagicMirror to Google Home app

### ISSUE THREAD

**Issue by radokristof** [eouia/MMM-AssistantMk2#95]
Hi!

How it is possible to add the Mirror as a device to my Google Home? So I can link this to a room!

Thanks!

**Comment by eouia** [comment]
https://github.com/eouia/MMM-AssistantMk2/blob/master/USAGE.md#register-your-mirror-as-google-assistant-related-device

**Comment by radokristof** [comment]
Thanks for your help! Now it works!! I had to install google-auth also to work!

**Comment by Gandohr** [comment]
After doing this I can add this to google home, can assign it to a room, but it’s not seen as a “real” home so can’t use it as a speaker/cast device. Any idea how to get that to work.
Would like this instance to also speak out broadcasts

**Comment by eouia** [comment]
It's not allowed. Registering device to Home network is just a pretty thing but useless. :D
Ok, it might be not completely useless when you consider some IoT features over the home. 
But broadcasting(and some other features) is not allowed to the SDK which is used for this module. The purpose of this SDK is not making alternative Google Home, but give an ability to control device by your voice.

**Comment by radokristof** [comment]
It's pretty useful for me :) That way I can link to a room and that way implicit targeting will work (Like turn off the lights will just turn off the lights in that room where the mirror is :) )

**Comment by Gandohr** [comment]
Ahh clear. Need to get a casting device for every room then :(

**Comment by radokristof** [comment]
@Gandohr what you want to achieve with casting? I mean what you are going to use this. Just to use the broadcast feature or listening music in every room, etc... Maybe we can find another way to do this...

**Comment by eouia** [comment]
There could be 3 way to broadcast.

- Use standalone python Google Assistant implements. It uses `Google Assistant for device LIBRARY` and that feature is implemented. The purpose of LIBRARY is to make `standalone alternative Google Home`. But Mine is using `Google Assistant for device SERVICE` instead. Unfortunately `broadcasting` is not allowed to SERVICE. But Library has not feature of `screen output` which mine has. I should select one, and I choice SERVICE due to screen  output and fully implementable with javascript at any platform. (LIBRARY is worked on only x86 and a64 architecture with python only)

- You can make my module to say something with notification. `ASSISTANT_SAY` notification would be. 

- Or you can use the real Google Home... Sorry, My module's purpose is vocal commander not Assistant alternative.

**Comment by Gandohr** [comment]
Current setup
Livingroom -> home mini
Kitchen -> home mini
Bedroom -> insignia voice
Guestroom -> home mini
Office -> magic mirror SDK (not used as mirror but informatie display)
Hall -> magic mirror SDK 

I would like to be able to use Play xxxx on all devices so spotify is heared in all rooms.
But also to say play music in office and play music only to the office.
Or broadcast and have a message play in all roooms. Or broadcast to office and have the broadcast only play in there.

So guess I need compatible speakers in every room :)

**Comment by mishu28nmv** [comment]
> Thanks for your help! Now it works!! I had to install google-auth also to work!

Hello, how did you installed google-auth?

**Comment by radokristof** [comment]
Hello, I can't remember :/

But it might be the Python package for google-auth. Try this:

pip install google-auth

**Comment by mishu28nmv** [comment]
Thank you. I will try it tomorrow.
Good night all!

**Comment by mishu28nmv** [comment]
I did install the google-uth with succes. Should I do something else, because I stiil can't add MM to GHome 😢
I'm just a beginner sorry

**Comment by eouia** [comment]
Did you follow this instruction? (And its better to post as a new issue)
https://github.com/eouia/MMM-AssistantMk2/wiki/Usage#register-your-mirror-as-google-assistant-related-device

**Comment by mishu28nmv** [comment]
Thanks, I'm doing that now. Where do I find model_id? I have only Project name, Project ID and Project number :(
