### ISSUE TITLE
YouTube playback not working

### ISSUE THREAD

**Issue by radokristof** [eouia/MMM-AssistantMk2#96]
I haven't found solution for this in earlier issues.

It says "here is [what I have asked for]" so it recognizes, but after that it does nothing.

What should I do?

Thanks!

**Comment by eouia** [comment]
For every query it responsed unproperly? How about "weather today" or "1+1" ?
If only screen output which be expected as a result was not displayed, but voice response was ok, I doubt you have some front-end error from other module.
Can you disable or omit other modules except MMM-AssistantMk2 and MMM-Hotword and try again?

**Comment by radokristof** [comment]
No, it answered all questions properly. I haven't tried weather, etc... but I have tried some basic questions and also controlling my lights. It worked okay.
When I ask to play YouTube, it says it will play (a small popup opens - which is in the bottom on your demo) with a text 'Try saying...' but it closes immediately (however how I could I reposition this window to the bottom, so I can see the suggestions?) and after that nothing happens. I can ask new questions, etc...

**Comment by eouia** [comment]
Which sentence did you use? 
"Play Crawling of LinkinPark on youtube" or "play youtube" will not work, because youtube(or spotify...) app action is allowed only to REAL Google Home device. (This SDK is still on beta stage)
So, it tried to activate youtube app, but failed. That might be the reason.

So, I implement my own Youtube hooking on this module since SDK doesn't support that feature.
You can activate it like "LinkinPark crawling" instead "PLAY linkinpark crawling".
Originally "LinkinPark crawling" query will response the result of googling about such term. When youtube URL is included in that result, Module will hook the URL and open my YTplayer to play it. That feature is not being included in Google Assistant SDK at this moment.

**Comment by radokristof** [comment]
I have tried Play 'something' on YouTube. As I remember I didn't said Play YouTube. Also I have several real Google device and I have found out that the best is also to say Play 'something' on 'app' on 'device' if you want to play it to a specific device.
So I should only say the 'song' and 'artist'? This screen will popup in fullscreen? How can I exit it?

**Comment by eouia** [comment]
After playing, it will exit automatically.
Or, if you have touch screen, just touch it.
Or, if you have any trigger with some notification (like H/W button), You can assign that notification to exit.
Or, if you set `pauseOnYoutube:false`, Your Hotword will make current playing to stop and exit.

**Comment by radokristof** [comment]
I have managed to start it! However I have choose a song which is not available :/ Now it shows that video is not available and I can't exit it :D

**Comment by radokristof** [comment]
Ok, I have exited it through VNC and clicking on it. However it says that this video is not available for every query.

**Comment by eouia** [comment]
when you meet 'not available', it will be closed after a few seconds. Or activate AMK2 again with your hotword.
Anyway there might be some reason not playing
- Owner doesn't allow to play out of youtube website or app.
- Something wrong. (front-end log is needed to examine.)

**Comment by radokristof** [comment]
`0|MagicMir | [AMK2] Conversation Error: { Error: 14 UNAVAILABLE: Service unavailable.
0|MagicMir |     at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
0|MagicMir |     at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
0|MagicMir |     at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
0|MagicMir |     at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
0|MagicMir |     at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
0|MagicMir |     at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
0|MagicMir |     at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
0|MagicMir |   code: 14,
0|MagicMir |   metadata: Metadata { _internal_repr: {} },
0|MagicMir |   details: 'Service unavailable.' }
0|MagicMir | (node:26194) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added. Use emitter.setMaxListeners() to increase limit
`

**Comment by eouia** [comment]
Hmmm. that error is not related with youtube playing itself. More prior. When you meet this error, you cannot get right response from your ANY query. But you've said you could have used it normally....

**Comment by radokristof** [comment]
If I ask something else, I don't get this error...
Restarted MagicMirror, now the error is gone, but it still refuses to play...

**Comment by eouia** [comment]
`Error: 14 UNAVAILABLE: Service unavailable.`
This error might rise when;
- Your internet connection is bad;
- Your mic setup is not proper or broken on runtime
- Your credentials is not mismatched...

I suspect second point.
Can you show me your configuration of both modules?

**Comment by radokristof** [comment]
I didn't have a USB microphone yet for RPi. My mirror is still in 'building' phase, so now I trigger it with TelegramBot (/q...).

Also the screen is truncated like this:
[photo](https://imgur.com/a/fH0OztCl).

How can I reposition this response window, so that the GoogleAssistant logo will stay at the top of my screen and this will display at the bottom in full width (like your demo?)

**Comment by eouia** [comment]
your photo url is broken.
All styiling is defined with CSS. You can look inside `MMM-AssistantMk2.css` and redefine which you need in `css/custom.css`.

Anyway, have you a telegram? my account is @eouia. It's better talk there than this issue board.

**Comment by radokristof** [comment]
Yes, I will write a PM.

**Comment by eouia** [comment]
With telegram talk, he solved his problem. Thus, I'll close this issue.
