### ISSUE TITLE
MK2 second user 

### ISSUE THREAD

**Issue by hird85** [eouia/MMM-AssistantMk2#97]
Hello i love the work you guys are doing on here but i have a little problem figuring out how to add a sencond user ,
I have a second users secondusr.json in the profile folder but i have no clue where to put the sencond users credentials files

i think my config.js file is correct
profiles: {
“default” : { // profile name.
profileFile: “default.json”, // profile file name.
lang: “en-US”
//currently available (estimation, not all tested):
// de-DE, en-AU, en-CA, en-GB, en-US, en-IN
// fr-CA, fr-FR, it-IT, ja-JP, es-ES, es-MX, ko-KR, pt-BR
// https://developers.google.com/assistant/sdk/reference/rpc/languages
},
// Add your other profiles here, if exists.
“other_profile” : {
profileFile: “secondusr.json”,
lang: “en-US”
}
},

**Comment by eouia** [comment]
I think you've followed this instruction : https://github.com/eouia/MMM-AssistantMk2/blob/master/INSTALL.md#get-auth-and-credentials-to-make-profile
After downloading `token.json`,   PUT IT into `profiles` directory.
```sh
mv token.json ./profiles/secondusr.json
```
Your configuration seems right.

**Comment by hird85** [comment]
thank you very much for your quick reply, I really like the work that has been done iv been following your project for a while 
I have both the user tokens in the profile directory but only my voice is activating MK2
any ideas why only my voice is getting recognised?

**Comment by eouia** [comment]
Show me your hotword config

**Comment by hird85** [comment]
This is the hotword config part
{
			module: "MMM-Hotword",
			config: {
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1"
				},
				autostart:true,
				onDetected: {
					notification: (payload) => {
					return "ASSISTANT_ACTIVATE"
					},
					payload: (payload) => {
						return {
						  profile: payload.hotword
						}
					}
				},
			},
		},

**Comment by eouia** [comment]
Your hotword configuration is using default values. There seems no trigger for `other_profile`
If you want to assign hotword `smart_mirror` to `other_profile` (and the others to your `default` profile - `default.json`); Configure Hotword like this.
```js
config: {
    snowboy: [
  {
    hotwords: "other_profile", //this will be sent to other module for distinguishing which hotword is detected.
    file: "resources/models/smart_mirror.umdl",
    sensitivity: '0.5',
  },
...
```

**Comment by hird85** [comment]
Thank you very much for your help it is working, Assistant mk2 is one of thje best module works great

**Comment by eouia** [comment]
Nice to hear it. I'll close this issue. Have a nice day.
