### ISSUE TITLE
This and other modules goes black after a couple of minutes on idle

### ISSUE THREAD

**Issue by PabloOyarzo** [eouia/MMM-AssistantMk2#98]
Hi, so all modules work fine, but after a couple of minutes, all of them goes black except forecast and I need to reboot in order to bring them back to normal. 

the modules I have are Clock, Calendar, CurrentWeather, Weatherforecast, MMM-AssistantMk2 and Newsfeed.

How do I debug what's happening when it all goes to black so I can provide more info?

**Comment by eouia** [comment]
I think it was function of `onIdle`.
```js
onIdle: {
      timer: 0,
      command: null
},

onActivate: {
      timer: 0,
      command: ""
},
```
Add this in your configuration of MMM-AssistantMk2.

**Comment by PabloOyarzo** [comment]
Worked. Left it on for 30 minutes and no issues. Thank you
