### ISSUE TITLE
Standard assistant function such as 'set a timer' doesn't work

### ISSUE THREAD

**Issue by ejay-ibm** [eouia/MMM-AssistantMk2#99]
Hi Sean, 
I'm wondering why such standard assistant function doesn't work. 
I say Set a timer to 30 seconds . The assistant reply i'm setting the timer. but after 30 second nothing happen . 
What would be needed to make it work ? 
Thank you

**Comment by eouia** [comment]
See Compatibility and feature support https://developers.google.com/assistant/sdk/overview 
It is not supported with Google Assistant Service. (With Google Assistant Library it will)
Why I select Google Assistant Service not Google Assistant Library as SDK even though GAL has many features by default;
- GAL supports only Python. I want to make this module with pure javascript, implemented chemically  into MM itself, not separated app. 
- GAL supports only limited architecture. I want to make this module universally.
- GAL is completed library to be alternative of REAL GOOGLE HOME devices. But I want to regard this module as a voice commander of MM, not alternative Google Home.

**Comment by eouia** [comment]
And if you want to get an alternative GOOGLE HOME on RPI, Just use AIY project. you can run Google Assistant and MM together physically on one RPI.

**Comment by ejay-ibm** [comment]
Will give it a try, Thank you I was not able to find the answer and the diff between service and Library , thanks for the light.

**Comment by ejay-ibm** [comment]
Ok I got it running and indeed the timer works ( too bad that Spotify still doesn't) 
On the other side i'm a bit sad because i'm loosing the MM assistant interface and all the possibilities to interact with other module in the mirror :(

**Comment by eouia** [comment]
You cannot eat your cake and have it . :D

**Comment by ejay-ibm** [comment]
nothing is impossible my friend. :)

**Comment by eouia** [comment]
Or.. you just need a timer module which can be activated on runtime...

**Comment by ejay-ibm** [comment]
ahaha  you see their’s always a solution :)

**Comment by eouia** [comment]
I'll try to build a tiny timer module for you. (But till next Wed, I should be with my family of my vacation)

**Comment by ejay-ibm** [comment]
Oh and by the way if you have any account on tippee or whatever to contribute in a financial way to your work I’ll be happy to help you . 
I did it for the magic mirror project and I think you assistant module is part of the biggest work done on the MM so you would deserve it . 
I’m not talking about hundred of euro . But if it can help and demonstrate how I appreciate your help and work by sending you a few . that will do the trick i guess. 
I just see that you are ready even to build a timer for me so that convince me even more. 
You know i’m sharing this mirror with my family and they are not as geek as me . So basic stuff need to work without exhausting my family users. 
I hope that you can still as well add the notification command we talked  about a few days ago that will be very useful. 
Let me know 
One Last thing I order a Respeaker ( Array mic ) I’ll let you know how good it work . 

And thanks again !

Ejay

**Comment by ejay-ibm** [comment]
Fantastic, take your time ,  Enjoy your vacation !

**Comment by eouia** [comment]
https://github.com/eouia/MMM-AssistantMk2/wiki/Tip:Making-Timer-with-gAction

This will give you some idea.

**Comment by ejay-ibm** [comment]
very instructive . 
Thank you
